ALTER TABLE [CUSTOMER].[CUSTOMER_SME]
	ADD CONSTRAINT [CK_EXPORT_WEIGHT] 
	CHECK  ((([EXPORT_WEIGHT]+[LOCAL_WEIGHT])<=(100)))

GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME] CHECK CONSTRAINT [CK_EXPORT_WEIGHT]