CREATE TABLE [CLASSIFY].[CATEGORY_TYPE] (
    [CATEGORY_TYPE_KEY]     INT           IDENTITY (1, 1) NOT NULL,
    [CATEGORY_TYPE_DESC]    VARCHAR (50)  NULL,
    [CATEGORY_TYPE_DESC_TH] NVARCHAR (50) NULL,
    [CATEGORY_TYPE_VALUE]   NVARCHAR (20) NULL,
    [PRIORITY]              INT           NULL,
    [DEL_FLAG]              BIT           NULL
);

