CREATE TABLE [CUSTOMER].[TEMP_UPDATE_SME_RISK_20110727] (
    [Cif]                 FLOAT          NULL,
    [Name]                NVARCHAR (255) NULL,
    [BaySize]             NVARCHAR (255) NULL,
    [Rating]              NVARCHAR (255) NULL,
    [BizTypeE]            NVARCHAR (255) NULL,
    [BranchMaxPrin]       FLOAT          NULL,
    [Class]               NVARCHAR (255) NULL,
    [ClassE]              NVARCHAR (255) NULL,
    [Principal]           FLOAT          NULL,
    [Contingent]          FLOAT          NULL,
    [UseValue]            FLOAT          NULL,
    [Reserve]             FLOAT          NULL,
    [ResvFull]            FLOAT          NULL,
    [AO_SME]              FLOAT          NULL,
    [DateReport]          NVARCHAR (255) NULL,
    [CusDeptFlag]         FLOAT          NULL,
    [CusDeptTran]         FLOAT          NULL,
    [Cont#]               NVARCHAR (255) NULL,
    [CUSTOMER_NAME_E]     NVARCHAR (255) NULL,
    [GROUP_ID]            FLOAT          NULL,
    [GROUP_SIZE_ID]       FLOAT          NULL,
    [GROUP_SIZE_DESC]     NVARCHAR (255) NULL,
    [GROUP_EXPOSURE]      FLOAT          NULL,
    [SIZE_ID]             FLOAT          NULL,
    [SIZE_DETAIL]         NVARCHAR (255) NULL,
    [STATUS_DETAIL]       NVARCHAR (255) NULL,
    [CM_EMP_ID]           NVARCHAR (255) NULL,
    [CM_FIRSTNAME]        NVARCHAR (255) NULL,
    [CM_LASTNAME]         NVARCHAR (255) NULL,
    [CM_FIRSTNAME_E]      NVARCHAR (255) NULL,
    [CM_LASTNAME_E]       NVARCHAR (255) NULL,
    [CM_CONTROLLING]      NVARCHAR (255) NULL,
    [HEAD_EMP_ID]         NVARCHAR (255) NULL,
    [HEAD_FIRSTNAME]      NVARCHAR (255) NULL,
    [HEAD_FIRSTNAME_E]    NVARCHAR (255) NULL,
    [MANAGER_EMP_ID]      NVARCHAR (255) NULL,
    [MANAGER_FIRSTNAME]   NVARCHAR (255) NULL,
    [MANAGER_FIRSTNAME_E] NVARCHAR (255) NULL,
    [BRANCH_ID]           FLOAT          NULL,
    [BRANCH_DESC_TH]      NVARCHAR (255) NULL,
    [REGION_ID]           NVARCHAR (255) NULL,
    [REGION_DESC]         NVARCHAR (255) NULL,
    [JUDGEMENT_DESC]      NVARCHAR (255) NULL,
    [BUSI_RISK1_ID]       NVARCHAR (255) NULL,
    [BUSI_RISK1_DESC]     NVARCHAR (255) NULL,
    [BUSI_RISK1_DESC_EN]  NVARCHAR (255) NULL,
    [RATING_KEY]          FLOAT          NULL,
    [RATING_DESC]         NVARCHAR (255) NULL,
    [RATING_UPDATE_DATE]  DATETIME       NULL,
    [NEXT_REVIEW_DATE]    NVARCHAR (255) NULL,
    [LEADER1_CA_OLD_ID]   NVARCHAR (255) NULL,
    [EMPNAME 8700]        NVARCHAR (255) NULL,
    [DATEDELETE 8700]     NVARCHAR (255) NULL,
    [NPL Dept#]           NVARCHAR (255) NULL,
    [TeamLead_Corp]       NVARCHAR (255) NULL,
    [Corp]                NVARCHAR (255) NULL
);

