CREATE TABLE [CUSTOMER].[TEMP_CHECK_SIZE_P_NOP_20110810] (
    [CM_NAME]  NVARCHAR (255) NULL,
    [CIF]      FLOAT          NULL,
    [CUSTNAME] NVARCHAR (255) NULL,
    [LEADER_S] NVARCHAR (255) NULL
);

