CREATE TABLE [dbo].[CUS_SME_EXPORTER] (
    [CIF]                INT             NOT NULL,
    [TOTAL_LIMIT]        NUMERIC (20, 5) NULL,
    [TOTAL_OS]           NUMERIC (20, 5) NULL,
    [GROUP_EXPOSURE]     NUMERIC (20, 5) NULL,
    [REVENUE]            NUMERIC (20, 5) NULL,
    [REVENUE_EXPORT]     NUMERIC (5, 2)  NULL,
    [REVENUE_LOCAL]      NUMERIC (5, 2)  NULL,
    [COGS]               NUMERIC (20, 5) NULL,
    [COGS_IMPORT]        NUMERIC (5, 2)  NULL,
    [COGS_LOCAL]         NUMERIC (5, 2)  NULL,
    [GROSS_MARGIN]       NUMERIC (20, 5) NULL,
    [SG_AND_A]           NUMERIC (20, 5) NULL,
    [NET_MARGIN]         NUMERIC (20, 5) NULL,
    [PAY_INTEREST]       NUMERIC (20, 5) NULL,
    [PAY_PRINCIPAL]      NUMERIC (20, 5) NULL,
    [UPDATE_BY]          NVARCHAR (10)   NULL,
    [UPDATE_DATE]        DATETIME        NULL,
    [EXPORT_TO_1]        INT             NULL,
    [EX_CURRENCY_TYPE_1] INT             NULL,
    [EX_PERCENTAGE_1]    NUMERIC (5, 2)  NULL,
    [EXPORT_TO_2]        INT             NULL,
    [EX_CURRENCY_TYPE_2] INT             NULL,
    [EX_PERCENTAGE_2]    NUMERIC (5, 2)  NULL,
    [EXPORT_TO_3]        INT             NULL,
    [EX_CURRENCY_TYPE_3] INT             NULL,
    [EX_PERCENTAGE_3]    NUMERIC (5, 2)  NULL,
    [IM_CURRENCY_TYPE_1] INT             NULL,
    [IM_PERCENTAGE_1]    NUMERIC (5, 2)  NULL,
    [IM_CURRENCY_TYPE_2] INT             NULL,
    [IM_PERCENTAGE_2]    NUMERIC (5, 2)  NULL,
    [IM_CURRENCY_TYPE_3] INT             NULL,
    [IM_PERCENTAGE_3]    NUMERIC (5, 2)  NULL,
    [REMARK]             TEXT            NULL
);

