CREATE TABLE [dbo].[Law_ALL] (
    [CIF_NO]                                INT            NOT NULL,
    [NAME]                                  NVARCHAR (80)  NULL,
    [CLineGroup]                            NVARCHAR (25)  NULL,
    [Id_CLine]                              TINYINT        NULL,
    [CLineS]                                NVARCHAR (20)  NULL,
    [Id_BR2]                                NVARCHAR (6)   NULL,
    [BR2_Name]                              NVARCHAR (80)  NULL,
    [Id_BRE1]                               NVARCHAR (6)   NULL,
    [BR_NameE1]                             NVARCHAR (100) NULL,
    [Id_GroupE]                             NVARCHAR (1)   NULL,
    [GroupE]                                NVARCHAR (50)  NULL,
    [Count_Id_BR2]                          TINYINT        NULL,
    [LOM]                                   NVARCHAR (10)  NULL,
    [C3_New]                                SMALLDATETIME  NULL,
    [C33]                                   NVARCHAR (14)  NULL,
    [C4_New]                                SMALLDATETIME  NULL,
    [C44]                                   NVARCHAR (14)  NULL,
    [FUND]                                  MONEY          NULL,
    [NOU]                                   SMALLDATETIME  NULL,
    [PHO]                                   NVARCHAR (14)  NULL,
    [RED2]                                  NVARCHAR (14)  NULL,
    [DARA]                                  SMALLDATETIME  NULL,
    [CHAR2]                                 MONEY          NULL,
    [Id_4100]                               NVARCHAR (5)   NULL,
    [4100_Detail]                           NVARCHAR (25)  NULL,
    [BR]                                    NVARCHAR (18)  NULL,
    [Id_Branch]                             SMALLINT       NULL,
    [Branch]                                NVARCHAR (50)  NULL,
    [AC]                                    NVARCHAR (25)  NULL,
    [ACNO]                                  NVARCHAR (13)  NULL,
    [ACCNO]                                 NVARCHAR (16)  NULL,
    [Id_TAN]                                INT            NULL,
    [Tan_Name]                              NVARCHAR (50)  NULL,
    [Tan_Tel]                               NVARCHAR (30)  NULL,
    [**********เตรียมยึด 001***********]    NVARCHAR (1)   NULL,
    [Id_Hold]                               TINYINT        NULL,
    [Hold]                                  NVARCHAR (25)  NULL,
    [*********รอประกาศขาย 002**********]    NVARCHAR (1)   NULL,
    [C5_New]                                SMALLDATETIME  NULL,
    [NIL10]                                 MONEY          NULL,
    [Count1]                                TINYINT        NULL,
    [Sale_Date1]                            SMALLDATETIME  NULL,
    [Count2]                                TINYINT        NULL,
    [Sale_Date2]                            SMALLDATETIME  NULL,
    [Count3]                                TINYINT        NULL,
    [Sale_Date3]                            SMALLDATETIME  NULL,
    [Count4]                                TINYINT        NULL,
    [Sale_Date4]                            SMALLDATETIME  NULL,
    [Sale_Detail]                           NVARCHAR (150) NULL,
    [**********ขายทรัพย์ 003***********]    NVARCHAR (1)   NULL,
    [Id_NEW2]                               TINYINT        NULL,
    [New2s]                                 NVARCHAR (60)  NULL,
    [C99_New]                               SMALLDATETIME  NULL,
    [E]                                     TINYINT        NULL,
    [E_Detail]                              NVARCHAR (20)  NULL,
    [NIL9]                                  MONEY          NULL,
    [NIL9_Out]                              MONEY          NULL,
    [NEW_Date]                              SMALLDATETIME  NULL,
    [**********ภายนอก 004***********]       NVARCHAR (1)   NULL,
    [C88_New]                               SMALLDATETIME  NULL,
    [C88_Id_COP]                            NVARCHAR (4)   NULL,
    [COPs]                                  NVARCHAR (50)  NULL,
    [C88_Dang]                              NVARCHAR (15)  NULL,
    [C88_Detail]                            NVARCHAR (100) NULL,
    [**********สืบทรัพย์ 005***********]    NVARCHAR (1)   NULL,
    [BR5]                                   TINYINT        NULL,
    [BR5_Detail]                            NVARCHAR (25)  NULL,
    [Detection_Date]                        SMALLDATETIME  NULL,
    [Detection_REM]                         NVARCHAR (255) NULL,
    [**********สืบยึดทรัพย์ 006***********] NVARCHAR (1)   NULL,
    [Id_Detention]                          TINYINT        NULL,
    [Detention]                             NVARCHAR (40)  NULL,
    [Detention_Date]                        SMALLDATETIME  NULL,
    [Detention_REM]                         NVARCHAR (255) NULL,
    [**********หาเวลา***********]           NVARCHAR (1)   NULL,
    [C3_NewEnd]                             INT            NULL,
    [C4_NewEnd]                             INT            NULL,
    [C5_NewEnd]                             INT            NULL,
    [C99_NewEnd]                            INT            NULL,
    [Detection_DateEnd]                     INT            NULL,
    [NOUEnd]                                INT            NULL,
    [DARAEnd]                               INT            NULL,
    [C4_New1]                               SMALLDATETIME  NULL,
    [C4_New1End]                            INT            NULL
);

