CREATE TABLE [dbo].[TB_SCHEDULE] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [TimeBegin]   NVARCHAR (10)  NULL,
    [TimeEnd]     NVARCHAR (10)  NULL,
    [SDate]       SMALLDATETIME  NULL,
    [Employee]    NVARCHAR (10)  NULL,
    [PersonName]  NVARCHAR (100) NULL,
    [PersonDep]   NVARCHAR (100) NULL,
    [PersonTel]   NVARCHAR (50)  NULL,
    [Risk]        NVARCHAR (10)  NULL,
    [RiskName]    NVARCHAR (100) NULL,
    [RiskTeam]    NVARCHAR (100) NULL,
    [RiskTel]     NVARCHAR (50)  NULL,
    [Objective]   TEXT           NULL,
    [Cif]         NVARCHAR (10)  NULL,
    [CifName]     NVARCHAR (100) NULL,
    [ID_Branch]   NVARCHAR (10)  NULL,
    [Depbranch]   NVARCHAR (100) NULL,
    [Location]    NVARCHAR (2)   NULL,
    [Days]        INT            NULL,
    [Rest]        INT            NULL,
    [Office_chk]  BIT            NULL,
    [Home_chk]    BIT            NULL,
    [Shop_chk]    BIT            NULL,
    [Fac_chk]     BIT            NULL,
    [Col_chk]     BIT            NULL,
    [Other_chk]   NVARCHAR (50)  NULL,
    [Attach_File] NVARCHAR (255) NULL,
    [TranDate]    DATETIME       NULL,
    [UserName]    NVARCHAR (20)  NULL,
    [IP]          NVARCHAR (20)  NULL
);

