CREATE TABLE [dbo].[ANNALS_COVENANT_NEXT_ACTION] (
    [NEXT_COVENANT_ACTION_ID] INT           NULL,
    [NEXT_COVENANT_ACTION]    NVARCHAR (50) NULL,
    [PRIORITY]                INT           NULL
);

