CREATE TABLE [dbo].[ByCus_CIF] (
    [Cif]             INT           NOT NULL,
    [Name]            NVARCHAR (80) NULL,
    [BOTID]           INT           NULL,
    [BaySize]         NVARCHAR (16) NULL,
    [BaySizeNo]       TINYINT       NULL,
    [Rating]          NVARCHAR (3)  NULL,
    [BizTypeE]        NVARCHAR (30) NULL,
    [Busi_Type]       INT           NULL,
    [BranchMaxPrin]   SMALLINT      NULL,
    [AgingOK]         MONEY         NULL,
    [AgingMax]        MONEY         NULL,
    [Class]           NVARCHAR (1)  NULL,
    [ClassE]          NVARCHAR (4)  NULL,
    [PrincipalFull]   MONEY         NULL,
    [Principal]       MONEY         NULL,
    [PrinCom]         MONEY         NULL,
    [PrinRetail]      MONEY         NULL,
    [Cont]            MONEY         NULL,
    [ContIAS]         MONEY         NULL,
    [Contingent]      MONEY         NULL,
    [Contingent_EFW]  MONEY         NULL,
    [AccruFull]       MONEY         NULL,
    [Accru]           MONEY         NULL,
    [SuspOri]         MONEY         NULL,
    [Susp]            MONEY         NULL,
    [UNEARNPRIN]      MONEY         NULL,
    [UNEARNINT]       MONEY         NULL,
    [UNCLEAPRIN]      MONEY         NULL,
    [UNCLEAINT]       MONEY         NULL,
    [DEFER]           MONEY         NULL,
    [UseValue]        MONEY         NULL,
    [BAfterC]         MONEY         NULL,
    [TdrLoss]         MONEY         NULL,
    [Reserve]         MONEY         NULL,
    [PVLOSS]          MONEY         NULL,
    [AddResv]         MONEY         NULL,
    [Totresv]         MONEY         NULL,
    [Full_IAS39]      MONEY         NULL,
    [AddResv_IAS39]   MONEY         NULL,
    [ResvFull]        MONEY         NULL,
    [CusDeptFlag]     TINYINT       NULL,
    [CusDeptTran]     INT           NULL,
    [Office_Id_CIM]   FLOAT         NULL,
    [AO_SME]          FLOAT         NULL,
    [Office_Id]       FLOAT         NULL,
    [Affiliate]       BIT           NOT NULL,
    [NplFlag]         NVARCHAR (3)  NULL,
    [FirstSMHistory]  DATETIME      NULL,
    [FirstSMDate]     DATETIME      NULL,
    [FirstSMYear]     INT           NULL,
    [FirstSMYear1]    INT           NULL,
    [LastSMCount]     INT           NULL,
    [LastSMDate]      DATETIME      NULL,
    [LastSMYear]      INT           NULL,
    [LastSMYear1]     INT           NULL,
    [SMMonthFirst]    INT           NULL,
    [SMMonthLast]     INT           NULL,
    [FirstNplHistory] DATETIME      NULL,
    [FirstNplDate]    DATETIME      NULL,
    [FirstNplYear]    INT           NULL,
    [FirstNplYear1]   INT           NULL,
    [LastNplCount]    INT           NULL,
    [LastNplDate]     DATETIME      NULL,
    [LastNplYear]     INT           NULL,
    [LastNplYear1]    INT           NULL,
    [NplMonthFirst]   INT           NULL,
    [NplMonthLast]    INT           NULL,
    [TdrFlag]         NVARCHAR (6)  NULL,
    [GDR]             NVARCHAR (1)  NULL,
    [TdrFirst]        INT           NULL,
    [Count]           TINYINT       NULL,
    [Date_Report]     INT           NULL,
    [DateReport]      NVARCHAR (7)  NULL,
    [DateRegister]    NVARCHAR (7)  NULL,
    [BOT]             NVARCHAR (10) NULL,
    [BOTYear]         NVARCHAR (15) NULL,
    [BOTClassAfter]   NVARCHAR (1)  NULL,
    [BOT1]            NVARCHAR (3)  NULL,
    [BOTYear1]        NVARCHAR (10) NULL,
    [BOTClass1]       NVARCHAR (1)  NULL,
    [CDR]             NVARCHAR (3)  NULL,
    [CDRYear]         NVARCHAR (10) NULL,
    [CDRClass]        NVARCHAR (1)  NULL,
    [CM_Dep]          NVARCHAR (10) NULL,
    [CM_Flag]         NVARCHAR (15) NULL,
    [CM_Group]        NVARCHAR (15) NULL,
    [CM_Temp]         NVARCHAR (15) NULL,
    [CM_Id_Ao]        FLOAT         NULL,
    [CM_Ao]           NVARCHAR (15) NULL,
    [CM_AoTel]        NVARCHAR (15) NULL,
    [RM_Dep]          NVARCHAR (10) NULL,
    [RM_Group]        NVARCHAR (15) NULL,
    [RM_Temp]         NVARCHAR (15) NULL,
    [RM_Id_Ao]        FLOAT         NULL,
    [RM_Ao]           NVARCHAR (15) NULL,
    [RM_AoTel]        NVARCHAR (15) NULL
);

