CREATE TABLE [dbo].[TB_FORM_FIELD_LIST_20111103] (
    [FIELD_LIST_ID]    INT            IDENTITY (1, 1) NOT NULL,
    [FORM_FIELD_ID]    INT            NULL,
    [FIELD_LIST_TEXT]  NVARCHAR (100) NULL,
    [FIELD_LIST_VALUE] NVARCHAR (100) NULL
);

