CREATE TABLE [dbo].[FACILITY INFORMATION_back] (
    [CIF]                                 NVARCHAR (20)  NOT NULL,
    [Default Date]                        DATETIME       NOT NULL,
    [APP_ID]                              NVARCHAR (5)   NULL,
    [LIMITTYP_A]                          NVARCHAR (1)   NULL,
    [LIMITNO]                             NVARCHAR (20)  NOT NULL,
    [Limit @ D]                           FLOAT          NULL,
    [Limit @ D-1]                         FLOAT          NULL,
    [Facility Purpose Description]        NVARCHAR (255) NULL,
    [Nature of Facility]                  NVARCHAR (255) NULL,
    [Seniority]                           NVARCHAR (255) NULL,
    [Basel Committed Indicator]           BIT            NOT NULL,
    [Maturity Date]                       DATETIME       NULL,
    [Principal Repayment Currency Code]   NVARCHAR (3)   NULL,
    [Principal Repayment Amount]          FLOAT          NULL,
    [Principal Repayment Cycle]           NVARCHAR (255) NULL,
    [Compounding Frequency of Interest]   NVARCHAR (255) NULL,
    [Sharing Limit with (CIF 1)]          NVARCHAR (255) NULL,
    [Sharing Limit with (CIF 2)]          NVARCHAR (255) NULL,
    [Sharing Limit with (CIF 3)]          NVARCHAR (255) NULL,
    [Sharing Limit with (CIF 4)]          NVARCHAR (255) NULL,
    [Sharing Limit with (CIF 5)]          NVARCHAR (255) NULL,
    [Sharing Limit with (CIF 6)]          NVARCHAR (255) NULL,
    [UPDATE_USER]                         VARCHAR (10)   NULL,
    [UPDATE_DATE]                         DATETIME       NULL,
    [UNDRAWN_AMOUNT_IN_NEXT_12_MONTHS]    FLOAT          NULL,
    [THIS_LIMIT_IS_MIXED_LINE]            BIT            NULL,
    [DEL_FLAG]                            BIT            NULL,
    [One Level Up Limit ID @ D-1]         NVARCHAR (255) NULL,
    [One Level Up Limit Currency @ D-1]   NVARCHAR (3)   NULL,
    [One Level Up Limit Amount @ D-1]     FLOAT          NULL,
    [Two Level Up Limit ID @ D-1]         NVARCHAR (255) NULL,
    [Two Level Up Limit Currency @ D-1]   NVARCHAR (3)   NULL,
    [Two Level Up Limit Amount @ D-1]     FLOAT          NULL,
    [Three Level Up Limit ID @ D-1]       NVARCHAR (255) NULL,
    [Three Level Up Limit Currency @ D-1] NVARCHAR (3)   NULL,
    [Three Level Up Limit Amount @ D-1]   FLOAT          NULL,
    [Four Level Up Limit ID @ D-1]        NVARCHAR (255) NULL,
    [Four Level Up Limit Currency @ D-1]  NVARCHAR (3)   NULL,
    [Four Level Up Limit Amount @ D-1]    FLOAT          NULL
);

