CREATE TABLE [dbo].[ANNALS_CREDIT_PROCESS] (
    [ID]           NVARCHAR (10) NOT NULL,
    [EMP_ID]       NVARCHAR (10) NULL,
    [USER_ID]      NVARCHAR (10) NULL,
    [PROCESS_ID]   NVARCHAR (4)  NULL,
    [PROCESS_DATE] DATETIME      NULL,
    [LEVEL_ID]     NVARCHAR (20) NULL
);

