CREATE TABLE [dbo].[ByCustomer] (
    [Cif]           INT            NOT NULL,
    [Name]          NVARCHAR (30)  NULL,
    [BOTID]         INT            NULL,
    [GLGROUP]       NVARCHAR (255) NULL,
    [PDGROUP]       NVARCHAR (50)  NULL,
    [GECustSize]    NVARCHAR (15)  NULL,
    [BaySize]       NVARCHAR (16)  NULL,
    [Rating]        NVARCHAR (3)   NULL,
    [Busi_Type]     INT            NULL,
    [Tdr]           NVARCHAR (6)   NULL,
    [Count]         TINYINT        NULL,
    [DateReport]    NVARCHAR (7)   NULL,
    [DateRegister]  NVARCHAR (7)   NULL,
    [Date_Report]   INT            NULL,
    [Branch]        SMALLINT       NULL,
    [BranchMaxPrin] SMALLINT       NULL,
    [Dept]          INT            NULL,
    [DEPT_APPV]     INT            NULL,
    [DEPT_TRAN]     INT            NULL,
    [Class]         NVARCHAR (1)   NULL,
    [ClassE]        NVARCHAR (4)   NULL,
    [AGING]         MONEY          NULL,
    [NPL]           MONEY          NULL,
    [Limit]         MONEY          NULL,
    [PrinResv]      MONEY          NULL,
    [PrincipalFull] MONEY          NULL,
    [PrincipalG]    NVARCHAR (25)  NULL,
    [Principal]     MONEY          NULL,
    [Cont]          MONEY          NULL,
    [CCF1]          MONEY          NULL,
    [Contingent]    MONEY          NULL,
    [AccruFull]     MONEY          NULL,
    [Accru]         MONEY          NULL,
    [SuspOri]       MONEY          NULL,
    [Susp]          MONEY          NULL,
    [UNEARNPRIN]    MONEY          NULL,
    [UNEARNINT]     MONEY          NULL,
    [UNCLEAPRIN]    MONEY          NULL,
    [UNCLEAINT]     MONEY          NULL,
    [DEFER]         MONEY          NULL,
    [UseValue]      MONEY          NULL,
    [BAfterC]       MONEY          NULL,
    [TdrLoss]       MONEY          NULL,
    [Reserve]       MONEY          NULL,
    [PVLOSS]        MONEY          NULL,
    [ExtraResv]     MONEY          NULL,
    [BaySpresv]     MONEY          NULL,
    [Totresv]       MONEY          NULL,
    [Limit_Out]     MONEY          NULL,
    [Principal_Out] MONEY          NULL,
    [Olddef_Exc]    MONEY          NULL,
    [ResvExc]       MONEY          NULL,
    [Full_IAS39]    MONEY          NULL,
    [ResvFull]      MONEY          NULL,
    [BotClass]      NVARCHAR (1)   NULL,
    [AddResv]       MONEY          NULL,
    [BotColl]       MONEY          NULL,
    [CUS_DEPT_FLAG] TINYINT        NULL,
    [CUS_DEPT_TRAN] INT            NULL,
    [OFFICR_ID]     BIGINT         NULL,
    [NPLFLAG]       BIT            NOT NULL,
    [StatusPAY]     TINYINT        NULL,
    [Affiliate]     BIT            NOT NULL,
    [BOT]           NVARCHAR (10)  NULL,
    [BOTYear]       NVARCHAR (15)  NULL,
    [BOTClassAfter] NVARCHAR (1)   NULL
);

