CREATE TABLE [dbo].[Id_Branch] (
    [Id_Branch]       SMALLINT       NOT NULL,
    [Branch_T]        NVARCHAR (100) NULL,
    [Branch_E]        NVARCHAR (100) NULL,
    [Id_RegG]         TINYINT        NULL,
    [RegG_Name]       NVARCHAR (25)  NULL,
    [RegG_NameE]      NVARCHAR (25)  NULL,
    [Id_RegSub]       SMALLINT       NULL,
    [Id_Region]       SMALLINT       NULL,
    [Region_Name]     NVARCHAR (25)  NULL,
    [Region_NameE]    NVARCHAR (25)  NULL,
    [Id_Province]     SMALLINT       NULL,
    [Province]        NVARCHAR (50)  NULL,
    [Id_ProGDPE]      NVARCHAR (15)  NULL,
    [Id_PartN]        TINYINT        NULL,
    [Part_NameN]      NVARCHAR (30)  NULL,
    [Part_NameNE]     NVARCHAR (30)  NULL,
    [Id_RegionOld]    SMALLINT       NULL,
    [Region_NameOld]  NVARCHAR (30)  NULL,
    [Region_NameEOld] NVARCHAR (30)  NULL,
    [Id_PartOld]      SMALLINT       NULL,
    [Part_NameOld]    NVARCHAR (30)  NULL,
    [Part_NameEOld]   NVARCHAR (30)  NULL,
    [Id_Part1]        SMALLINT       NULL,
    [Part1_Name]      NVARCHAR (30)  NULL,
    [Id_Part2]        SMALLINT       NULL,
    [Part2_Name]      NVARCHAR (30)  NULL,
    [Part2_NameE]     NVARCHAR (50)  NULL,
    [Id_Part3]        SMALLINT       NULL,
    [Part3_Name]      NVARCHAR (30)  NULL,
    [Id_Part4]        SMALLINT       NULL,
    [Part4_Name]      NVARCHAR (50)  NULL,
    [Addres]          NVARCHAR (100) NULL,
    [Post]            NVARCHAR (10)  NULL,
    [Tel]             NVARCHAR (50)  NULL,
    [DateOpen]        NVARCHAR (15)  NULL,
    [Id_BCenter]      NVARCHAR (4)   NULL,
    [Segment]         NVARCHAR (25)  NULL,
    [Out_Of_Scope]    INT            NULL
);

