CREATE TABLE [dbo].[Detail_ByAcc] (
    [CIF]           INT           NULL,
    [Branch]        SMALLINT      NULL,
    [Busi_Type]     INT           NULL,
    [AccGL]         INT           NULL,
    [ACCNO]         NVARCHAR (16) NULL,
    [CONTNO]        NVARCHAR (13) NULL,
    [SEQNO]         INT           NULL,
    [AGING]         MONEY         NULL,
    [Limit]         MONEY         NULL,
    [PrincipalFull] MONEY         NULL,
    [Principal]     MONEY         NULL,
    [AccruFull]     MONEY         NULL,
    [Accru]         MONEY         NULL,
    [SuspOri]       MONEY         NULL,
    [Susp]          MONEY         NULL,
    [UNEARNPRIN]    MONEY         NULL,
    [UNEARNINT]     MONEY         NULL,
    [PAY_PRIN]      MONEY         NULL,
    [PAY_INT]       MONEY         NULL,
    [PAY_SUSP]      MONEY         NULL,
    [RATE_TYPE]     NVARCHAR (4)  NULL,
    [RATE_LOAD]     MONEY         NULL,
    [INT_RATE]      MONEY         NULL,
    [OPEN_ACC]      SMALLDATETIME NULL,
    [DUE_DATE]      NVARCHAR (10) NULL,
    [ISSU_DATE]     SMALLDATETIME NULL,
    [LPAY_DATE]     SMALLDATETIME NULL,
    [APP_ID]        NVARCHAR (3)  NULL
);

