CREATE TABLE [dbo].[ANNALS_PROCESS] (
    [PROCESS_ID]    CHAR (4)       NOT NULL,
    [PEOCESS_HEAD]  NVARCHAR (100) NULL,
    [PROCESS]       NVARCHAR (200) NULL,
    [PROCESS_GROUP] CHAR (1)       NULL
);

