CREATE TABLE [dbo].[GROUP_SIZE] (
    [GROUP_SIZE_ID] SMALLINT       IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION]   NVARCHAR (255) NOT NULL,
    [PRIORITY]      SMALLINT       NOT NULL,
    [UPDATE_DATE]   DATETIME       NOT NULL,
    [UPDATE_BY]     NVARCHAR (10)  NOT NULL
);

