CREATE TABLE [dbo].[TEMP_20090223_SIZE_SUMMARY_CIFTYPE1] (
    [GROUP_SIZE_DETAIL]        NVARCHAR (255) NULL,
    [สำนักงานใหญ่]             INT            NULL,
    [ภาคนครหลวง]               INT            NULL,
    [ภาค 1]                    INT            NULL,
    [ภาค 2]                    INT            NULL,
    [ภาค 3]                    INT            NULL,
    [ภาค 4]                    INT            NULL,
    [ภาค 5]                    INT            NULL,
    [ภาค 6]                    INT            NULL,
    [ภาค 7]                    INT            NULL,
    [ภาค 8]                    INT            NULL,
    [สังกัดฝ่ายธุรกิจสาขากลาง] INT            NULL,
    [ภาคภูมิภาค]               INT            NULL,
    [ภาค 9]                    INT            NULL,
    [ภาค 10]                   INT            NULL,
    [ภาค 11]                   INT            NULL,
    [ภาค 12]                   INT            NULL,
    [ภาค 13]                   INT            NULL,
    [ภาค 14]                   INT            NULL,
    [ภาค 15]                   INT            NULL,
    [ภาค 16]                   INT            NULL,
    [ภาค 17]                   INT            NULL,
    [ภาค 18]                   INT            NULL,
    [ภาค 19]                   INT            NULL,
    [สาขาต่างประเทศ]           INT            NULL,
    [AAMC]                     INT            NULL
);

