CREATE TABLE [dbo].[Temp_Update_Port_20111201] (
    [CIF]                     FLOAT          NULL,
    [CUSTOMER_NAME]           NVARCHAR (255) NULL,
    [GROUP_ID]                FLOAT          NULL,
    [MAIN_CIF]                FLOAT          NULL,
    [SIZE_ID]                 FLOAT          NULL,
    [SIZE_DETAIL]             NVARCHAR (255) NULL,
    [STATUS_ID]               FLOAT          NULL,
    [STATUS_DETAIL]           NVARCHAR (255) NULL,
    [CM_EMP_ID]               NVARCHAR (255) NULL,
    [CM_TITLE_NAME]           NVARCHAR (255) NULL,
    [CM_FIRSTNAME]            NVARCHAR (255) NULL,
    [DEPTTRAN]                FLOAT          NULL,
    [CONTROLLING_UNIT_BRANCH] NVARCHAR (255) NULL,
    [CONTROLLING_UNIT]        NVARCHAR (255) NULL,
    [EIGHT_UP]                NVARCHAR (255) NULL,
    [EIGHT_UP_NAME]           NVARCHAR (255) NULL,
    [ByCustomer_ASOF]         DATETIME       NULL,
    [GECustSize]              NVARCHAR (255) NULL,
    [BaySize]                 NVARCHAR (255) NULL,
    [BranchMaxPrin]           NVARCHAR (255) NULL,
    [Principal]               NVARCHAR (255) NULL,
    [Accru]                   NVARCHAR (255) NULL,
    [Susp]                    NVARCHAR (255) NULL,
    [Tdr]                     NVARCHAR (255) NULL,
    [AGING]                   NVARCHAR (255) NULL,
    [Limit]                   NVARCHAR (255) NULL,
    [NPLFLAG]                 NVARCHAR (255) NULL,
    [LOCATION_PROVINCE_TH]    NVARCHAR (255) NULL,
    [Update CM Emp ID]        NVARCHAR (255) NULL,
    [EMP_ID]                  NVARCHAR (10)  NULL
);

