CREATE TABLE [dbo].[TEMP_ALSCOM] (
    [CIF]            INT           NULL,
    [FIRST_NAMe]     VARCHAR (40)  NULL,
    [LAST_NAME]      VARCHAR (40)  NULL,
    [APPNUMBER]      NUMERIC (38)  NULL,
    [APPSTATUSTEXT]  VARCHAR (15)  NULL,
    [DECISION_DATE]  DATETIME      NULL,
    [PENDING_CODE_1] VARCHAR (10)  NULL,
    [PENDING_DESC_1] VARCHAR (100) NULL,
    [CANCEL_CODE_1]  VARCHAR (10)  NULL,
    [CANCEL_DESC_1]  VARCHAR (100) NULL,
    [DECLINE_CODE_1] VARCHAR (10)  NULL,
    [DECLINE_DESC_1] VARCHAR (100) NULL
);

