CREATE TABLE [dbo].[COLLVAL] (
    [COLL_ID]      INT         NOT NULL,
    [CIF]          INT         NOT NULL,
    [AID]          INT         NULL,
    [FORECASTVAL]  MONEY       NULL,
    [FORECASTLOSE] MONEY       NULL,
    [COLLVAL]      MONEY       NULL,
    [UNITVAL]      MONEY       NULL,
    [UNITTYPE]     VARCHAR (2) NULL,
    [PERC_CTRL]    FLOAT       NULL,
    [PRICE_CTRL]   MONEY       NULL,
    [DATE_CTRL]    DATETIME    NULL,
    [PERC_JBK]     FLOAT       NULL,
    [PRICE_JBK]    MONEY       NULL,
    [DATE_JBK]     DATETIME    NULL,
    [PERC_BS]      FLOAT       NULL,
    [PRICE_BS]     MONEY       NULL,
    [DATE_BS]      DATETIME    NULL,
    [PERC_DEPT]    FLOAT       NULL,
    [PRICE_DEPT]   MONEY       NULL,
    [DATE_DEPT]    DATETIME    NULL,
    [DEPT]         SMALLINT    NULL,
    [BUYCOLL]      CHAR (1)    NULL,
    [SELLER]       SMALLINT    NULL,
    [COMMENT]      TEXT        NULL,
    [DATEDELETE]   DATETIME    NULL,
    [EMP_ID]       VARCHAR (6) NOT NULL,
    [UP_DT]        DATETIME    NOT NULL
);

