CREATE TABLE [dbo].[ACCEL_RECONCILE] (
    [PRODUCT_TYPE]  NVARCHAR (5)  NOT NULL,
    [TYPE]          NUMERIC (2)   NOT NULL,
    [SEGMENT]       NVARCHAR (10) NOT NULL,
    [SEGMENT_VALUE] NVARCHAR (8)  NULL,
    [AGGREGATION]   NUMERIC (1)   NOT NULL,
    [SOURCE_FIELD]  NVARCHAR (20) NOT NULL,
    [SOURCE_VALUE]  NVARCHAR (50) NULL,
    [SOURCE_DATE]   NVARCHAR (8)  NULL
);

