CREATE TABLE [dbo].[TB_EMPLOYEE_Backup] (
    [EMP_ID]          NVARCHAR (10)  NOT NULL,
    [TITLE_CODE]      TINYINT        NULL,
    [EMPNAME]         VARCHAR (50)   NULL,
    [EMPSURNAME]      VARCHAR (50)   NULL,
    [EMPNAME_E]       NVARCHAR (50)  NULL,
    [EMPSURNAME_E]    NVARCHAR (50)  NULL,
    [EMAIL]           CHAR (30)      NULL,
    [IDCARD]          VARCHAR (50)   NULL,
    [TAX_NO]          VARCHAR (50)   NULL,
    [ACCNO]           CHAR (16)      NULL,
    [ADDRESS]         VARCHAR (30)   NULL,
    [SOI]             VARCHAR (20)   NULL,
    [ROAD]            VARCHAR (30)   NULL,
    [LOCALITY]        VARCHAR (30)   NULL,
    [DISTRINCT]       VARCHAR (30)   NULL,
    [PROV_CODE]       CHAR (2)       NULL,
    [ZIPCODE]         CHAR (5)       NULL,
    [TEL_HOME]        VARCHAR (30)   NULL,
    [TEL_MOBILE]      VARCHAR (20)   NULL,
    [TEL_INDOOR]      VARCHAR (30)   NULL,
    [DATEOFBIRTH]     DATETIME       NULL,
    [IMAGENAME]       VARCHAR (20)   NULL,
    [DATEOFSTART]     DATETIME       NULL,
    [STATUS]          CHAR (1)       NULL,
    [TEAM_ID]         NVARCHAR (10)  NULL,
    [GROUP_HEAD]      CHAR (1)       NULL,
    [ROLE]            TINYINT        NULL,
    [PERMIT]          CHAR (1)       NULL,
    [USERNAME]        NVARCHAR (10)  NULL,
    [PASSWD]          NVARCHAR (20)  NULL,
    [UP_DT]           DATETIME       NULL,
    [Dept]            SMALLINT       NULL,
    [Id_Region]       SMALLINT       NULL,
    [Id_Branch]       SMALLINT       NULL,
    [POSITION_CODE]   CHAR (5)       NULL,
    [Id_Region_Group] NVARCHAR (255) NULL,
    [Id_Branch_Group] NVARCHAR (255) NULL,
    [Id_Group_Group]  NTEXT          NULL,
    [level_id]        NCHAR (1)      NULL
);

