CREATE TABLE [dbo].[BUSINESS_DESTINATION] (
    [BUSINESS_DESTINATION_ID]   NUMERIC (3)    IDENTITY (1, 1) NOT NULL,
    [BUSINESS_DESTINATION_DESC] NVARCHAR (100) NULL,
    [PRIORITY]                  INT            NULL
);

