CREATE TABLE [dbo].[ANNALS_COVENANT_DETAIL_BACKUP_20120220] (
    [COVENANT_DETAIL_ID] NVARCHAR (3)   NULL,
    [COVENANT_DETAIL]    NVARCHAR (MAX) NULL,
    [PRIORITY]           INT            NULL,
    [COVENANT_TYPE_ID]   NVARCHAR (1)   NULL
);

