CREATE TABLE [dbo].[REP_OD] (
    [tdr]        VARCHAR (10)   NOT NULL,
    [baysize]    NVARCHAR (20)  NOT NULL,
    [g_coll]     SMALLINT       NOT NULL,
    [m_j_lim]    CHAR (1)       NOT NULL,
    [g_numcust]  SMALLINT       NOT NULL,
    [accno]      VARCHAR (18)   NOT NULL,
    [ctrl_unit]  NVARCHAR (50)  NOT NULL,
    [cif]        INT            NOT NULL,
    [name]       NVARCHAR (70)  NOT NULL,
    [busi_type]  INT            NOT NULL,
    [busi_desc]  NVARCHAR (100) NOT NULL,
    [idrating]   NVARCHAR (5)   NOT NULL,
    [brname]     NVARCHAR (50)  NOT NULL,
    [od_int]     SMALLMONEY     NOT NULL,
    [od_date]    DATETIME       NOT NULL,
    [adjclass]   NCHAR (1)      NOT NULL,
    [gclass]     SMALLINT       NOT NULL,
    [class_h]    NCHAR (24)     NOT NULL,
    [od_lim]     MONEY          NOT NULL,
    [od_prin]    MONEY          NOT NULL,
    [od_aging]   SMALLMONEY     NOT NULL,
    [pns_lim]    MONEY          NOT NULL,
    [pns_prin]   MONEY          NOT NULL,
    [pns_aging]  SMALLMONEY     NOT NULL,
    [als_lim]    MONEY          NOT NULL,
    [als_prin]   MONEY          NOT NULL,
    [als_aging]  SMALLMONEY     NOT NULL,
    [alsh_lim]   MONEY          NOT NULL,
    [alsh_prin]  MONEY          NOT NULL,
    [alsh_aging] SMALLMONEY     NOT NULL,
    [alsp_lim]   MONEY          NOT NULL,
    [alsp_prin]  MONEY          NOT NULL,
    [alsp_aging] SMALLMONEY     NOT NULL,
    [pr_lim]     MONEY          NOT NULL,
    [pr_prin]    MONEY          NOT NULL,
    [pr_aging]   SMALLMONEY     NOT NULL,
    [imx_lim]    MONEY          NOT NULL,
    [imx_prin]   MONEY          NOT NULL,
    [imx_aging]  SMALLMONEY     NOT NULL,
    [cts_lim]    MONEY          NOT NULL,
    [cts_prin]   MONEY          NOT NULL,
    [ccts_prin]  MONEY          NOT NULL,
    [ccts_aging] SMALLMONEY     NOT NULL,
    [mvmdam12]   MONEY          NOT NULL,
    [mvmdam11]   MONEY          NOT NULL,
    [mvmdam10]   MONEY          NOT NULL,
    [mvmdam09]   MONEY          NOT NULL,
    [mvmdam08]   MONEY          NOT NULL,
    [mvmdam07]   MONEY          NOT NULL,
    [mvmdam06]   MONEY          NOT NULL,
    [mvmdam05]   MONEY          NOT NULL,
    [mvmdam04]   MONEY          NOT NULL,
    [mvmdam03]   MONEY          NOT NULL,
    [mvmdam02]   MONEY          NOT NULL,
    [mvmdam01]   MONEY          NOT NULL,
    [mvmdr_avg]  MONEY          NOT NULL,
    [mvmcam12]   MONEY          NOT NULL,
    [mvmcam11]   MONEY          NOT NULL,
    [mvmcam10]   MONEY          NOT NULL,
    [mvmcam09]   MONEY          NOT NULL,
    [mvmcam08]   MONEY          NOT NULL,
    [mvmcam07]   MONEY          NOT NULL,
    [mvmcam06]   MONEY          NOT NULL,
    [mvmcam05]   MONEY          NOT NULL,
    [mvmcam04]   MONEY          NOT NULL,
    [mvmcam03]   MONEY          NOT NULL,
    [mvmcam02]   MONEY          NOT NULL,
    [mvmcam01]   MONEY          NOT NULL,
    [mvmcr_avg]  MONEY          NOT NULL,
    [limit12]    MONEY          NOT NULL,
    [limit11]    MONEY          NOT NULL,
    [limit10]    MONEY          NOT NULL,
    [limit09]    MONEY          NOT NULL,
    [limit08]    MONEY          NOT NULL,
    [limit07]    MONEY          NOT NULL,
    [limit06]    MONEY          NOT NULL,
    [limit05]    MONEY          NOT NULL,
    [limit04]    MONEY          NOT NULL,
    [limit03]    MONEY          NOT NULL,
    [limit02]    MONEY          NOT NULL,
    [limit01]    MONEY          NOT NULL,
    [utineg12]   MONEY          NOT NULL,
    [utineg11]   MONEY          NOT NULL,
    [utineg10]   MONEY          NOT NULL,
    [utineg09]   MONEY          NOT NULL,
    [utineg08]   MONEY          NOT NULL,
    [utineg07]   MONEY          NOT NULL,
    [utineg06]   MONEY          NOT NULL,
    [utineg05]   MONEY          NOT NULL,
    [utineg04]   MONEY          NOT NULL,
    [utineg03]   MONEY          NOT NULL,
    [utineg02]   MONEY          NOT NULL,
    [utineg01]   MONEY          NOT NULL,
    [utiliz_avg] MONEY          NOT NULL,
    [maxbal12]   MONEY          NOT NULL,
    [maxbal11]   MONEY          NOT NULL,
    [maxbal10]   MONEY          NOT NULL,
    [maxbal09]   MONEY          NOT NULL,
    [maxbal08]   MONEY          NOT NULL,
    [maxbal07]   MONEY          NOT NULL,
    [maxbal06]   MONEY          NOT NULL,
    [maxbal05]   MONEY          NOT NULL,
    [maxbal04]   MONEY          NOT NULL,
    [maxbal03]   MONEY          NOT NULL,
    [maxbal02]   MONEY          NOT NULL,
    [maxbal01]   MONEY          NOT NULL,
    [maxbalavg]  MONEY          NOT NULL,
    [minbal12]   MONEY          NOT NULL,
    [minbal11]   MONEY          NOT NULL,
    [minbal10]   MONEY          NOT NULL,
    [minbal09]   MONEY          NOT NULL,
    [minbal08]   MONEY          NOT NULL,
    [minbal07]   MONEY          NOT NULL,
    [minbal06]   MONEY          NOT NULL,
    [minbal05]   MONEY          NOT NULL,
    [minbal04]   MONEY          NOT NULL,
    [minbal03]   MONEY          NOT NULL,
    [minbal02]   MONEY          NOT NULL,
    [minbal01]   MONEY          NOT NULL,
    [minbalavg]  MONEY          NOT NULL,
    [nmonth_cur] SMALLINT       NOT NULL,
    [chqre_dact] SMALLINT       NOT NULL,
    [chqre_daca] MONEY          NOT NULL,
    [chqrdtpv3m] SMALLINT       NULL,
    [chqredpv3m] MONEY          NULL,
    [chqrdt01]   SMALLINT       NOT NULL,
    [chqred01]   MONEY          NOT NULL,
    [chqre_cact] SMALLINT       NOT NULL,
    [chqre_caca] MONEY          NOT NULL,
    [chqrctpv3m] SMALLINT       NULL,
    [chqrecpv3m] MONEY          NULL,
    [chqrct01]   SMALLINT       NOT NULL,
    [chqrec01]   MONEY          NOT NULL,
    [LIM_ACCUM]  MONEY          NULL,
    [NMONTH_OD]  SMALLINT       NULL,
    [LIM_AVG]    MONEY          NULL,
    [ACCNEG_OD]  MONEY          NULL,
    [DNEGPOS_OD] SMALLINT       NULL,
    [PCTUTIAVG]  MONEY          NULL,
    [PCTUTI01]   MONEY          NULL,
    [PCTMVM01]   MONEY          NULL,
    [birthdate]  DATETIME       NULL,
    [beingcust]  DATETIME       NULL,
    [oldcontrac] DATETIME       NULL,
    [run_date]   DATETIME       NOT NULL
);

