CREATE TABLE [dbo].[Excel_npl_all_20100716] (
    [Cif]                FLOAT          NULL,
    [Name]               NVARCHAR (255) NULL,
    [NameEng]            NVARCHAR (255) NULL,
    [BaySize]            NVARCHAR (255) NULL,
    [BizTypeE]           NVARCHAR (255) NULL,
    [Id Branch]          FLOAT          NULL,
    [Branch Thai]        NVARCHAR (255) NULL,
    [Branch English]     NVARCHAR (255) NULL,
    [Id Region]          FLOAT          NULL,
    [Region Thai]        NVARCHAR (255) NULL,
    [Region English]     NVARCHAR (255) NULL,
    [Id_Hub]             FLOAT          NULL,
    [Hub_Name_T]         NVARCHAR (255) NULL,
    [Hub_Name_E]         NVARCHAR (255) NULL,
    [Busi_Type]          FLOAT          NULL,
    [Class]              NVARCHAR (255) NULL,
    [ClassE]             NVARCHAR (255) NULL,
    [Cont]               FLOAT          NULL,
    [Principal]          FLOAT          NULL,
    [Contingent_EFW]     FLOAT          NULL,
    [prin_sum]           MONEY          NULL,
    [UseValue]           FLOAT          NULL,
    [Full_IAS39]         FLOAT          NULL,
    [Totresv]            FLOAT          NULL,
    [ResvFull]           FLOAT          NULL,
    [Resv_diff]          MONEY          NULL,
    [Flag]               FLOAT          NULL,
    [Id_DepTran]         FLOAT          NULL,
    [Dep/Branch Thai]    NVARCHAR (255) NULL,
    [Dep/Branch English] NVARCHAR (255) NULL,
    [Office_Id]          FLOAT          NULL,
    [office_name]        NVARCHAR (255) NULL,
    [TdrFlag]            NVARCHAR (255) NULL,
    [TdrFirst]           FLOAT          NULL,
    [NplFlag]            NVARCHAR (255) NULL,
    [FirstNplYear]       FLOAT          NULL,
    [Rating]             NVARCHAR (255) NULL,
    [CM_Sme]             NVARCHAR (255) NULL
);

