CREATE TABLE [dbo].[Temp_Update_Port_LastTime_20100122] (
    [CIF]                       FLOAT          NULL,
    [CUSTOMER_NAME]             NVARCHAR (255) NULL,
    [CUSTOMER_NAME_E]           NVARCHAR (255) NULL,
    [GROUP_ID]                  FLOAT          NULL,
    [CM_CODE]                   NVARCHAR (255) NULL,
    [CM_NAME]                   NVARCHAR (255) NULL,
    [ผู้ดูแลใหม่]               NVARCHAR (255) NULL,
    [ID]                        NVARCHAR (255) NULL,
    [SIZE_DETAIL]               NVARCHAR (255) NULL,
    [OLD_CM_CODE]               NVARCHAR (255) NULL,
    [OLD_CM_NAME]               NVARCHAR (255) NULL,
    [BRANCH_ID]                 FLOAT          NULL,
    [BRANCH_NAME]               NVARCHAR (255) NULL,
    [Id_Region]                 FLOAT          NULL,
    [Region_Name]               NVARCHAR (255) NULL,
    [REGION_NAME2]              NVARCHAR (255) NULL,
    [GROUP_SIZE_ID]             FLOAT          NULL,
    [GROUP_SIZE_DETAIL]         NVARCHAR (255) NULL,
    [JUDGEMENT_ID]              NVARCHAR (255) NULL,
    [JUDGEMENT_DETAIL]          NVARCHAR (255) NULL,
    [BUSI_RISK1_ID]             NVARCHAR (255) NULL,
    [BUSI_RISK1_DETAIL]         NVARCHAR (255) NULL,
    [BUSI_RISK2_ID]             NVARCHAR (255) NULL,
    [BUSI_RISK2_DETAIL]         NVARCHAR (255) NULL,
    [BUSI_RISK3_ID]             NVARCHAR (255) NULL,
    [BUSI_RISK3_DETAIL]         NVARCHAR (255) NULL,
    [UPDATE_BY]                 NVARCHAR (255) NULL,
    [UPDATE_BY_NAME]            NVARCHAR (255) NULL,
    [UPDATE_DATE]               DATETIME       NULL,
    [BUSI_TYPE_CIM]             NVARCHAR (255) NULL,
    [DEPTFLAG]                  FLOAT          NULL,
    [DEPTTRAN]                  FLOAT          NULL,
    [OFFICR_ID]                 NVARCHAR (255) NULL,
    [OFFICR_NAME]               NVARCHAR (255) NULL,
    [CONTROLLING_UNIT]          NVARCHAR (255) NULL,
    [CONTROLLING_UNIT_E]        NVARCHAR (255) NULL,
    [REGION_CONTROLLING_UNIT]   NVARCHAR (255) NULL,
    [BUSINESS_DESTINATION_ID]   FLOAT          NULL,
    [BUSINESS_DESTINATION_DESC] NVARCHAR (255) NULL,
    [EXPORT_WEIGHT]             FLOAT          NULL,
    [LOCAL_WEIGHT]              FLOAT          NULL,
    [STATUS_ID]                 FLOAT          NULL,
    [STATUS_DETAIL]             NVARCHAR (255) NULL,
    [SIZE_ID]                   FLOAT          NULL,
    [F45]                       NVARCHAR (255) NULL,
    [F46]                       NVARCHAR (255) NULL,
    [F47]                       NVARCHAR (255) NULL,
    [F48]                       NVARCHAR (255) NULL,
    [F49]                       NVARCHAR (255) NULL,
    [F50]                       NVARCHAR (255) NULL,
    [F51]                       NVARCHAR (255) NULL,
    [F52]                       NVARCHAR (255) NULL,
    [F53]                       NVARCHAR (255) NULL
);

