CREATE TABLE [dbo].[ByAccount] (
    [Cif]           INT            NULL,
    [PKAcc]         NVARCHAR (48)  NULL,
    [BOTID]         INT            NULL,
    [Busi_Type]     INT            NULL,
    [Branch]        SMALLINT       NULL,
    [Dept]          INT            NULL,
    [DEPT_APPV]     INT            NULL,
    [DEPT_TRAN]     INT            NULL,
    [DEPT_CTRL]     INT            NULL,
    [GECustSize]    NVARCHAR (15)  NULL,
    [GESize2]       NVARCHAR (17)  NULL,
    [GLGROUP]       NVARCHAR (255) NULL,
    [PDGROUP]       NVARCHAR (50)  NULL,
    [ACCGL]         INT            NULL,
    [ACCNO]         NVARCHAR (16)  NULL,
    [CONTNO]        NVARCHAR (13)  NULL,
    [SEQNO]         INT            NULL,
    [AGING]         MONEY          NULL,
    [ADJCLASS]      NVARCHAR (1)   NULL,
    [Class]         NVARCHAR (1)   NULL,
    [CLADJ]         NVARCHAR (1)   NULL,
    [LimitNO]       NVARCHAR (20)  NULL,
    [Limit]         MONEY          NULL,
    [LimitApp]      MONEY          NULL,
    [FCY_TYPE]      SMALLINT       NULL,
    [NPL]           MONEY          NULL,
    [PrincipalFull] MONEY          NULL,
    [Principal]     MONEY          NULL,
    [AccruFull]     MONEY          NULL,
    [Accru]         MONEY          NULL,
    [SuspOri]       MONEY          NULL,
    [Susp]          MONEY          NULL,
    [UNEARNPRIN]    MONEY          NULL,
    [UNEARNINT]     MONEY          NULL,
    [UNCLEAPRIN]    MONEY          NULL,
    [UNCLEAINT]     MONEY          NULL,
    [DEFER]         MONEY          NULL,
    [UseValue]      MONEY          NULL,
    [Reserve]       MONEY          NULL,
    [PVLOSS]        MONEY          NULL,
    [ExtraResv]     MONEY          NULL,
    [AddResv]       MONEY          NULL,
    [Totresv]       MONEY          NULL,
    [Olddef_Exc]    MONEY          NULL,
    [ResvExc]       MONEY          NULL,
    [Full_IAS39]    MONEY          NULL,
    [ResvFull]      MONEY          NULL,
    [BAFTERC]       MONEY          NULL,
    [TDRLOSS]       MONEY          NULL,
    [INT_RATE]      MONEY          NULL,
    [RATE_TYPE]     NVARCHAR (3)   NULL,
    [SIGN]          NVARCHAR (1)   NULL,
    [RATE_LOAD]     MONEY          NULL,
    [DUE_DATE]      SMALLDATETIME  NULL,
    [ISSU_DATE]     SMALLDATETIME  NULL,
    [OPEN_ACC]      SMALLDATETIME  NULL,
    [Pay_PRIN]      MONEY          NULL,
    [Pay_INT]       MONEY          NULL,
    [Pay_SUSP]      MONEY          NULL,
    [Post_PRIN]     MONEY          NULL,
    [Post_INT]      MONEY          NULL,
    [Post_SUSP]     MONEY          NULL,
    [Rev_Accru]     MONEY          NULL,
    [NPLFLAG]       BIT            NOT NULL,
    [APP_ID]        NVARCHAR (3)   NULL,
    [ResvFLAG]      BIT            NOT NULL,
    [CCF1FLAG]      BIT            NOT NULL,
    [BeforeGE]      NVARCHAR (1)   NULL,
    [Interbank]     BIT            NOT NULL,
    [Affiliate]     BIT            NOT NULL
);

