CREATE TABLE [dbo].[BUSINESS_TYPE_4] (
    [TYPE4_ID]       VARCHAR (8)    NOT NULL,
    [RESEARCH_CODE]  VARCHAR (8)    NOT NULL,
    [DESCRIPTION]    NVARCHAR (255) NOT NULL,
    [DESCRIPTION_EN] VARCHAR (255)  NOT NULL,
    [TYPE3_ID]       VARCHAR (6)    NOT NULL,
    [NOTE]           CHAR (1)       NULL,
    [PRIORITY]       INT            NULL,
    [UPDATE_BY]      NVARCHAR (10)  NULL,
    [UPDATE_DATE]    DATETIME       NOT NULL
);

