CREATE TABLE [dbo].[Temp_Update_Port_R14_15] (
    [CIF]                     FLOAT          NULL,
    [CUSTOMER_NAME]           NVARCHAR (255) NULL,
    [GROUP_ID]                FLOAT          NULL,
    [GROUP_SIZE_DETAIL]       NVARCHAR (255) NULL,
    [CM_CODE]                 NVARCHAR (255) NULL,
    [CM_NAME]                 NVARCHAR (255) NULL,
    [ผู้ดูแลใหม่]             NVARCHAR (255) NULL,
    [ID]                      NVARCHAR (255) NULL,
    [OLD_CM_CODE]             NVARCHAR (255) NULL,
    [OLD_CM_NAME]             NVARCHAR (255) NULL,
    [SIZE_DETAIL]             NVARCHAR (255) NULL,
    [STATUS_DETAIL]           NVARCHAR (255) NULL,
    [BRANCH_ID]               FLOAT          NULL,
    [BRANCH_NAME]             NVARCHAR (255) NULL,
    [Id_Region]               FLOAT          NULL,
    [Region_Name]             NVARCHAR (255) NULL,
    [REGION_NAME2]            NVARCHAR (255) NULL,
    [GROUP_SIZE_ID]           FLOAT          NULL,
    [JUDGEMENT_ID]            NVARCHAR (255) NULL,
    [JUDGEMENT_DETAIL]        NVARCHAR (255) NULL,
    [BUSI_RISK1_ID]           NVARCHAR (255) NULL,
    [BUSI_RISK1_DETAIL]       NVARCHAR (255) NULL,
    [BUSI_RISK2_ID]           NVARCHAR (255) NULL,
    [BUSI_RISK2_DETAIL]       NVARCHAR (255) NULL,
    [BUSI_RISK3_ID]           NVARCHAR (255) NULL,
    [BUSI_RISK3_DETAIL]       NVARCHAR (255) NULL,
    [UPDATE_BY]               NVARCHAR (255) NULL,
    [UPDATE_BY_NAME]          NVARCHAR (255) NULL,
    [UPDATE_DATE]             FLOAT          NULL,
    [BUSI_TYPE_CIM]           NVARCHAR (255) NULL,
    [DEPTFLAG]                FLOAT          NULL,
    [DEPTTRAN]                FLOAT          NULL,
    [OFFICR_ID]               NVARCHAR (255) NULL,
    [OFFICR_NAME]             NVARCHAR (255) NULL,
    [CONTROLLING_UNIT]        NVARCHAR (255) NULL,
    [CONTROLLING_UNIT_E]      NVARCHAR (255) NULL,
    [REGION_CONTROLLING_UNIT] NVARCHAR (255) NULL,
    [SIZE_ID]                 FLOAT          NULL
);

