CREATE TABLE [dbo].[ANNALS_CHANGE_TO_COMMON] (
    [ID]          NVARCHAR (10)  NULL,
    [CHANGE_DATE] DATETIME       NOT NULL,
    [SUBJECT]     NVARCHAR (100) NULL,
    [DETAIL]      NVARCHAR (MAX) NULL
);

