CREATE TABLE [dbo].[Id_Branch_ton] (
    [Id_Branch]              SMALLINT       NULL,
    [Branch_T]               NVARCHAR (60)  NULL,
    [Branch_E]               NVARCHAR (60)  NULL,
    [Id_RegSub]              SMALLINT       NULL,
    [Id_Region]              SMALLINT       NULL,
    [Region_Name]            NVARCHAR (25)  NULL,
    [Region_NameE]           NVARCHAR (25)  NULL,
    [Up]                     NVARCHAR (10)  NULL,
    [Up_name]                NVARCHAR (50)  NULL,
    [Section]                TINYINT        NULL,
    [Section_Name]           NVARCHAR (50)  NULL,
    [Section_Id_Controlling] INT            NULL,
    [Section_Controlling]    NVARCHAR (50)  NULL,
    [RegionType]             NVARCHAR (5)   NULL,
    [Id_Hub]                 INT            NULL,
    [Hub_Name_T]             NVARCHAR (50)  NULL,
    [Center]                 NVARCHAR (50)  NULL,
    [BotCond]                BIT            NOT NULL,
    [CityCode]               TINYINT        NULL,
    [Area]                   INT            NULL,
    [***********]            NVARCHAR (1)   NULL,
    [Id_RegSub_V1]           SMALLINT       NULL,
    [Id_Region_V1]           SMALLINT       NULL,
    [Region_Name_V1]         NVARCHAR (25)  NULL,
    [Region_NameE_V1]        NVARCHAR (25)  NULL,
    [Id_HubSort_V1]          INT            NULL,
    [Id_Hub_V1]              INT            NULL,
    [Hub_Name_T_V1]          NVARCHAR (50)  NULL,
    [Hub_Name_E_V1]          NVARCHAR (50)  NULL,
    [Hub_Province_V1]        NVARCHAR (25)  NULL,
    [Id_RegG]                TINYINT        NULL,
    [RegG_Name]              NVARCHAR (25)  NULL,
    [RegG_NameE]             NVARCHAR (25)  NULL,
    [Region_GroupT]          NVARCHAR (35)  NULL,
    [Region_GroupE]          NVARCHAR (35)  NULL,
    [Id_Region_GroupE1]      TINYINT        NULL,
    [Region_GroupE1]         NVARCHAR (35)  NULL,
    [Id_Region_GroupE2]      TINYINT        NULL,
    [Region_GroupE2]         NVARCHAR (35)  NULL,
    [Id_Province]            SMALLINT       NULL,
    [Province]               NVARCHAR (50)  NULL,
    [ProvinceE]              NVARCHAR (50)  NULL,
    [Id_ProGDPE]             NVARCHAR (15)  NULL,
    [Addres]                 NVARCHAR (100) NULL,
    [Post]                   NVARCHAR (10)  NULL,
    [Tel]                    NVARCHAR (50)  NULL,
    [DateOpen]               NVARCHAR (15)  NULL
);

