CREATE TABLE [dbo].[TB_PROVINCE] (
    [PROV_CODE]   INT           NOT NULL,
    [PROV_NAME]   NVARCHAR (50) NULL,
    [PROV_NAME_E] NVARCHAR (50) NULL,
    [ZONE_CODE]   NVARCHAR (10) NULL,
    [AREA_CODE]   NVARCHAR (2)  NOT NULL
);

