CREATE TABLE [dbo].[Temp_Seng_Toey_20120201] (
    [ID]                   NVARCHAR (255) NULL,
    [REG-DATE]             DATETIME       NULL,
    [APP-DATE]             DATETIME       NULL,
    [APP-YEAR]             INT            NULL,
    [APP-MONTH]            INT            NULL,
    [CIF]                  INT            NULL,
    [CUSTOMER]             NVARCHAR (255) NULL,
    [EMP-ID]               NVARCHAR (255) NULL,
    [EMPLOYEE]             NVARCHAR (255) NULL,
    [BRANCH-ID]            NVARCHAR (255) NULL,
    [BRANCH-NAME]          NVARCHAR (255) NULL,
    [REGION-ID]            NVARCHAR (255) NULL,
    [REGION-NAME]          NVARCHAR (255) NULL,
    [NEW]                  FLOAT          NULL,
    [OLD]                  FLOAT          NULL,
    [REVIEW]               FLOAT          NULL,
    [EXCEPTION]            FLOAT          NULL,
    [CREDIT_LINE]          FLOAT          NULL,
    [O-D]                  FLOAT          NULL,
    [(O-D)]                FLOAT          NULL,
    [F-L]                  FLOAT          NULL,
    [(F-L)]                FLOAT          NULL,
    [L-G]                  FLOAT          NULL,
    [(L-G)]                FLOAT          NULL,
    [STL-PN]               FLOAT          NULL,
    [(STL-PN)]             FLOAT          NULL,
    [TRADE-FIN]            FLOAT          NULL,
    [(TRADE-FIN)]          FLOAT          NULL,
    [OTHERS]               FLOAT          NULL,
    [(OTHERS)]             FLOAT          NULL,
    [SUM-INCREASE]         FLOAT          NULL,
    [SUM-DECREASE]         FLOAT          NULL,
    [NET]                  FLOAT          NULL,
    [SUM-RM_VALUE]         FLOAT          NULL,
    [PROCESS_HEAD]         NVARCHAR (255) NULL,
    [PROCESS_GROUP]        NVARCHAR (255) NULL,
    [PROCESS]              NVARCHAR (255) NULL,
    [TTY_SME(S)]           FLOAT          NULL,
    [TTY_SME(M)]           FLOAT          NULL,
    [APP-TYPE]             NVARCHAR (255) NULL,
    [LEVEL_NAME]           NVARCHAR (255) NULL,
    [Job_Type]             NVARCHAR (255) NULL,
    [Authority]            NVARCHAR (255) NULL,
    [REFERRAL_NO]          NVARCHAR (255) NULL,
    [REFERENCE]            NVARCHAR (255) NULL,
    [Board]                NVARCHAR (255) NULL,
    [LEVEL_PROCESS_ID]     NVARCHAR (255) NULL,
    [BUSINESS_ID]          NVARCHAR (255) NULL,
    [BUSINESS_TYPE]        NVARCHAR (255) NULL,
    [Customer_Size]        NVARCHAR (255) NULL,
    [SIZE_DETAIL]          NVARCHAR (255) NULL,
    [EMP_APPROVE]          NVARCHAR (255) NULL,
    [EMP_APPROVE2]         NVARCHAR (255) NULL,
    [LIM_AMT]              FLOAT          NULL,
    [BRANCH_NAME]          NVARCHAR (255) NULL,
    [Out_Of_Scope]         NVARCHAR (255) NULL,
    [principal]            FLOAT          NULL,
    [grp_lim]              FLOAT          NULL,
    [grp_coll]             FLOAT          NULL,
    [LTV_S]                FLOAT          NULL,
    [cons_ltv]             FLOAT          NULL,
    [GROUP_SIZE_ID]        FLOAT          NULL,
    [GROUP_SIZE_DETAIL]    NVARCHAR (255) NULL,
    [REGION_NEW]           NVARCHAR (255) NULL,
    [Region_Code]          NVARCHAR (255) NULL,
    [Class]                NVARCHAR (255) NULL,
    [HEAD_EMP_ID]          NVARCHAR (255) NULL,
    [HEAD_TITLE_NAME]      NVARCHAR (255) NULL,
    [HEAD_EMPNAME]         NVARCHAR (255) NULL,
    [HEAD_EMPSURNAME]      NVARCHAR (255) NULL,
    [HEAD_TITLE_NAME_E]    NVARCHAR (255) NULL,
    [HEAD_EMPNAME_E]       NVARCHAR (255) NULL,
    [HEAD_EMPSURNAME_E]    NVARCHAR (255) NULL,
    [MANAGER_EMP_ID]       NVARCHAR (255) NULL,
    [MANAGER_TITLE_NAME]   NVARCHAR (255) NULL,
    [MANAGER_EMPNAME]      NVARCHAR (255) NULL,
    [MANAGER_EMPSURNAME]   NVARCHAR (255) NULL,
    [MANAGER_TITLE_NAME_E] NVARCHAR (255) NULL,
    [MANAGER_EMPNAME_E]    NVARCHAR (255) NULL,
    [MANAGER_EMPSURNAME_E] NVARCHAR (255) NULL
);

