CREATE TABLE [dbo].[SME_GROUP_EXPOSURE] (
    [EXPOSURE_ID]      INT             IDENTITY (1, 1) NOT NULL,
    [EXPOSURE_TYPE_ID] INT             NOT NULL,
    [TOTAL_EXPOSURE]   NUMERIC (20, 2) NULL,
    [TOTAL_APPRAISAL]  NUMERIC (20, 2) NULL,
    [UPDATE_DATE]      DATETIME        NOT NULL,
    [UPDATE_BY]        NVARCHAR (10)   NOT NULL
);

