CREATE TABLE [dbo].[ByAccDaily_541121] (
    [Cif]           INT           NULL,
    [PKAcc]         NVARCHAR (48) NULL,
    [Branch]        SMALLINT      NULL,
    [Busi_Type]     INT           NULL,
    [DEPT_APPV]     INT           NULL,
    [GLGroup]       NVARCHAR (15) NULL,
    [PDGroup]       NVARCHAR (6)  NULL,
    [ACCGL]         INT           NULL,
    [ACCNO]         NVARCHAR (16) NULL,
    [CONTNO]        NVARCHAR (13) NULL,
    [SEQNO]         INT           NULL,
    [AGING]         MONEY         NULL,
    [ADJCLASS]      NVARCHAR (1)  NULL,
    [CLADJ]         NVARCHAR (1)  NULL,
    [Limit]         MONEY         NULL,
    [LimitApp]      MONEY         NULL,
    [PrincipalFull] MONEY         NULL,
    [PrinFMS]       MONEY         NULL,
    [Principal]     MONEY         NULL,
    [AccruFull]     MONEY         NULL,
    [AccruFMS]      MONEY         NULL,
    [Accru]         MONEY         NULL,
    [SuspOri]       MONEY         NULL,
    [Susp]          MONEY         NULL,
    [UNEARNPRIN]    MONEY         NULL,
    [UNEARNINT]     MONEY         NULL,
    [UNCLEAPRIN]    MONEY         NULL,
    [UNCLEAINT]     MONEY         NULL,
    [DEFER]         MONEY         NULL,
    [PAY_PRIN]      MONEY         NULL,
    [PAY_INT]       MONEY         NULL,
    [PAY_SUSP]      MONEY         NULL,
    [INT_RATE]      MONEY         NULL,
    [RATE_TYPE]     NVARCHAR (3)  NULL,
    [SIGN]          NVARCHAR (1)  NULL,
    [RATE_LOAD]     MONEY         NULL,
    [OPEN_ACC]      DATETIME      NULL,
    [DUE_DATE]      DATETIME      NULL,
    [ISSU_DATE]     DATETIME      NULL,
    [LPAY_DATE]     DATETIME      NULL,
    [APP_ID]        NVARCHAR (3)  NULL
);

