CREATE TABLE [dbo].[Id_DepBranch] (
    [Status]             NVARCHAR (1)  NULL,
    [Flag]               TINYINT       NOT NULL,
    [Id_DepTran]         INT           NOT NULL,
    [DepTranT]           NVARCHAR (70) NULL,
    [DepTranE]           NVARCHAR (70) NULL,
    [Id_Lending]         INT           NULL,
    [LendingT]           NVARCHAR (50) NULL,
    [LendingE]           NVARCHAR (70) NULL,
    [Id_LendingSubSort]  INT           NULL,
    [Id_LendingSub]      INT           NULL,
    [LendingSubT]        NVARCHAR (50) NULL,
    [LendingSubE]        NVARCHAR (70) NULL,
    [Id_LendingSubSort1] INT           NULL,
    [Id_LendingSub1]     INT           NULL,
    [LendingSubT1]       NVARCHAR (50) NULL,
    [LendingSubE1]       NVARCHAR (70) NULL,
    [Id_Province]        SMALLINT      NULL,
    [ProvinceT]          NVARCHAR (50) NULL,
    [ProvinceE]          NVARCHAR (50) NULL,
    [Id_Head]            TINYINT       NULL,
    [Head]               NVARCHAR (25) NULL,
    [CustSizeControl]    NVARCHAR (9)  NULL,
    [Id_Region]          INT           NULL,
    [Region]             NVARCHAR (20) NULL,
    [Id_HubSort]         INT           NULL,
    [Id_Hub]             INT           NULL,
    [Hub_Name_T]         NVARCHAR (50) NULL,
    [Hub_Name_E]         NVARCHAR (50) NULL,
    [Hub_Province]       NVARCHAR (25) NULL,
    [Id_BU]              INT           NULL,
    [BU]                 NVARCHAR (50) NULL
);

