CREATE TABLE [dbo].[Detail] (
    [Cif]              INT            NOT NULL,
    [Name]             NVARCHAR (60)  NULL,
    [BOTID]            INT            NULL,
    [Tdr]              NVARCHAR (6)   NULL,
    [Branch]           SMALLINT       NULL,
    [Branch_T]         NVARCHAR (50)  NULL,
    [Class]            NVARCHAR (1)   NULL,
    [ByCustomer_AGING] MONEY          NULL,
    [ByCusDaily_AGING] MONEY          NULL,
    [AgingTxt]         NVARCHAR (30)  NULL,
    [Principal]        MONEY          NULL,
    [Accru]            MONEY          NULL,
    [Susp]             MONEY          NULL,
    [PAY_PRIN]         MONEY          NULL,
    [PAY_INT]          MONEY          NULL,
    [PAY_SUSP]         MONEY          NULL,
    [Id_Group]         INT            NULL,
    [Group]            NVARCHAR (50)  NULL,
    [Id_Part]          INT            NULL,
    [Part_Name]        NVARCHAR (30)  NULL,
    [Id_Region]        INT            NULL,
    [Region_Name]      NVARCHAR (30)  NULL,
    [CUS_DEPT_FLAG]    TINYINT        NULL,
    [CUS_DEPT_TRAN]    INT            NULL,
    [Dep]              NVARCHAR (50)  NULL,
    [OFFICR_ID]        INT            NULL,
    [Office]           NVARCHAR (100) NULL
);

