CREATE TABLE [dbo].[CUSTOMER_SME_RATING_TYPE] (
    [RATING_TYPE_KEY]  INT           IDENTITY (1, 1) NOT NULL,
    [RATING_TYPE_CODE] NVARCHAR (10) NULL,
    [RATING_TYPE_DESC] NVARCHAR (50) NULL,
    [PRIORITY]         INT           NULL
);

