CREATE TABLE [dbo].[TBDASOF] (
    [TB_TABLE]   NVARCHAR (50) NOT NULL,
    [OLDDASOF]   SMALLDATETIME NULL,
    [DASOF]      SMALLDATETIME NULL,
    [DAY_ASOF]   TINYINT       NULL,
    [MONTH_ASOF] TINYINT       NULL,
    [YEAR_ASOF]  SMALLINT      NULL,
    [UP_DT]      SMALLDATETIME NULL
);

