CREATE TABLE [dbo].[CLS_WHEN_APPROVE_BACKUP_20100310] (
    [ID_KEY]                       INT             IDENTITY (1, 1) NOT NULL,
    [CIF]                          NUMERIC (20)    NOT NULL,
    [LEADER1_CA_OLD_ID]            NVARCHAR (10)   NOT NULL,
    [CLS_LIMIT_ROOT_ID_KEY]        NUMERIC (10)    NULL,
    [CLS_LIMIT_L1_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_LIMIT_L2_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_LIMIT_L3_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_LIMIT_L4_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_LIMIT_L5_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_LIMIT_L6_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_LIMIT_L7_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_LIMIT_L8_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_LIMIT_PRODUCT_ID_KEY]     NUMERIC (10)    NULL,
    [PRODUCT_KEY]                  NUMERIC (10)    NULL,
    [CLS_PRODUCT_ID_KEY]           NUMERIC (10)    NULL,
    [LIMIT_STATUS_ID_KEY]          NUMERIC (10)    NULL,
    [CLS_CURRENCY_ID_KEY]          NUMERIC (10)    NULL,
    [LIMIT_PURPOSE_ID_KEY]         NUMERIC (10)    NULL,
    [BUSINESS_RISK_ID_KEY]         NUMERIC (10)    NULL,
    [CA_KEY]                       NUMERIC (10)    NULL,
    [CREATED_BY_USER_CODE]         VARCHAR (10)    NULL,
    [CREATED_BY_USER_NAME]         VARCHAR (100)   NULL,
    [UPDATED_BY_USER_CODE]         VARCHAR (10)    NULL,
    [UPDATED_BY_USER_NAME]         VARCHAR (100)   NULL,
    [UPDATED_STATUS_BY_USER_CODE]  VARCHAR (10)    NULL,
    [UPDATED_STATUS_BY_USER_NAME]  VARCHAR (100)   NULL,
    [LIMIT_NO_ROOT]                NUMERIC (18)    NULL,
    [LIMIT_NO_L1]                  NUMERIC (18)    NULL,
    [LIMIT_NO_L2]                  NUMERIC (18)    NULL,
    [LIMIT_NO_L3]                  NUMERIC (18)    NULL,
    [LIMIT_NO_L4]                  NUMERIC (18)    NULL,
    [LIMIT_NO_L5]                  NUMERIC (18)    NULL,
    [LIMIT_NO_L6]                  NUMERIC (18)    NULL,
    [LIMIT_NO_L7]                  NUMERIC (18)    NULL,
    [LIMIT_NO_L8]                  NUMERIC (18)    NULL,
    [LIMIT_NO_PRODUCT]             NUMERIC (18)    NULL,
    [LIMIT_ROOT_STATUS]            VARCHAR (1)     NULL,
    [LIMIT_L1_STATUS]              VARCHAR (1)     NULL,
    [LIMIT_L2_STATUS]              VARCHAR (1)     NULL,
    [LIMIT_L3_STATUS]              VARCHAR (1)     NULL,
    [LIMIT_L4_STATUS]              VARCHAR (1)     NULL,
    [LIMIT_L5_STATUS]              VARCHAR (1)     NULL,
    [LIMIT_L6_STATUS]              VARCHAR (1)     NULL,
    [LIMIT_L7_STATUS]              VARCHAR (1)     NULL,
    [LIMIT_L8_STATUS]              VARCHAR (1)     NULL,
    [LIMIT_PRODUCT_STATUS]         VARCHAR (1)     NULL,
    [LIMIT_REVOLVING_TYPE]         VARCHAR (1)     NULL,
    [APPL_KEY]                     VARCHAR (50)    NULL,
    [APPL_ID]                      VARCHAR (5)     NULL,
    [PRODUCT_CODE]                 VARCHAR (20)    NULL,
    [PRODUCT_NAME]                 VARCHAR (50)    NULL,
    [ACCOUNT_NO]                   VARCHAR (100)   NULL,
    [CIF_LIST_CA_NO]               VARCHAR (1000)  NULL,
    [CIF_LIST_ROOT]                VARCHAR (1000)  NULL,
    [CIF_LIST_PRODUCT]             VARCHAR (1000)  NULL,
    [NO_OF_CIF_CANO]               NUMERIC (38)    NULL,
    [LIMIT_AMOUNT_ROOT_THB]        NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_ROOT_CCY]        NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L1_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L1_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L2_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L2_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L3_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L3_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L4_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L4_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L5_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L5_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L6_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L6_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L7_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L7_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L8_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_L8_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_PRODUCT_THB]     NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_PRODUCT_CCY]     NUMERIC (20, 2) NULL,
    [LIMIT_USED_ROOT_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_USED_ROOT_CCY]          NUMERIC (20, 2) NULL,
    [LIMIT_USED_L1_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L1_CCY]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L2_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L2_CCY]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L3_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L3_CCY]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L4_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L4_CCY]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L5_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L5_CCY]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L6_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L6_CCY]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L7_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L7_CCY]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L8_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_L8_CCY]            NUMERIC (20, 2) NULL,
    [LIMIT_USED_PRODUCT_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_USED_PRODUCT_CCY]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_ROOT_THB]     NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_L1_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_L2_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_L3_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_L4_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_L5_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_L6_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_L7_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_L8_THB]       NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_PRODUCT_THB]  NUMERIC (20, 2) NULL,
    [LIMIT_AVAI_RATIO_L1_THB]      NUMERIC (38, 2) NULL,
    [LIMIT_AVAI_RATIO_L2_THB]      NUMERIC (38, 2) NULL,
    [LIMIT_AVAI_RATIO_L3_THB]      NUMERIC (38, 2) NULL,
    [LIMIT_AVAI_RATIO_L4_THB]      NUMERIC (38, 2) NULL,
    [LIMIT_AVAI_RATIO_L5_THB]      NUMERIC (38, 2) NULL,
    [LIMIT_AVAI_RATIO_L6_THB]      NUMERIC (38, 2) NULL,
    [LIMIT_AVAI_RATIO_L7_THB]      NUMERIC (38, 2) NULL,
    [LIMIT_AVAI_RATIO_L8_THB]      NUMERIC (38, 2) NULL,
    [LIMIT_AVAI_RATIO_PRODUCT_THB] NUMERIC (38, 2) NULL,
    [HOLD_AMOUNT_THB]              NUMERIC (20, 2) NULL,
    [HOLD_AMOUNT_CCY]              NUMERIC (20, 2) NULL,
    [LIMIT_AMOUNT_CA_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_USED_CA_THB]            NUMERIC (20, 2) NULL,
    [LIMIT_AVAILABLE_CA_THB]       NUMERIC (20, 2) NULL,
    [GECID]                        NUMERIC (8)     NULL,
    [CREATED_DATE]                 DATETIME        NULL,
    [UPDATE_DATE]                  DATETIME        NULL,
    [UPDATE_STATUS_DATE]           DATETIME        NULL,
    [ASOFDATE]                     DATETIME        NULL,
    [ETL_DT]                       DATETIME        NULL,
    [LIMIT_PRODUCT_CA_NO]          NVARCHAR (40)   NULL,
    [LIMIT_PRODUCT_CA_DATE]        DATETIME        NULL,
    [LIMIT_PRODUCT_APPV_DATE]      DATETIME        NULL,
    [LIMIT_PRODUCT_APPV_AUTH_UNIT] NVARCHAR (100)  NULL,
    [LIMIT_PRODUCT_PREVIOUS_CA_NO] NVARCHAR (40)   NULL,
    [LIMIT_PRODUCT_EFFECT_DATE]    DATETIME        NULL,
    [LIMIT_PRODUCT_EXPIRE_DATE]    DATETIME        NULL,
    [LIMIT_PRODUCT_SIGN_DATE]      DATETIME        NULL,
    [LIMIT_CHANGE_ROOT_THB]        NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_L1_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_L2_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_L3_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_L4_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_L5_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_L6_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_L7_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_L8_THB]          NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_PRODUCT_THB]     NUMERIC (20, 2) NULL,
    [LIMIT_CHANGE_DATE]            DATETIME        NULL,
    [MAPPING_STATUS]               NVARCHAR (1)    NULL,
    [LEADER1_CREATED_DATE]         DATETIME        NULL,
    [LEADER1_UPDATE_DATE]          DATETIME        NULL
);

