CREATE TABLE [dbo].[ANNALS_CREDIT] (
    [ID]                 NVARCHAR (10)  NOT NULL,
    [ANNALS_TYPE]        NVARCHAR (1)   NULL,
    [ANNALS_SEQ_NO]      NVARCHAR (5)   NULL,
    [ANNALS_YEAR]        NVARCHAR (4)   NULL,
    [ID_OUT]             NVARCHAR (11)  NULL,
    [EMP_APPROVE_ID]     NVARCHAR (10)  NULL,
    [EMP_REQUEST_ID]     NVARCHAR (10)  NULL,
    [EMP_APPROVE2_ID]    NVARCHAR (10)  NULL,
    [Send_To_Board]      NVARCHAR (2)   NULL,
    [BOARD_ID]           NVARCHAR (2)   NULL,
    [BOARD_Others]       NVARCHAR (50)  NULL,
    [RM_ID]              NVARCHAR (10)  NULL,
    [BRANCH_ID]          NVARCHAR (10)  NULL,
    [Flag]               NVARCHAR (1)   NULL,
    [DEP_ID]             NVARCHAR (10)  NULL,
    [REGION_ID]          NVARCHAR (10)  NULL,
    [Others]             NVARCHAR (MAX) NULL,
    [Others2]            NVARCHAR (MAX) NULL,
    [Result]             NVARCHAR (50)  NULL,
    [Comment]            NVARCHAR (10)  NULL,
    [CM_Judgement]       NVARCHAR (10)  NULL,
    [CM_Judgement_Board] NVARCHAR (10)  NULL,
    [CM_Remark]          NVARCHAR (MAX) NULL,
    [Reason]             NVARCHAR (MAX) NULL,
    [Reason2]            NVARCHAR (MAX) NULL,
    [Job_Type_Id]        NVARCHAR (2)   NULL,
    [SME_Referral_No]    NVARCHAR (11)  NULL,
    [Customer_Size]      NVARCHAR (2)   NULL,
    [EMP_APPROVE3_ID]    NVARCHAR (10)  NULL,
    [EMP_APPROVE4_ID]    NVARCHAR (10)  NULL,
    [COVENANT_FLAG]      NVARCHAR (1)   NULL,
    [DO_KFS_FLAG]        NVARCHAR (1)   NULL,
    [SUB_COMMITTEE_1]    NVARCHAR (10)  NULL,
    [SUB_COMMITTEE_2]    NVARCHAR (10)  NULL,
    [SUB_COMMITTEE_3]    NVARCHAR (10)  NULL,
    [APPROVE_CUS_TYPE]   NVARCHAR (1)   NULL,
    [APPROVE_INC_TYPE]   NVARCHAR (1)   NULL,
    [OUT_OF_SCOPE_ID]    NVARCHAR (1)   NULL,
    [GROUP_EXPOSURE]     MONEY          NULL,
    [REVIEW_DATE]        DATETIME       NULL,
    [EMP_CONTROL]        NVARCHAR (10)  NULL
);

