CREATE TABLE [dbo].[BUSINESS_TYPE_2] (
    [TYPE2_ID]       VARCHAR (4)    NOT NULL,
    [RESEARCH_CODE]  VARCHAR (8)    NOT NULL,
    [DESCRIPTION]    NVARCHAR (255) NOT NULL,
    [DESCRIPTION_EN] VARCHAR (255)  NOT NULL,
    [TYPE1_ID]       VARCHAR (2)    NOT NULL,
    [NOTE]           CHAR (1)       NOT NULL,
    [PRIORITY]       INT            NOT NULL,
    [UPDATE_BY]      NVARCHAR (10)  NOT NULL,
    [UPDATE_DATE]    DATETIME       NOT NULL
);

