CREATE TABLE [dbo].[PORT_20110404] (
    [CIF]           INT            NULL,
    [Name]          NVARCHAR (255) NULL,
    [BaySize]       NVARCHAR (255) NULL,
    [Rating]        NVARCHAR (255) NULL,
    [BranchMaxPrin] FLOAT          NULL,
    [AgingMax]      FLOAT          NULL,
    [Class]         NVARCHAR (255) NULL,
    [ClassE]        NVARCHAR (255) NULL,
    [Prin_Cash]     FLOAT          NULL,
    [Prin_Cash MB]  FLOAT          NULL,
    [Contingent]    FLOAT          NULL,
    [CusDeptFlag]   FLOAT          NULL,
    [CusDeptTran]   FLOAT          NULL,
    [NplFlag]       NVARCHAR (255) NULL,
    [TdrFlag]       NVARCHAR (255) NULL,
    [MCIF]          FLOAT          NULL,
    [NUMCUST]       FLOAT          NULL,
    [LIM_AMT]       FLOAT          NULL,
    [LIM_USE_TB]    FLOAT          NULL,
    [LIM_AVAL]      FLOAT          NULL,
    [GLIM_AVAL]     FLOAT          NULL,
    [LIM_REV]       FLOAT          NULL,
    [LIM_NREV]      FLOAT          NULL,
    [PRINCIPAL]     FLOAT          NULL,
    [SING_LIM]      FLOAT          NULL,
    [GSING_LIM]     FLOAT          NULL,
    [GRP_LIM]       FLOAT          NULL,
    [GRP_LIM_1]     NVARCHAR (255) NULL,
    [GRP_LIM_2]     NVARCHAR (255) NULL,
    [group rank]    FLOAT          NULL,
    [GRP_COLL]      FLOAT          NULL,
    [LTV]           FLOAT          NULL,
    [MIX_LINE]      NVARCHAR (255) NULL,
    [JOINT_LINE]    NVARCHAR (255) NULL,
    [COLL_CO]       NVARCHAR (255) NULL,
    [G_COLL]        FLOAT          NULL,
    [COLL_DEPO]     FLOAT          NULL,
    [COLL_NDEPO]    FLOAT          NULL,
    [CONS_LTV]      FLOAT          NULL,
    [LEAS_MAC]      FLOAT          NULL,
    [OVER_AUT]      FLOAT          NULL,
    [BizE]          NVARCHAR (255) NULL,
    [Port]          NVARCHAR (255) NULL,
    [Port1]         NVARCHAR (255) NULL,
    [KFS Domain]    NVARCHAR (255) NULL,
    [KFS Flag]      NVARCHAR (255) NULL,
    [Rating Flag]   NVARCHAR (255) NULL,
    [CM Name]       NVARCHAR (255) NULL,
    [Corp lead]     NVARCHAR (255) NULL,
    [Corp CM Name]  NVARCHAR (255) NULL,
    [CM Name New]   NVARCHAR (255) NULL,
    [Branch Name]   NVARCHAR (255) NULL,
    [Branch RM]     INT            NULL,
    [NEW CM ID]     NVARCHAR (10)  NOT NULL,
    [NEW CM NAME]   NVARCHAR (255) NULL
);

