CREATE TABLE [dbo].[TEMP_LastCA_LastNCB_2010] (
    [CIF_No]             INT            NULL,
    [Customer_Name]      NVARCHAR (255) NULL,
    [LRequest_Date]      DATETIME       NULL,
    [LResponse_Date]     DATETIME       NULL,
    [NCB_date]           NVARCHAR (255) NULL,
    [REFERENCE_DATE]     DATETIME       NULL,
    [CA_CREATE_DATE]     DATETIME       NULL,
    [Register_date]      NVARCHAR (255) NULL,
    [APPROVE_DATE]       DATETIME       NULL,
    [Apprv_date]         NVARCHAR (255) NULL,
    [OLD_ID]             NVARCHAR (10)  NULL,
    [CA_NO_ID]           NVARCHAR (9)   NULL,
    [REFERENCE]          NVARCHAR (100) NULL,
    [CIF]                INT            NULL,
    [OLD_VALUEs]         MONEY          NULL,
    [RM_VALUEs]          MONEY          NULL,
    [CM_VALUEs]          MONEY          NULL,
    [APPROVE_VALUEs]     MONEY          NULL,
    [REJECT_DATE]        DATETIME       NULL,
    [REJECT_REASON]      NVARCHAR (200) NULL,
    [LAST_PROCESS]       NVARCHAR (200) NULL,
    [LAST_PROCESS_ID]    NVARCHAR (4)   NULL,
    [LAST_PROCESS_GROUP] NVARCHAR (1)   NULL,
    [LAST_PROCESS_DATE]  DATETIME       NULL,
    [LP_END_OF_MONTH]    DATETIME       NULL,
    [EMP_ID]             NVARCHAR (10)  NULL,
    [EMPNAME]            NVARCHAR (120) NULL,
    [LEVEL_ID]           NVARCHAR (20)  NULL,
    [LEVEL_NAME]         NVARCHAR (255) NULL,
    [NEW_CUS]            NVARCHAR (3)   NULL,
    [Reason]             NVARCHAR (255) NULL,
    [Customer_Size]      NVARCHAR (2)   NULL,
    [SIZE_DETAIL]        NVARCHAR (50)  NULL,
    [SUBJECT_GROUP]      NVARCHAR (8)   NULL,
    [RECIVER]            NVARCHAR (255) NULL,
    [Send_To_Board]      NVARCHAR (2)   NULL,
    [Authority]          NVARCHAR (255) NULL,
    [EMP_REQUEST_ID]     NVARCHAR (10)  NULL,
    [EMP_REQUEST_NAME]   NVARCHAR (120) NULL,
    [EMP_APPROVE_ID]     NVARCHAR (10)  NULL,
    [EMP_APPROVE1_NAME]  NVARCHAR (120) NULL,
    [EMP_APPROVE2_ID]    NVARCHAR (10)  NULL,
    [EMP_APPROVE2_NAME]  NVARCHAR (120) NULL,
    [EMP_APPROVE3_ID]    NVARCHAR (10)  NULL,
    [EMP_APPROVE3_NAME]  NVARCHAR (120) NULL,
    [EMP_APPROVE4_ID]    NVARCHAR (10)  NULL,
    [EMP_APPROVE4_NAME]  NVARCHAR (120) NULL,
    [SUB_COMMITTEE_1]    NVARCHAR (10)  NULL,
    [EMP_SUB_COMM1_NAME] NVARCHAR (120) NULL,
    [SUB_COMMITTEE_2]    NVARCHAR (10)  NULL,
    [EMP_SUB_COMM2_NAME] NVARCHAR (120) NULL,
    [SUB_COMMITTEE_3]    NVARCHAR (10)  NULL,
    [EMP_SUB_COMM3_NAME] NVARCHAR (120) NULL
);

