CREATE TABLE [dbo].[Temp_Report_Chart] (
    [ID]               NVARCHAR (10)   NOT NULL,
    [REG-DATE]         DATETIME        NULL,
    [APP-DATE]         DATETIME        NULL,
    [CIF]              INT             NULL,
    [CUSTOMER]         NVARCHAR (71)   NULL,
    [EMP-ID]           NVARCHAR (10)   NULL,
    [EMPLOYEE]         VARCHAR (121)   NULL,
    [BRANCH-ID]        NVARCHAR (10)   NULL,
    [BRANCH-NAME]      NVARCHAR (50)   NULL,
    [REGION-ID]        NVARCHAR (10)   NULL,
    [REGION-NAME]      NVARCHAR (30)   NULL,
    [NEW]              INT             NOT NULL,
    [OLD]              INT             NOT NULL,
    [REVIEW]           INT             NOT NULL,
    [EXCEPTION]        INT             NOT NULL,
    [APPROVE]          INT             NOT NULL,
    [O-D]              MONEY           NULL,
    [(O-D)]            MONEY           NULL,
    [F-L]              MONEY           NULL,
    [(F-L)]            MONEY           NULL,
    [L-G]              MONEY           NULL,
    [(L-G)]            MONEY           NULL,
    [STL-PN]           MONEY           NULL,
    [(STL-PN)]         MONEY           NULL,
    [TRADE-FIN]        MONEY           NULL,
    [(TRADE-FIN)]      MONEY           NULL,
    [OTHERS]           MONEY           NULL,
    [(OTHERS)]         MONEY           NULL,
    [SUM-INCREASE]     MONEY           NULL,
    [SUM-DECREASE]     MONEY           NULL,
    [NET]              MONEY           NULL,
    [SUM-RM_VALUE]     MONEY           NULL,
    [PROCESS_HEAD]     NVARCHAR (100)  NULL,
    [PROCESS_GROUP]    CHAR (1)        NULL,
    [PROCESS]          NVARCHAR (200)  NULL,
    [TTY]              NUMERIC (18, 7) NULL,
    [PAT]              NUMERIC (18, 7) NULL,
    [APP-TYPE]         VARCHAR (30)    NOT NULL,
    [LEVEL_NAME]       NVARCHAR (255)  NULL,
    [JOB_TYPE]         NVARCHAR (50)   NULL,
    [AUTHORITY]        NVARCHAR (255)  NULL,
    [REFERRAL_NO]      NVARCHAR (11)   NULL,
    [REFERENCE]        NVARCHAR (100)  NULL,
    [BOARD]            NVARCHAR (100)  NULL,
    [LEVEL_PROCESS_ID] NVARCHAR (20)   NULL,
    [Business_ID]      NVARCHAR (6)    NULL,
    [Business_Type]    NVARCHAR (255)  NULL,
    [Customer_Size]    NVARCHAR (2)    NULL,
    [SIZE_DETAIL]      NVARCHAR (50)   NULL,
    [reason_remark]    NVARCHAR (MAX)  NULL,
    [result_remark]    NVARCHAR (MAX)  NULL,
    [EMP_APPROVE_ID]   NVARCHAR (10)   NULL,
    [EMP_APPROVE2_ID]  NVARCHAR (10)   NULL
);

