CREATE TABLE [dbo].[CA_P200_P300_P400_FROM_LEADER_SME] (
    [CA_ID]                     VARCHAR (12)   NOT NULL,
    [YEAR_LETTER]               VARCHAR (4)    NOT NULL,
    [ID_ABOUTCIF]               CHAR (1)       NOT NULL,
    [ABOUTCIF]                  NVARCHAR (30)  NULL,
    [GROUP_ID]                  NVARCHAR (10)  NULL,
    [GROUP_NAME]                NVARCHAR (200) NULL,
    [ID_SUBJECT]                CHAR (5)       NULL,
    [SUBJECT]                   NVARCHAR (100) NULL,
    [SUBJECT_DETAIL]            NVARCHAR (100) NULL,
    [DETAIL]                    TEXT           NULL,
    [DAY_LETTER]                DATETIME       NULL,
    [CIF]                       INT            NULL,
    [NAME]                      NVARCHAR (100) NULL,
    [CIF1]                      INT            NULL,
    [NAME1]                     NVARCHAR (100) NULL,
    [CIF2]                      INT            NULL,
    [NAME2]                     NVARCHAR (100) NULL,
    [CIF3]                      INT            NULL,
    [NAME3]                     NVARCHAR (100) NULL,
    [CIF4]                      INT            NULL,
    [NAME4]                     NVARCHAR (100) NULL,
    [FROM_BR]                   SMALLINT       NULL,
    [Branch_T]                  NVARCHAR (50)  NULL,
    [Province]                  NVARCHAR (50)  NULL,
    [FROM_REGION]               SMALLINT       NULL,
    [Region_Name]               NVARCHAR (25)  NULL,
    [LEAD_ID]                   NVARCHAR (10)  NULL,
    [LEAD_NAME]                 VARCHAR (101)  NOT NULL,
    [วันที่ส่งเรื่องให้พิจารณา] DATETIME       NULL,
    [PROCESS_ID]                CHAR (4)       NULL,
    [PROCESS]                   NVARCHAR (200) NULL,
    [LAST_PROCESS_DATE]         DATETIME       NULL,
    [ระยะเวลาดำเนินงาน]         INT            NULL,
    [รหัสพนักงานผู้ออก]         NVARCHAR (10)  NULL,
    [ชื่อผู้ออก]                VARCHAR (50)   NULL,
    [LETTERSORT]                VARCHAR (16)   NOT NULL,
    [PROCESS_EMP_UT]            NVARCHAR (10)  NULL,
    [PROCESS_EMP_ID]            NVARCHAR (10)  NULL,
    [PROCESS_EMP_NAME]          VARCHAR (50)   NULL
);

