CREATE TABLE [dbo].[TEMP_SM_Nov_FILL_IN] (
    [No]                   FLOAT          NULL,
    [Cif]                  FLOAT          NULL,
    [Name]                 NVARCHAR (255) NULL,
    [CustomerName]         NVARCHAR (255) NULL,
    [BaySize]              NVARCHAR (255) NULL,
    [Rating]               NVARCHAR (255) NULL,
    [Business Type]        NVARCHAR (255) NULL,
    [Tdr]                  NVARCHAR (255) NULL,
    [Prin#]                FLOAT          NULL,
    [UseValue]             FLOAT          NULL,
    [Resv#]                FLOAT          NULL,
    [SumOfResvFull]        FLOAT          NULL,
    [LendingSubE]          NVARCHAR (255) NULL,
    [DeptFlag]             NVARCHAR (255) NULL,
    [DeptTran]             FLOAT          NULL,
    [Controlling Unit]     NVARCHAR (255) NULL,
    [Branch_ID]            FLOAT          NULL,
    [Branch]               NVARCHAR (255) NULL,
    [Region_ID]            FLOAT          NULL,
    [Region]               NVARCHAR (255) NULL,
    [F21]                  NVARCHAR (255) NULL,
    [Region1]              FLOAT          NULL,
    [BOT Reclassification] NVARCHAR (255) NULL,
    [ID_Team]              FLOAT          NULL,
    [Team]                 NVARCHAR (255) NULL,
    [ID_Group]             FLOAT          NULL,
    [Group]                NVARCHAR (255) NULL,
    [ID_CM]                FLOAT          NULL,
    [CM]                   NVARCHAR (255) NULL,
    [ID_RM]                FLOAT          NULL,
    [RM]                   NVARCHAR (255) NULL,
    [Monthly Payment]      FLOAT          NULL,
    [M 1]                  NVARCHAR (255) NULL,
    [M 2]                  NVARCHAR (255) NULL,
    [M 3]                  NVARCHAR (255) NULL,
    [M 4]                  NVARCHAR (255) NULL,
    [M 5]                  NVARCHAR (255) NULL,
    [M 6]                  NVARCHAR (255) NULL,
    [M 7]                  NVARCHAR (255) NULL,
    [M 8]                  NVARCHAR (255) NULL,
    [M 9]                  NVARCHAR (255) NULL,
    [M 10]                 NVARCHAR (255) NULL,
    [M 11]                 NVARCHAR (255) NULL,
    [M 12]                 NVARCHAR (255) NULL,
    [M 13]                 NVARCHAR (255) NULL,
    [Move from ]           NVARCHAR (255) NULL,
    [SM_Last]              NVARCHAR (255) NULL,
    [NPL Last]             NVARCHAR (255) NULL,
    [MAX_AGING_16/12/11]   FLOAT          NULL,
    [CM_FIRSTNAME_E]       NVARCHAR (255) NULL,
    [HEAD_FIRSTNAME_E]     NVARCHAR (255) NULL,
    [MANAGER_FIRSTNAME_E]  NVARCHAR (255) NULL,
    [Pass leader1 date]    DATETIME       NULL,
    [Flood pass leader1]   DATETIME       NULL,
    [Flood]                NVARCHAR (255) NULL,
    [Expected to be NPL]   NVARCHAR (255) NULL,
    [Comments]             NVARCHAR (255) NULL
);

