CREATE TABLE [dbo].[View_052009_cheng] (
    [REFERENCE]       NVARCHAR (255) NULL,
    [SME_Referral_No] NVARCHAR (255) NULL,
    [ID]              NVARCHAR (255) NULL,
    [REG-DATE]        DATETIME       NULL,
    [APP-DATE]        DATETIME       NULL,
    [CIF]             FLOAT          NULL,
    [CUSTOMER]        NVARCHAR (255) NULL,
    [EMP-ID]          NVARCHAR (255) NULL,
    [EMPLOYEE]        NVARCHAR (255) NULL,
    [BRANCH-ID]       NVARCHAR (255) NULL,
    [BRANCH-NAME]     NVARCHAR (255) NULL,
    [REGION-ID]       NVARCHAR (255) NULL,
    [REGION-NAME]     NVARCHAR (255) NULL,
    [NEW]             FLOAT          NULL,
    [OLD]             FLOAT          NULL,
    [REVIEW]          FLOAT          NULL,
    [Other]           FLOAT          NULL,
    [Credit_Line]     FLOAT          NULL,
    [O-D]             FLOAT          NULL,
    [(O-D)]           FLOAT          NULL,
    [F-L]             FLOAT          NULL,
    [(F-L)]           FLOAT          NULL,
    [L-G]             FLOAT          NULL,
    [(L-G)]           FLOAT          NULL,
    [STL-PN]          FLOAT          NULL,
    [(STL-PN)]        FLOAT          NULL,
    [TRADE-FIN]       FLOAT          NULL,
    [(TRADE-FIN)]     FLOAT          NULL,
    [OTHERS]          FLOAT          NULL,
    [(OTHERS)]        FLOAT          NULL,
    [SUM-INCREASE]    FLOAT          NULL,
    [SUM-RM_VALUE]    FLOAT          NULL,
    [PROCESS]         NVARCHAR (255) NULL,
    [PROCESS_DETAIL]  NVARCHAR (255) NULL,
    [APP-TYPE]        NVARCHAR (255) NULL,
    [LEVEL_NAME]      NVARCHAR (255) NULL,
    [Head_Name]       NVARCHAR (255) NULL,
    [Head_Surname]    NVARCHAR (255) NULL,
    [SECTION]         NVARCHAR (255) NULL,
    [SECTION1]        NVARCHAR (255) NULL,
    [Board]           NVARCHAR (255) NULL,
    [JOB_TYPE]        NVARCHAR (255) NULL,
    [TTY_SME(S)]      FLOAT          NULL,
    [TTY_SME(M)]      FLOAT          NULL
);

