CREATE TABLE [EMPLOYEE].[EMP20110531_BACKUP] (
    [IEMPID]      NVARCHAR (10)  NOT NULL,
    [NTTITLE]     NVARCHAR (255) NULL,
    [NETITLE]     NVARCHAR (255) NULL,
    [NTNAME]      NVARCHAR (255) NULL,
    [NENAME]      NVARCHAR (255) NULL,
    [NTSURN]      NVARCHAR (255) NULL,
    [NESURN]      NVARCHAR (255) NULL,
    [IEPOSIT]     NVARCHAR (255) NULL,
    [EEPOSIT]     NVARCHAR (255) NULL,
    [EEPOSITE]    NVARCHAR (255) NULL,
    [IESECTION]   NVARCHAR (255) NULL,
    [EESECTION]   NVARCHAR (255) NULL,
    [EEDEPT]      NVARCHAR (255) NULL,
    [EESECTIONE]  NVARCHAR (255) NULL,
    [EEDEPE]      NVARCHAR (255) NULL,
    [tel ภายใน]   NVARCHAR (255) NULL,
    [E mail]      NVARCHAR (255) NULL,
    [วันเริ่มงาน] DATETIME       NULL
);

