ALTER TABLE [CLASSIFY].[MENU_MASTER]
	ADD CONSTRAINT [PK_MENU_MASTER]
	PRIMARY KEY CLUSTERED ([MENU_KEY] ASC)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]