ALTER TABLE [CLASSIFY].[CATE_LINK_CATE_TYPE]
	ADD CONSTRAINT [PK_CATE_LINK_CATE_TYPE]
	PRIMARY KEY CLUSTERED ([LINKED_TYPE_KEY] ASC)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]