ALTER TABLE [CLASSIFY].[CATEGORY]
	ADD CONSTRAINT [PK_CATEGORY]
	PRIMARY KEY CLUSTERED ([CATEGORY_KEY] ASC)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]