ALTER TABLE [CLASSIFY].[APP_PROFILE]
	WITH CHECK ADD CONSTRAINT [FK_APP_PROFILE_USER_DATA] 
	FOREIGN KEY ([EMP_ID])
	REFERENCES [EMPLOYEE].[USER_DATA] ([EMP_ID])
GO

ALTER TABLE [CLASSIFY].[APP_PROFILE] CHECK CONSTRAINT [FK_APP_PROFILE_USER_DATA]
