ALTER TABLE [CLASSIFY].[CATE_AND_MENU]  WITH CHECK ADD  CONSTRAINT [FK_CATE_AND_MENU_MENU_MASTER] FOREIGN KEY([MENU_KEY])
REFERENCES [CLASSIFY].[MENU_MASTER] ([MENU_KEY])
GO

ALTER TABLE [CLASSIFY].[CATE_AND_MENU] CHECK CONSTRAINT [FK_CATE_AND_MENU_MENU_MASTER]