ALTER TABLE [CLASSIFY].[APP_PROFILE]
	WITH CHECK ADD CONSTRAINT [FK_APP_PROFILE_APPLICATION] 
	FOREIGN KEY ([APP_KEY])
	REFERENCES [CLASSIFY].[APPLICATION] ([APP_KEY])	
GO
ALTER TABLE [CLASSIFY].[APP_PROFILE] CHECK CONSTRAINT [FK_APP_PROFILE_APPLICATION]