ALTER TABLE [CLASSIFY].[CATE_LINK_CATE]
	ADD CONSTRAINT [FK_CATE_LINK_CATE_CATE_LINK_CATE_TYPE] 
	FOREIGN KEY ([LINKED_TYPE_KEY])
	REFERENCES [CLASSIFY].[CATE_LINK_CATE_TYPE] ([LINKED_TYPE_KEY])	

