ALTER TABLE [CLASSIFY].[CATEGORY_TYPE]
	ADD CONSTRAINT [PK_CATEGORY_TYPE]
	PRIMARY KEY CLUSTERED ([CATEGORY_TYPE_KEY] ASC)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]