ALTER TABLE [CLASSIFY].[CATE_AND_APP]
    ADD CONSTRAINT [FK_CATE_AND_APP_CATEGORY] FOREIGN KEY ([CATEGORY_KEY]) REFERENCES [CLASSIFY].[CATEGORY] ([CATEGORY_KEY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

