ALTER TABLE [CLASSIFY].[CATE_AND_CUS]  WITH CHECK ADD  CONSTRAINT [FK_CATE_AND_CUS_CATEGORY] FOREIGN KEY([CATEGORY_KEY])
REFERENCES [CLASSIFY].[CATEGORY] ([CATEGORY_KEY])
GO

ALTER TABLE [CLASSIFY].[CATE_AND_CUS] CHECK CONSTRAINT [FK_CATE_AND_CUS_CATEGORY]
GO