CREATE TABLE [CUSTOMER].[CUSTOMER_SME]
(
	[CIF] [int] NOT NULL,
	[GROUP_ID] [int] NULL,
	[CM_CODE] [nvarchar](10) NULL,
	[OLD_CM_CODE] [nvarchar](10) NULL,
	[BRANCH_ID] [smallint] NULL,
	[JUDGEMENT_ID] [nvarchar](5) NULL,
	[BUSI_RISK1_ID] [varchar](8) NULL,
	[BUSI_RISK2_ID] [varchar](8) NULL,
	[BUSI_RISK3_ID] [varchar](8) NULL,
	[BUSINESS_DESTINATION_ID] [numeric](3, 0) NULL,
	[EXPORT_WEIGHT] [numeric](3, 0) NULL,
	[LOCAL_WEIGHT] [numeric](3, 0) NULL,
	[STATUS_ID] [int] NULL,
	[SIZE_ID] [int] NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](10) NULL,
	[RATING_TYPE_KEY] [int] NULL,
	[RATING_KEY] [int] NULL,
	[RATING_UPDATE_DATE] [datetime] NULL,
	[EXTERNAL_SOURCE_MEMO] [ntext] NULL,
	[NEXT_REVIEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_CUSTOMER_SME] PRIMARY KEY CLUSTERED 
(
	[CIF] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME]  WITH NOCHECK ADD  CONSTRAINT [CK_EXPORT_WEIGHT] CHECK  ((([EXPORT_WEIGHT]+[LOCAL_WEIGHT])<=(100)))
GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME] CHECK CONSTRAINT [CK_EXPORT_WEIGHT]
GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME] ADD  CONSTRAINT [DF_CUSTOMER_SME_BUSINESS_DESTINATION_ID]  DEFAULT ((1)) FOR [BUSINESS_DESTINATION_ID]
GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME] ADD  CONSTRAINT [DF_CUSTOMER_SME_STATUS_ID]  DEFAULT ((1)) FOR [STATUS_ID]
GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME] ADD  CONSTRAINT [DF_CUSTOMER_SME_SIZE_ID]  DEFAULT ((1)) FOR [SIZE_ID]
GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME] ADD  CONSTRAINT [DF_CUSTOMER_SME_RATING_TYPE_KEY_1]  DEFAULT ((1)) FOR [RATING_TYPE_KEY]
GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME] ADD  CONSTRAINT [DF_CUSTOMER_SME_RATING_KEY_1]  DEFAULT ((1)) FOR [RATING_KEY]
GO
