CREATE TABLE [CUSTOMER].[CUSTOMER]
(
	[CIF] [int] NOT NULL,
	[CUS_TITLE] [nvarchar](10) NULL,
	[CUS_FIRST] [nvarchar](30) NULL,
	[CUS_LAST] [nvarchar](30) NULL,
	[CUS1_TITLE] [nvarchar](10) NULL,
	[CUS1_FIRST] [nvarchar](30) NULL,
	[CUS1_LAST] [nvarchar](30) NULL,
	[CUS2_TITLE] [nvarchar](10) NULL,
	[CUS2_FIRST] [nvarchar](30) NULL,
	[CUS2_LAST] [nvarchar](30) NULL,
	[CUS3_TITLE] [nvarchar](10) NULL,
	[CUS3_FIRST] [nvarchar](30) NULL,
	[CUS3_LAST] [nvarchar](30) NULL,
	[CTITLE_E] [nvarchar](15) NULL,
	[CFIRST_E] [nvarchar](40) NULL,
	[CLAST_E] [nvarchar](40) NULL,
	[CifType] [nvarchar](1) NULL,
	[BOTID] [int] NULL,
	[MAIN_CUST] [int] NULL,
	[GROUP_CUST] [nvarchar](1) NULL,
	[GROUPCIF] [int] NULL,
	[BAYRATING] [nvarchar](2) NULL,
	[RATING] [nvarchar](5) NULL,
	[ADDR1] [nvarchar](110) NULL,
	[ADDR2] [nvarchar](70) NULL,
	[PROV] [nvarchar](2) NULL,
	[ZIPCODE] [int] NULL,
	[TEL_HOME] [nvarchar](20) NULL,
	[TEL_OFF] [nvarchar](20) NULL,
	[TAX_NO] [nvarchar](10) NULL,
	[CUS_TYPE] [nvarchar](4) NULL,
	[BUSI_TYPE] [nvarchar](6) NULL,
	[CLASS] [nvarchar](1) NULL,
	[IDCARD] [nvarchar](13) NULL,
	[OFFICR_ID] [bigint] NULL,
	[DATEFAS] [datetime] NULL,
	[BEINGCUST] [datetime] NULL,
	[BTHDATE] [datetime] NULL,
	[DEPTFLAG] [tinyint] NULL,
	[DEPTTRAN] [int] NULL,
	[CIF0] [int] NULL,
	[CIF1] [int] NULL,
	[CIF2] [int] NULL,
	[PROVSHOP] [nvarchar](2) NULL,
	[SEX] [char](1) NULL,
	[ADDRWORK1] [nvarchar](110) NULL,
	[ADDRWORK2] [nvarchar](70) NULL,
	[ZIPSHOP] [int] NULL,
	[CARDTYPE] [nvarchar](10) NULL,
	[CARDNO] [nvarchar](10) NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[CIF] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
