CREATE TABLE [CUSTOMER].[CUSTOMER_SME_RATING_TYPE]
(
		[RATING_TYPE_KEY] [int] IDENTITY(1,1) NOT NULL,
	[RATING_TYPE_CODE] [nvarchar](10) NULL,
	[RATING_TYPE_DESC] [nvarchar](50) NULL,
	[PRIORITY] [int] NULL,
 CONSTRAINT [PK_CUSTOMER_SME_RATING_TYPE_1] PRIMARY KEY CLUSTERED 
(
	[RATING_TYPE_KEY] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
