CREATE TABLE [CUSTOMER].[CUSTOMER_SME_SIZE](
	[SIZE_ID] [int] IDENTITY(1,1) NOT NULL,
	[SIZE_DETAIL] [nvarchar](50) NULL,
	[PRIORITY] [int] NULL,
 CONSTRAINT [PK_CUSTOMER_SME_SIZE] PRIMARY KEY CLUSTERED 
(
	[SIZE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]