CREATE TABLE [CUSTOMER].[CUSTOMER_SME_RATING_TYPE]
(
		[RATING_TYPE_KEY] [int] IDENTITY(1,1) NOT NULL,
	[RATING_TYPE_CODE] [nvarchar](10) NULL,
	[RATING_TYPE_DESC] [nvarchar](50) NULL,
	[PRIORITY] [int] NULL
)
