CREATE TABLE [CUSTOMER].[CUSTOMER_STATUS]
(
	[STATUS_ID] [int] IDENTITY(1,1) NOT NULL,
	[STATUS_DETAIL] [nvarchar](50) NULL,
	[PRIORITY] [int] NULL,
 CONSTRAINT [PK_CUSTOMER_STATUS] PRIMARY KEY CLUSTERED 
(
	[STATUS_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
