CREATE TABLE [CUSTOMER].[CUSTOMER_SME_RATING]
(
	[RATING_KEY] [int] IDENTITY(1,1) NOT NULL,
	[RATING_CODE] [nvarchar](10) NULL,
	[RATING_TYPE_KEY] [int] NOT NULL,
	[RATING_DESC] [nvarchar](50) NULL,
	[PRIORITY] [int] NULL
)

