CREATE TABLE [CUSTOMER].[CUSTOMER_SME_GROUP]
(
	[GROUP_ID] [int] NOT NULL,
	[GROUP_SIZE_ID] [smallint] NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](10) NOT NULL,
	[GROUP_EXPOSURE] [money] NULL,
	[NEXT_REVIEW_DATE] [datetime] NULL
 )

