CREATE TABLE [CUSTOMER].[CUSTOMER_SME_GROUP]
(
	[GROUP_ID] [int] NOT NULL,
	[GROUP_SIZE_ID] [smallint] NOT NULL,
	[UPDATE_DATE] [datetime] NOT NULL,
	[UPDATE_BY] [nvarchar](10) NOT NULL,
	[GROUP_EXPOSURE] [money] NULL,
	[NEXT_REVIEW_DATE] [datetime] NULL,
 CONSTRAINT [PK_CUSTOMER_SME_GROUP] PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME_GROUP] ADD  CONSTRAINT [DF_CUSTOMER_SME_GROUP_GROUP_SIZE_ID]  DEFAULT ((1)) FOR [GROUP_SIZE_ID]
GO

ALTER TABLE [CUSTOMER].[CUSTOMER_SME_GROUP] ADD  CONSTRAINT [DF_CUSTOMER_SME_GROUP_UPDATE_DATE]  DEFAULT (getdate()) FOR [UPDATE_DATE]
GO
