//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SSProjectApp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SS_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SS_Entities object using the connection string found in the 'SS_Entities' section of the application configuration file.
        /// </summary>
        public SS_Entities() : base("name=SS_Entities", "SS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SS_Entities object.
        /// </summary>
        public SS_Entities(string connectionString) : base(connectionString, "SS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SS_Entities object.
        /// </summary>
        public SS_Entities(EntityConnection connection) : base(connection, "SS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TEMP_SS_DATA> TEMP_SS_DATA
        {
            get
            {
                if ((_TEMP_SS_DATA == null))
                {
                    _TEMP_SS_DATA = base.CreateObjectSet<TEMP_SS_DATA>("TEMP_SS_DATA");
                }
                return _TEMP_SS_DATA;
            }
        }
        private ObjectSet<TEMP_SS_DATA> _TEMP_SS_DATA;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TEMP_SS_DATA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTEMP_SS_DATA(TEMP_SS_DATA tEMP_SS_DATA)
        {
            base.AddObject("TEMP_SS_DATA", tEMP_SS_DATA);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SSProjectModel", Name="TEMP_SS_DATA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TEMP_SS_DATA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TEMP_SS_DATA object.
        /// </summary>
        /// <param name="cIF">Initial value of the CIF property.</param>
        /// <param name="fILENAME">Initial value of the FILENAME property.</param>
        public static TEMP_SS_DATA CreateTEMP_SS_DATA(global::System.Int32 cIF, global::System.String fILENAME)
        {
            TEMP_SS_DATA tEMP_SS_DATA = new TEMP_SS_DATA();
            tEMP_SS_DATA.CIF = cIF;
            tEMP_SS_DATA.FILENAME = fILENAME;
            return tEMP_SS_DATA;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CIF
        {
            get
            {
                return _CIF;
            }
            set
            {
                if (_CIF != value)
                {
                    OnCIFChanging(value);
                    ReportPropertyChanging("CIF");
                    _CIF = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CIF");
                    OnCIFChanged();
                }
            }
        }
        private global::System.Int32 _CIF;
        partial void OnCIFChanging(global::System.Int32 value);
        partial void OnCIFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FILENAME
        {
            get
            {
                return _FILENAME;
            }
            set
            {
                if (_FILENAME != value)
                {
                    OnFILENAMEChanging(value);
                    ReportPropertyChanging("FILENAME");
                    _FILENAME = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FILENAME");
                    OnFILENAMEChanged();
                }
            }
        }
        private global::System.String _FILENAME;
        partial void OnFILENAMEChanging(global::System.String value);
        partial void OnFILENAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> RM_DefaultMargin
        {
            get
            {
                return _RM_DefaultMargin;
            }
            set
            {
                OnRM_DefaultMarginChanging(value);
                ReportPropertyChanging("RM_DefaultMargin");
                _RM_DefaultMargin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_DefaultMargin");
                OnRM_DefaultMarginChanged();
            }
        }
        private Nullable<global::System.Double> _RM_DefaultMargin;
        partial void OnRM_DefaultMarginChanging(Nullable<global::System.Double> value);
        partial void OnRM_DefaultMarginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> RM_OperatingProfit
        {
            get
            {
                return _RM_OperatingProfit;
            }
            set
            {
                OnRM_OperatingProfitChanging(value);
                ReportPropertyChanging("RM_OperatingProfit");
                _RM_OperatingProfit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_OperatingProfit");
                OnRM_OperatingProfitChanged();
            }
        }
        private Nullable<global::System.Double> _RM_OperatingProfit;
        partial void OnRM_OperatingProfitChanging(Nullable<global::System.Double> value);
        partial void OnRM_OperatingProfitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_CurrentLiabilitiesWithBay
        {
            get
            {
                return _RM_CurrentLiabilitiesWithBay;
            }
            set
            {
                OnRM_CurrentLiabilitiesWithBayChanging(value);
                ReportPropertyChanging("RM_CurrentLiabilitiesWithBay");
                _RM_CurrentLiabilitiesWithBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_CurrentLiabilitiesWithBay");
                OnRM_CurrentLiabilitiesWithBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_CurrentLiabilitiesWithBay;
        partial void OnRM_CurrentLiabilitiesWithBayChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_CurrentLiabilitiesWithBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_LongTermDebtWithBay
        {
            get
            {
                return _RM_LongTermDebtWithBay;
            }
            set
            {
                OnRM_LongTermDebtWithBayChanging(value);
                ReportPropertyChanging("RM_LongTermDebtWithBay");
                _RM_LongTermDebtWithBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_LongTermDebtWithBay");
                OnRM_LongTermDebtWithBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_LongTermDebtWithBay;
        partial void OnRM_LongTermDebtWithBayChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_LongTermDebtWithBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_WorkingCapitalNeed
        {
            get
            {
                return _RM_WorkingCapitalNeed;
            }
            set
            {
                OnRM_WorkingCapitalNeedChanging(value);
                ReportPropertyChanging("RM_WorkingCapitalNeed");
                _RM_WorkingCapitalNeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_WorkingCapitalNeed");
                OnRM_WorkingCapitalNeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_WorkingCapitalNeed;
        partial void OnRM_WorkingCapitalNeedChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_WorkingCapitalNeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_LoanNeed
        {
            get
            {
                return _RM_LoanNeed;
            }
            set
            {
                OnRM_LoanNeedChanging(value);
                ReportPropertyChanging("RM_LoanNeed");
                _RM_LoanNeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_LoanNeed");
                OnRM_LoanNeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_LoanNeed;
        partial void OnRM_LoanNeedChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_LoanNeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_WorkingCapitalCal
        {
            get
            {
                return _RM_WorkingCapitalCal;
            }
            set
            {
                OnRM_WorkingCapitalCalChanging(value);
                ReportPropertyChanging("RM_WorkingCapitalCal");
                _RM_WorkingCapitalCal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_WorkingCapitalCal");
                OnRM_WorkingCapitalCalChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_WorkingCapitalCal;
        partial void OnRM_WorkingCapitalCalChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_WorkingCapitalCalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_LoanCal
        {
            get
            {
                return _RM_LoanCal;
            }
            set
            {
                OnRM_LoanCalChanging(value);
                ReportPropertyChanging("RM_LoanCal");
                _RM_LoanCal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_LoanCal");
                OnRM_LoanCalChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_LoanCal;
        partial void OnRM_LoanCalChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_LoanCalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_WorkingCapitalRequire
        {
            get
            {
                return _RM_WorkingCapitalRequire;
            }
            set
            {
                OnRM_WorkingCapitalRequireChanging(value);
                ReportPropertyChanging("RM_WorkingCapitalRequire");
                _RM_WorkingCapitalRequire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_WorkingCapitalRequire");
                OnRM_WorkingCapitalRequireChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_WorkingCapitalRequire;
        partial void OnRM_WorkingCapitalRequireChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_WorkingCapitalRequireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_LoanRequire
        {
            get
            {
                return _RM_LoanRequire;
            }
            set
            {
                OnRM_LoanRequireChanging(value);
                ReportPropertyChanging("RM_LoanRequire");
                _RM_LoanRequire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_LoanRequire");
                OnRM_LoanRequireChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_LoanRequire;
        partial void OnRM_LoanRequireChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_LoanRequireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_LimitOfLGAndAvalNonCash
        {
            get
            {
                return _RM_LimitOfLGAndAvalNonCash;
            }
            set
            {
                OnRM_LimitOfLGAndAvalNonCashChanging(value);
                ReportPropertyChanging("RM_LimitOfLGAndAvalNonCash");
                _RM_LimitOfLGAndAvalNonCash = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_LimitOfLGAndAvalNonCash");
                OnRM_LimitOfLGAndAvalNonCashChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_LimitOfLGAndAvalNonCash;
        partial void OnRM_LimitOfLGAndAvalNonCashChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_LimitOfLGAndAvalNonCashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> RM_DSCRInThisTime
        {
            get
            {
                return _RM_DSCRInThisTime;
            }
            set
            {
                OnRM_DSCRInThisTimeChanging(value);
                ReportPropertyChanging("RM_DSCRInThisTime");
                _RM_DSCRInThisTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_DSCRInThisTime");
                OnRM_DSCRInThisTimeChanged();
            }
        }
        private Nullable<global::System.Double> _RM_DSCRInThisTime;
        partial void OnRM_DSCRInThisTimeChanging(Nullable<global::System.Double> value);
        partial void OnRM_DSCRInThisTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> RM_DEInThisTime
        {
            get
            {
                return _RM_DEInThisTime;
            }
            set
            {
                OnRM_DEInThisTimeChanging(value);
                ReportPropertyChanging("RM_DEInThisTime");
                _RM_DEInThisTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_DEInThisTime");
                OnRM_DEInThisTimeChanged();
            }
        }
        private Nullable<global::System.Double> _RM_DEInThisTime;
        partial void OnRM_DEInThisTimeChanging(Nullable<global::System.Double> value);
        partial void OnRM_DEInThisTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> RM_LTV
        {
            get
            {
                return _RM_LTV;
            }
            set
            {
                OnRM_LTVChanging(value);
                ReportPropertyChanging("RM_LTV");
                _RM_LTV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_LTV");
                OnRM_LTVChanged();
            }
        }
        private Nullable<global::System.Double> _RM_LTV;
        partial void OnRM_LTVChanging(Nullable<global::System.Double> value);
        partial void OnRM_LTVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_WorkingCapitalNeedBay
        {
            get
            {
                return _RM_WorkingCapitalNeedBay;
            }
            set
            {
                OnRM_WorkingCapitalNeedBayChanging(value);
                ReportPropertyChanging("RM_WorkingCapitalNeedBay");
                _RM_WorkingCapitalNeedBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_WorkingCapitalNeedBay");
                OnRM_WorkingCapitalNeedBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_WorkingCapitalNeedBay;
        partial void OnRM_WorkingCapitalNeedBayChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_WorkingCapitalNeedBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_LoanNeedBay
        {
            get
            {
                return _RM_LoanNeedBay;
            }
            set
            {
                OnRM_LoanNeedBayChanging(value);
                ReportPropertyChanging("RM_LoanNeedBay");
                _RM_LoanNeedBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_LoanNeedBay");
                OnRM_LoanNeedBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_LoanNeedBay;
        partial void OnRM_LoanNeedBayChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_LoanNeedBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_WorkingCapitalApprove
        {
            get
            {
                return _RM_WorkingCapitalApprove;
            }
            set
            {
                OnRM_WorkingCapitalApproveChanging(value);
                ReportPropertyChanging("RM_WorkingCapitalApprove");
                _RM_WorkingCapitalApprove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_WorkingCapitalApprove");
                OnRM_WorkingCapitalApproveChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_WorkingCapitalApprove;
        partial void OnRM_WorkingCapitalApproveChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_WorkingCapitalApproveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RM_LoanApprove
        {
            get
            {
                return _RM_LoanApprove;
            }
            set
            {
                OnRM_LoanApproveChanging(value);
                ReportPropertyChanging("RM_LoanApprove");
                _RM_LoanApprove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RM_LoanApprove");
                OnRM_LoanApproveChanged();
            }
        }
        private Nullable<global::System.Decimal> _RM_LoanApprove;
        partial void OnRM_LoanApproveChanging(Nullable<global::System.Decimal> value);
        partial void OnRM_LoanApproveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DEFAULT_DefaultMargin
        {
            get
            {
                return _DEFAULT_DefaultMargin;
            }
            set
            {
                OnDEFAULT_DefaultMarginChanging(value);
                ReportPropertyChanging("DEFAULT_DefaultMargin");
                _DEFAULT_DefaultMargin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_DefaultMargin");
                OnDEFAULT_DefaultMarginChanged();
            }
        }
        private Nullable<global::System.Double> _DEFAULT_DefaultMargin;
        partial void OnDEFAULT_DefaultMarginChanging(Nullable<global::System.Double> value);
        partial void OnDEFAULT_DefaultMarginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DEFAULT_OperatingProfit
        {
            get
            {
                return _DEFAULT_OperatingProfit;
            }
            set
            {
                OnDEFAULT_OperatingProfitChanging(value);
                ReportPropertyChanging("DEFAULT_OperatingProfit");
                _DEFAULT_OperatingProfit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_OperatingProfit");
                OnDEFAULT_OperatingProfitChanged();
            }
        }
        private Nullable<global::System.Double> _DEFAULT_OperatingProfit;
        partial void OnDEFAULT_OperatingProfitChanging(Nullable<global::System.Double> value);
        partial void OnDEFAULT_OperatingProfitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_CurrentLiabilitiesWithBay
        {
            get
            {
                return _DEFAULT_CurrentLiabilitiesWithBay;
            }
            set
            {
                OnDEFAULT_CurrentLiabilitiesWithBayChanging(value);
                ReportPropertyChanging("DEFAULT_CurrentLiabilitiesWithBay");
                _DEFAULT_CurrentLiabilitiesWithBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_CurrentLiabilitiesWithBay");
                OnDEFAULT_CurrentLiabilitiesWithBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_CurrentLiabilitiesWithBay;
        partial void OnDEFAULT_CurrentLiabilitiesWithBayChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_CurrentLiabilitiesWithBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_LongTermDebtWithBay
        {
            get
            {
                return _DEFAULT_LongTermDebtWithBay;
            }
            set
            {
                OnDEFAULT_LongTermDebtWithBayChanging(value);
                ReportPropertyChanging("DEFAULT_LongTermDebtWithBay");
                _DEFAULT_LongTermDebtWithBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_LongTermDebtWithBay");
                OnDEFAULT_LongTermDebtWithBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_LongTermDebtWithBay;
        partial void OnDEFAULT_LongTermDebtWithBayChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_LongTermDebtWithBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_WorkingCapitalNeed
        {
            get
            {
                return _DEFAULT_WorkingCapitalNeed;
            }
            set
            {
                OnDEFAULT_WorkingCapitalNeedChanging(value);
                ReportPropertyChanging("DEFAULT_WorkingCapitalNeed");
                _DEFAULT_WorkingCapitalNeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_WorkingCapitalNeed");
                OnDEFAULT_WorkingCapitalNeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_WorkingCapitalNeed;
        partial void OnDEFAULT_WorkingCapitalNeedChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_WorkingCapitalNeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_LoanNeed
        {
            get
            {
                return _DEFAULT_LoanNeed;
            }
            set
            {
                OnDEFAULT_LoanNeedChanging(value);
                ReportPropertyChanging("DEFAULT_LoanNeed");
                _DEFAULT_LoanNeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_LoanNeed");
                OnDEFAULT_LoanNeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_LoanNeed;
        partial void OnDEFAULT_LoanNeedChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_LoanNeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_WorkingCapitalCal
        {
            get
            {
                return _DEFAULT_WorkingCapitalCal;
            }
            set
            {
                OnDEFAULT_WorkingCapitalCalChanging(value);
                ReportPropertyChanging("DEFAULT_WorkingCapitalCal");
                _DEFAULT_WorkingCapitalCal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_WorkingCapitalCal");
                OnDEFAULT_WorkingCapitalCalChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_WorkingCapitalCal;
        partial void OnDEFAULT_WorkingCapitalCalChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_WorkingCapitalCalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_LoanCal
        {
            get
            {
                return _DEFAULT_LoanCal;
            }
            set
            {
                OnDEFAULT_LoanCalChanging(value);
                ReportPropertyChanging("DEFAULT_LoanCal");
                _DEFAULT_LoanCal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_LoanCal");
                OnDEFAULT_LoanCalChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_LoanCal;
        partial void OnDEFAULT_LoanCalChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_LoanCalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_WorkingCapitalRequire
        {
            get
            {
                return _DEFAULT_WorkingCapitalRequire;
            }
            set
            {
                OnDEFAULT_WorkingCapitalRequireChanging(value);
                ReportPropertyChanging("DEFAULT_WorkingCapitalRequire");
                _DEFAULT_WorkingCapitalRequire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_WorkingCapitalRequire");
                OnDEFAULT_WorkingCapitalRequireChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_WorkingCapitalRequire;
        partial void OnDEFAULT_WorkingCapitalRequireChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_WorkingCapitalRequireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_LoanRequire
        {
            get
            {
                return _DEFAULT_LoanRequire;
            }
            set
            {
                OnDEFAULT_LoanRequireChanging(value);
                ReportPropertyChanging("DEFAULT_LoanRequire");
                _DEFAULT_LoanRequire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_LoanRequire");
                OnDEFAULT_LoanRequireChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_LoanRequire;
        partial void OnDEFAULT_LoanRequireChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_LoanRequireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_LimitOfLGAndAvalNonCash
        {
            get
            {
                return _DEFAULT_LimitOfLGAndAvalNonCash;
            }
            set
            {
                OnDEFAULT_LimitOfLGAndAvalNonCashChanging(value);
                ReportPropertyChanging("DEFAULT_LimitOfLGAndAvalNonCash");
                _DEFAULT_LimitOfLGAndAvalNonCash = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_LimitOfLGAndAvalNonCash");
                OnDEFAULT_LimitOfLGAndAvalNonCashChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_LimitOfLGAndAvalNonCash;
        partial void OnDEFAULT_LimitOfLGAndAvalNonCashChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_LimitOfLGAndAvalNonCashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DEFAULT_DSCRInThisTime
        {
            get
            {
                return _DEFAULT_DSCRInThisTime;
            }
            set
            {
                OnDEFAULT_DSCRInThisTimeChanging(value);
                ReportPropertyChanging("DEFAULT_DSCRInThisTime");
                _DEFAULT_DSCRInThisTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_DSCRInThisTime");
                OnDEFAULT_DSCRInThisTimeChanged();
            }
        }
        private Nullable<global::System.Double> _DEFAULT_DSCRInThisTime;
        partial void OnDEFAULT_DSCRInThisTimeChanging(Nullable<global::System.Double> value);
        partial void OnDEFAULT_DSCRInThisTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DEFAULT_DEInThisTime
        {
            get
            {
                return _DEFAULT_DEInThisTime;
            }
            set
            {
                OnDEFAULT_DEInThisTimeChanging(value);
                ReportPropertyChanging("DEFAULT_DEInThisTime");
                _DEFAULT_DEInThisTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_DEInThisTime");
                OnDEFAULT_DEInThisTimeChanged();
            }
        }
        private Nullable<global::System.Double> _DEFAULT_DEInThisTime;
        partial void OnDEFAULT_DEInThisTimeChanging(Nullable<global::System.Double> value);
        partial void OnDEFAULT_DEInThisTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DEFAULT_LTV
        {
            get
            {
                return _DEFAULT_LTV;
            }
            set
            {
                OnDEFAULT_LTVChanging(value);
                ReportPropertyChanging("DEFAULT_LTV");
                _DEFAULT_LTV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_LTV");
                OnDEFAULT_LTVChanged();
            }
        }
        private Nullable<global::System.Double> _DEFAULT_LTV;
        partial void OnDEFAULT_LTVChanging(Nullable<global::System.Double> value);
        partial void OnDEFAULT_LTVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_WorkingCapitalNeedBay
        {
            get
            {
                return _DEFAULT_WorkingCapitalNeedBay;
            }
            set
            {
                OnDEFAULT_WorkingCapitalNeedBayChanging(value);
                ReportPropertyChanging("DEFAULT_WorkingCapitalNeedBay");
                _DEFAULT_WorkingCapitalNeedBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_WorkingCapitalNeedBay");
                OnDEFAULT_WorkingCapitalNeedBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_WorkingCapitalNeedBay;
        partial void OnDEFAULT_WorkingCapitalNeedBayChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_WorkingCapitalNeedBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_LoanNeedBay
        {
            get
            {
                return _DEFAULT_LoanNeedBay;
            }
            set
            {
                OnDEFAULT_LoanNeedBayChanging(value);
                ReportPropertyChanging("DEFAULT_LoanNeedBay");
                _DEFAULT_LoanNeedBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_LoanNeedBay");
                OnDEFAULT_LoanNeedBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_LoanNeedBay;
        partial void OnDEFAULT_LoanNeedBayChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_LoanNeedBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_WorkingCapitalApprove
        {
            get
            {
                return _DEFAULT_WorkingCapitalApprove;
            }
            set
            {
                OnDEFAULT_WorkingCapitalApproveChanging(value);
                ReportPropertyChanging("DEFAULT_WorkingCapitalApprove");
                _DEFAULT_WorkingCapitalApprove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_WorkingCapitalApprove");
                OnDEFAULT_WorkingCapitalApproveChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_WorkingCapitalApprove;
        partial void OnDEFAULT_WorkingCapitalApproveChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_WorkingCapitalApproveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> DEFAULT_LoanApprove
        {
            get
            {
                return _DEFAULT_LoanApprove;
            }
            set
            {
                OnDEFAULT_LoanApproveChanging(value);
                ReportPropertyChanging("DEFAULT_LoanApprove");
                _DEFAULT_LoanApprove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DEFAULT_LoanApprove");
                OnDEFAULT_LoanApproveChanged();
            }
        }
        private Nullable<global::System.Decimal> _DEFAULT_LoanApprove;
        partial void OnDEFAULT_LoanApproveChanging(Nullable<global::System.Decimal> value);
        partial void OnDEFAULT_LoanApproveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CM_DefaultMargin
        {
            get
            {
                return _CM_DefaultMargin;
            }
            set
            {
                OnCM_DefaultMarginChanging(value);
                ReportPropertyChanging("CM_DefaultMargin");
                _CM_DefaultMargin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_DefaultMargin");
                OnCM_DefaultMarginChanged();
            }
        }
        private Nullable<global::System.Double> _CM_DefaultMargin;
        partial void OnCM_DefaultMarginChanging(Nullable<global::System.Double> value);
        partial void OnCM_DefaultMarginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CM_OperatingProfit
        {
            get
            {
                return _CM_OperatingProfit;
            }
            set
            {
                OnCM_OperatingProfitChanging(value);
                ReportPropertyChanging("CM_OperatingProfit");
                _CM_OperatingProfit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_OperatingProfit");
                OnCM_OperatingProfitChanged();
            }
        }
        private Nullable<global::System.Double> _CM_OperatingProfit;
        partial void OnCM_OperatingProfitChanging(Nullable<global::System.Double> value);
        partial void OnCM_OperatingProfitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_CurrentLiabilitiesWithBay
        {
            get
            {
                return _CM_CurrentLiabilitiesWithBay;
            }
            set
            {
                OnCM_CurrentLiabilitiesWithBayChanging(value);
                ReportPropertyChanging("CM_CurrentLiabilitiesWithBay");
                _CM_CurrentLiabilitiesWithBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_CurrentLiabilitiesWithBay");
                OnCM_CurrentLiabilitiesWithBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_CurrentLiabilitiesWithBay;
        partial void OnCM_CurrentLiabilitiesWithBayChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_CurrentLiabilitiesWithBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_LongTermDebtWithBay
        {
            get
            {
                return _CM_LongTermDebtWithBay;
            }
            set
            {
                OnCM_LongTermDebtWithBayChanging(value);
                ReportPropertyChanging("CM_LongTermDebtWithBay");
                _CM_LongTermDebtWithBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_LongTermDebtWithBay");
                OnCM_LongTermDebtWithBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_LongTermDebtWithBay;
        partial void OnCM_LongTermDebtWithBayChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_LongTermDebtWithBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_WorkingCapitalNeed
        {
            get
            {
                return _CM_WorkingCapitalNeed;
            }
            set
            {
                OnCM_WorkingCapitalNeedChanging(value);
                ReportPropertyChanging("CM_WorkingCapitalNeed");
                _CM_WorkingCapitalNeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_WorkingCapitalNeed");
                OnCM_WorkingCapitalNeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_WorkingCapitalNeed;
        partial void OnCM_WorkingCapitalNeedChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_WorkingCapitalNeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_LoanNeed
        {
            get
            {
                return _CM_LoanNeed;
            }
            set
            {
                OnCM_LoanNeedChanging(value);
                ReportPropertyChanging("CM_LoanNeed");
                _CM_LoanNeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_LoanNeed");
                OnCM_LoanNeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_LoanNeed;
        partial void OnCM_LoanNeedChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_LoanNeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_WorkingCapitalCal
        {
            get
            {
                return _CM_WorkingCapitalCal;
            }
            set
            {
                OnCM_WorkingCapitalCalChanging(value);
                ReportPropertyChanging("CM_WorkingCapitalCal");
                _CM_WorkingCapitalCal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_WorkingCapitalCal");
                OnCM_WorkingCapitalCalChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_WorkingCapitalCal;
        partial void OnCM_WorkingCapitalCalChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_WorkingCapitalCalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_LoanCal
        {
            get
            {
                return _CM_LoanCal;
            }
            set
            {
                OnCM_LoanCalChanging(value);
                ReportPropertyChanging("CM_LoanCal");
                _CM_LoanCal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_LoanCal");
                OnCM_LoanCalChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_LoanCal;
        partial void OnCM_LoanCalChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_LoanCalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_WorkingCapitalRequire
        {
            get
            {
                return _CM_WorkingCapitalRequire;
            }
            set
            {
                OnCM_WorkingCapitalRequireChanging(value);
                ReportPropertyChanging("CM_WorkingCapitalRequire");
                _CM_WorkingCapitalRequire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_WorkingCapitalRequire");
                OnCM_WorkingCapitalRequireChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_WorkingCapitalRequire;
        partial void OnCM_WorkingCapitalRequireChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_WorkingCapitalRequireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_LoanRequire
        {
            get
            {
                return _CM_LoanRequire;
            }
            set
            {
                OnCM_LoanRequireChanging(value);
                ReportPropertyChanging("CM_LoanRequire");
                _CM_LoanRequire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_LoanRequire");
                OnCM_LoanRequireChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_LoanRequire;
        partial void OnCM_LoanRequireChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_LoanRequireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_LimitOfLGAndAvalNonCash
        {
            get
            {
                return _CM_LimitOfLGAndAvalNonCash;
            }
            set
            {
                OnCM_LimitOfLGAndAvalNonCashChanging(value);
                ReportPropertyChanging("CM_LimitOfLGAndAvalNonCash");
                _CM_LimitOfLGAndAvalNonCash = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_LimitOfLGAndAvalNonCash");
                OnCM_LimitOfLGAndAvalNonCashChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_LimitOfLGAndAvalNonCash;
        partial void OnCM_LimitOfLGAndAvalNonCashChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_LimitOfLGAndAvalNonCashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CM_DSCRInThisTime
        {
            get
            {
                return _CM_DSCRInThisTime;
            }
            set
            {
                OnCM_DSCRInThisTimeChanging(value);
                ReportPropertyChanging("CM_DSCRInThisTime");
                _CM_DSCRInThisTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_DSCRInThisTime");
                OnCM_DSCRInThisTimeChanged();
            }
        }
        private Nullable<global::System.Double> _CM_DSCRInThisTime;
        partial void OnCM_DSCRInThisTimeChanging(Nullable<global::System.Double> value);
        partial void OnCM_DSCRInThisTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CM_DEInThisTime
        {
            get
            {
                return _CM_DEInThisTime;
            }
            set
            {
                OnCM_DEInThisTimeChanging(value);
                ReportPropertyChanging("CM_DEInThisTime");
                _CM_DEInThisTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_DEInThisTime");
                OnCM_DEInThisTimeChanged();
            }
        }
        private Nullable<global::System.Double> _CM_DEInThisTime;
        partial void OnCM_DEInThisTimeChanging(Nullable<global::System.Double> value);
        partial void OnCM_DEInThisTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CM_LTV
        {
            get
            {
                return _CM_LTV;
            }
            set
            {
                OnCM_LTVChanging(value);
                ReportPropertyChanging("CM_LTV");
                _CM_LTV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_LTV");
                OnCM_LTVChanged();
            }
        }
        private Nullable<global::System.Double> _CM_LTV;
        partial void OnCM_LTVChanging(Nullable<global::System.Double> value);
        partial void OnCM_LTVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_WorkingCapitalNeedBay
        {
            get
            {
                return _CM_WorkingCapitalNeedBay;
            }
            set
            {
                OnCM_WorkingCapitalNeedBayChanging(value);
                ReportPropertyChanging("CM_WorkingCapitalNeedBay");
                _CM_WorkingCapitalNeedBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_WorkingCapitalNeedBay");
                OnCM_WorkingCapitalNeedBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_WorkingCapitalNeedBay;
        partial void OnCM_WorkingCapitalNeedBayChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_WorkingCapitalNeedBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_LoanNeedBay
        {
            get
            {
                return _CM_LoanNeedBay;
            }
            set
            {
                OnCM_LoanNeedBayChanging(value);
                ReportPropertyChanging("CM_LoanNeedBay");
                _CM_LoanNeedBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_LoanNeedBay");
                OnCM_LoanNeedBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_LoanNeedBay;
        partial void OnCM_LoanNeedBayChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_LoanNeedBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_WorkingCapitalApprove
        {
            get
            {
                return _CM_WorkingCapitalApprove;
            }
            set
            {
                OnCM_WorkingCapitalApproveChanging(value);
                ReportPropertyChanging("CM_WorkingCapitalApprove");
                _CM_WorkingCapitalApprove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_WorkingCapitalApprove");
                OnCM_WorkingCapitalApproveChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_WorkingCapitalApprove;
        partial void OnCM_WorkingCapitalApproveChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_WorkingCapitalApproveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CM_LoanApprove
        {
            get
            {
                return _CM_LoanApprove;
            }
            set
            {
                OnCM_LoanApproveChanging(value);
                ReportPropertyChanging("CM_LoanApprove");
                _CM_LoanApprove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CM_LoanApprove");
                OnCM_LoanApproveChanged();
            }
        }
        private Nullable<global::System.Decimal> _CM_LoanApprove;
        partial void OnCM_LoanApproveChanging(Nullable<global::System.Decimal> value);
        partial void OnCM_LoanApproveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CMDEFAULT_DefaultMargin
        {
            get
            {
                return _CMDEFAULT_DefaultMargin;
            }
            set
            {
                OnCMDEFAULT_DefaultMarginChanging(value);
                ReportPropertyChanging("CMDEFAULT_DefaultMargin");
                _CMDEFAULT_DefaultMargin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_DefaultMargin");
                OnCMDEFAULT_DefaultMarginChanged();
            }
        }
        private Nullable<global::System.Double> _CMDEFAULT_DefaultMargin;
        partial void OnCMDEFAULT_DefaultMarginChanging(Nullable<global::System.Double> value);
        partial void OnCMDEFAULT_DefaultMarginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CMDEFAULT_OperatingProfit
        {
            get
            {
                return _CMDEFAULT_OperatingProfit;
            }
            set
            {
                OnCMDEFAULT_OperatingProfitChanging(value);
                ReportPropertyChanging("CMDEFAULT_OperatingProfit");
                _CMDEFAULT_OperatingProfit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_OperatingProfit");
                OnCMDEFAULT_OperatingProfitChanged();
            }
        }
        private Nullable<global::System.Double> _CMDEFAULT_OperatingProfit;
        partial void OnCMDEFAULT_OperatingProfitChanging(Nullable<global::System.Double> value);
        partial void OnCMDEFAULT_OperatingProfitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_CurrentLiabilitiesWithBay
        {
            get
            {
                return _CMDEFAULT_CurrentLiabilitiesWithBay;
            }
            set
            {
                OnCMDEFAULT_CurrentLiabilitiesWithBayChanging(value);
                ReportPropertyChanging("CMDEFAULT_CurrentLiabilitiesWithBay");
                _CMDEFAULT_CurrentLiabilitiesWithBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_CurrentLiabilitiesWithBay");
                OnCMDEFAULT_CurrentLiabilitiesWithBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_CurrentLiabilitiesWithBay;
        partial void OnCMDEFAULT_CurrentLiabilitiesWithBayChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_CurrentLiabilitiesWithBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_LongTermDebtWithBay
        {
            get
            {
                return _CMDEFAULT_LongTermDebtWithBay;
            }
            set
            {
                OnCMDEFAULT_LongTermDebtWithBayChanging(value);
                ReportPropertyChanging("CMDEFAULT_LongTermDebtWithBay");
                _CMDEFAULT_LongTermDebtWithBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_LongTermDebtWithBay");
                OnCMDEFAULT_LongTermDebtWithBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_LongTermDebtWithBay;
        partial void OnCMDEFAULT_LongTermDebtWithBayChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_LongTermDebtWithBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_WorkingCapitalNeed
        {
            get
            {
                return _CMDEFAULT_WorkingCapitalNeed;
            }
            set
            {
                OnCMDEFAULT_WorkingCapitalNeedChanging(value);
                ReportPropertyChanging("CMDEFAULT_WorkingCapitalNeed");
                _CMDEFAULT_WorkingCapitalNeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_WorkingCapitalNeed");
                OnCMDEFAULT_WorkingCapitalNeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_WorkingCapitalNeed;
        partial void OnCMDEFAULT_WorkingCapitalNeedChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_WorkingCapitalNeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_LoanNeed
        {
            get
            {
                return _CMDEFAULT_LoanNeed;
            }
            set
            {
                OnCMDEFAULT_LoanNeedChanging(value);
                ReportPropertyChanging("CMDEFAULT_LoanNeed");
                _CMDEFAULT_LoanNeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_LoanNeed");
                OnCMDEFAULT_LoanNeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_LoanNeed;
        partial void OnCMDEFAULT_LoanNeedChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_LoanNeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_WorkingCapitalCal
        {
            get
            {
                return _CMDEFAULT_WorkingCapitalCal;
            }
            set
            {
                OnCMDEFAULT_WorkingCapitalCalChanging(value);
                ReportPropertyChanging("CMDEFAULT_WorkingCapitalCal");
                _CMDEFAULT_WorkingCapitalCal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_WorkingCapitalCal");
                OnCMDEFAULT_WorkingCapitalCalChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_WorkingCapitalCal;
        partial void OnCMDEFAULT_WorkingCapitalCalChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_WorkingCapitalCalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_LoanCal
        {
            get
            {
                return _CMDEFAULT_LoanCal;
            }
            set
            {
                OnCMDEFAULT_LoanCalChanging(value);
                ReportPropertyChanging("CMDEFAULT_LoanCal");
                _CMDEFAULT_LoanCal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_LoanCal");
                OnCMDEFAULT_LoanCalChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_LoanCal;
        partial void OnCMDEFAULT_LoanCalChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_LoanCalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_WorkingCapitalRequire
        {
            get
            {
                return _CMDEFAULT_WorkingCapitalRequire;
            }
            set
            {
                OnCMDEFAULT_WorkingCapitalRequireChanging(value);
                ReportPropertyChanging("CMDEFAULT_WorkingCapitalRequire");
                _CMDEFAULT_WorkingCapitalRequire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_WorkingCapitalRequire");
                OnCMDEFAULT_WorkingCapitalRequireChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_WorkingCapitalRequire;
        partial void OnCMDEFAULT_WorkingCapitalRequireChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_WorkingCapitalRequireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_LoanRequire
        {
            get
            {
                return _CMDEFAULT_LoanRequire;
            }
            set
            {
                OnCMDEFAULT_LoanRequireChanging(value);
                ReportPropertyChanging("CMDEFAULT_LoanRequire");
                _CMDEFAULT_LoanRequire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_LoanRequire");
                OnCMDEFAULT_LoanRequireChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_LoanRequire;
        partial void OnCMDEFAULT_LoanRequireChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_LoanRequireChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_LimitOfLGAndAvalNonCash
        {
            get
            {
                return _CMDEFAULT_LimitOfLGAndAvalNonCash;
            }
            set
            {
                OnCMDEFAULT_LimitOfLGAndAvalNonCashChanging(value);
                ReportPropertyChanging("CMDEFAULT_LimitOfLGAndAvalNonCash");
                _CMDEFAULT_LimitOfLGAndAvalNonCash = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_LimitOfLGAndAvalNonCash");
                OnCMDEFAULT_LimitOfLGAndAvalNonCashChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_LimitOfLGAndAvalNonCash;
        partial void OnCMDEFAULT_LimitOfLGAndAvalNonCashChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_LimitOfLGAndAvalNonCashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CMDEFAULT_DSCRInThisTime
        {
            get
            {
                return _CMDEFAULT_DSCRInThisTime;
            }
            set
            {
                OnCMDEFAULT_DSCRInThisTimeChanging(value);
                ReportPropertyChanging("CMDEFAULT_DSCRInThisTime");
                _CMDEFAULT_DSCRInThisTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_DSCRInThisTime");
                OnCMDEFAULT_DSCRInThisTimeChanged();
            }
        }
        private Nullable<global::System.Double> _CMDEFAULT_DSCRInThisTime;
        partial void OnCMDEFAULT_DSCRInThisTimeChanging(Nullable<global::System.Double> value);
        partial void OnCMDEFAULT_DSCRInThisTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CMDEFAULT_DEInThisTime
        {
            get
            {
                return _CMDEFAULT_DEInThisTime;
            }
            set
            {
                OnCMDEFAULT_DEInThisTimeChanging(value);
                ReportPropertyChanging("CMDEFAULT_DEInThisTime");
                _CMDEFAULT_DEInThisTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_DEInThisTime");
                OnCMDEFAULT_DEInThisTimeChanged();
            }
        }
        private Nullable<global::System.Double> _CMDEFAULT_DEInThisTime;
        partial void OnCMDEFAULT_DEInThisTimeChanging(Nullable<global::System.Double> value);
        partial void OnCMDEFAULT_DEInThisTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CMDEFAULT_LTV
        {
            get
            {
                return _CMDEFAULT_LTV;
            }
            set
            {
                OnCMDEFAULT_LTVChanging(value);
                ReportPropertyChanging("CMDEFAULT_LTV");
                _CMDEFAULT_LTV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_LTV");
                OnCMDEFAULT_LTVChanged();
            }
        }
        private Nullable<global::System.Double> _CMDEFAULT_LTV;
        partial void OnCMDEFAULT_LTVChanging(Nullable<global::System.Double> value);
        partial void OnCMDEFAULT_LTVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_WorkingCapitalNeedBay
        {
            get
            {
                return _CMDEFAULT_WorkingCapitalNeedBay;
            }
            set
            {
                OnCMDEFAULT_WorkingCapitalNeedBayChanging(value);
                ReportPropertyChanging("CMDEFAULT_WorkingCapitalNeedBay");
                _CMDEFAULT_WorkingCapitalNeedBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_WorkingCapitalNeedBay");
                OnCMDEFAULT_WorkingCapitalNeedBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_WorkingCapitalNeedBay;
        partial void OnCMDEFAULT_WorkingCapitalNeedBayChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_WorkingCapitalNeedBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_LoanNeedBay
        {
            get
            {
                return _CMDEFAULT_LoanNeedBay;
            }
            set
            {
                OnCMDEFAULT_LoanNeedBayChanging(value);
                ReportPropertyChanging("CMDEFAULT_LoanNeedBay");
                _CMDEFAULT_LoanNeedBay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_LoanNeedBay");
                OnCMDEFAULT_LoanNeedBayChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_LoanNeedBay;
        partial void OnCMDEFAULT_LoanNeedBayChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_LoanNeedBayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_WorkingCapitalApprove
        {
            get
            {
                return _CMDEFAULT_WorkingCapitalApprove;
            }
            set
            {
                OnCMDEFAULT_WorkingCapitalApproveChanging(value);
                ReportPropertyChanging("CMDEFAULT_WorkingCapitalApprove");
                _CMDEFAULT_WorkingCapitalApprove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_WorkingCapitalApprove");
                OnCMDEFAULT_WorkingCapitalApproveChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_WorkingCapitalApprove;
        partial void OnCMDEFAULT_WorkingCapitalApproveChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_WorkingCapitalApproveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CMDEFAULT_LoanApprove
        {
            get
            {
                return _CMDEFAULT_LoanApprove;
            }
            set
            {
                OnCMDEFAULT_LoanApproveChanging(value);
                ReportPropertyChanging("CMDEFAULT_LoanApprove");
                _CMDEFAULT_LoanApprove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMDEFAULT_LoanApprove");
                OnCMDEFAULT_LoanApproveChanged();
            }
        }
        private Nullable<global::System.Decimal> _CMDEFAULT_LoanApprove;
        partial void OnCMDEFAULT_LoanApproveChanging(Nullable<global::System.Decimal> value);
        partial void OnCMDEFAULT_LoanApproveChanged();

        #endregion
    
    }

    #endregion
    
}
