ALTER TABLE [CLASSIFY].[LINKED_CATEGORY_TYPE]
    ADD CONSTRAINT [FK_CATEGORY_TYPE_RECURSIVE_CATEGORY_TYPE] FOREIGN KEY ([CATEGORY_TYPE_KEY]) REFERENCES [CLASSIFY].[CATEGORY_TYPE] ([CATEGORY_TYPE_KEY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

