ALTER TABLE [CLASSIFY].[CATE_AND_MENU]
    ADD CONSTRAINT [FK_CATE_AND_MENU_MENU_MASTER] FOREIGN KEY ([MENU_KEY]) REFERENCES [PERMISSION].[MENU_MASTER] ([MENU_KEY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

