ALTER TABLE [CLASSIFY].[CATEGORY_TYPE]
    ADD CONSTRAINT [PK_CLASSIFY_TYPE.CATEGORY] PRIMARY KEY CLUSTERED ([CATEGORY_TYPE_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

