ALTER TABLE [CLASSIFY].[LINKED_CATEGORY]
    ADD CONSTRAINT [FK_CATEGORY_RECURSIVE_CATEGORY1] FOREIGN KEY ([LINK_TO_CATEGORY_KEY]) REFERENCES [CLASSIFY].[CATEGORY] ([CATEGORY_KEY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

