ALTER TABLE [CLASSIFY].[CATE_AND_EMP]
    ADD CONSTRAINT [FK_CATE_AND_EMP_CATEGORY] FOREIGN KEY ([CATEGORY_KEY]) REFERENCES [CLASSIFY].[CATEGORY] ([CATEGORY_KEY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

