ALTER TABLE [CLASSIFY].[LINKED_CATEGORY_TYPE]
    ADD CONSTRAINT [PK_CATEGORY_TYPE_RECURSIVE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

