ALTER TABLE [CLASSIFY].[LINKED_TYPE]
    ADD CONSTRAINT [PK_CATEGORY_RECURSIVE_TYPE_KEY] PRIMARY KEY CLUSTERED ([LINKED_TYPE_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

