ALTER TABLE [dbo].[SME_GROUP_EXPOSURE]
    ADD CONSTRAINT [FK_SME_GROUP_EXPOSURE_SME_EXPOSURE_TYPE] FOREIGN KEY ([EXPOSURE_TYPE_ID]) REFERENCES [dbo].[SME_EXPOSURE_TYPE] ([EXPOSURE_TYPE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

