ALTER TABLE [dbo].[JUDGEMENT_MONTHLY]
    ADD CONSTRAINT [PK_JUDGEMENT_MONTHLY] PRIMARY KEY CLUSTERED ([CIF] ASC, [SNAP_DATE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

