ALTER TABLE [dbo].[CM_PORT_BY_BRANCH]
    ADD CONSTRAINT [PK_CM_PORT_BY_BRANCH] PRIMARY KEY CLUSTERED ([BRANCH_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

