ALTER TABLE [dbo].[TB_KPI_LAST_CA]
    ADD CONSTRAINT [PK_TB_KPI_LAST_CA] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

