ALTER TABLE [dbo].[RatingPivot]
    ADD CONSTRAINT [PK_RatingPivot] PRIMARY KEY CLUSTERED ([cif] ASC, [yy] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

