ALTER TABLE [dbo].[Id_Fled_Type]
    ADD CONSTRAINT [PK_Id_Fled_Type] PRIMARY KEY CLUSTERED ([Id_Fled_Type] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

