ALTER TABLE [dbo].[EXPORTER_LOOKUP]
    ADD CONSTRAINT [PK_EXPORTER_LOOKUP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

