ALTER TABLE [dbo].[RoleGroup_CifInRole]
    ADD CONSTRAINT [PK_TEST_CIF_VIEW] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

