ALTER TABLE [dbo].[Authen_Application]
    ADD CONSTRAINT [PK_Authen_Application] PRIMARY KEY CLUSTERED ([AppId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

