ALTER TABLE [dbo].[ANNALS_CHANGE_TO_COMMON]
    ADD CONSTRAINT [PK_ANNALS_CHANGE_TO_COMMON] PRIMARY KEY CLUSTERED ([CHANGE_DATE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

