ALTER TABLE [dbo].[RELATION_EXPOSURE_CIF]
    ADD CONSTRAINT [FK_RELATION_EXPOSURE_CIF_SME_GROUP_EXPOSURE] FOREIGN KEY ([EXPOSURE_ID]) REFERENCES [dbo].[SME_GROUP_EXPOSURE] ([EXPOSURE_ID]) ON DELETE CASCADE ON UPDATE NO ACTION;

