ALTER TABLE [dbo].[RELATION_GROUP_EXPOSURE]
    ADD CONSTRAINT [FK_RELATION_GROUP_EXPOSURE_CUSTOMER_SME_GROUP] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[CUSTOMER_SME_GROUP] ([GROUP_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

