ALTER TABLE [dbo].[Bus_Type]
    ADD CONSTRAINT [PK_Bus_Type] PRIMARY KEY CLUSTERED ([Id_Bus_Type] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

