ALTER TABLE [dbo].[CIMfms]
    ADD CONSTRAINT [PK_CIMfms] PRIMARY KEY CLUSTERED ([ACCGL] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

