ALTER TABLE [dbo].[CUSTOMER_SME_HISTORY]
    ADD CONSTRAINT [PK_CUSTOMER_SME_JUDGEMENT_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

