ALTER TABLE [dbo].[CustomerTemp]
    ADD CONSTRAINT [PK_CustomerTemp] PRIMARY KEY CLUSTERED ([Cif] ASC, [Create_date] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

