ALTER TABLE [dbo].[CIF_WATCHLIST_CA]
    ADD CONSTRAINT [PK_CIF_WATCHLIST_CA] PRIMARY KEY CLUSTERED ([CIF] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

