ALTER TABLE [dbo].[TBM_CAT002]
    ADD CONSTRAINT [PK_TBM_CAT002] PRIMARY KEY CLUSTERED ([IBRNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

