ALTER TABLE [dbo].[TB_Holiday]
    ADD CONSTRAINT [PK_TB_Holiday] PRIMARY KEY CLUSTERED ([Days] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

