ALTER TABLE [dbo].[Controlling_Users_Region]
    ADD CONSTRAINT [PK_Controlling_Users_Region] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

