ALTER TABLE [dbo].[ANNALS_VIEWER]
    ADD CONSTRAINT [PK_ANNALS_VIEWER] PRIMARY KEY CLUSTERED ([ANNALS_TYPE] ASC, [ANNALS_SEQ_NO] ASC, [ANNALS_YEAR] ASC, [EMP_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

