ALTER TABLE [dbo].[CUS_SME_EXPORT_WEIGHT]
    ADD CONSTRAINT [FK_CUS_SME_EXPORT_WEIGHT_EXPORTER_LOOKUP] FOREIGN KEY ([EXPORT_TO]) REFERENCES [dbo].[EXPORTER_LOOKUP] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

