ALTER TABLE [dbo].[CIF_NOT_IN_CUSTOMER_SME]
    ADD CONSTRAINT [PK_CIF_NOT_IN_CUSTOMER_SME] PRIMARY KEY CLUSTERED ([CIF] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

