ALTER TABLE [dbo].[CUSTOMER_STATUS]
    ADD CONSTRAINT [PK_CUSTOMER_STATUS] PRIMARY KEY CLUSTERED ([STATUS_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

