ALTER TABLE [dbo].[ANNALS_JUDGEMENT]
    ADD CONSTRAINT [PK_ANNALS_JUDGEMENT] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

