ALTER TABLE [dbo].[EXPORTER_LOOKUP]
    ADD CONSTRAINT [FK_EXPORTER_LOOKUP_EXPORT_LOOKUP_TYPE] FOREIGN KEY ([LOOKUP_TYPE]) REFERENCES [dbo].[EXPORT_LOOKUP_TYPE] ([LOOKUP_TYPE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

