ALTER TABLE [dbo].[SME_GROUP_EXPOSURE]
    ADD CONSTRAINT [PK_SME_GROUP_EXPOSURE] PRIMARY KEY CLUSTERED ([EXPOSURE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

