ALTER TABLE [dbo].[TEMP_Vintage_200906]
    ADD CONSTRAINT [PK_TEMP_Vintage_200906] PRIMARY KEY CLUSTERED ([CIF] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

