ALTER TABLE [dbo].[TB_TITLE]
    ADD CONSTRAINT [PK_TB_TITLE] PRIMARY KEY CLUSTERED ([TITLE_CODE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

