ALTER TABLE [dbo].[REGION10_DESC]
    ADD CONSTRAINT [PK_REGION10_DESC] PRIMARY KEY CLUSTERED ([BRANCH_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

