ALTER TABLE [dbo].[RELATION_GROUP_EXPOSURE]
    ADD CONSTRAINT [PK_RELATION_GROUP_EXPOSURE] PRIMARY KEY CLUSTERED ([G_EXPO_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

