ALTER TABLE [dbo].[ANNALS_PROJECT]
    ADD CONSTRAINT [PK_ANNALS_PROJECT_TYPE] PRIMARY KEY CLUSTERED ([Project_Code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

