ALTER TABLE [dbo].[CUS_SME_IMPORT_WEIGHT]
    ADD CONSTRAINT [FK_CUS_SME_IMPORT_WEIGHT_EXPORTER_LOOKUP1] FOREIGN KEY ([CURRENCY_TYPE]) REFERENCES [dbo].[EXPORTER_LOOKUP] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

