ALTER TABLE [dbo].[ANNALS_CUS_NCB_EXCEPT_TYPE]
    ADD CONSTRAINT [PK_ANNALS_CUS_NCB_EXCEPT_TYPE] PRIMARY KEY CLUSTERED ([CUS_NCB_EXCEPT_TYPE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

