ALTER TABLE [dbo].[ANNALS_SUBJECT]
    ADD CONSTRAINT [PK_ANNALS_SUBJECT] PRIMARY KEY CLUSTERED ([SUBJECT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

