ALTER TABLE [dbo].[ANNALS_COVENANT]
    ADD CONSTRAINT [PK_ANNALS_COVENANT] PRIMARY KEY CLUSTERED ([IDEN] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

