ALTER TABLE [dbo].[Id_Department]
    ADD CONSTRAINT [PK_Id_Department] PRIMARY KEY CLUSTERED ([Id_Depart] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

