ALTER TABLE [dbo].[ANNALS_GL_TYPE]
    ADD CONSTRAINT [PK_ANNALS_GL_TYPE] PRIMARY KEY CLUSTERED ([DECB_RD_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

