ALTER TABLE [dbo].[Id_TypeCid05]
    ADD CONSTRAINT [PK_Id_TypeCid05] PRIMARY KEY CLUSTERED ([Id_TypeCid05] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

