ALTER TABLE [dbo].[Controlling_LeadsInLevel]
    ADD CONSTRAINT [PK_Controlling_LeadsInLevel] PRIMARY KEY CLUSTERED ([LEVEL_ID] ASC, [EMP_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

