ALTER TABLE [dbo].[Controlling_Level]
    ADD CONSTRAINT [PK_CONTROLLING_LEVEL] PRIMARY KEY CLUSTERED ([LEVEL_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

