ALTER TABLE [dbo].[REP_OD13]
    ADD CONSTRAINT [PK_REP_OD12] PRIMARY KEY CLUSTERED ([accno] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

