ALTER TABLE [dbo].[CLS_WHEN_APPROVE]
    ADD CONSTRAINT [PK_CLS_WHEN_APPROVE] PRIMARY KEY CLUSTERED ([ID_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

