ALTER TABLE [dbo].[CUS_SME_EXPORTER]
    ADD CONSTRAINT [FK_CUS_SME_EXPORTER_EXPORTER_LOOKUP6] FOREIGN KEY ([IM_CURRENCY_TYPE_1]) REFERENCES [dbo].[EXPORTER_LOOKUP] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

