ALTER TABLE [dbo].[BUSINESS_TYPE_2]
    ADD CONSTRAINT [PK_TYPE2] PRIMARY KEY CLUSTERED ([TYPE2_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

