ALTER TABLE [dbo].[RELATION_EXPOSURE_CIF]
    ADD CONSTRAINT [PK_RELATION_EXPOSURE_CIF] PRIMARY KEY CLUSTERED ([EXPO_CIF_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

