ALTER TABLE [dbo].[CUS_SME_EXPORTER]
    ADD CONSTRAINT [PK_CUS_SME_EXPORTER] PRIMARY KEY CLUSTERED ([CIF] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

