ALTER TABLE [dbo].[TEMP_TB_CLS_MAPPING_BY_IDEN]
    ADD CONSTRAINT [PK_TEMP_TB_CLS_MAPPING_BY_IDEN] PRIMARY KEY CLUSTERED ([SUBJECT_IDEN] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

