ALTER TABLE [dbo].[CUS_SME_IMPORT_WEIGHT]
    ADD CONSTRAINT [FK_CUS_SME_IMPORT_WEIGHT_CUS_SME_EXPORTER] FOREIGN KEY ([CIF]) REFERENCES [dbo].[CUS_SME_EXPORTER] ([CIF]) ON DELETE NO ACTION ON UPDATE NO ACTION;

