ALTER TABLE [dbo].[ByCustomer_2547]
    ADD CONSTRAINT [PK_ByCustomer_2547] PRIMARY KEY CLUSTERED ([Cif] ASC, [YM] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

