ALTER TABLE [dbo].[COLLVAL]
    ADD CONSTRAINT [PK_COLLVAL] PRIMARY KEY CLUSTERED ([COLL_ID] ASC, [CIF] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

