ALTER TABLE [dbo].[TBM_CAT902]
    ADD CONSTRAINT [PK_TBM_CAT902] PRIMARY KEY CLUSTERED ([IAREA] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

