ALTER TABLE [dbo].[TEMP_OLD_EMP_LINE]
    ADD CONSTRAINT [PK_TEMP_OLD_EMP_LINE] PRIMARY KEY CLUSTERED ([EMP_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

