ALTER TABLE [dbo].[TEMP_PORT_20111231]
    ADD CONSTRAINT [PK_TEMP_PORT_20111231] PRIMARY KEY CLUSTERED ([Cif] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

