ALTER TABLE [dbo].[CUSTOMER_SME_RATING]
    ADD CONSTRAINT [FK_CUSTOMER_SME_RATING_CUSTOMER_SME_RATING_TYPE1] FOREIGN KEY ([RATING_TYPE_KEY]) REFERENCES [dbo].[CUSTOMER_SME_RATING_TYPE] ([RATING_TYPE_KEY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

