ALTER TABLE [dbo].[ANNALS_TYPE]
    ADD CONSTRAINT [PK_ANNALS_TYPE] PRIMARY KEY CLUSTERED ([ANNALS_TYPE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

