ALTER TABLE [dbo].[TB_EMPLOYEE]
    ADD CONSTRAINT [PK_TB_EMPLOYEE_1] PRIMARY KEY CLUSTERED ([EMP_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

