ALTER TABLE [dbo].[ANNALS]
    ADD CONSTRAINT [PK_ANNALS] PRIMARY KEY CLUSTERED ([ANNALS_TYPE] ASC, [ANNALS_SEQ_NO] ASC, [ANNALS_YEAR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

