ALTER TABLE [dbo].[TEMP_CLASS_HISTORY]
    ADD CONSTRAINT [PK_TEMP_CLASS_HISTORY] PRIMARY KEY CLUSTERED ([CIF] ASC, [AS_OF] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

