ALTER TABLE [dbo].[EXPORT_LOOKUP_TYPE]
    ADD CONSTRAINT [PK_EXPORT_LOOKUP_TYPE] PRIMARY KEY CLUSTERED ([LOOKUP_TYPE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

