ALTER TABLE [dbo].[BUSINESS_DESTINATION]
    ADD CONSTRAINT [PK_BUSINESS_DESTINATION] PRIMARY KEY CLUSTERED ([BUSINESS_DESTINATION_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

