ALTER TABLE [dbo].[TEMP_KPI_DEBT_20091117]
    ADD CONSTRAINT [PK_TEMP_KPI_DEBT] PRIMARY KEY CLUSTERED ([cif] ASC, [AS_OF_DATE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

