ALTER TABLE [dbo].[TB_CONTACT]
    ADD CONSTRAINT [PK_TR_] PRIMARY KEY CLUSTERED ([CIF] ASC, [NAME] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

