ALTER TABLE [dbo].[Bus_Group]
    ADD CONSTRAINT [PK_Bus_Group] PRIMARY KEY CLUSTERED ([Id_Bus_Group] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

