ALTER TABLE [dbo].[UPLOAD_FILE_TYPE]
    ADD CONSTRAINT [PK_UPLOAD_FILE_TYPE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

