ALTER TABLE [dbo].[TB_CUSTOMER_RISK]
    ADD CONSTRAINT [PK_TB_CUSTOMER_RISK] PRIMARY KEY CLUSTERED ([Cif] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

