ALTER TABLE [dbo].[busi_map]
    ADD CONSTRAINT [PK_busi_map] PRIMARY KEY CLUSTERED ([new_code] ASC, [old_code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

