ALTER TABLE [dbo].[CUS_SME_IMPORT_WEIGHT]
    ADD CONSTRAINT [FK_CUS_SME_IMPORT_WEIGHT_EXPORTER_LOOKUP] FOREIGN KEY ([IMPORT_FROM]) REFERENCES [dbo].[EXPORTER_LOOKUP] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

