ALTER TABLE [dbo].[TB_LOG]
    ADD CONSTRAINT [PK_TB_LOG_1] PRIMARY KEY CLUSTERED ([TRANDATE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

