ALTER TABLE [dbo].[Id_Shr_Type]
    ADD CONSTRAINT [PK_Id_Shr_Type] PRIMARY KEY CLUSTERED ([Id_Shr_Type] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

