ALTER TABLE [dbo].[Controlling_User_Root_Viewer]
    ADD CONSTRAINT [PK_Controlling_User_Root_Viewer] PRIMARY KEY CLUSTERED ([EMP_ID] ASC, [LEVEL_ROOT_VIEWER] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

