ALTER TABLE [dbo].[ANNALS_OBJECT]
    ADD CONSTRAINT [PK_ANNALS_OBJECT] PRIMARY KEY CLUSTERED ([OBJECT_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

