ALTER TABLE [dbo].[RoleGroup_RoleCategory]
    ADD CONSTRAINT [PK_TEST_ROLE_CATEGORY] PRIMARY KEY CLUSTERED ([ROLE_CATEGORY_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

