ALTER TABLE [dbo].[CUS_SME_EXPORTER]
    ADD CONSTRAINT [FK_CUS_SME_EXPORTER_EXPORTER_LOOKUP3] FOREIGN KEY ([EX_CURRENCY_TYPE_2]) REFERENCES [dbo].[EXPORTER_LOOKUP] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

