ALTER TABLE [dbo].[ANNALS_AUTHORITY]
    ADD CONSTRAINT [PK_ANNALS_AUTHORITY] PRIMARY KEY CLUSTERED ([Authority_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

