ALTER TABLE [dbo].[ANNALS_JOB_TYPE]
    ADD CONSTRAINT [PK_ANNALS_JOB_TYPE] PRIMARY KEY CLUSTERED ([Job_Type_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

