ALTER TABLE [dbo].[CUSTOMER_SME_SIZE]
    ADD CONSTRAINT [PK_CUSTOMER_SME_SIZE] PRIMARY KEY CLUSTERED ([SIZE_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

