ALTER TABLE [dbo].[RoleGroup_RoleLink]
    ADD CONSTRAINT [PK_TEST_ROLE_LINK] PRIMARY KEY CLUSTERED ([LINK_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

