ALTER TABLE [dbo].[Id_Branch]
    ADD CONSTRAINT [PK_Id_Branch] PRIMARY KEY CLUSTERED ([Id_Branch] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

