ALTER TABLE [dbo].[ANNALS_CREDIT_ACCOUNT]
    ADD CONSTRAINT [PK_ANNALS_CREDIT_ACCOUNT] PRIMARY KEY NONCLUSTERED ([IDEN] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

