ALTER TABLE [dbo].[CUSTOMER_SME_RATING_TYPE]
    ADD CONSTRAINT [PK_CUSTOMER_SME_RATING_TYPE_1] PRIMARY KEY CLUSTERED ([RATING_TYPE_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

