ALTER TABLE [dbo].[ANNALS_OLD_REGION]
    ADD CONSTRAINT [PK_ANNALS_OLD_REGION] PRIMARY KEY CLUSTERED ([ANNALS_ID] ASC, [INSERT_DATE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

