ALTER TABLE [EMPLOYEE].[EMP20110531]
    ADD CONSTRAINT [PK_EMP20110531] PRIMARY KEY CLUSTERED ([IEMPID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

