ALTER TABLE [EMPLOYEE].[USER_DATA]
    ADD CONSTRAINT [PK_USER_DATA] PRIMARY KEY CLUSTERED ([EMP_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

