ALTER TABLE [PERMISSION].[APPLICATION]
    ADD CONSTRAINT [PK_APPLICATION] PRIMARY KEY CLUSTERED ([APP_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

