ALTER TABLE [PERMISSION].[MENU_MASTER]
    ADD CONSTRAINT [FK_MENU_MASTER_MENU_MASTER] FOREIGN KEY ([MENU_PARENT_KEY]) REFERENCES [PERMISSION].[MENU_MASTER] ([MENU_KEY]) ON DELETE NO ACTION ON UPDATE NO ACTION;

