ALTER TABLE [PERMISSION].[MENU_MASTER]
    ADD CONSTRAINT [PK_MENU_MASTER] PRIMARY KEY CLUSTERED ([MENU_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

