ALTER TABLE [SM].[SM_HISTORY]
    ADD CONSTRAINT [PK_SM_HISTORY] PRIMARY KEY CLUSTERED ([IDEN] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

