CREATE TABLE [SS].[FINANCIAL_CUSTOMER]
(
	[SMES_ID] [int] NOT NULL,
	[CREATE_USER] [nvarchar](10) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_USER] [nvarchar](10) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[CIF] [int] NULL,
	[CUSTOMER_TYPE] [nvarchar](4) NULL,
	[BIRTH_DATE] [datetime] NULL,
	[NATIONALITY_LIST_ID] [nvarchar](4) NULL,
	[EXPERIENCE] [int] NULL,
	[JURISTIC_LIST_ID] [nvarchar](4) NULL,
	[REGISTER_DATE] [datetime] NULL,
	[OPERATE_DATE] [datetime] NULL,
	[BLACKLIST_LIST_ID] [nvarchar](4) NULL,
	[NCB_LIST_ID] [nvarchar](4) NULL,
	[NCB_CODE] [nvarchar](4) NULL,
	[TDR_LIST_ID] [nvarchar](4) NULL,
	[RATING_LISt_ID] [nvarchar](4) NULL,
	[LEGAL_LIST_ID] [nvarchar](4) NULL,
	[REGIS_DOC_LIST_ID] [nvarchar](4) NULL,
	[SHAREHOLDER_LIST_ID] [nvarchar](4) NULL,
	[BNATIONALITY_LIST_ID] [nvarchar](4) NULL
)
