CREATE TABLE [SS].[FINANCIAL_DATA_EXCELL]
(
	[IDEN] [int] IDENTITY(1,1) NOT NULL,
	[FILE_NAME] [nvarchar](255) NULL,
	[CIF] [int] NOT NULL,
	[CIF_NAME] [nvarchar](100) NULL,
	[BUS_Code] [nvarchar](10) NULL,
	[BUS_GRP] [nvarchar](50) NULL,
	[RM_I_GROSS_PROFIT] [money] NULL,
	[CM_I_GROSS_PROFIT] [money] NULL,
	[RM_C_EBIDA_PERCENT] [money] NULL,
	[CM_C_EBIDA_PERCENT] [money] NULL,
	[RM_C_EBIDA] [money] NULL,
	[CM_C_EBIDA] [money] NULL,
	[RM_C_WORKING_CAPITAL] [money] NULL,
	[CM_C_WORKING_CAPITAL] [money] NULL,
	[RM_C_LOAN] [money] NULL,
	[CM_C_LOAN] [money] NULL,
	[RM_A_WORKING_CAPITAL] [money] NULL,
	[CM_A_WORKING_CAPITAL] [money] NULL,
	[RM_A_LOAN] [money] NULL,
	[CM_A_LOAN] [money] NULL,
	[RM_I_WORKING_CAPITAL] [money] NULL,
	[CM_I_WORKING_CAPITAL] [money] NULL,
	[RM_I_LOAN] [money] NULL,
	[CM_I_LOAN] [money] NULL,
	[RM_I_DSCR] [money] NULL,
	[CM_I_DSCR] [money] NULL,
	[UPDATE_DATE] [datetime] NULL
)
