CREATE UNIQUE NONCLUSTERED INDEX [IX_CATE_AND_CUS]
    ON [CLASSIFY].[CATE_AND_CUS]
(
	[CATEGORY_KEY] ASC,
	[CIF] ASC
)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
