CREATE UNIQUE NONCLUSTERED INDEX [IX_APP_PROFILE] ON [CLASSIFY].[APP_PROFILE] 
(
	[APP_KEY] ASC,
	[EMP_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

