//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 26/4/2554 13:43:49
namespace LGDCollectionData.Entities
{
    
    /// <summary>
    /// There are no comments for LGDEntities in the schema.
    /// </summary>
    public partial class LGDEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new LGDEntities object using the connection string found in the 'LGDEntities' section of the application configuration file.
        /// </summary>
        public LGDEntities() : 
                base("name=LGDEntities", "LGDEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LGDEntities object.
        /// </summary>
        public LGDEntities(string connectionString) : 
                base(connectionString, "LGDEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LGDEntities object.
        /// </summary>
        public LGDEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "LGDEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for USER_DATA in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<USER_DATA> USER_DATA
        {
            get
            {
                if ((this._USER_DATA == null))
                {
                    this._USER_DATA = base.CreateQuery<USER_DATA>("[USER_DATA]");
                }
                return this._USER_DATA;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<USER_DATA> _USER_DATA;
        /// <summary>
        /// There are no comments for USER_DATA in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToUSER_DATA(USER_DATA uSER_DATA)
        {
            base.AddObject("USER_DATA", uSER_DATA);
        }
    }
    /// <summary>
    /// There are no comments for LGDModel.USER_DATA in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EMP_ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LGDModel", Name="USER_DATA")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class USER_DATA : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new USER_DATA object.
        /// </summary>
        /// <param name="eMP_ID">Initial value of EMP_ID.</param>
        /// <param name="eMP_ID_DISPLAY">Initial value of EMP_ID_DISPLAY.</param>
        /// <param name="eMP_TITLE">Initial value of EMP_TITLE.</param>
        /// <param name="eMP_NAME">Initial value of EMP_NAME.</param>
        /// <param name="eMP_SURNAME">Initial value of EMP_SURNAME.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static USER_DATA CreateUSER_DATA(string eMP_ID, string eMP_ID_DISPLAY, string eMP_TITLE, string eMP_NAME, string eMP_SURNAME)
        {
            USER_DATA uSER_DATA = new USER_DATA();
            uSER_DATA.EMP_ID = eMP_ID;
            uSER_DATA.EMP_ID_DISPLAY = eMP_ID_DISPLAY;
            uSER_DATA.EMP_TITLE = eMP_TITLE;
            uSER_DATA.EMP_NAME = eMP_NAME;
            uSER_DATA.EMP_SURNAME = eMP_SURNAME;
            return uSER_DATA;
        }
        /// <summary>
        /// There are no comments for property EMP_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMP_ID
        {
            get
            {
                return this._EMP_ID;
            }
            set
            {
                this.OnEMP_IDChanging(value);
                this.ReportPropertyChanging("EMP_ID");
                this._EMP_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EMP_ID");
                this.OnEMP_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMP_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_IDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_IDChanged();
        /// <summary>
        /// There are no comments for property EMP_ID_DISPLAY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMP_ID_DISPLAY
        {
            get
            {
                return this._EMP_ID_DISPLAY;
            }
            set
            {
                this.OnEMP_ID_DISPLAYChanging(value);
                this.ReportPropertyChanging("EMP_ID_DISPLAY");
                this._EMP_ID_DISPLAY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EMP_ID_DISPLAY");
                this.OnEMP_ID_DISPLAYChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMP_ID_DISPLAY;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_ID_DISPLAYChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_ID_DISPLAYChanged();
        /// <summary>
        /// There are no comments for property EMP_TITLE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMP_TITLE
        {
            get
            {
                return this._EMP_TITLE;
            }
            set
            {
                this.OnEMP_TITLEChanging(value);
                this.ReportPropertyChanging("EMP_TITLE");
                this._EMP_TITLE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EMP_TITLE");
                this.OnEMP_TITLEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMP_TITLE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_TITLEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_TITLEChanged();
        /// <summary>
        /// There are no comments for property EMP_NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMP_NAME
        {
            get
            {
                return this._EMP_NAME;
            }
            set
            {
                this.OnEMP_NAMEChanging(value);
                this.ReportPropertyChanging("EMP_NAME");
                this._EMP_NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EMP_NAME");
                this.OnEMP_NAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMP_NAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_NAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_NAMEChanged();
        /// <summary>
        /// There are no comments for property EMP_SURNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMP_SURNAME
        {
            get
            {
                return this._EMP_SURNAME;
            }
            set
            {
                this.OnEMP_SURNAMEChanging(value);
                this.ReportPropertyChanging("EMP_SURNAME");
                this._EMP_SURNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EMP_SURNAME");
                this.OnEMP_SURNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMP_SURNAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_SURNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_SURNAMEChanged();
        /// <summary>
        /// There are no comments for property EMP_TITLE_E in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMP_TITLE_E
        {
            get
            {
                return this._EMP_TITLE_E;
            }
            set
            {
                this.OnEMP_TITLE_EChanging(value);
                this.ReportPropertyChanging("EMP_TITLE_E");
                this._EMP_TITLE_E = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EMP_TITLE_E");
                this.OnEMP_TITLE_EChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMP_TITLE_E;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_TITLE_EChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_TITLE_EChanged();
        /// <summary>
        /// There are no comments for property EMP_NAME_E in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMP_NAME_E
        {
            get
            {
                return this._EMP_NAME_E;
            }
            set
            {
                this.OnEMP_NAME_EChanging(value);
                this.ReportPropertyChanging("EMP_NAME_E");
                this._EMP_NAME_E = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EMP_NAME_E");
                this.OnEMP_NAME_EChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMP_NAME_E;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_NAME_EChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_NAME_EChanged();
        /// <summary>
        /// There are no comments for property EMP_SURNAME_E in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMP_SURNAME_E
        {
            get
            {
                return this._EMP_SURNAME_E;
            }
            set
            {
                this.OnEMP_SURNAME_EChanging(value);
                this.ReportPropertyChanging("EMP_SURNAME_E");
                this._EMP_SURNAME_E = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EMP_SURNAME_E");
                this.OnEMP_SURNAME_EChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMP_SURNAME_E;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_SURNAME_EChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMP_SURNAME_EChanged();
        /// <summary>
        /// There are no comments for property PASSWD in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PASSWD
        {
            get
            {
                return this._PASSWD;
            }
            set
            {
                this.OnPASSWDChanging(value);
                this.ReportPropertyChanging("PASSWD");
                this._PASSWD = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PASSWD");
                this.OnPASSWDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PASSWD;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPASSWDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPASSWDChanged();
        /// <summary>
        /// There are no comments for property EMAIL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMAIL
        {
            get
            {
                return this._EMAIL;
            }
            set
            {
                this.OnEMAILChanging(value);
                this.ReportPropertyChanging("EMAIL");
                this._EMAIL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EMAIL");
                this.OnEMAILChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMAIL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMAILChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMAILChanged();
        /// <summary>
        /// There are no comments for property PHONE_OFFICE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PHONE_OFFICE
        {
            get
            {
                return this._PHONE_OFFICE;
            }
            set
            {
                this.OnPHONE_OFFICEChanging(value);
                this.ReportPropertyChanging("PHONE_OFFICE");
                this._PHONE_OFFICE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PHONE_OFFICE");
                this.OnPHONE_OFFICEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PHONE_OFFICE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPHONE_OFFICEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPHONE_OFFICEChanged();
        /// <summary>
        /// There are no comments for property PHONE_HOME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PHONE_HOME
        {
            get
            {
                return this._PHONE_HOME;
            }
            set
            {
                this.OnPHONE_HOMEChanging(value);
                this.ReportPropertyChanging("PHONE_HOME");
                this._PHONE_HOME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PHONE_HOME");
                this.OnPHONE_HOMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PHONE_HOME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPHONE_HOMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPHONE_HOMEChanged();
        /// <summary>
        /// There are no comments for property PHONE_MOBILE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PHONE_MOBILE
        {
            get
            {
                return this._PHONE_MOBILE;
            }
            set
            {
                this.OnPHONE_MOBILEChanging(value);
                this.ReportPropertyChanging("PHONE_MOBILE");
                this._PHONE_MOBILE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PHONE_MOBILE");
                this.OnPHONE_MOBILEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PHONE_MOBILE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPHONE_MOBILEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPHONE_MOBILEChanged();
        /// <summary>
        /// There are no comments for property CREATE_DATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> CREATE_DATE
        {
            get
            {
                return this._CREATE_DATE;
            }
            set
            {
                this.OnCREATE_DATEChanging(value);
                this.ReportPropertyChanging("CREATE_DATE");
                this._CREATE_DATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CREATE_DATE");
                this.OnCREATE_DATEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _CREATE_DATE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCREATE_DATEChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCREATE_DATEChanged();
        /// <summary>
        /// There are no comments for property EXPIRE_DATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> EXPIRE_DATE
        {
            get
            {
                return this._EXPIRE_DATE;
            }
            set
            {
                this.OnEXPIRE_DATEChanging(value);
                this.ReportPropertyChanging("EXPIRE_DATE");
                this._EXPIRE_DATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EXPIRE_DATE");
                this.OnEXPIRE_DATEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _EXPIRE_DATE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEXPIRE_DATEChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEXPIRE_DATEChanged();
        /// <summary>
        /// There are no comments for property UPDATE_DATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> UPDATE_DATE
        {
            get
            {
                return this._UPDATE_DATE;
            }
            set
            {
                this.OnUPDATE_DATEChanging(value);
                this.ReportPropertyChanging("UPDATE_DATE");
                this._UPDATE_DATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UPDATE_DATE");
                this.OnUPDATE_DATEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _UPDATE_DATE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUPDATE_DATEChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUPDATE_DATEChanged();
        /// <summary>
        /// There are no comments for property LAST_SIGN_ON_DATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> LAST_SIGN_ON_DATE
        {
            get
            {
                return this._LAST_SIGN_ON_DATE;
            }
            set
            {
                this.OnLAST_SIGN_ON_DATEChanging(value);
                this.ReportPropertyChanging("LAST_SIGN_ON_DATE");
                this._LAST_SIGN_ON_DATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LAST_SIGN_ON_DATE");
                this.OnLAST_SIGN_ON_DATEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _LAST_SIGN_ON_DATE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLAST_SIGN_ON_DATEChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLAST_SIGN_ON_DATEChanged();
        /// <summary>
        /// There are no comments for property LAST_CHANGE_PASS_DATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> LAST_CHANGE_PASS_DATE
        {
            get
            {
                return this._LAST_CHANGE_PASS_DATE;
            }
            set
            {
                this.OnLAST_CHANGE_PASS_DATEChanging(value);
                this.ReportPropertyChanging("LAST_CHANGE_PASS_DATE");
                this._LAST_CHANGE_PASS_DATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LAST_CHANGE_PASS_DATE");
                this.OnLAST_CHANGE_PASS_DATEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _LAST_CHANGE_PASS_DATE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLAST_CHANGE_PASS_DATEChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLAST_CHANGE_PASS_DATEChanged();
        /// <summary>
        /// There are no comments for property DEL_FLAG in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> DEL_FLAG
        {
            get
            {
                return this._DEL_FLAG;
            }
            set
            {
                this.OnDEL_FLAGChanging(value);
                this.ReportPropertyChanging("DEL_FLAG");
                this._DEL_FLAG = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DEL_FLAG");
                this.OnDEL_FLAGChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _DEL_FLAG;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDEL_FLAGChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDEL_FLAGChanged();
    }
}
