'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection
Imports System.Runtime.Serialization

Namespace webservice.linq
	
    '<System.Data.Linq.Mapping.DatabaseAttribute(Name:="BAY01")> _
    Partial Public Class BranchLinqDataContext
        Inherits System.Data.Linq.DataContext

        Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource

#Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub
#End Region

        Public Sub New()
            MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("BAY01ConnectionString").ConnectionString, mappingSource)
            OnCreated()
        End Sub

        Public Sub New(ByVal connection As String)
            MyBase.New(connection, mappingSource)
            OnCreated()
        End Sub

        Public Sub New(ByVal connection As System.Data.IDbConnection)
            MyBase.New(connection, mappingSource)
            OnCreated()
        End Sub

        Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
            MyBase.New(connection, mappingSource)
            OnCreated()
        End Sub

        Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
            MyBase.New(connection, mappingSource)
            OnCreated()
        End Sub

        Public ReadOnly Property Id_Branches() As System.Data.Linq.Table(Of Id_Branch)
            Get
                Return Me.GetTable(Of Id_Branch)()
            End Get
        End Property
    End Class
	
	<Table(Name:="dbo.Id_Branch"),  _
	 DataContract()>  _
	Partial Public Class Id_Branch
		
		Private _Id_Branch As System.Nullable(Of Short)
		
		Private _Branch_T As String
		
		Private _Branch_E As String
		
		Private _Id_RegG As System.Nullable(Of Byte)
		
		Private _RegG_Name As String
		
		Private _RegG_NameE As String
		
		Private _Id_RegSub As System.Nullable(Of Short)
		
		Private _Id_Region As System.Nullable(Of Short)
		
		Private _Region_Name As String
		
		Private _Region_NameE As String
		
		Private _Id_Province As System.Nullable(Of Short)
		
		Private _Province As String
		
		Private _Id_ProGDPE As String
		
		Private _Id_PartN As System.Nullable(Of Byte)
		
		Private _Part_NameN As String
		
		Private _Part_NameNE As String
		
		Private _Id_RegionOld As System.Nullable(Of Short)
		
		Private _Region_NameOld As String
		
		Private _Region_NameEOld As String
		
		Private _Id_PartOld As System.Nullable(Of Short)
		
		Private _Part_NameOld As String
		
		Private _Part_NameEOld As String
		
		Private _Id_Part1 As System.Nullable(Of Short)
		
		Private _Part1_Name As String
		
		Private _Id_Part2 As System.Nullable(Of Short)
		
		Private _Part2_Name As String
		
		Private _Part2_NameE As String
		
		Private _Id_Part3 As System.Nullable(Of Short)
		
		Private _Part3_Name As String
		
		Private _Id_Part4 As System.Nullable(Of Short)
		
		Private _Part4_Name As String
		
		Private _Addres As String
		
		Private _Post As String
		
		Private _Tel As String
		
		Private _DateOpen As String
		
		Private _Id_BCenter As String
		
		Private _Segment As String
		
		Public Sub New()
			MyBase.New
		End Sub
		
		<Column(Storage:="_Id_Branch", DbType:="SmallInt"),  _
		 DataMember(Order:=1)>  _
		Public Property Id_Branch() As System.Nullable(Of Short)
			Get
				Return Me._Id_Branch
			End Get
			Set
				If (Me._Id_Branch.Equals(value) = false) Then
					Me._Id_Branch = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Branch_T", DbType:="NVarChar(50)"),  _
		 DataMember(Order:=2)>  _
		Public Property Branch_T() As String
			Get
				Return Me._Branch_T
			End Get
			Set
				If (String.Equals(Me._Branch_T, value) = false) Then
					Me._Branch_T = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Branch_E", DbType:="NVarChar(50)"),  _
		 DataMember(Order:=3)>  _
		Public Property Branch_E() As String
			Get
				Return Me._Branch_E
			End Get
			Set
				If (String.Equals(Me._Branch_E, value) = false) Then
					Me._Branch_E = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_RegG", DbType:="TinyInt"),  _
		 DataMember(Order:=4)>  _
		Public Property Id_RegG() As System.Nullable(Of Byte)
			Get
				Return Me._Id_RegG
			End Get
			Set
				If (Me._Id_RegG.Equals(value) = false) Then
					Me._Id_RegG = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_RegG_Name", DbType:="NVarChar(25)"),  _
		 DataMember(Order:=5)>  _
		Public Property RegG_Name() As String
			Get
				Return Me._RegG_Name
			End Get
			Set
				If (String.Equals(Me._RegG_Name, value) = false) Then
					Me._RegG_Name = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_RegG_NameE", DbType:="NVarChar(25)"),  _
		 DataMember(Order:=6)>  _
		Public Property RegG_NameE() As String
			Get
				Return Me._RegG_NameE
			End Get
			Set
				If (String.Equals(Me._RegG_NameE, value) = false) Then
					Me._RegG_NameE = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_RegSub", DbType:="SmallInt"),  _
		 DataMember(Order:=7)>  _
		Public Property Id_RegSub() As System.Nullable(Of Short)
			Get
				Return Me._Id_RegSub
			End Get
			Set
				If (Me._Id_RegSub.Equals(value) = false) Then
					Me._Id_RegSub = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_Region", DbType:="SmallInt"),  _
		 DataMember(Order:=8)>  _
		Public Property Id_Region() As System.Nullable(Of Short)
			Get
				Return Me._Id_Region
			End Get
			Set
				If (Me._Id_Region.Equals(value) = false) Then
					Me._Id_Region = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Region_Name", DbType:="NVarChar(25)"),  _
		 DataMember(Order:=9)>  _
		Public Property Region_Name() As String
			Get
				Return Me._Region_Name
			End Get
			Set
				If (String.Equals(Me._Region_Name, value) = false) Then
					Me._Region_Name = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Region_NameE", DbType:="NVarChar(25)"),  _
		 DataMember(Order:=10)>  _
		Public Property Region_NameE() As String
			Get
				Return Me._Region_NameE
			End Get
			Set
				If (String.Equals(Me._Region_NameE, value) = false) Then
					Me._Region_NameE = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_Province", DbType:="SmallInt"),  _
		 DataMember(Order:=11)>  _
		Public Property Id_Province() As System.Nullable(Of Short)
			Get
				Return Me._Id_Province
			End Get
			Set
				If (Me._Id_Province.Equals(value) = false) Then
					Me._Id_Province = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Province", DbType:="NVarChar(50)"),  _
		 DataMember(Order:=12)>  _
		Public Property Province() As String
			Get
				Return Me._Province
			End Get
			Set
				If (String.Equals(Me._Province, value) = false) Then
					Me._Province = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_ProGDPE", DbType:="NVarChar(15)"),  _
		 DataMember(Order:=13)>  _
		Public Property Id_ProGDPE() As String
			Get
				Return Me._Id_ProGDPE
			End Get
			Set
				If (String.Equals(Me._Id_ProGDPE, value) = false) Then
					Me._Id_ProGDPE = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_PartN", DbType:="TinyInt"),  _
		 DataMember(Order:=14)>  _
		Public Property Id_PartN() As System.Nullable(Of Byte)
			Get
				Return Me._Id_PartN
			End Get
			Set
				If (Me._Id_PartN.Equals(value) = false) Then
					Me._Id_PartN = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part_NameN", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=15)>  _
		Public Property Part_NameN() As String
			Get
				Return Me._Part_NameN
			End Get
			Set
				If (String.Equals(Me._Part_NameN, value) = false) Then
					Me._Part_NameN = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part_NameNE", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=16)>  _
		Public Property Part_NameNE() As String
			Get
				Return Me._Part_NameNE
			End Get
			Set
				If (String.Equals(Me._Part_NameNE, value) = false) Then
					Me._Part_NameNE = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_RegionOld", DbType:="SmallInt"),  _
		 DataMember(Order:=17)>  _
		Public Property Id_RegionOld() As System.Nullable(Of Short)
			Get
				Return Me._Id_RegionOld
			End Get
			Set
				If (Me._Id_RegionOld.Equals(value) = false) Then
					Me._Id_RegionOld = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Region_NameOld", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=18)>  _
		Public Property Region_NameOld() As String
			Get
				Return Me._Region_NameOld
			End Get
			Set
				If (String.Equals(Me._Region_NameOld, value) = false) Then
					Me._Region_NameOld = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Region_NameEOld", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=19)>  _
		Public Property Region_NameEOld() As String
			Get
				Return Me._Region_NameEOld
			End Get
			Set
				If (String.Equals(Me._Region_NameEOld, value) = false) Then
					Me._Region_NameEOld = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_PartOld", DbType:="SmallInt"),  _
		 DataMember(Order:=20)>  _
		Public Property Id_PartOld() As System.Nullable(Of Short)
			Get
				Return Me._Id_PartOld
			End Get
			Set
				If (Me._Id_PartOld.Equals(value) = false) Then
					Me._Id_PartOld = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part_NameOld", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=21)>  _
		Public Property Part_NameOld() As String
			Get
				Return Me._Part_NameOld
			End Get
			Set
				If (String.Equals(Me._Part_NameOld, value) = false) Then
					Me._Part_NameOld = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part_NameEOld", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=22)>  _
		Public Property Part_NameEOld() As String
			Get
				Return Me._Part_NameEOld
			End Get
			Set
				If (String.Equals(Me._Part_NameEOld, value) = false) Then
					Me._Part_NameEOld = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_Part1", DbType:="SmallInt"),  _
		 DataMember(Order:=23)>  _
		Public Property Id_Part1() As System.Nullable(Of Short)
			Get
				Return Me._Id_Part1
			End Get
			Set
				If (Me._Id_Part1.Equals(value) = false) Then
					Me._Id_Part1 = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part1_Name", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=24)>  _
		Public Property Part1_Name() As String
			Get
				Return Me._Part1_Name
			End Get
			Set
				If (String.Equals(Me._Part1_Name, value) = false) Then
					Me._Part1_Name = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_Part2", DbType:="SmallInt"),  _
		 DataMember(Order:=25)>  _
		Public Property Id_Part2() As System.Nullable(Of Short)
			Get
				Return Me._Id_Part2
			End Get
			Set
				If (Me._Id_Part2.Equals(value) = false) Then
					Me._Id_Part2 = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part2_Name", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=26)>  _
		Public Property Part2_Name() As String
			Get
				Return Me._Part2_Name
			End Get
			Set
				If (String.Equals(Me._Part2_Name, value) = false) Then
					Me._Part2_Name = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part2_NameE", DbType:="NVarChar(50)"),  _
		 DataMember(Order:=27)>  _
		Public Property Part2_NameE() As String
			Get
				Return Me._Part2_NameE
			End Get
			Set
				If (String.Equals(Me._Part2_NameE, value) = false) Then
					Me._Part2_NameE = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_Part3", DbType:="SmallInt"),  _
		 DataMember(Order:=28)>  _
		Public Property Id_Part3() As System.Nullable(Of Short)
			Get
				Return Me._Id_Part3
			End Get
			Set
				If (Me._Id_Part3.Equals(value) = false) Then
					Me._Id_Part3 = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part3_Name", DbType:="NVarChar(30)"),  _
		 DataMember(Order:=29)>  _
		Public Property Part3_Name() As String
			Get
				Return Me._Part3_Name
			End Get
			Set
				If (String.Equals(Me._Part3_Name, value) = false) Then
					Me._Part3_Name = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_Part4", DbType:="SmallInt"),  _
		 DataMember(Order:=30)>  _
		Public Property Id_Part4() As System.Nullable(Of Short)
			Get
				Return Me._Id_Part4
			End Get
			Set
				If (Me._Id_Part4.Equals(value) = false) Then
					Me._Id_Part4 = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Part4_Name", DbType:="NVarChar(50)"),  _
		 DataMember(Order:=31)>  _
		Public Property Part4_Name() As String
			Get
				Return Me._Part4_Name
			End Get
			Set
				If (String.Equals(Me._Part4_Name, value) = false) Then
					Me._Part4_Name = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Addres", DbType:="NVarChar(100)"),  _
		 DataMember(Order:=32)>  _
		Public Property Addres() As String
			Get
				Return Me._Addres
			End Get
			Set
				If (String.Equals(Me._Addres, value) = false) Then
					Me._Addres = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Post", DbType:="NVarChar(10)"),  _
		 DataMember(Order:=33)>  _
		Public Property Post() As String
			Get
				Return Me._Post
			End Get
			Set
				If (String.Equals(Me._Post, value) = false) Then
					Me._Post = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Tel", DbType:="NVarChar(50)"),  _
		 DataMember(Order:=34)>  _
		Public Property Tel() As String
			Get
				Return Me._Tel
			End Get
			Set
				If (String.Equals(Me._Tel, value) = false) Then
					Me._Tel = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_DateOpen", DbType:="NVarChar(15)"),  _
		 DataMember(Order:=35)>  _
		Public Property DateOpen() As String
			Get
				Return Me._DateOpen
			End Get
			Set
				If (String.Equals(Me._DateOpen, value) = false) Then
					Me._DateOpen = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Id_BCenter", DbType:="NVarChar(4)"),  _
		 DataMember(Order:=36)>  _
		Public Property Id_BCenter() As String
			Get
				Return Me._Id_BCenter
			End Get
			Set
				If (String.Equals(Me._Id_BCenter, value) = false) Then
					Me._Id_BCenter = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Segment", DbType:="NVarChar(25)"),  _
		 DataMember(Order:=37)>  _
		Public Property Segment() As String
			Get
				Return Me._Segment
			End Get
			Set
				If (String.Equals(Me._Segment, value) = false) Then
					Me._Segment = value
				End If
			End Set
		End Property
	End Class
End Namespace
