ALTER TABLE [CUSTOMER].[CUSTOMER_SME_RATING]
	ADD CONSTRAINT [FK_CUSTOMER_SME_RATING_CUSTOMER_SME_RATING_TYPE] 
	FOREIGN KEY ([RATING_TYPE_KEY])
	REFERENCES [CUSTOMER].[CUSTOMER_SME_RATING_TYPE] ([RATING_TYPE_KEY])	

