ALTER TABLE [CUSTOMER].[CUSTOMER_SME_RATING]
	ADD CONSTRAINT [PK_CUSTOMER_SME_RATING]
	PRIMARY KEY CLUSTERED ([RATING_KEY])
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]