ALTER TABLE [CUSTOMER].[ByCus_CIF]
	ADD CONSTRAINT [PK_ByCus_CIF] PRIMARY KEY CLUSTERED 
(
	[Cif] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]