ALTER TABLE [CUSTOMER].[CUSTOMER_SME_RATING_TYPE]
	ADD CONSTRAINT [PK_CUSTOMER_SME_RATING_TYPE]
	PRIMARY KEY CLUSTERED ([RATING_TYPE_KEY] ASC)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]