ALTER TABLE [CUSTOMER].[BUSINESS_DESTINATION]
	ADD CONSTRAINT [PK_BUSINESS_DESTINATION]
	PRIMARY KEY CLUSTERED ([BUSINESS_DESTINATION_ID] ASC)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]