ALTER TABLE [SS].[FINANCIAL_STATUS]
	ADD CONSTRAINT [PK_FINANCIAL_STATUS]
	PRIMARY KEY CLUSTERED (STATUS_ID)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]