ALTER TABLE [SS].[FINANCIAL_LIST]
	ADD CONSTRAINT [PK_FINANCIAL_LIST]
	PRIMARY KEY CLUSTERED (LIST_ID)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]