ALTER TABLE [SS].[FINANCIAL_ROLE]
	ADD CONSTRAINT [PK_ROLE_ID]
	PRIMARY KEY CLUSTERED (ROLE_ID)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]