ALTER TABLE [SS].[FINANCIAL_DATA_EXCELL]
	ADD CONSTRAINT [PK_FINANCIAL_DATA_EXCELL]
	PRIMARY KEY CLUSTERED (CIF)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]