//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets87E61FD9465781C92F40C3CBFE13BF9D458826CB05C5EF2E2CA108C68E08114B))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets87E61FD9465781C92F40C3CBFE13BF9D458826CB05C5EF2E2CA108C68E08114B : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets87E61FD9465781C92F40C3CBFE13BF9D458826CB05C5EF2E2CA108C68E08114B()
        {
            this.EdmEntityContainerName = "UserSystemEntities";
            this.StoreEntityContainerName = "RISKModelStoreContainer";
            this.HashOverMappingClosure = "3af914f76660eb44892821600f377523c201919e341771a0c2b75f7537e45c32";
            this.HashOverAllExtentViews = "4bdcb2db39d9733ca66aa4bc01da0915339a4769c61741d91703d1d116beaa72";
            this.ViewCount = 26;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            if ((index == 25))
            {
                return GetView25();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.CATE_AND_APP
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.CATE_AND_APP", @"
    SELECT VALUE -- Constructing CATE_AND_APP
        [RISKModel.Store.CATE_AND_APP](T1.[CATE_AND_APP.ID], T1.[CATE_AND_APP.CATEGORY_KEY], T1.[CATE_AND_APP.APP_KEY], T1.[CATE_AND_APP.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [CATE_AND_APP.ID], 
            T.CATEGORY_KEY AS [CATE_AND_APP.CATEGORY_KEY], 
            T.APP_KEY AS [CATE_AND_APP.APP_KEY], 
            T.DEL_FLAG AS [CATE_AND_APP.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.CATE_AND_APP AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.CATE_AND_CUS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.CATE_AND_CUS", @"
    SELECT VALUE -- Constructing CATE_AND_CUS
        [RISKModel.Store.CATE_AND_CUS](T1.[CATE_AND_CUS.ID], T1.[CATE_AND_CUS.CATEGORY_KEY], T1.[CATE_AND_CUS.CIF], T1.[CATE_AND_CUS.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [CATE_AND_CUS.ID], 
            T.CATEGORY_KEY AS [CATE_AND_CUS.CATEGORY_KEY], 
            T.CIF AS [CATE_AND_CUS.CIF], 
            T.DEL_FLAG AS [CATE_AND_CUS.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.CATE_AND_CUS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.CATE_AND_EMP
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.CATE_AND_EMP", @"
    SELECT VALUE -- Constructing CATE_AND_EMP
        [RISKModel.Store.CATE_AND_EMP](T1.[CATE_AND_EMP.ID], T1.[CATE_AND_EMP.CATEGORY_KEY], T1.[CATE_AND_EMP.EMP_ID], T1.[CATE_AND_EMP.HEAD_PRIORITY], T1.[CATE_AND_EMP.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [CATE_AND_EMP.ID], 
            T.CATEGORY_KEY AS [CATE_AND_EMP.CATEGORY_KEY], 
            T.EMP_ID AS [CATE_AND_EMP.EMP_ID], 
            T.HEAD_PRIORITY AS [CATE_AND_EMP.HEAD_PRIORITY], 
            T.DEL_FLAG AS [CATE_AND_EMP.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.CATE_AND_EMP AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.CATE_AND_MENU
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.CATE_AND_MENU", @"
    SELECT VALUE -- Constructing CATE_AND_MENU
        [RISKModel.Store.CATE_AND_MENU](T1.[CATE_AND_MENU.ID], T1.[CATE_AND_MENU.CATEGORY_KEY], T1.[CATE_AND_MENU.MENU_KEY], T1.[CATE_AND_MENU.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [CATE_AND_MENU.ID], 
            T.CATEGORY_KEY AS [CATE_AND_MENU.CATEGORY_KEY], 
            T.MENU_KEY AS [CATE_AND_MENU.MENU_KEY], 
            T.DEL_FLAG AS [CATE_AND_MENU.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.CATE_AND_MENU AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.CATEGORY
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.CATEGORY", @"
    SELECT VALUE -- Constructing CATEGORY
        [RISKModel.Store.CATEGORY](T1.[CATEGORY.CATEGORY_KEY], T1.[CATEGORY.CATEGORY_DESC], T1.[CATEGORY.CATEGORY_DESC_TH], T1.[CATEGORY.CATEGORY_VALUE], T1.[CATEGORY.CATEGORY_TYPE_KEY], T1.CATEGORY_PRIORITY, T1.[CATEGORY.DEL_FLAG])
    FROM (
        SELECT 
            T.CATEGORY_KEY AS [CATEGORY.CATEGORY_KEY], 
            T.CATEGORY_DESC AS [CATEGORY.CATEGORY_DESC], 
            T.CATEGORY_DESC_TH AS [CATEGORY.CATEGORY_DESC_TH], 
            T.CATEGORY_VALUE AS [CATEGORY.CATEGORY_VALUE], 
            T.CATEGORY_TYPE_KEY AS [CATEGORY.CATEGORY_TYPE_KEY], 
            T.PRIORITY AS CATEGORY_PRIORITY, 
            T.DEL_FLAG AS [CATEGORY.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.CATEGORies AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.CATEGORY_TYPE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.CATEGORY_TYPE", @"
    SELECT VALUE -- Constructing CATEGORY_TYPE
        [RISKModel.Store.CATEGORY_TYPE](T1.[CATEGORY_TYPE.CATEGORY_TYPE_KEY], T1.[CATEGORY_TYPE.CATEGORY_TYPE_DESC], T1.[CATEGORY_TYPE.CATEGORY_TYPE_DESC_TH], T1.[CATEGORY_TYPE.CATEGORY_TYPE_VALUE], T1.[CATEGORY_TYPE.PRIORITY], T1.[CATEGORY_TYPE.DEL_FLAG])
    FROM (
        SELECT 
            T.CATEGORY_TYPE_KEY AS [CATEGORY_TYPE.CATEGORY_TYPE_KEY], 
            T.CATEGORY_TYPE_DESC AS [CATEGORY_TYPE.CATEGORY_TYPE_DESC], 
            T.CATEGORY_TYPE_DESC_TH AS [CATEGORY_TYPE.CATEGORY_TYPE_DESC_TH], 
            T.CATEGORY_TYPE_VALUE AS [CATEGORY_TYPE.CATEGORY_TYPE_VALUE], 
            T.PRIORITY AS [CATEGORY_TYPE.PRIORITY], 
            T.DEL_FLAG AS [CATEGORY_TYPE.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.CATEGORY_TYPE AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.LINKED_CATEGORY
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.LINKED_CATEGORY", @"
    SELECT VALUE -- Constructing LINKED_CATEGORY
        [RISKModel.Store.LINKED_CATEGORY](T1.[LINKED_CATEGORY.ID], T1.[LINKED_CATEGORY.CATEGORY_KEY], T1.[LINKED_CATEGORY.LINK_TO_CATEGORY_KEY], T1.[LINKED_CATEGORY.LINKED_TYPE_KEY], T1.[LINKED_CATEGORY.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [LINKED_CATEGORY.ID], 
            T.CATEGORY_KEY AS [LINKED_CATEGORY.CATEGORY_KEY], 
            T.LINK_TO_CATEGORY_KEY AS [LINKED_CATEGORY.LINK_TO_CATEGORY_KEY], 
            T.LINKED_TYPE_KEY AS [LINKED_CATEGORY.LINKED_TYPE_KEY], 
            T.DEL_FLAG AS [LINKED_CATEGORY.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.LINKED_CATEGORY AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.LINKED_CATEGORY_TYPE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.LINKED_CATEGORY_TYPE", @"
    SELECT VALUE -- Constructing LINKED_CATEGORY_TYPE
        [RISKModel.Store.LINKED_CATEGORY_TYPE](T1.[LINKED_CATEGORY_TYPE.ID], T1.[LINKED_CATEGORY_TYPE.CATEGORY_TYPE_KEY], T1.[LINKED_CATEGORY_TYPE.LINK_TO_CATEGORY_TYPE_KEY], T1.[LINKED_CATEGORY_TYPE.LINKED_TYPE_KEY], T1.[LINKED_CATEGORY_TYPE.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [LINKED_CATEGORY_TYPE.ID], 
            T.CATEGORY_TYPE_KEY AS [LINKED_CATEGORY_TYPE.CATEGORY_TYPE_KEY], 
            T.LINK_TO_CATEGORY_TYPE_KEY AS [LINKED_CATEGORY_TYPE.LINK_TO_CATEGORY_TYPE_KEY], 
            T.LINKED_TYPE_KEY AS [LINKED_CATEGORY_TYPE.LINKED_TYPE_KEY], 
            T.DEL_FLAG AS [LINKED_CATEGORY_TYPE.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.LINKED_CATEGORY_TYPE AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.LINKED_TYPE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.LINKED_TYPE", @"
    SELECT VALUE -- Constructing LINKED_TYPE
        [RISKModel.Store.LINKED_TYPE](T1.[LINKED_TYPE.LINKED_TYPE_KEY], T1.[LINKED_TYPE.DESCRIPTION], T1.[LINKED_TYPE.DEL_FLAG])
    FROM (
        SELECT 
            T.LINKED_TYPE_KEY AS [LINKED_TYPE.LINKED_TYPE_KEY], 
            T.DESCRIPTION AS [LINKED_TYPE.DESCRIPTION], 
            T.DEL_FLAG AS [LINKED_TYPE.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.LINKED_TYPE AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.USER_DATA
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.USER_DATA", "\r\n    SELECT VALUE -- Constructing USER_DATA\r\n        [RISKModel.Store.USER_DATA]" +
                    "(T1.[USER_DATA.EMP_ID], T1.[USER_DATA.EMP_ID_DISPLAY], T1.[USER_DATA.EMP_TITLE]," +
                    " T1.[USER_DATA.EMP_NAME], T1.[USER_DATA.EMP_SURNAME], T1.[USER_DATA.EMP_TITLE_E]" +
                    ", T1.[USER_DATA.EMP_NAME_E], T1.[USER_DATA.EMP_SURNAME_E], T1.[USER_DATA.PASSWD]" +
                    ", T1.[USER_DATA.EMAIL], T1.[USER_DATA.PHONE_OFFICE], T1.[USER_DATA.PHONE_HOME], " +
                    "T1.[USER_DATA.PHONE_MOBILE], T1.[USER_DATA.CREATE_DATE], T1.[USER_DATA.EXPIRE_DA" +
                    "TE], T1.[USER_DATA.UPDATE_DATE], T1.[USER_DATA.LAST_SIGN_ON_DATE], T1.[USER_DATA" +
                    ".LAST_CHANGE_PASS_DATE], T1.[USER_DATA.DEL_FLAG])\r\n    FROM (\r\n        SELECT \r\n" +
                    "            T.EMP_ID AS [USER_DATA.EMP_ID], \r\n            T.EMP_ID_DISPLAY AS [U" +
                    "SER_DATA.EMP_ID_DISPLAY], \r\n            T.EMP_TITLE AS [USER_DATA.EMP_TITLE], \r\n" +
                    "            T.EMP_NAME AS [USER_DATA.EMP_NAME], \r\n            T.EMP_SURNAME AS [" +
                    "USER_DATA.EMP_SURNAME], \r\n            T.EMP_TITLE_E AS [USER_DATA.EMP_TITLE_E], " +
                    "\r\n            T.EMP_NAME_E AS [USER_DATA.EMP_NAME_E], \r\n            T.EMP_SURNAM" +
                    "E_E AS [USER_DATA.EMP_SURNAME_E], \r\n            T.PASSWD AS [USER_DATA.PASSWD], " +
                    "\r\n            T.EMAIL AS [USER_DATA.EMAIL], \r\n            T.PHONE_OFFICE AS [USE" +
                    "R_DATA.PHONE_OFFICE], \r\n            T.PHONE_HOME AS [USER_DATA.PHONE_HOME], \r\n  " +
                    "          T.PHONE_MOBILE AS [USER_DATA.PHONE_MOBILE], \r\n            T.CREATE_DAT" +
                    "E AS [USER_DATA.CREATE_DATE], \r\n            T.EXPIRE_DATE AS [USER_DATA.EXPIRE_D" +
                    "ATE], \r\n            T.UPDATE_DATE AS [USER_DATA.UPDATE_DATE], \r\n            T.LA" +
                    "ST_SIGN_ON_DATE AS [USER_DATA.LAST_SIGN_ON_DATE], \r\n            T.LAST_CHANGE_PA" +
                    "SS_DATE AS [USER_DATA.LAST_CHANGE_PASS_DATE], \r\n            T.DEL_FLAG AS [USER_" +
                    "DATA.DEL_FLAG], \r\n            True AS _from0\r\n        FROM UserSystemEntities.US" +
                    "ER_DATA AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.APPLICATION
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.APPLICATION", @"
    SELECT VALUE -- Constructing APPLICATION
        [RISKModel.Store.APPLICATION](T1.[APPLICATION.APP_KEY], T1.[APPLICATION.APP_DESC], T1.APPLICATION_PRIORITY, T1.[APPLICATION.DEL_FLAG])
    FROM (
        SELECT 
            T.APP_KEY AS [APPLICATION.APP_KEY], 
            T.APP_DESC AS [APPLICATION.APP_DESC], 
            T.PRIORITY AS APPLICATION_PRIORITY, 
            T.DEL_FLAG AS [APPLICATION.DEL_FLAG], 
            True AS _from0
        FROM UserSystemEntities.APPLICATIONs AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.MENU_MASTER
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.MENU_MASTER", @"
    SELECT VALUE -- Constructing MENU_MASTER
        [RISKModel.Store.MENU_MASTER](T1.[MENU_MASTER.MENU_KEY], T1.[MENU_MASTER.MENU_TITLE], T1.[MENU_MASTER.MENU_URL], T1.[MENU_MASTER.MENU_POPUP_OPT], T1.[MENU_MASTER.MENU_REL], T1.[MENU_MASTER.MENU_TOOLTIP], T1.[MENU_MASTER.MENU_PRIORITY], T1.[MENU_MASTER.MENU_DEL_FLAG], T1.[MENU_MASTER.MENU_PARENT_KEY])
    FROM (
        SELECT 
            T.MENU_KEY AS [MENU_MASTER.MENU_KEY], 
            T.MENU_TITLE AS [MENU_MASTER.MENU_TITLE], 
            T.MENU_URL AS [MENU_MASTER.MENU_URL], 
            T.MENU_POPUP_OPT AS [MENU_MASTER.MENU_POPUP_OPT], 
            T.MENU_REL AS [MENU_MASTER.MENU_REL], 
            T.MENU_TOOLTIP AS [MENU_MASTER.MENU_TOOLTIP], 
            T.MENU_PRIORITY AS [MENU_MASTER.MENU_PRIORITY], 
            T.MENU_DEL_FLAG AS [MENU_MASTER.MENU_DEL_FLAG], 
            T.MENU_PARENT_KEY AS [MENU_MASTER.MENU_PARENT_KEY], 
            True AS _from0
        FROM UserSystemEntities.MENU_MASTER AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.CATE_AND_APP
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.CATE_AND_APP", @"
    SELECT VALUE -- Constructing CATE_AND_APP
        [RISKModel.CATE_AND_APP](T1.[CATE_AND_APP.ID], T1.[CATE_AND_APP.CATEGORY_KEY], T1.[CATE_AND_APP.APP_KEY], T1.[CATE_AND_APP.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [CATE_AND_APP.ID], 
            T.CATEGORY_KEY AS [CATE_AND_APP.CATEGORY_KEY], 
            T.APP_KEY AS [CATE_AND_APP.APP_KEY], 
            T.DEL_FLAG AS [CATE_AND_APP.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.CATE_AND_APP AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.CATE_AND_CUS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.CATE_AND_CUS", @"
    SELECT VALUE -- Constructing CATE_AND_CUS
        [RISKModel.CATE_AND_CUS](T1.[CATE_AND_CUS.ID], T1.[CATE_AND_CUS.CATEGORY_KEY], T1.[CATE_AND_CUS.CIF], T1.[CATE_AND_CUS.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [CATE_AND_CUS.ID], 
            T.CATEGORY_KEY AS [CATE_AND_CUS.CATEGORY_KEY], 
            T.CIF AS [CATE_AND_CUS.CIF], 
            T.DEL_FLAG AS [CATE_AND_CUS.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.CATE_AND_CUS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.CATE_AND_EMP
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.CATE_AND_EMP", @"
    SELECT VALUE -- Constructing CATE_AND_EMP
        [RISKModel.CATE_AND_EMP](T1.[CATE_AND_EMP.ID], T1.[CATE_AND_EMP.CATEGORY_KEY], T1.[CATE_AND_EMP.EMP_ID], T1.[CATE_AND_EMP.HEAD_PRIORITY], T1.[CATE_AND_EMP.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [CATE_AND_EMP.ID], 
            T.CATEGORY_KEY AS [CATE_AND_EMP.CATEGORY_KEY], 
            T.EMP_ID AS [CATE_AND_EMP.EMP_ID], 
            T.HEAD_PRIORITY AS [CATE_AND_EMP.HEAD_PRIORITY], 
            T.DEL_FLAG AS [CATE_AND_EMP.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.CATE_AND_EMP AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.CATE_AND_MENU
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.CATE_AND_MENU", @"
    SELECT VALUE -- Constructing CATE_AND_MENU
        [RISKModel.CATE_AND_MENU](T1.[CATE_AND_MENU.ID], T1.[CATE_AND_MENU.CATEGORY_KEY], T1.[CATE_AND_MENU.MENU_KEY], T1.[CATE_AND_MENU.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [CATE_AND_MENU.ID], 
            T.CATEGORY_KEY AS [CATE_AND_MENU.CATEGORY_KEY], 
            T.MENU_KEY AS [CATE_AND_MENU.MENU_KEY], 
            T.DEL_FLAG AS [CATE_AND_MENU.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.CATE_AND_MENU AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.CATEGORies
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.CATEGORies", @"
    SELECT VALUE -- Constructing CATEGORies
        [RISKModel.CATEGORY](T1.[CATEGORY.CATEGORY_KEY], T1.[CATEGORY.CATEGORY_DESC], T1.[CATEGORY.CATEGORY_DESC_TH], T1.[CATEGORY.CATEGORY_VALUE], T1.[CATEGORY.CATEGORY_TYPE_KEY], T1.CATEGORY_PRIORITY, T1.[CATEGORY.DEL_FLAG])
    FROM (
        SELECT 
            T.CATEGORY_KEY AS [CATEGORY.CATEGORY_KEY], 
            T.CATEGORY_DESC AS [CATEGORY.CATEGORY_DESC], 
            T.CATEGORY_DESC_TH AS [CATEGORY.CATEGORY_DESC_TH], 
            T.CATEGORY_VALUE AS [CATEGORY.CATEGORY_VALUE], 
            T.CATEGORY_TYPE_KEY AS [CATEGORY.CATEGORY_TYPE_KEY], 
            T.PRIORITY AS CATEGORY_PRIORITY, 
            T.DEL_FLAG AS [CATEGORY.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.CATEGORY AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.CATEGORY_TYPE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.CATEGORY_TYPE", @"
    SELECT VALUE -- Constructing CATEGORY_TYPE
        [RISKModel.CATEGORY_TYPE](T1.[CATEGORY_TYPE.CATEGORY_TYPE_KEY], T1.[CATEGORY_TYPE.CATEGORY_TYPE_DESC], T1.[CATEGORY_TYPE.CATEGORY_TYPE_DESC_TH], T1.[CATEGORY_TYPE.CATEGORY_TYPE_VALUE], T1.[CATEGORY_TYPE.PRIORITY], T1.[CATEGORY_TYPE.DEL_FLAG])
    FROM (
        SELECT 
            T.CATEGORY_TYPE_KEY AS [CATEGORY_TYPE.CATEGORY_TYPE_KEY], 
            T.CATEGORY_TYPE_DESC AS [CATEGORY_TYPE.CATEGORY_TYPE_DESC], 
            T.CATEGORY_TYPE_DESC_TH AS [CATEGORY_TYPE.CATEGORY_TYPE_DESC_TH], 
            T.CATEGORY_TYPE_VALUE AS [CATEGORY_TYPE.CATEGORY_TYPE_VALUE], 
            T.PRIORITY AS [CATEGORY_TYPE.PRIORITY], 
            T.DEL_FLAG AS [CATEGORY_TYPE.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.CATEGORY_TYPE AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.LINKED_CATEGORY
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.LINKED_CATEGORY", @"
    SELECT VALUE -- Constructing LINKED_CATEGORY
        [RISKModel.LINKED_CATEGORY](T1.[LINKED_CATEGORY.ID], T1.[LINKED_CATEGORY.CATEGORY_KEY], T1.[LINKED_CATEGORY.LINK_TO_CATEGORY_KEY], T1.[LINKED_CATEGORY.LINKED_TYPE_KEY], T1.[LINKED_CATEGORY.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [LINKED_CATEGORY.ID], 
            T.CATEGORY_KEY AS [LINKED_CATEGORY.CATEGORY_KEY], 
            T.LINK_TO_CATEGORY_KEY AS [LINKED_CATEGORY.LINK_TO_CATEGORY_KEY], 
            T.LINKED_TYPE_KEY AS [LINKED_CATEGORY.LINKED_TYPE_KEY], 
            T.DEL_FLAG AS [LINKED_CATEGORY.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.LINKED_CATEGORY AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.LINKED_CATEGORY_TYPE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.LINKED_CATEGORY_TYPE", @"
    SELECT VALUE -- Constructing LINKED_CATEGORY_TYPE
        [RISKModel.LINKED_CATEGORY_TYPE](T1.[LINKED_CATEGORY_TYPE.ID], T1.[LINKED_CATEGORY_TYPE.CATEGORY_TYPE_KEY], T1.[LINKED_CATEGORY_TYPE.LINK_TO_CATEGORY_TYPE_KEY], T1.[LINKED_CATEGORY_TYPE.LINKED_TYPE_KEY], T1.[LINKED_CATEGORY_TYPE.DEL_FLAG])
    FROM (
        SELECT 
            T.ID AS [LINKED_CATEGORY_TYPE.ID], 
            T.CATEGORY_TYPE_KEY AS [LINKED_CATEGORY_TYPE.CATEGORY_TYPE_KEY], 
            T.LINK_TO_CATEGORY_TYPE_KEY AS [LINKED_CATEGORY_TYPE.LINK_TO_CATEGORY_TYPE_KEY], 
            T.LINKED_TYPE_KEY AS [LINKED_CATEGORY_TYPE.LINKED_TYPE_KEY], 
            T.DEL_FLAG AS [LINKED_CATEGORY_TYPE.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.LINKED_CATEGORY_TYPE AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.LINKED_TYPE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.LINKED_TYPE", @"
    SELECT VALUE -- Constructing LINKED_TYPE
        [RISKModel.LINKED_TYPE](T1.[LINKED_TYPE.LINKED_TYPE_KEY], T1.[LINKED_TYPE.DESCRIPTION], T1.[LINKED_TYPE.DEL_FLAG])
    FROM (
        SELECT 
            T.LINKED_TYPE_KEY AS [LINKED_TYPE.LINKED_TYPE_KEY], 
            T.DESCRIPTION AS [LINKED_TYPE.DESCRIPTION], 
            T.DEL_FLAG AS [LINKED_TYPE.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.LINKED_TYPE AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.USER_DATA
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.USER_DATA", "\r\n    SELECT VALUE -- Constructing USER_DATA\r\n        [RISKModel.USER_DATA](T1.[U" +
                    "SER_DATA.EMP_ID], T1.[USER_DATA.EMP_ID_DISPLAY], T1.[USER_DATA.EMP_TITLE], T1.[U" +
                    "SER_DATA.EMP_NAME], T1.[USER_DATA.EMP_SURNAME], T1.[USER_DATA.EMP_TITLE_E], T1.[" +
                    "USER_DATA.EMP_NAME_E], T1.[USER_DATA.EMP_SURNAME_E], T1.[USER_DATA.PASSWD], T1.[" +
                    "USER_DATA.EMAIL], T1.[USER_DATA.PHONE_OFFICE], T1.[USER_DATA.PHONE_HOME], T1.[US" +
                    "ER_DATA.PHONE_MOBILE], T1.[USER_DATA.CREATE_DATE], T1.[USER_DATA.EXPIRE_DATE], T" +
                    "1.[USER_DATA.UPDATE_DATE], T1.[USER_DATA.LAST_SIGN_ON_DATE], T1.[USER_DATA.LAST_" +
                    "CHANGE_PASS_DATE], T1.[USER_DATA.DEL_FLAG])\r\n    FROM (\r\n        SELECT \r\n      " +
                    "      T.EMP_ID AS [USER_DATA.EMP_ID], \r\n            T.EMP_ID_DISPLAY AS [USER_DA" +
                    "TA.EMP_ID_DISPLAY], \r\n            T.EMP_TITLE AS [USER_DATA.EMP_TITLE], \r\n      " +
                    "      T.EMP_NAME AS [USER_DATA.EMP_NAME], \r\n            T.EMP_SURNAME AS [USER_D" +
                    "ATA.EMP_SURNAME], \r\n            T.EMP_TITLE_E AS [USER_DATA.EMP_TITLE_E], \r\n    " +
                    "        T.EMP_NAME_E AS [USER_DATA.EMP_NAME_E], \r\n            T.EMP_SURNAME_E AS" +
                    " [USER_DATA.EMP_SURNAME_E], \r\n            T.PASSWD AS [USER_DATA.PASSWD], \r\n    " +
                    "        T.EMAIL AS [USER_DATA.EMAIL], \r\n            T.PHONE_OFFICE AS [USER_DATA" +
                    ".PHONE_OFFICE], \r\n            T.PHONE_HOME AS [USER_DATA.PHONE_HOME], \r\n        " +
                    "    T.PHONE_MOBILE AS [USER_DATA.PHONE_MOBILE], \r\n            T.CREATE_DATE AS [" +
                    "USER_DATA.CREATE_DATE], \r\n            T.EXPIRE_DATE AS [USER_DATA.EXPIRE_DATE], " +
                    "\r\n            T.UPDATE_DATE AS [USER_DATA.UPDATE_DATE], \r\n            T.LAST_SIG" +
                    "N_ON_DATE AS [USER_DATA.LAST_SIGN_ON_DATE], \r\n            T.LAST_CHANGE_PASS_DAT" +
                    "E AS [USER_DATA.LAST_CHANGE_PASS_DATE], \r\n            T.DEL_FLAG AS [USER_DATA.D" +
                    "EL_FLAG], \r\n            True AS _from0\r\n        FROM RISKModelStoreContainer.USE" +
                    "R_DATA AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.APPLICATIONs
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.APPLICATIONs", @"
    SELECT VALUE -- Constructing APPLICATIONs
        [RISKModel.APPLICATION](T1.[APPLICATION.APP_KEY], T1.[APPLICATION.APP_DESC], T1.APPLICATION_PRIORITY, T1.[APPLICATION.DEL_FLAG])
    FROM (
        SELECT 
            T.APP_KEY AS [APPLICATION.APP_KEY], 
            T.APP_DESC AS [APPLICATION.APP_DESC], 
            T.PRIORITY AS APPLICATION_PRIORITY, 
            T.DEL_FLAG AS [APPLICATION.DEL_FLAG], 
            True AS _from0
        FROM RISKModelStoreContainer.APPLICATION AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.MENU_MASTER
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.MENU_MASTER", @"
    SELECT VALUE -- Constructing MENU_MASTER
        [RISKModel.MENU_MASTER](T1.[MENU_MASTER.MENU_KEY], T1.[MENU_MASTER.MENU_TITLE], T1.[MENU_MASTER.MENU_URL], T1.[MENU_MASTER.MENU_POPUP_OPT], T1.[MENU_MASTER.MENU_REL], T1.[MENU_MASTER.MENU_TOOLTIP], T1.[MENU_MASTER.MENU_PRIORITY], T1.[MENU_MASTER.MENU_DEL_FLAG], T1.[MENU_MASTER.MENU_PARENT_KEY])
    FROM (
        SELECT 
            T.MENU_KEY AS [MENU_MASTER.MENU_KEY], 
            T.MENU_TITLE AS [MENU_MASTER.MENU_TITLE], 
            T.MENU_URL AS [MENU_MASTER.MENU_URL], 
            T.MENU_POPUP_OPT AS [MENU_MASTER.MENU_POPUP_OPT], 
            T.MENU_REL AS [MENU_MASTER.MENU_REL], 
            T.MENU_TOOLTIP AS [MENU_MASTER.MENU_TOOLTIP], 
            T.MENU_PRIORITY AS [MENU_MASTER.MENU_PRIORITY], 
            T.MENU_DEL_FLAG AS [MENU_MASTER.MENU_DEL_FLAG], 
            T.MENU_PARENT_KEY AS [MENU_MASTER.MENU_PARENT_KEY], 
            True AS _from0
        FROM RISKModelStoreContainer.MENU_MASTER AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for RISKModelStoreContainer.MASTER_EMPLOYEE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("RISKModelStoreContainer.MASTER_EMPLOYEE", "\r\n    SELECT VALUE -- Constructing MASTER_EMPLOYEE\r\n        [RISKModel.Store.MAST" +
                    "ER_EMPLOYEE](T1.[MASTER_EMPLOYEE.EMP_ID], T1.[MASTER_EMPLOYEE.EMP_ID_DISPLAY], T" +
                    "1.[MASTER_EMPLOYEE.IEMPID], T1.[MASTER_EMPLOYEE.NTTITLE], T1.[MASTER_EMPLOYEE.NT" +
                    "NAME], T1.[MASTER_EMPLOYEE.NTSURN], T1.[MASTER_EMPLOYEE.EEPOSIT], T1.[MASTER_EMP" +
                    "LOYEE.EESECTION], T1.[MASTER_EMPLOYEE.EEDEPT], T1.[MASTER_EMPLOYEE.NETITLE], T1." +
                    "[MASTER_EMPLOYEE.NENAME], T1.[MASTER_EMPLOYEE.NESURN], T1.[MASTER_EMPLOYEE.EEPOS" +
                    "ITE], T1.[MASTER_EMPLOYEE.EESECTIONE], T1.[MASTER_EMPLOYEE.EEDEPE], T1.[MASTER_E" +
                    "MPLOYEE.POSITION], T1.[MASTER_EMPLOYEE.POSITION_CODE], T1.[MASTER_EMPLOYEE.IESEC" +
                    "TION], T1.[MASTER_EMPLOYEE.PHONE_OFFICE], T1.[MASTER_EMPLOYEE.EMAIL])\r\n    FROM " +
                    "(\r\n        SELECT \r\n            T.EMP_ID AS [MASTER_EMPLOYEE.EMP_ID], \r\n        " +
                    "    T.EMP_ID_DISPLAY AS [MASTER_EMPLOYEE.EMP_ID_DISPLAY], \r\n            T.IEMPID" +
                    " AS [MASTER_EMPLOYEE.IEMPID], \r\n            T.NTTITLE AS [MASTER_EMPLOYEE.NTTITL" +
                    "E], \r\n            T.NTNAME AS [MASTER_EMPLOYEE.NTNAME], \r\n            T.NTSURN A" +
                    "S [MASTER_EMPLOYEE.NTSURN], \r\n            T.EEPOSIT AS [MASTER_EMPLOYEE.EEPOSIT]" +
                    ", \r\n            T.EESECTION AS [MASTER_EMPLOYEE.EESECTION], \r\n            T.EEDE" +
                    "PT AS [MASTER_EMPLOYEE.EEDEPT], \r\n            T.NETITLE AS [MASTER_EMPLOYEE.NETI" +
                    "TLE], \r\n            T.NENAME AS [MASTER_EMPLOYEE.NENAME], \r\n            T.NESURN" +
                    " AS [MASTER_EMPLOYEE.NESURN], \r\n            T.EEPOSITE AS [MASTER_EMPLOYEE.EEPOS" +
                    "ITE], \r\n            T.EESECTIONE AS [MASTER_EMPLOYEE.EESECTIONE], \r\n            " +
                    "T.EEDEPE AS [MASTER_EMPLOYEE.EEDEPE], \r\n            T.POSITION AS [MASTER_EMPLOY" +
                    "EE.POSITION], \r\n            T.POSITION_CODE AS [MASTER_EMPLOYEE.POSITION_CODE], " +
                    "\r\n            T.IESECTION AS [MASTER_EMPLOYEE.IESECTION], \r\n            T.PHONE_" +
                    "OFFICE AS [MASTER_EMPLOYEE.PHONE_OFFICE], \r\n            T.EMAIL AS [MASTER_EMPLO" +
                    "YEE.EMAIL], \r\n            True AS _from0\r\n        FROM UserSystemEntities.MASTER" +
                    "_EMPLOYEE AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// return view for UserSystemEntities.MASTER_EMPLOYEE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView25()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("UserSystemEntities.MASTER_EMPLOYEE", "\r\n    SELECT VALUE -- Constructing MASTER_EMPLOYEE\r\n        [RISKModel.MASTER_EMP" +
                    "LOYEE](T1.[MASTER_EMPLOYEE.EMP_ID], T1.[MASTER_EMPLOYEE.EMP_ID_DISPLAY], T1.[MAS" +
                    "TER_EMPLOYEE.IEMPID], T1.[MASTER_EMPLOYEE.NTTITLE], T1.[MASTER_EMPLOYEE.NTNAME]," +
                    " T1.[MASTER_EMPLOYEE.NTSURN], T1.[MASTER_EMPLOYEE.EEPOSIT], T1.[MASTER_EMPLOYEE." +
                    "EESECTION], T1.[MASTER_EMPLOYEE.EEDEPT], T1.[MASTER_EMPLOYEE.NETITLE], T1.[MASTE" +
                    "R_EMPLOYEE.NENAME], T1.[MASTER_EMPLOYEE.NESURN], T1.[MASTER_EMPLOYEE.EEPOSITE], " +
                    "T1.[MASTER_EMPLOYEE.EESECTIONE], T1.[MASTER_EMPLOYEE.EEDEPE], T1.[MASTER_EMPLOYE" +
                    "E.POSITION], T1.[MASTER_EMPLOYEE.POSITION_CODE], T1.[MASTER_EMPLOYEE.IESECTION]," +
                    " T1.[MASTER_EMPLOYEE.PHONE_OFFICE], T1.[MASTER_EMPLOYEE.EMAIL])\r\n    FROM (\r\n   " +
                    "     SELECT \r\n            T.EMP_ID AS [MASTER_EMPLOYEE.EMP_ID], \r\n            T." +
                    "EMP_ID_DISPLAY AS [MASTER_EMPLOYEE.EMP_ID_DISPLAY], \r\n            T.IEMPID AS [M" +
                    "ASTER_EMPLOYEE.IEMPID], \r\n            T.NTTITLE AS [MASTER_EMPLOYEE.NTTITLE], \r\n" +
                    "            T.NTNAME AS [MASTER_EMPLOYEE.NTNAME], \r\n            T.NTSURN AS [MAS" +
                    "TER_EMPLOYEE.NTSURN], \r\n            T.EEPOSIT AS [MASTER_EMPLOYEE.EEPOSIT], \r\n  " +
                    "          T.EESECTION AS [MASTER_EMPLOYEE.EESECTION], \r\n            T.EEDEPT AS " +
                    "[MASTER_EMPLOYEE.EEDEPT], \r\n            T.NETITLE AS [MASTER_EMPLOYEE.NETITLE], " +
                    "\r\n            T.NENAME AS [MASTER_EMPLOYEE.NENAME], \r\n            T.NESURN AS [M" +
                    "ASTER_EMPLOYEE.NESURN], \r\n            T.EEPOSITE AS [MASTER_EMPLOYEE.EEPOSITE], " +
                    "\r\n            T.EESECTIONE AS [MASTER_EMPLOYEE.EESECTIONE], \r\n            T.EEDE" +
                    "PE AS [MASTER_EMPLOYEE.EEDEPE], \r\n            T.POSITION AS [MASTER_EMPLOYEE.POS" +
                    "ITION], \r\n            T.POSITION_CODE AS [MASTER_EMPLOYEE.POSITION_CODE], \r\n    " +
                    "        T.IESECTION AS [MASTER_EMPLOYEE.IESECTION], \r\n            T.PHONE_OFFICE" +
                    " AS [MASTER_EMPLOYEE.PHONE_OFFICE], \r\n            T.EMAIL AS [MASTER_EMPLOYEE.EM" +
                    "AIL], \r\n            True AS _from0\r\n        FROM RISKModelStoreContainer.MASTER_" +
                    "EMPLOYEE AS T\r\n    ) AS T1");
        }
    }
}
