CREATE VIEW dbo.View_2
AS
SELECT     DASOF, [KEY], TITLE, ACCOUNT_NAME, OWNER_NAME, ADDRESS, BANK_CODE, BANK_NAME, BRANCH_CODE, BRANCH_NAME, CLOSE_DATE
FROM         DBF_IMPORT.dbo.DB2DB_BL_CLOSE_ACT
