Create VIEW [dbo].[REPORT68_32_M_SUM_BY_MONTH]
AS
SELECT     MONTH, SUM(ALL_REQUEST) AS ALL_REQUEST, SUM(ALL_RM_VALUEs) AS ALL_RM_VALUEs, SUM(APPROVE_REQUEST) AS APPROVE_REQUEST, 
                      SUM(APPROVE_APPROVE_VALUEs) AS APPROVE_APPROVE_VALUEs
FROM         dbo.REPORT32_31_SUM_ALL_REQUEST
WHERE     (Customer_Size = N'3')
GROUP BY MONTH
