ALTER TABLE [dbo].[TB_TEMP_CUST_12M_20100630]
    ADD CONSTRAINT [PK_TB_TEMP_CUST_12M_20100630] PRIMARY KEY CLUSTERED ([cif] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

