ALTER TABLE [dbo].[rep_prod]
    ADD CONSTRAINT [PK_rep_prod] PRIMARY KEY CLUSTERED ([cif] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

