ALTER TABLE [dbo].[BUSI_TYPE3]
    ADD CONSTRAINT [PK_BUSI_TYPE3] PRIMARY KEY CLUSTERED ([TYPE3_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

