ALTER TABLE [dbo].[ID_AO_CM]
    ADD CONSTRAINT [PK_ID_AO_CM] PRIMARY KEY CLUSTERED ([AO_SME] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

