ALTER TABLE [dbo].[tdr]
    ADD CONSTRAINT [PK_tdr] PRIMARY KEY CLUSTERED ([cif] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

