CREATE TABLE [dbo].[CUSTOMER_SME_CORP] (
    [Cif]             FLOAT          NULL,
    [Name]            NVARCHAR (255) NULL,
    [BaySize]         NVARCHAR (255) NULL,
    [Rating]          NVARCHAR (255) NULL,
    [Busi_Type]       FLOAT          NULL,
    [BranchMaxPrin]   FLOAT          NULL,
    [AgingMax]        FLOAT          NULL,
    [Class]           NVARCHAR (255) NULL,
    [Principal]       FLOAT          NULL,
    [Contingent]      FLOAT          NULL,
    [Sum P+C]         FLOAT          NULL,
    [Principal_5311]  FLOAT          NULL,
    [Contingent_5311] FLOAT          NULL,
    [Sum P+C_5311]    FLOAT          NULL,
    [Prin_Sugar]      NVARCHAR (255) NULL,
    [Sugar_flag]      NVARCHAR (255) NULL,
    [No_Account]      NVARCHAR (255) NULL,
    [CusDeptFlag]     FLOAT          NULL,
    [CusDeptTran]     FLOAT          NULL,
    [Region_new]      NVARCHAR (255) NULL,
    [DepTranT]        NVARCHAR (255) NULL,
    [GRP_LIM]         FLOAT          NULL,
    [SEQ]             FLOAT          NULL,
    [SIZE_NEW]        NVARCHAR (255) NULL,
    [GSING_LIM]       FLOAT          NULL,
    [SING_LIM]        FLOAT          NULL,
    [CASH]            FLOAT          NULL,
    [NON_CASH]        FLOAT          NULL,
    [CM_CODE]         FLOAT          NULL,
    [CM_NAME]         NVARCHAR (255) NULL,
    [MCIF]            FLOAT          NULL,
    [NUMCUST]         FLOAT          NULL,
    [Not Corp]        NVARCHAR (255) NULL,
    [CCR_PORTFOLIO]   NVARCHAR (255) NULL,
    [NewCMID]         NVARCHAR (255) NULL,
    [NEW CM NAME]     NVARCHAR (255) NULL
);

