CREATE TABLE [dbo].[TEMP_MAX_AGING_EDW] (
    [DATE_ID_KEY]                  NUMERIC (10)    NOT NULL,
    [CIF]                          NUMERIC (10)    NOT NULL,
    [TDR]                          VARCHAR (1)     NULL,
    [TDR_ASOFDATE]                 DATETIME        NULL,
    [TOTAL_CASH_PRINCIPAL]         NUMERIC (16, 2) NULL,
    [MAX_AGING]                    NUMERIC (6, 2)  NULL,
    [MAX_AGING_HIST_30DAY]         VARCHAR (30)    NULL,
    [OD_PRINCIPAL]                 NUMERIC (16, 2) NULL,
    [OD_MAX_AGING]                 NUMERIC (6, 2)  NULL,
    [OD_MAX_AGING_HIST_30DAY]      VARCHAR (30)    NULL,
    [TL_COM_PRINCIPAL]             NUMERIC (16, 2) NULL,
    [TL_COM_MAX_AGING]             NUMERIC (6, 2)  NULL,
    [TL_COM_MAX_AGING_HIST_30DAY]  VARCHAR (30)    NULL,
    [TL_HL_PL_STF_PRINCIPAL]       NUMERIC (16, 2) NULL,
    [TL_HL_PL_STF_MAX_AGING]       NUMERIC (6, 2)  NULL,
    [TL_HL_PL_STF_MAX_AGING_30DAY] VARCHAR (30)    NULL,
    [PN_PRINCIPAL]                 NUMERIC (16, 2) NULL,
    [PN_MAX_AGING]                 NUMERIC (6, 2)  NULL,
    [PN_MAX_AGING_HIST_30DAY]      VARCHAR (30)    NULL,
    [BD_PRINCIPAL]                 NUMERIC (16, 2) NULL,
    [BD_MAX_AGING]                 NUMERIC (6, 2)  NULL,
    [BD_MAX_AGING_HIST_30DAY]      VARCHAR (30)    NULL,
    [TRADE_PRINCIPAL]              NUMERIC (16, 2) NULL,
    [TRADE_MAX_AGING]              NUMERIC (6, 2)  NULL,
    [TRADE_MAX_AGING_HIST_30DAY]   VARCHAR (30)    NULL,
    [CLAIM_PRINCIPAL]              NUMERIC (16, 2) NULL,
    [CLAIM_MAX_AGING]              NUMERIC (6, 2)  NULL,
    [CLAIM_MAX_AGING_HIST_30DAY]   VARCHAR (30)    NULL,
    [FNX_PRINCIPAL]                NUMERIC (16, 2) NULL,
    [FNX_MAX_AGING]                NUMERIC (6, 2)  NULL,
    [FNX_MAX_AGING_HIST_30DAY]     VARCHAR (30)    NULL,
    [CUSTOMER_KEY]                 NUMERIC (10)    NULL,
    [DEMOGRAPHICS_KEY]             NUMERIC (10)    NULL,
    [GECID]                        NUMERIC (8)     NULL,
    [GECID_COMPANY]                NUMERIC (8)     NULL,
    [ETL_ASOFDATE]                 DATETIME        NULL,
    [ETL_DT]                       DATETIME        NULL
);

