CREATE TABLE [dbo].[LCIdaily] (
    [DASOF]       NVARCHAR (12)   NULL,
    [BRAN]        INT             NULL,
    [BRANCH_NAM]  NVARCHAR (100)  NULL,
    [ACCGL]       INT             NULL,
    [ACCNO]       NVARCHAR (100)  NULL,
    [CONTNO]      NVARCHAR (100)  NULL,
    [SEQNO]       INT             NULL,
    [CIF]         INT             NULL,
    [CIF_NAME]    NVARCHAR (100)  NULL,
    [APP_ID]      NVARCHAR (100)  NULL,
    [OPENDATE]    DATETIME        NULL,
    [DUE_DATE]    DATETIME        NULL,
    [ISSU_DATE]   DATETIME        NULL,
    [LACT_DATE]   DATETIME        NULL,
    [LPAY_DATE]   DATETIME        NULL,
    [UPD_DATE]    DATETIME        NULL,
    [DEPT]        INT             NULL,
    [DEPT_MAIN2]  NVARCHAR (100)  NULL,
    [DEPT_APPV]   INT             NULL,
    [DEPT_APPR2]  NVARCHAR (100)  NULL,
    [DEPT_ISSU]   INT             NULL,
    [DEPT_ISSU2]  NVARCHAR (100)  NULL,
    [DEPT_TRAN]   INT             NULL,
    [DEPT_TRAN_]  NVARCHAR (100)  NULL,
    [ST_PRIN]     DECIMAL (18, 2) NULL,
    [ST_ACCRU]    DECIMAL (18, 2) NULL,
    [ST_SUSP]     DECIMAL (18, 2) NULL,
    [PRINCIPAL]   DECIMAL (18, 2) NULL,
    [ACCRU]       DECIMAL (18, 2) NULL,
    [SUSP]        DECIMAL (18, 2) NULL,
    [N_BAL_DATE]  DATETIME        NULL,
    [N_PRI_DATE]  DATETIME        NULL,
    [N_ACC_DATE]  DATETIME        NULL,
    [N_SUS_DATE]  DATETIME        NULL,
    [N_BAL]       DECIMAL (18, 2) NULL,
    [N_PRIN]      DECIMAL (18, 2) NULL,
    [N_ACCRU]     DECIMAL (18, 2) NULL,
    [N_SUSP]      DECIMAL (18, 2) NULL,
    [P_PRI_DATE]  DATETIME        NULL,
    [P_ACC_DATE]  DATETIME        NULL,
    [P_SUSP_DATE] DATETIME        NULL,
    [PAY_PRIN]    DECIMAL (18, 2) NULL,
    [PAY_INT]     DECIMAL (18, 2) NULL,
    [PAY_SUSP]    DECIMAL (18, 2) NULL,
    [L_PRI_DATE]  DATETIME        NULL,
    [L_ACC_DATE]  DATETIME        NULL,
    [L_SUS_DATE]  DATETIME        NULL,
    [L_PRIN]      DECIMAL (18, 2) NULL,
    [L_ACCRU]     DECIMAL (18, 2) NULL,
    [L_SUSP]      DECIMAL (18, 2) NULL,
    [PO_AC_DATE]  DATETIME        NULL,
    [POST_PRIN]   DECIMAL (18, 2) NULL,
    [POST_INT]    DECIMAL (18, 2) NULL,
    [POST_SUSP]   DECIMAL (18, 2) NULL,
    [ST_CAL_INT]  NVARCHAR (100)  NULL,
    [ADJ_INT]     NVARCHAR (100)  NULL,
    [INT_TYPE]    NVARCHAR (100)  NULL,
    [INT_ADV]     DECIMAL (18, 2) NULL,
    [RATE_TYPE]   NVARCHAR (100)  NULL,
    [RATE_TYPE_]  NVARCHAR (100)  NULL,
    [RATE_LOAD]   DECIMAL (18, 2) NULL,
    [INT_RATE]    DECIMAL (18, 2) NULL,
    [RESV_SYS]    DECIMAL (18, 2) NULL,
    [REQ_RESV]    DECIMAL (18, 2) NULL,
    [OFF_PRIN]    DECIMAL (18, 2) NULL,
    [OFF_ACCRU]   DECIMAL (18, 2) NULL,
    [AGING]       DECIMAL (18, 2) NULL,
    [MAX_AGING]   DECIMAL (18, 2) NULL,
    [LI_OF_DATE]  DATETIME        NULL,
    [LI_CL_DATE]  DATETIME        NULL,
    [LIMITNO]     NVARCHAR (100)  NULL,
    [LIMIT_TYPE]  NVARCHAR (100)  NULL,
    [LIMIT]       DECIMAL (18, 2) NULL,
    [FEE]         DECIMAL (18, 2) NULL,
    [FEE_THYR]    DECIMAL (18, 2) NULL,
    [FEE_LAYR]    DECIMAL (18, 2) NULL,
    [REVT_ACCRU]  DECIMAL (18, 2) NULL,
    [FCY_CODE]    INT             NULL,
    [CURR_CODE_]  NVARCHAR (100)  NULL,
    [LOAN_CODE]   NVARCHAR (100)  NULL,
    [LOAN_CODE_]  NVARCHAR (100)  NULL,
    [BUSI_TYPE]   NVARCHAR (100)  NULL,
    [LOAN_PURP2]  NVARCHAR (100)  NULL,
    [LOAN_TYPE]   NVARCHAR (100)  NULL,
    [PROM_TYPE]   NVARCHAR (100)  NULL,
    [PROMOTE_T2]  NVARCHAR (100)  NULL,
    [LO_PR_TYPE]  NVARCHAR (100)  NULL,
    [LOAN_PRIN2]  NVARCHAR (100)  NULL,
    [EXCHG_RATE]  DECIMAL (18, 2) NULL,
    [PAY_TERM]    NVARCHAR (100)  NULL,
    [PAY_AMT_PI]  DECIMAL (18, 2) NULL,
    [NO_INSTALL]  INT             NULL,
    [ACCT_CASE]   NVARCHAR (100)  NULL,
    [ACCT_CASE_]  NVARCHAR (100)  NULL,
    [CLASS]       NVARCHAR (100)  NULL,
    [SME_TYPE]    NVARCHAR (100)  NULL,
    [SME_TYPE_D]  NVARCHAR (100)  NULL,
    [REASON_COD]  DECIMAL (18, 2) NULL,
    [REASON_CO2]  NVARCHAR (100)  NULL,
    [OFFICR_ID]   NVARCHAR (100)  NULL,
    [PERSONAL_N]  NVARCHAR (100)  NULL,
    [PERSONAL_O]  NVARCHAR (100)  NULL,
    [CASE_NO]     NVARCHAR (100)  NULL,
    [AREA]        INT             NULL,
    [AREA_DESC]   NVARCHAR (100)  NULL,
    [REGION]      INT             NULL,
    [REGION_DES]  NVARCHAR (100)  NULL,
    [AVG_OUTSTA]  DECIMAL (18, 2) NULL,
    [MIN_INT_RA]  DECIMAL (18, 2) NULL,
    [MAX_INT_RA]  DECIMAL (18, 2) NULL,
    [CLOSE_DATE]  NVARCHAR (100)  NULL,
    [OLD_DUE_DA]  NVARCHAR (100)  NULL,
    [DUE_BAL]     DECIMAL (18, 2) NULL,
    [NOT_PAY_SI]  NVARCHAR (100)  NULL,
    [NOT_PAY]     DECIMAL (18, 2) NULL,
    [ASOF_DATE]   NVARCHAR (100)  NULL,
    [LIMIT_VAL2]  DECIMAL (18, 2) NULL,
    [DPD]         NVARCHAR (100)  NULL,
    [DAYS]        NVARCHAR (100)  NULL,
    [ZERO_INT_D]  NVARCHAR (100)  NULL,
    [RATE_MIN]    NVARCHAR (100)  NULL,
    [RATE_MIN_D]  NVARCHAR (100)  NULL,
    [UNEARNPRIN]  DECIMAL (18, 2) NULL,
    [UNEARNINT]   DECIMAL (18, 2) NULL,
    [Keyind]      NVARCHAR (506)  NULL,
    [Limitapp]    DECIMAL (18, 2) NULL,
    [Deptflag]    NVARCHAR (100)  NULL,
    [c126]        NVARCHAR (100)  NULL,
    [c127]        NVARCHAR (100)  NULL,
    [c128]        NVARCHAR (100)  NULL,
    [c129]        NVARCHAR (100)  NULL,
    [c130]        NVARCHAR (100)  NULL,
    [c131]        NVARCHAR (100)  NULL,
    [c132]        NVARCHAR (100)  NULL,
    [c133]        NVARCHAR (100)  NULL,
    [c134]        NVARCHAR (100)  NULL
);

