CREATE TABLE [dbo].[ALS_DAILY] (
    [DASOF]              DATETIME        NOT NULL,
    [BRANCH]             NVARCHAR (3)    NOT NULL,
    [ACCOUNT]            NVARCHAR (14)   NOT NULL,
    [NAME]               NVARCHAR (13)   NULL,
    [ADDR1]              NVARCHAR (40)   NULL,
    [ADDR2]              NVARCHAR (40)   NULL,
    [PROV]               NVARCHAR (30)   NULL,
    [ZIP]                NVARCHAR (10)   NULL,
    [TEL]                NVARCHAR (8)    NULL,
    [APPROVE_DEPT]       NVARCHAR (4)    NULL,
    [MAIN_DEPT]          NVARCHAR (4)    NULL,
    [TYPE_ACC]           NVARCHAR (2)    NULL,
    [BUSI_TYPE]          NVARCHAR (6)    NULL,
    [CUST_TYPE]          NVARCHAR (4)    NULL,
    [LOAN_TYPE]          NVARCHAR (4)    NULL,
    [PRINCIPAL]          DECIMAL (14, 2) NULL,
    [ADVANCE]            DECIMAL (14, 2) NULL,
    [NUMBER_DAY]         NVARCHAR (4)    NULL,
    [CREDIT_LINE]        DECIMAL (14, 2) NULL,
    [OPEN_DATE]          DATETIME        NULL,
    [DUE_DATE]           DATETIME        NULL,
    [L_TRANS_DATE]       DATETIME        NULL,
    [NON_ACCRU_DATE]     DATETIME        NULL,
    [STOP_DATE]          DATETIME        NULL,
    [OLD_YEARLY_INT]     DECIMAL (12, 2) NULL,
    [THIS_YEARLY_INT]    DECIMAL (12, 2) NULL,
    [PAY_DATE]           DATETIME        NULL,
    [TYPE_PAY]           NVARCHAR (2)    NULL,
    [NUMBER_PERIOD]      NVARCHAR (4)    NULL,
    [PERIOD_PER_TIME]    NVARCHAR (5)    NULL,
    [LOAN_PURPOSE]       NVARCHAR (6)    NULL,
    [AUTO_HIGH_INT]      NVARCHAR (1)    NULL,
    [NUM_MONTH]          DECIMAL (5, 2)  NULL,
    [PROJ_CODE]          NVARCHAR (4)    NULL,
    [INT_RATE]           DECIMAL (9, 7)  NULL,
    [RATE_LOADING]       DECIMAL (9, 5)  NULL,
    [RATE_CHARGE]        DECIMAL (9, 7)  NULL,
    [DEBT_STATUS]        NVARCHAR (2)    NULL,
    [AVL_CR_LIMIT]       DECIMAL (14, 2) NULL,
    [ACCRU]              DECIMAL (14, 2) NULL,
    [POST_ACCRU]         DECIMAL (14, 2) NULL,
    [NON_ACCRU]          DECIMAL (14, 2) NULL,
    [POST_NON_ACCRU]     DECIMAL (14, 2) NULL,
    [GL_CODE]            NVARCHAR (10)   NULL,
    [LAST_PRIN]          DECIMAL (14, 2) NULL,
    [LAST_ACCRU]         DECIMAL (14, 2) NULL,
    [PAY_NON_ACCRU]      DECIMAL (14, 2) NULL,
    [ACCT_STATUS]        NVARCHAR (2)    NULL,
    [ACCR_STATUS]        NVARCHAR (2)    NULL,
    [CIF_NO]             NVARCHAR (10)   NULL,
    [SIGN_CONTRACT_DATE] DATETIME        NULL,
    [PENALTY_CODE]       NVARCHAR (2)    NULL,
    [PAY_AMOUNT]         DECIMAL (12, 2) NULL,
    [THAI_NAME]          NVARCHAR (40)   NULL,
    [AFFILIATE_ACCT]     NVARCHAR (10)   NULL,
    [PERSONAL_ID]        NVARCHAR (13)   NULL,
    [TDR_FLAG]           NVARCHAR (1)    NULL,
    [PAY_PRIN_MTD]       DECIMAL (15, 2) NULL,
    [PAY_INT_MTD]        DECIMAL (17, 2) NULL,
    [RCVY_NONACCR_MTD]   DECIMAL (17, 2) NULL,
    [ORIG_DUE_DATE]      DATETIME        NULL,
    [STOP_INT]           NVARCHAR (1)    NULL,
    [ACCOUNT_TYPE]       NVARCHAR (3)    NULL,
    [OLDST_DUE_DATE]     DATETIME        NULL,
    [DAY_PDUE]           INT             NULL,
    [APRV_BY_1]          NVARCHAR (15)   NULL,
    [APRV_BY_2]          NVARCHAR (15)   NULL,
    [APRV_DATE_1]        NVARCHAR (10)   NULL,
    [APRV_DATE_2]        NVARCHAR (10)   NULL,
    [ACCR_ITD]           DECIMAL (17, 2) NULL,
    [PD_ITD]             DECIMAL (17, 2) NULL,
    [PRIM_OFFICER]       NVARCHAR (5)    NULL,
    [ORIG_RATE]          DECIMAL (11, 7) NULL,
    [CONTROL_UNIT]       NVARCHAR (4)    NULL,
    [PAY_POST]           NVARCHAR (2)    NULL,
    [ACCT_FROM]          NVARCHAR (4)    NULL,
    [ORG_DU_PMT]         DECIMAL (17, 2) NULL,
    [BILL_FREQ]          NVARCHAR (1)    NULL,
    [BILL_INCR]          NVARCHAR (3)    NULL,
    [BILL_DAY]           NVARCHAR (2)    NULL,
    [PMT_METH]           NVARCHAR (1)    NULL,
    [CLOSE_DATE]         NVARCHAR (10)   NULL,
    [AUTO_DR_MTHD]       NVARCHAR (1)    NULL,
    [PGP_AMT]            DECIMAL (16, 2) NULL,
    [PREP_RATE]          DECIMAL (18, 7) NULL,
    [AUTO_DEBIT]         NVARCHAR (1)    NULL,
    [PREPRIN_PAID]       DECIMAL (15, 2) NULL,
    [CURR_PDUE_DATE]     DATETIME        NULL,
    [OLDEST_DATE]        DATETIME        NULL,
    [PAST_DUE_PRI]       DECIMAL (15, 2) NULL,
    [PAST_DUE_INT]       DECIMAL (15, 2) NULL,
    [PAST_DUE_FEE]       DECIMAL (15, 2) NULL,
    [TOTAL_PAST_DUE]     DECIMAL (15, 2) NULL,
    [CURR_DUE_PRI]       DECIMAL (15, 2) NULL,
    [CURR_DUE_INT]       DECIMAL (15, 2) NULL,
    [CURR_DUE_FEE]       DECIMAL (15, 2) NULL,
    [TOTAL_CURR_DUE]     DECIMAL (15, 2) NULL,
    [GRAND_TOTAL_PRI]    DECIMAL (15, 2) NULL,
    [GRAND_TOTAL_INT]    DECIMAL (15, 2) NULL,
    [GRAND_TOTAL_FEE]    DECIMAL (15, 2) NULL,
    [GRAND_TOTAL]        DECIMAL (15, 2) NULL,
    [BA_DUE_NOT_PD]      DECIMAL (13, 2) NULL,
    [AC_DUE_NOT_PD]      DECIMAL (12, 2) NULL,
    [FF_DUE_NOT_PD]      DECIMAL (11, 2) NULL,
    [TOT_FEE]            DECIMAL (11, 2) NULL,
    [BA_AVAIL_BAL]       DECIMAL (13, 2) NULL,
    [BA_HOLD_BAL]        DECIMAL (13, 2) NULL,
    [STOP_ADV_IND]       NVARCHAR (1)    NULL,
    [LAST_PMT_DATE]      DATETIME        NULL,
    [NUM_DUE_SEQMENT]    INT             NULL,
    [FIRST_ADVANCE_AMT]  DECIMAL (13, 2) NULL,
    [DISBURSEMENT_DATE]  DATETIME        NULL,
    [LAST_ADVANCE_AMT]   DECIMAL (13, 2) NULL,
    [PAYOFF_DATE]        DATETIME        NULL,
    [PAYOFF_MAT]         DECIMAL (13, 2) NULL,
    [DECISION_CD]        NVARCHAR (15)   NULL,
    [FIRST_DUE_DATE]     DATETIME        NULL,
    [NPL_OUT_DATE]       DATETIME        NULL,
    [ZERO_BAL_REASON_CD] NVARCHAR (1)    NULL,
    [RISK_GRADING]       NVARCHAR (10)   NULL,
    [RT_CONTROL_UNIT]    NVARCHAR (5)    NULL,
    [RT_APPROVE_DEPT]    INT             NULL,
    [RT_MAINT_DEPT]      INT             NULL,
    [PERDIUM]            DECIMAL (17, 5) NULL,
    [COLL_CD]            NVARCHAR (1)    NULL,
    [COM_APPL_ID]        NVARCHAR (10)   NULL,
    [APP_IN_DATE]        DATETIME        NULL,
    [FUNDING_DATE]       DATETIME        NULL
);

