CREATE TABLE [dbo].[lim_exp_old] (
    [cif]        FLOAT          NULL,
    [custname]   NVARCHAR (255) NULL,
    [sing_lim]   FLOAT          NULL,
    [cash_com]   FLOAT          NULL,
    [principal]  FLOAT          NULL,
    [unearnprin] FLOAT          NULL,
    [accru]      FLOAT          NULL,
    [unearnint]  FLOAT          NULL,
    [non_cash]   FLOAT          NULL,
    [n_cash_nfx] FLOAT          NULL,
    [bay_rate]   NVARCHAR (255) NULL,
    [adjclass]   NVARCHAR (255) NULL,
    [class_h]    NVARCHAR (255) NULL,
    [m_aging]    FLOAT          NULL,
    [age_grp]    NVARCHAR (255) NULL,
    [aging_h]    NVARCHAR (255) NULL,
    [tdr]        BIT            NOT NULL,
    [cm_code]    FLOAT          NULL,
    [cm_name]    NVARCHAR (255) NULL,
    [cm_grp]     NVARCHAR (255) NULL,
    [dept_ctrl]  FLOAT          NULL,
    [main_br]    FLOAT          NULL,
    [ctrl_area]  FLOAT          NULL,
    [org_ctrl]   FLOAT          NULL,
    [org_flag]   FLOAT          NULL,
    [rm_port]    NVARCHAR (255) NULL,
    [port_adj]   NVARCHAR (255) NULL,
    [mcif]       FLOAT          NULL,
    [numcust]    FLOAT          NULL,
    [grp_lim]    FLOAT          NULL,
    [grp_size]   NVARCHAR (255) NULL,
    [grp_coll]   FLOAT          NULL,
    [grp_ltv]    FLOAT          NULL,
    [gsing_lim]  FLOAT          NULL,
    [busi_type]  FLOAT          NULL,
    [risk_busi]  FLOAT          NULL,
    [busi_risk1] FLOAT          NULL,
    [busi_risk2] FLOAT          NULL,
    [busi_risk3] FLOAT          NULL,
    [custsize]   NVARCHAR (255) NULL,
    [totresv]    FLOAT          NULL,
    [joint_line] NVARCHAR (255) NULL,
    [mix_line]   NVARCHAR (255) NULL,
    [coll_co]    NVARCHAR (255) NULL,
    [g_coll]     FLOAT          NULL,
    [od_flag]    NVARCHAR (255) NULL,
    [prn_sugar]  FLOAT          NULL,
    [labor]      FLOAT          NULL,
    [ggrp_size]  NVARCHAR (255) NULL,
    [ciftype]    FLOAT          NULL,
    [leader_grp] NVARCHAR (255) NULL,
    [newbusi]    NVARCHAR (255) NULL,
    [watch_list] NVARCHAR (255) NULL
);

