CREATE TABLE [dbo].[CUSTOMER_CCR_0329] (
    [CIF]               FLOAT          NULL,
    [CNAME]             NVARCHAR (255) NULL,
    [CIF_GROUP]         FLOAT          NULL,
    [NAME_GROUP]        NVARCHAR (255) NULL,
    [CM_TeamLead_ID]    FLOAT          NULL,
    [TeamLead_Fname_Th] NVARCHAR (255) NULL,
    [TeamLead_Lname_Th] NVARCHAR (255) NULL,
    [TeamLead_Fname_En] NVARCHAR (255) NULL,
    [TeamLead_Lname_En] NVARCHAR (255) NULL,
    [CM_Grp]            FLOAT          NULL,
    [CM_Lead_ID]        FLOAT          NULL,
    [CM_Lead_Fname_Th]  NVARCHAR (255) NULL,
    [CM_Lead_Lname_Th]  NVARCHAR (255) NULL,
    [CM_Lead_Fname_En]  NVARCHAR (255) NULL,
    [CM_Lead_Lname_En]  NVARCHAR (255) NULL,
    [CM_ID]             FLOAT          NULL,
    [CM_Fname_Th]       NVARCHAR (255) NULL,
    [CM_Lname_Th]       NVARCHAR (255) NULL,
    [CM_Fname_En]       NVARCHAR (255) NULL,
    [CM_Lname_En]       NVARCHAR (255) NULL,
    [Busines Type_CCR]  NVARCHAR (255) NULL,
    [BizTypeE]          NVARCHAR (255) NULL,
    [F23]               NVARCHAR (255) NULL,
    [F24]               NVARCHAR (255) NULL,
    [F25]               NVARCHAR (255) NULL
);

