CREATE TABLE [dbo].[rep_prod] (
    [cif]        INT             NOT NULL,
    [custname]   VARCHAR (50)    NOT NULL,
    [sing_lim]   NUMERIC (20, 2) NOT NULL,
    [cm_grp]     VARCHAR (3)     NOT NULL,
    [ctrl_area]  NUMERIC (3)     NOT NULL,
    [grp_size]   VARCHAR (30)    NOT NULL,
    [custsize]   VARCHAR (30)    NULL,
    [busi_type]  NUMERIC (8)     NOT NULL,
    [busi_desc]  VARCHAR (35)    NOT NULL,
    [adjclass]   CHAR (1)        NOT NULL,
    [class_h]    VARCHAR (24)    NOT NULL,
    [m_aging]    NUMERIC (7, 2)  NOT NULL,
    [aging_h]    VARCHAR (24)    NOT NULL,
    [tot_prin]   NUMERIC (20, 2) NOT NULL,
    [od_lim]     NUMERIC (20, 2) NOT NULL,
    [od_prin]    NUMERIC (20, 2) NOT NULL,
    [od_aging]   NUMERIC (7, 2)  NOT NULL,
    [pns_lim]    NUMERIC (20, 2) NOT NULL,
    [pns_prin]   NUMERIC (20, 2) NOT NULL,
    [pns_aging]  NUMERIC (7, 2)  NOT NULL,
    [als_lim]    NUMERIC (20, 2) NOT NULL,
    [als_prin]   NUMERIC (20, 2) NOT NULL,
    [als_aging]  NUMERIC (7, 2)  NOT NULL,
    [alsh_lim]   NUMERIC (20, 2) NOT NULL,
    [alsh_prin]  NUMERIC (20, 2) NOT NULL,
    [alsh_aging] NUMERIC (7, 2)  NOT NULL,
    [alsp_lim]   NUMERIC (20, 2) NOT NULL,
    [alsp_prin]  NUMERIC (20, 2) NOT NULL,
    [alsp_aging] NUMERIC (7, 2)  NOT NULL,
    [pr_lim]     NUMERIC (20, 2) NOT NULL,
    [pr_prin]    NUMERIC (20, 2) NOT NULL,
    [pr_aging]   NUMERIC (7, 2)  NOT NULL,
    [imx_lim]    NUMERIC (20, 2) NOT NULL,
    [imx_prin_c] NUMERIC (20, 2) NOT NULL,
    [imx_prin_n] NUMERIC (20, 2) NOT NULL,
    [imx_aging]  NUMERIC (7, 2)  NOT NULL,
    [cts_lim]    NUMERIC (20, 2) NOT NULL,
    [cts_prin]   NUMERIC (20, 2) NOT NULL,
    [ccts_prin]  NUMERIC (20, 2) NOT NULL,
    [ccts_aging] NUMERIC (7, 2)  NOT NULL,
    [as_of]      DATETIME        NULL
);

