CREATE TABLE [dbo].[tdr] (
    [cif]        DECIMAL (11)    NOT NULL,
    [befortdr]   CHAR (1)        NOT NULL,
    [aftertdr]   CHAR (1)        NOT NULL,
    [botid]      DECIMAL (11)    NOT NULL,
    [name]       CHAR (70)       NOT NULL,
    [count]      DECIMAL (4)     NOT NULL,
    [date_repor] DECIMAL (11)    NOT NULL,
    [date_regit] DECIMAL (11)    NOT NULL,
    [regiterdat] DECIMAL (4)     NOT NULL,
    [regitermon] DECIMAL (4)     NOT NULL,
    [regiteryea] DECIMAL (6)     NOT NULL,
    [balancetdr] DECIMAL (19, 5) NOT NULL,
    [method_tdr] CHAR (12)       NOT NULL,
    [status]     CHAR (3)        NOT NULL,
    [pvloss]     DECIMAL (17, 2) NOT NULL,
    [principal]  DECIMAL (15, 2) NOT NULL,
    [accru]      DECIMAL (15, 2) NOT NULL,
    [susp]       DECIMAL (15, 2) NOT NULL,
    [unearnprin] DECIMAL (15, 2) NOT NULL,
    [unearnint]  DECIMAL (15, 2) NOT NULL,
    [loan]       DECIMAL (15, 2) NOT NULL,
    [cont]       DECIMAL (15, 2) NOT NULL,
    [reserve]    DECIMAL (15, 2) NOT NULL,
    [bafterc]    DECIMAL (15, 2) NOT NULL,
    [tdrloss]    DECIMAL (15, 2) NOT NULL,
    [totresv]    DECIMAL (15, 2) NOT NULL,
    [addresv]    DECIMAL (15, 2) NOT NULL,
    [class]      CHAR (1)        NOT NULL,
    [jan06]      CHAR (1)        NOT NULL,
    [feb06]      CHAR (1)        NOT NULL,
    [mar06]      CHAR (1)        NOT NULL,
    [apr06]      CHAR (1)        NOT NULL,
    [may06]      CHAR (1)        NOT NULL,
    [jun06]      CHAR (1)        NOT NULL,
    [jul06]      CHAR (1)        NOT NULL,
    [aug06]      CHAR (1)        NOT NULL,
    [sep06]      CHAR (1)        NOT NULL,
    [oct06]      CHAR (1)        NOT NULL,
    [nov06]      CHAR (1)        NOT NULL,
    [dec06]      CHAR (1)        NOT NULL,
    [jan07]      CHAR (1)        NOT NULL,
    [feb07]      CHAR (1)        NOT NULL,
    [mar07]      CHAR (1)        NOT NULL,
    [apr07]      CHAR (1)        NOT NULL,
    [may07]      CHAR (1)        NOT NULL,
    [jun07]      CHAR (1)        NOT NULL,
    [jul07]      CHAR (1)        NOT NULL,
    [aug07]      CHAR (1)        NOT NULL,
    [sep07]      CHAR (1)        NOT NULL,
    [oct07]      CHAR (1)        NOT NULL,
    [nov07]      CHAR (1)        NOT NULL,
    [dec07]      CHAR (1)        NOT NULL,
    [type]       DECIMAL (2)     NOT NULL,
    [type_t]     DECIMAL (2)     NOT NULL,
    [sp_resv]    CHAR (1)        NOT NULL,
    [totaddresv] DECIMAL (15, 2) NOT NULL,
    [tot_need]   DECIMAL (15, 2) NOT NULL,
    [resvbygaap] DECIMAL (15, 2) NOT NULL,
    [nxt_3mth]   CHAR (1)        NOT NULL,
    [nxt_6mth]   CHAR (1)        NOT NULL,
    [nxt]        CHAR (1)        NOT NULL,
    [oldtype]    DECIMAL (2)     NOT NULL,
    [bottdrtype] CHAR (6)        NOT NULL,
    [oldpvloss]  DECIMAL (15, 2) NOT NULL,
    [tdraging]   DECIMAL (9, 2)  NOT NULL,
    [dept_ctrl]  DECIMAL (4)     NOT NULL,
    [limit_cash] DECIMAL (15, 2) NOT NULL,
    [bucket]     CHAR (30)       NOT NULL,
    [sp_cnt]     DECIMAL (2)     NOT NULL,
    [lnsresv_6]  DECIMAL (15, 2) NOT NULL,
    [contresv_6] DECIMAL (15, 2) NOT NULL,
    [resv_m6]    DECIMAL (15, 2) NOT NULL,
    [spresv_m5]  DECIMAL (15, 2) NOT NULL,
    [diff]       DECIMAL (15, 2) NOT NULL,
    [jan08]      CHAR (1)        NOT NULL,
    [feb08]      CHAR (1)        NOT NULL,
    [mar08]      CHAR (1)        NOT NULL,
    [apr08]      CHAR (1)        NOT NULL
);

