CREATE TABLE [dbo].[BL_CLOSE_ACT] (
    [DASOF]        DATETIME      NULL,
    [KEY]          NVARCHAR (13) NULL,
    [TITLE]        NVARCHAR (12) NULL,
    [ACCOUNT_NAME] NVARCHAR (40) NULL,
    [OWNER_NAME]   NVARCHAR (40) NULL,
    [ADDRESS]      NVARCHAR (58) NULL,
    [BANK_CODE]    NVARCHAR (2)  NULL,
    [BANK_NAME]    NVARCHAR (20) NULL,
    [BRANCH_CODE]  NVARCHAR (3)  NULL,
    [BRANCH_NAME]  NVARCHAR (20) NULL,
    [CLOSE_DATE]   NVARCHAR (7)  NULL
);

