CREATE TABLE [dbo].[BUSINESS_TYPE] (
    [TYPE1_ID]         NVARCHAR (255) NULL,
    [RESEARCH_CODE_1]  NVARCHAR (255) NULL,
    [DESCRIPTION_1]    NVARCHAR (255) NULL,
    [DESCRIPTION_EN_1] NVARCHAR (255) NULL,
    [TYPE2_ID]         NVARCHAR (255) NULL,
    [RESEARCH_CODE_2]  NVARCHAR (255) NULL,
    [DESCRIPTION_2]    NVARCHAR (255) NULL,
    [DESCRIPTION_EN_2] NVARCHAR (255) NULL,
    [TYPE3_ID]         NVARCHAR (255) NULL,
    [RESEARCH_CODE_3]  NVARCHAR (255) NULL,
    [DESCRIPTION_3]    NVARCHAR (255) NULL,
    [DESCRIPTION_EN_3] NVARCHAR (255) NULL,
    [TYPE4_ID]         NVARCHAR (255) NULL,
    [RESEARCH_CODE_4]  FLOAT          NULL,
    [DESCRIPTION_4]    NVARCHAR (255) NULL,
    [DESCRIPTION_EN_4] NVARCHAR (255) NULL
);

