CREATE TABLE [dbo].[Customer_AOsme_Dtail_new_MS] (
    [ASOF]                  DATETIME       NULL,
    [CIF_NO]                FLOAT          NULL,
    [CIF_TYPE]              FLOAT          NULL,
    [CUST_NAME]             NVARCHAR (255) NULL,
    [DEPT_FLAG]             FLOAT          NULL,
    [DEPT_TRAN]             FLOAT          NULL,
    [Ctrl_Unit]             NVARCHAR (255) NULL,
    [DEPT_FLAG_T]           FLOAT          NULL,
    [DEPT_TRAN_T]           FLOAT          NULL,
    [Ctrl_Unit_old]         NVARCHAR (255) NULL,
    [BAY_RATING_TYPE]       NVARCHAR (255) NULL,
    [BAY_RATING]            FLOAT          NULL,
    [RISK_GRADE]            NVARCHAR (255) NULL,
    [CUST_SIZE]             NVARCHAR (255) NULL,
    [AO_SME]                FLOAT          NULL,
    [AO_SME_NEME]           NVARCHAR (255) NULL,
    [Prin_cash]             FLOAT          NULL,
    [Prin_noncash]          FLOAT          NULL,
    [Cash+NonCash]          FLOAT          NULL,
    [8up]                   NVARCHAR (255) NULL,
    [8up_name]              NVARCHAR (255) NULL,
    [Section]               FLOAT          NULL,
    [Section_name]          NVARCHAR (255) NULL,
    [กลุ่มลูกค้าธุรกิจ SME] NVARCHAR (255) NULL,
    [RegionNew_No]          FLOAT          NULL,
    [RegionNewTx]           NVARCHAR (255) NULL,
    [RegionType]            NVARCHAR (255) NULL,
    [RegionOld]             NVARCHAR (255) NULL,
    [Dept_size]             NVARCHAR (255) NULL,
    [Baysize]               NVARCHAR (255) NULL,
    [BrMaxprin]             FLOAT          NULL,
    [Reg_BrMax_or_CU]       NVARCHAR (255) NULL
);

