CREATE TABLE [dbo].[TMaster_2_Last_Register] (
    [Cif_No]        INT            NOT NULL,
    [T_Name]        NVARCHAR (150) NULL,
    [BOTID]         NVARCHAR (10)  NULL,
    [Count]         TINYINT        NULL,
    [DateRegiter]   INT            NULL,
    [RegiterDate]   TINYINT        NULL,
    [RegiterMonth]  TINYINT        NULL,
    [RegiterYear]   SMALLINT       NULL,
    [DateCutOff]    NVARCHAR (50)  NULL,
    [Id_BusType95]  INT            NULL,
    [Tax_Card]      NVARCHAR (30)  NULL,
    [Num_Promise]   NVARCHAR (50)  NULL,
    [Method_Tdr]    NVARCHAR (11)  NULL,
    [Balance]       MONEY          NULL,
    [PrinTdr]       MONEY          NULL,
    [AccruTdr]      MONEY          NULL,
    [SuspTdr]       MONEY          NULL,
    [Principal_D]   MONEY          NULL,
    [Accru_D]       MONEY          NULL,
    [Susp_D]        MONEY          NULL,
    [Loss]          MONEY          NULL,
    [Asset_Receive] MONEY          NULL,
    [Reser]         MONEY          NULL,
    [Tax1]          MONEY          NULL,
    [Tax2]          MONEY          NULL,
    [Tax3]          MONEY          NULL,
    [Other]         NVARCHAR (250) NULL,
    [TOTRE_PV]      MONEY          NULL,
    [TOTRE_CL]      MONEY          NULL,
    [Class_Before]  NVARCHAR (1)   NULL,
    [Class_After]   NVARCHAR (1)   NULL,
    [Id_Branch]     SMALLINT       NULL,
    [Branch]        NVARCHAR (70)  NULL,
    [Id_Province]   SMALLINT       NULL,
    [Province]      NVARCHAR (70)  NULL,
    [Id_Region]     SMALLINT       NULL,
    [Region]        NVARCHAR (30)  NULL,
    [Dept_Old]      INT            NULL,
    [Dept]          INT            NULL,
    [Dept_Tran]     INT            NULL,
    [Date_Report]   INT            NULL,
    [Ao_Old]        NVARCHAR (70)  NULL,
    [Asset_Re]      NVARCHAR (80)  NULL,
    [GroupDep]      NVARCHAR (30)  NULL,
    [CIF2]          INT            NULL,
    [Method1]       TINYINT        NULL,
    [Method2]       TINYINT        NULL,
    [Method3]       TINYINT        NULL,
    [Method4]       TINYINT        NULL,
    [Method5]       TINYINT        NULL,
    [Method6]       TINYINT        NULL,
    [Method7]       TINYINT        NULL,
    [Method8]       TINYINT        NULL,
    [Method9]       TINYINT        NULL
);

