CREATE UNIQUE NONCLUSTERED INDEX [IX_CATEGORY_TYPE_RECURSIVE]
    ON [CLASSIFY].[LINKED_CATEGORY_TYPE]([CATEGORY_TYPE_KEY] ASC, [LINK_TO_CATEGORY_TYPE_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

