CREATE NONCLUSTERED INDEX [CLS_LIMIT_PRODUCT_ID_KEY_CLS_WHEN_APPROVE]
    ON [dbo].[CLS_WHEN_APPROVE]([CLS_LIMIT_PRODUCT_ID_KEY] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

