CREATE NONCLUSTERED INDEX [_dta_index_Id_Branch_12_258099960__K8_K1_2]
    ON [dbo].[Id_Branch]([Id_Region] ASC, [Id_Branch] ASC)
    INCLUDE([Branch_T]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

