CREATE CLUSTERED INDEX [_dta_index_ANNALS_CREDIT_ACCOUNT_c_9_1609772792__K3]
    ON [dbo].[ANNALS_CREDIT_ACCOUNT]([CIF] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

