ALTER TABLE [EMPLOYEE].[USER_DATA]
	ADD CONSTRAINT [PK_USER_DATA]
	PRIMARY KEY CLUSTERED ([EMP_ID] ASC)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]