'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection
Imports System.Runtime.Serialization

Namespace webservice.linq.[stop]
	
	<System.Data.Linq.Mapping.DatabaseAttribute(Name:="STOP")>  _
	Partial Public Class StopLinqDataContext
		Inherits System.Data.Linq.DataContext
		
		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub InsertSTOP_CUSTOMER(instance As STOP_CUSTOMER)
    End Sub
    Partial Private Sub UpdateSTOP_CUSTOMER(instance As STOP_CUSTOMER)
    End Sub
    Partial Private Sub DeleteSTOP_CUSTOMER(instance As STOP_CUSTOMER)
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("STOPConnectionString").ConnectionString, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public ReadOnly Property STOP_CUSTOMERs() As System.Data.Linq.Table(Of STOP_CUSTOMER)
			Get
				Return Me.GetTable(Of STOP_CUSTOMER)
			End Get
		End Property
	End Class
	
	<Table(Name:="dbo.STOP_CUSTOMER"),  _
	 DataContract()>  _
	Partial Public Class STOP_CUSTOMER
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _CIF As Integer
		
		Private _AGING_DPD_IN As System.Nullable(Of Decimal)
		
		Private _AGING_DPD_C_IN As System.Nullable(Of Decimal)
		
		Private _AGING_DPD_O_IN As System.Nullable(Of Decimal)
		
		Private _AGING_H_IN As String
		
		Private _HAS_OTHER_CLASS_IN As System.Nullable(Of Char)
		
		Private _CLASS_H_IN As String
		
		Private _IS_TDR_IN As System.Nullable(Of Char)
		
		Private _OD_UTILIZE_IN As System.Nullable(Of Decimal)
		
		Private _JUDGEMENT_ID_IN As String
		
		Private _BUSINESS_SIM_FLAG_IN As System.Nullable(Of Char)
		
		Private _BUSINESS_CODE_IN As String
		
		Private _BUSINESS_DESC_IN As String
		
		Private _AGING_CRITERIA_IN As System.Nullable(Of Char)
		
		Private _CLASS_CRITERIA_IN As System.Nullable(Of Char)
		
		Private _TDR_CRITERIA_IN As System.Nullable(Of Char)
		
		Private _OD_UTILIZE_CRITERIA_IN As System.Nullable(Of Char)
		
		Private _JUDGEMENT_CRITERIA_IN As System.Nullable(Of Char)
		
		Private _BUSINESS_CRITERIA_IN As System.Nullable(Of Char)
		
		Private _DATE_IN As System.Nullable(Of Date)
		
		Private _UPDATE_ACTION_ID As String
		
		Private _UPDATE_ACTION_DATE As System.Nullable(Of Date)
		
		Private _UPDATE_ACTION_USER As String
		
		Private _UPDATE_PAY_ABILITY_ID As String
		
		Private _UPDATE_DEPT_RESOLVE_ID As String
		
		Private _UPDATE_TDR_DATE As System.Nullable(Of Date)
		
		Private _SEQUENCE As System.Nullable(Of Integer)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCIFChanging(value As Integer)
    End Sub
    Partial Private Sub OnCIFChanged()
    End Sub
    Partial Private Sub OnAGING_DPD_INChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnAGING_DPD_INChanged()
    End Sub
    Partial Private Sub OnAGING_DPD_C_INChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnAGING_DPD_C_INChanged()
    End Sub
    Partial Private Sub OnAGING_DPD_O_INChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnAGING_DPD_O_INChanged()
    End Sub
    Partial Private Sub OnAGING_H_INChanging(value As String)
    End Sub
    Partial Private Sub OnAGING_H_INChanged()
    End Sub
    Partial Private Sub OnHAS_OTHER_CLASS_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnHAS_OTHER_CLASS_INChanged()
    End Sub
    Partial Private Sub OnCLASS_H_INChanging(value As String)
    End Sub
    Partial Private Sub OnCLASS_H_INChanged()
    End Sub
    Partial Private Sub OnIS_TDR_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnIS_TDR_INChanged()
    End Sub
    Partial Private Sub OnOD_UTILIZE_INChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnOD_UTILIZE_INChanged()
    End Sub
    Partial Private Sub OnJUDGEMENT_ID_INChanging(value As String)
    End Sub
    Partial Private Sub OnJUDGEMENT_ID_INChanged()
    End Sub
    Partial Private Sub OnBUSINESS_SIM_FLAG_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnBUSINESS_SIM_FLAG_INChanged()
    End Sub
    Partial Private Sub OnBUSINESS_CODE_INChanging(value As String)
    End Sub
    Partial Private Sub OnBUSINESS_CODE_INChanged()
    End Sub
    Partial Private Sub OnBUSINESS_DESC_INChanging(value As String)
    End Sub
    Partial Private Sub OnBUSINESS_DESC_INChanged()
    End Sub
    Partial Private Sub OnAGING_CRITERIA_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnAGING_CRITERIA_INChanged()
    End Sub
    Partial Private Sub OnCLASS_CRITERIA_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnCLASS_CRITERIA_INChanged()
    End Sub
    Partial Private Sub OnTDR_CRITERIA_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnTDR_CRITERIA_INChanged()
    End Sub
    Partial Private Sub OnOD_UTILIZE_CRITERIA_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnOD_UTILIZE_CRITERIA_INChanged()
    End Sub
    Partial Private Sub OnJUDGEMENT_CRITERIA_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnJUDGEMENT_CRITERIA_INChanged()
    End Sub
    Partial Private Sub OnBUSINESS_CRITERIA_INChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnBUSINESS_CRITERIA_INChanged()
    End Sub
    Partial Private Sub OnDATE_INChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDATE_INChanged()
    End Sub
    Partial Private Sub OnUPDATE_ACTION_IDChanging(value As String)
    End Sub
    Partial Private Sub OnUPDATE_ACTION_IDChanged()
    End Sub
    Partial Private Sub OnUPDATE_ACTION_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUPDATE_ACTION_DATEChanged()
    End Sub
    Partial Private Sub OnUPDATE_ACTION_USERChanging(value As String)
    End Sub
    Partial Private Sub OnUPDATE_ACTION_USERChanged()
    End Sub
    Partial Private Sub OnUPDATE_PAY_ABILITY_IDChanging(value As String)
    End Sub
    Partial Private Sub OnUPDATE_PAY_ABILITY_IDChanged()
    End Sub
    Partial Private Sub OnUPDATE_DEPT_RESOLVE_IDChanging(value As String)
    End Sub
    Partial Private Sub OnUPDATE_DEPT_RESOLVE_IDChanged()
    End Sub
    Partial Private Sub OnUPDATE_TDR_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUPDATE_TDR_DATEChanged()
    End Sub
    Partial Private Sub OnSEQUENCEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSEQUENCEChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me.Initialize
		End Sub
		
		<Column(Storage:="_CIF", DbType:="Int NOT NULL", IsPrimaryKey:=true),  _
		 DataMember(Order:=1)>  _
		Public Property CIF() As Integer
			Get
				Return Me._CIF
			End Get
			Set
				If ((Me._CIF = value)  _
							= false) Then
					Me.OnCIFChanging(value)
					Me.SendPropertyChanging
					Me._CIF = value
					Me.SendPropertyChanged("CIF")
					Me.OnCIFChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_AGING_DPD_IN", DbType:="Money"),  _
		 DataMember(Order:=2)>  _
		Public Property AGING_DPD_IN() As System.Nullable(Of Decimal)
			Get
				Return Me._AGING_DPD_IN
			End Get
			Set
				If (Me._AGING_DPD_IN.Equals(value) = false) Then
					Me.OnAGING_DPD_INChanging(value)
					Me.SendPropertyChanging
					Me._AGING_DPD_IN = value
					Me.SendPropertyChanged("AGING_DPD_IN")
					Me.OnAGING_DPD_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_AGING_DPD_C_IN", DbType:="Money"),  _
		 DataMember(Order:=3)>  _
		Public Property AGING_DPD_C_IN() As System.Nullable(Of Decimal)
			Get
				Return Me._AGING_DPD_C_IN
			End Get
			Set
				If (Me._AGING_DPD_C_IN.Equals(value) = false) Then
					Me.OnAGING_DPD_C_INChanging(value)
					Me.SendPropertyChanging
					Me._AGING_DPD_C_IN = value
					Me.SendPropertyChanged("AGING_DPD_C_IN")
					Me.OnAGING_DPD_C_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_AGING_DPD_O_IN", DbType:="Money"),  _
		 DataMember(Order:=4)>  _
		Public Property AGING_DPD_O_IN() As System.Nullable(Of Decimal)
			Get
				Return Me._AGING_DPD_O_IN
			End Get
			Set
				If (Me._AGING_DPD_O_IN.Equals(value) = false) Then
					Me.OnAGING_DPD_O_INChanging(value)
					Me.SendPropertyChanging
					Me._AGING_DPD_O_IN = value
					Me.SendPropertyChanged("AGING_DPD_O_IN")
					Me.OnAGING_DPD_O_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_AGING_H_IN", DbType:="VarChar(12)"),  _
		 DataMember(Order:=5)>  _
		Public Property AGING_H_IN() As String
			Get
				Return Me._AGING_H_IN
			End Get
			Set
				If (String.Equals(Me._AGING_H_IN, value) = false) Then
					Me.OnAGING_H_INChanging(value)
					Me.SendPropertyChanging
					Me._AGING_H_IN = value
					Me.SendPropertyChanged("AGING_H_IN")
					Me.OnAGING_H_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_HAS_OTHER_CLASS_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=6)>  _
		Public Property HAS_OTHER_CLASS_IN() As System.Nullable(Of Char)
			Get
				Return Me._HAS_OTHER_CLASS_IN
			End Get
			Set
				If (Me._HAS_OTHER_CLASS_IN.Equals(value) = false) Then
					Me.OnHAS_OTHER_CLASS_INChanging(value)
					Me.SendPropertyChanging
					Me._HAS_OTHER_CLASS_IN = value
					Me.SendPropertyChanged("HAS_OTHER_CLASS_IN")
					Me.OnHAS_OTHER_CLASS_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_CLASS_H_IN", DbType:="VarChar(12)"),  _
		 DataMember(Order:=7)>  _
		Public Property CLASS_H_IN() As String
			Get
				Return Me._CLASS_H_IN
			End Get
			Set
				If (String.Equals(Me._CLASS_H_IN, value) = false) Then
					Me.OnCLASS_H_INChanging(value)
					Me.SendPropertyChanging
					Me._CLASS_H_IN = value
					Me.SendPropertyChanged("CLASS_H_IN")
					Me.OnCLASS_H_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_IS_TDR_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=8)>  _
		Public Property IS_TDR_IN() As System.Nullable(Of Char)
			Get
				Return Me._IS_TDR_IN
			End Get
			Set
				If (Me._IS_TDR_IN.Equals(value) = false) Then
					Me.OnIS_TDR_INChanging(value)
					Me.SendPropertyChanging
					Me._IS_TDR_IN = value
					Me.SendPropertyChanged("IS_TDR_IN")
					Me.OnIS_TDR_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_OD_UTILIZE_IN", DbType:="Money"),  _
		 DataMember(Order:=9)>  _
		Public Property OD_UTILIZE_IN() As System.Nullable(Of Decimal)
			Get
				Return Me._OD_UTILIZE_IN
			End Get
			Set
				If (Me._OD_UTILIZE_IN.Equals(value) = false) Then
					Me.OnOD_UTILIZE_INChanging(value)
					Me.SendPropertyChanging
					Me._OD_UTILIZE_IN = value
					Me.SendPropertyChanged("OD_UTILIZE_IN")
					Me.OnOD_UTILIZE_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_JUDGEMENT_ID_IN", DbType:="NVarChar(5)"),  _
		 DataMember(Order:=10)>  _
		Public Property JUDGEMENT_ID_IN() As String
			Get
				Return Me._JUDGEMENT_ID_IN
			End Get
			Set
				If (String.Equals(Me._JUDGEMENT_ID_IN, value) = false) Then
					Me.OnJUDGEMENT_ID_INChanging(value)
					Me.SendPropertyChanging
					Me._JUDGEMENT_ID_IN = value
					Me.SendPropertyChanged("JUDGEMENT_ID_IN")
					Me.OnJUDGEMENT_ID_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_BUSINESS_SIM_FLAG_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=11)>  _
		Public Property BUSINESS_SIM_FLAG_IN() As System.Nullable(Of Char)
			Get
				Return Me._BUSINESS_SIM_FLAG_IN
			End Get
			Set
				If (Me._BUSINESS_SIM_FLAG_IN.Equals(value) = false) Then
					Me.OnBUSINESS_SIM_FLAG_INChanging(value)
					Me.SendPropertyChanging
					Me._BUSINESS_SIM_FLAG_IN = value
					Me.SendPropertyChanged("BUSINESS_SIM_FLAG_IN")
					Me.OnBUSINESS_SIM_FLAG_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_BUSINESS_CODE_IN", DbType:="NVarChar(10)"),  _
		 DataMember(Order:=12)>  _
		Public Property BUSINESS_CODE_IN() As String
			Get
				Return Me._BUSINESS_CODE_IN
			End Get
			Set
				If (String.Equals(Me._BUSINESS_CODE_IN, value) = false) Then
					Me.OnBUSINESS_CODE_INChanging(value)
					Me.SendPropertyChanging
					Me._BUSINESS_CODE_IN = value
					Me.SendPropertyChanged("BUSINESS_CODE_IN")
					Me.OnBUSINESS_CODE_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_BUSINESS_DESC_IN", DbType:="NVarChar(255)"),  _
		 DataMember(Order:=13)>  _
		Public Property BUSINESS_DESC_IN() As String
			Get
				Return Me._BUSINESS_DESC_IN
			End Get
			Set
				If (String.Equals(Me._BUSINESS_DESC_IN, value) = false) Then
					Me.OnBUSINESS_DESC_INChanging(value)
					Me.SendPropertyChanging
					Me._BUSINESS_DESC_IN = value
					Me.SendPropertyChanged("BUSINESS_DESC_IN")
					Me.OnBUSINESS_DESC_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_AGING_CRITERIA_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=14)>  _
		Public Property AGING_CRITERIA_IN() As System.Nullable(Of Char)
			Get
				Return Me._AGING_CRITERIA_IN
			End Get
			Set
				If (Me._AGING_CRITERIA_IN.Equals(value) = false) Then
					Me.OnAGING_CRITERIA_INChanging(value)
					Me.SendPropertyChanging
					Me._AGING_CRITERIA_IN = value
					Me.SendPropertyChanged("AGING_CRITERIA_IN")
					Me.OnAGING_CRITERIA_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_CLASS_CRITERIA_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=15)>  _
		Public Property CLASS_CRITERIA_IN() As System.Nullable(Of Char)
			Get
				Return Me._CLASS_CRITERIA_IN
			End Get
			Set
				If (Me._CLASS_CRITERIA_IN.Equals(value) = false) Then
					Me.OnCLASS_CRITERIA_INChanging(value)
					Me.SendPropertyChanging
					Me._CLASS_CRITERIA_IN = value
					Me.SendPropertyChanged("CLASS_CRITERIA_IN")
					Me.OnCLASS_CRITERIA_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_TDR_CRITERIA_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=16)>  _
		Public Property TDR_CRITERIA_IN() As System.Nullable(Of Char)
			Get
				Return Me._TDR_CRITERIA_IN
			End Get
			Set
				If (Me._TDR_CRITERIA_IN.Equals(value) = false) Then
					Me.OnTDR_CRITERIA_INChanging(value)
					Me.SendPropertyChanging
					Me._TDR_CRITERIA_IN = value
					Me.SendPropertyChanged("TDR_CRITERIA_IN")
					Me.OnTDR_CRITERIA_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_OD_UTILIZE_CRITERIA_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=17)>  _
		Public Property OD_UTILIZE_CRITERIA_IN() As System.Nullable(Of Char)
			Get
				Return Me._OD_UTILIZE_CRITERIA_IN
			End Get
			Set
				If (Me._OD_UTILIZE_CRITERIA_IN.Equals(value) = false) Then
					Me.OnOD_UTILIZE_CRITERIA_INChanging(value)
					Me.SendPropertyChanging
					Me._OD_UTILIZE_CRITERIA_IN = value
					Me.SendPropertyChanged("OD_UTILIZE_CRITERIA_IN")
					Me.OnOD_UTILIZE_CRITERIA_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_JUDGEMENT_CRITERIA_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=18)>  _
		Public Property JUDGEMENT_CRITERIA_IN() As System.Nullable(Of Char)
			Get
				Return Me._JUDGEMENT_CRITERIA_IN
			End Get
			Set
				If (Me._JUDGEMENT_CRITERIA_IN.Equals(value) = false) Then
					Me.OnJUDGEMENT_CRITERIA_INChanging(value)
					Me.SendPropertyChanging
					Me._JUDGEMENT_CRITERIA_IN = value
					Me.SendPropertyChanged("JUDGEMENT_CRITERIA_IN")
					Me.OnJUDGEMENT_CRITERIA_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_BUSINESS_CRITERIA_IN", DbType:="Char(1)"),  _
		 DataMember(Order:=19)>  _
		Public Property BUSINESS_CRITERIA_IN() As System.Nullable(Of Char)
			Get
				Return Me._BUSINESS_CRITERIA_IN
			End Get
			Set
				If (Me._BUSINESS_CRITERIA_IN.Equals(value) = false) Then
					Me.OnBUSINESS_CRITERIA_INChanging(value)
					Me.SendPropertyChanging
					Me._BUSINESS_CRITERIA_IN = value
					Me.SendPropertyChanged("BUSINESS_CRITERIA_IN")
					Me.OnBUSINESS_CRITERIA_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_DATE_IN", DbType:="DateTime"),  _
		 DataMember(Order:=20)>  _
		Public Property DATE_IN() As System.Nullable(Of Date)
			Get
				Return Me._DATE_IN
			End Get
			Set
				If (Me._DATE_IN.Equals(value) = false) Then
					Me.OnDATE_INChanging(value)
					Me.SendPropertyChanging
					Me._DATE_IN = value
					Me.SendPropertyChanged("DATE_IN")
					Me.OnDATE_INChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_UPDATE_ACTION_ID", DbType:="NVarChar(2)"),  _
		 DataMember(Order:=21)>  _
		Public Property UPDATE_ACTION_ID() As String
			Get
				Return Me._UPDATE_ACTION_ID
			End Get
			Set
				If (String.Equals(Me._UPDATE_ACTION_ID, value) = false) Then
					Me.OnUPDATE_ACTION_IDChanging(value)
					Me.SendPropertyChanging
					Me._UPDATE_ACTION_ID = value
					Me.SendPropertyChanged("UPDATE_ACTION_ID")
					Me.OnUPDATE_ACTION_IDChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_UPDATE_ACTION_DATE", DbType:="DateTime"),  _
		 DataMember(Order:=22)>  _
		Public Property UPDATE_ACTION_DATE() As System.Nullable(Of Date)
			Get
				Return Me._UPDATE_ACTION_DATE
			End Get
			Set
				If (Me._UPDATE_ACTION_DATE.Equals(value) = false) Then
					Me.OnUPDATE_ACTION_DATEChanging(value)
					Me.SendPropertyChanging
					Me._UPDATE_ACTION_DATE = value
					Me.SendPropertyChanged("UPDATE_ACTION_DATE")
					Me.OnUPDATE_ACTION_DATEChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_UPDATE_ACTION_USER", DbType:="NVarChar(10)"),  _
		 DataMember(Order:=23)>  _
		Public Property UPDATE_ACTION_USER() As String
			Get
				Return Me._UPDATE_ACTION_USER
			End Get
			Set
				If (String.Equals(Me._UPDATE_ACTION_USER, value) = false) Then
					Me.OnUPDATE_ACTION_USERChanging(value)
					Me.SendPropertyChanging
					Me._UPDATE_ACTION_USER = value
					Me.SendPropertyChanged("UPDATE_ACTION_USER")
					Me.OnUPDATE_ACTION_USERChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_UPDATE_PAY_ABILITY_ID", DbType:="NVarChar(2)"),  _
		 DataMember(Order:=24)>  _
		Public Property UPDATE_PAY_ABILITY_ID() As String
			Get
				Return Me._UPDATE_PAY_ABILITY_ID
			End Get
			Set
				If (String.Equals(Me._UPDATE_PAY_ABILITY_ID, value) = false) Then
					Me.OnUPDATE_PAY_ABILITY_IDChanging(value)
					Me.SendPropertyChanging
					Me._UPDATE_PAY_ABILITY_ID = value
					Me.SendPropertyChanged("UPDATE_PAY_ABILITY_ID")
					Me.OnUPDATE_PAY_ABILITY_IDChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_UPDATE_DEPT_RESOLVE_ID", DbType:="NVarChar(2)"),  _
		 DataMember(Order:=25)>  _
		Public Property UPDATE_DEPT_RESOLVE_ID() As String
			Get
				Return Me._UPDATE_DEPT_RESOLVE_ID
			End Get
			Set
				If (String.Equals(Me._UPDATE_DEPT_RESOLVE_ID, value) = false) Then
					Me.OnUPDATE_DEPT_RESOLVE_IDChanging(value)
					Me.SendPropertyChanging
					Me._UPDATE_DEPT_RESOLVE_ID = value
					Me.SendPropertyChanged("UPDATE_DEPT_RESOLVE_ID")
					Me.OnUPDATE_DEPT_RESOLVE_IDChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_UPDATE_TDR_DATE", DbType:="DateTime"),  _
		 DataMember(Order:=26)>  _
		Public Property UPDATE_TDR_DATE() As System.Nullable(Of Date)
			Get
				Return Me._UPDATE_TDR_DATE
			End Get
			Set
				If (Me._UPDATE_TDR_DATE.Equals(value) = false) Then
					Me.OnUPDATE_TDR_DATEChanging(value)
					Me.SendPropertyChanging
					Me._UPDATE_TDR_DATE = value
					Me.SendPropertyChanged("UPDATE_TDR_DATE")
					Me.OnUPDATE_TDR_DATEChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_SEQUENCE", DbType:="Int"),  _
		 DataMember(Order:=27)>  _
		Public Property SEQUENCE() As System.Nullable(Of Integer)
			Get
				Return Me._SEQUENCE
			End Get
			Set
				If (Me._SEQUENCE.Equals(value) = false) Then
					Me.OnSEQUENCEChanging(value)
					Me.SendPropertyChanging
					Me._SEQUENCE = value
					Me.SendPropertyChanged("SEQUENCE")
					Me.OnSEQUENCEChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub Initialize()
			OnCreated
		End Sub
		
		<OnDeserializing(),  _
		 System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)>  _
		Public Sub OnDeserializing(ByVal context As StreamingContext)
			Me.Initialize
		End Sub
	End Class
End Namespace
