CREATE TABLE [CLASSIFY].[CATE_AND_EMP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY_KEY] [int] NOT NULL,
	[EMP_ID] [varchar](10) NOT NULL,
	[HEAD_PRIORITY] [int] NULL,
	[DEL_FLAG] [bit] NULL)
