CREATE TABLE [CLASSIFY].[CATEGORY]
(
	[CATEGORY_KEY] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY_DESC] [varchar](100) NULL,
	[CATEGORY_DESC_TH] [nvarchar](100) NULL,
	[CATEGORY_VALUE] [nvarchar](20) NULL,
	[CATEGORY_TYPE_KEY] [int] NULL,
	[PRIORITY] [int] NULL,
	[DEL_FLAG] [bit] NULL
)
