CREATE TABLE [CLASSIFY].[CATE_LINK_CATE]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY_KEY] [int] NOT NULL,
	[LINK_TO_CATEGORY_KEY] [int] NOT NULL,
	[LINKED_TYPE_KEY] [int] NOT NULL,
	[DEL_FLAG] [bit] NULL
)
