-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[P_CLS_SELECT_BY_CA]
	-- Add the parameters for the stored procedure here
	@leader1CAOldId nvarchar(10)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT *
	INTO #TEMP_CLS
	FROM (
		select distinct LIMIT_NO_ROOT AS LIMIT_NO
				, 'R' AS LIMIT_TYPE
				, LIMIT_ROOT_STATUS AS LIMIT_STATUS
				, CASE WHEN LIMIT_NO_ROOT IS NULL THEN 'DUMMY' ELSE NULL END AS PRODUCT_NAME
				, CIF_LIST_ROOT AS CIF_LIST
				, LIMIT_AMOUNT_ROOT_THB AS LIMIT_AMOUNT
				, LIMIT_CHANGE_ROOT_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_ROOT
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId

		union 

		select distinct LIMIT_NO_L1
				, 'L'
				, LIMIT_L1_STATUS
				, NULL
				, NULL
				, LIMIT_AMOUNT_L1_THB
				, LIMIT_CHANGE_L1_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_ROOT
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
			and LIMIT_NO_L1 is not null

		union 

		select distinct LIMIT_NO_L2
				, 'L'
				, LIMIT_L2_STATUS
				, NULL
				, NULL
				, LIMIT_AMOUNT_L2_THB
				, LIMIT_CHANGE_L2_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_L1
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
			and LIMIT_NO_L2 is not null

		union 

		select distinct LIMIT_NO_L3
				, 'L'
				, LIMIT_L3_STATUS
				, NULL
				, NULL
				, LIMIT_AMOUNT_L3_THB
				, LIMIT_CHANGE_L3_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_L2
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
			and LIMIT_NO_L3 is not null

		union 

		select distinct LIMIT_NO_L4
				, 'L'
				, LIMIT_L4_STATUS
				, NULL
				, NULL
				, LIMIT_AMOUNT_L4_THB
				, LIMIT_CHANGE_L4_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_L3
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
			and LIMIT_NO_L4 is not null

		union 

		select distinct LIMIT_NO_L5
				, 'L'
				, LIMIT_L5_STATUS
				, NULL
				, NULL
				, LIMIT_AMOUNT_L5_THB
				, LIMIT_CHANGE_L5_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_L4
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
			and LIMIT_NO_L5 is not null

		union 

		select distinct LIMIT_NO_L6
				, 'L'
				, LIMIT_L6_STATUS
				, NULL
				, NULL
				, LIMIT_AMOUNT_L6_THB
				, LIMIT_CHANGE_L6_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_L5
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
			and LIMIT_NO_L6 is not null

		union 

		select distinct LIMIT_NO_L7
				, 'L'
				, LIMIT_L7_STATUS
				, NULL
				, NULL
				, LIMIT_AMOUNT_L7_THB
				, LIMIT_CHANGE_L7_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_L6
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
			and LIMIT_NO_L7 is not null

		union 

		select distinct LIMIT_NO_L8
				, 'L'
				, LIMIT_L8_STATUS
				, NULL
				, NULL
				, LIMIT_AMOUNT_L8_THB
				, LIMIT_CHANGE_L8_THB AS LIMIT_CHANGE
				, NULL AS LIMIT_CHANGE_DATE
				, LIMIT_NO_L7
				,NULL AS LIMIT_PRODUCT_EFFECT_DATE
				,NULL AS LIMIT_PRODUCT_EXPIRE_DATE
				,NULL AS LIMIT_PRODUCT_CA_NO
				,NULL AS LIMIT_PRODUCT_CA_DATE
				,NULL AS LIMIT_PRODUCT_APPV_DATE
				,NULL AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,NULL AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,NULL AS MAPPING_STATUS
				,NULL AS ACCOUNT_NO
				,NULL AS ID_KEY
		  FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
			and LIMIT_NO_L8 is not null

		union 

		select distinct LIMIT_NO_PRODUCT
				, 'P'
				, LIMIT_PRODUCT_STATUS
				, PRODUCT_NAME
				, CIF_LIST_PRODUCT
				, LIMIT_AMOUNT_PRODUCT_THB
				, LIMIT_CHANGE_PRODUCT_THB AS LIMIT_CHANGE
				, LIMIT_CHANGE_DATE
				,CASE 
					WHEN LIMIT_NO_L8 IS NULL AND LIMIT_NO_L7 IS NULL AND LIMIT_NO_L6 IS NULL
						AND LIMIT_NO_L5 IS NULL AND LIMIT_NO_L4 IS NULL AND LIMIT_NO_L3 IS NULL
						AND LIMIT_NO_L2 IS NULL AND LIMIT_NO_L1 IS NULL
						THEN LIMIT_NO_ROOT
					WHEN LIMIT_NO_L8 IS NULL AND LIMIT_NO_L7 IS NULL AND LIMIT_NO_L6 IS NULL
						AND LIMIT_NO_L5 IS NULL AND LIMIT_NO_L4 IS NULL AND LIMIT_NO_L3 IS NULL
						AND LIMIT_NO_L2 IS NULL
						THEN LIMIT_NO_L1
					WHEN LIMIT_NO_L8 IS NULL AND LIMIT_NO_L7 IS NULL AND LIMIT_NO_L6 IS NULL
						AND LIMIT_NO_L5 IS NULL AND LIMIT_NO_L4 IS NULL AND LIMIT_NO_L3 IS NULL
						THEN LIMIT_NO_L2
					WHEN LIMIT_NO_L8 IS NULL AND LIMIT_NO_L7 IS NULL AND LIMIT_NO_L6 IS NULL
						AND LIMIT_NO_L5 IS NULL AND LIMIT_NO_L4 IS NULL
						THEN LIMIT_NO_L3
					WHEN LIMIT_NO_L8 IS NULL AND LIMIT_NO_L7 IS NULL AND LIMIT_NO_L6 IS NULL
						AND LIMIT_NO_L5 IS NULL
						THEN LIMIT_NO_L4
					WHEN LIMIT_NO_L8 IS NULL AND LIMIT_NO_L7 IS NULL AND LIMIT_NO_L6 IS NULL
						THEN LIMIT_NO_L5
					WHEN LIMIT_NO_L8 IS NULL AND LIMIT_NO_L7 IS NULL
						THEN LIMIT_NO_L6
					WHEN LIMIT_NO_L8 IS NULL
						THEN LIMIT_NO_L7
					ELSE LIMIT_NO_L8
				END
				, LIMIT_PRODUCT_EFFECT_DATE
				, LIMIT_PRODUCT_EXPIRE_DATE
				,LIMIT_PRODUCT_CA_NO
				,LIMIT_PRODUCT_CA_DATE
				,LIMIT_PRODUCT_APPV_DATE
				,LIMIT_PRODUCT_APPV_AUTH_UNIT
				,LIMIT_PRODUCT_PREVIOUS_CA_NO
				,MAPPING_STATUS
				,ACCOUNT_NO
				,ID_KEY

			FROM [CLS_WHEN_APPROVE]
		WHERE LEADER1_CA_OLD_ID = @leader1CAOldId
	) CLS;

	WITH CTE_CLS AS (	SELECT CLS1.LIMIT_NO
								,CLS1.LIMIT_TYPE
								,CLS1.LIMIT_STATUS
								,CLS1.PRODUCT_NAME
								,CLS1.CIF_LIST
								,CLS1.LIMIT_AMOUNT
								,CLS1.LIMIT_CHANGE
								,CLS1.LIMIT_CHANGE_DATE
								,CLS1.LIMIT_NO_ROOT
								,CLS1.LIMIT_PRODUCT_EFFECT_DATE
								,CLS1.LIMIT_PRODUCT_EXPIRE_DATE
								,CONVERT(NVARCHAR(MAX),CLS1.LIMIT_NO_ROOT) AS PRIORITY
								,CLS1.LIMIT_PRODUCT_CA_NO
								,CLS1.LIMIT_PRODUCT_CA_DATE
								,CLS1.LIMIT_PRODUCT_APPV_DATE
								,CLS1.LIMIT_PRODUCT_APPV_AUTH_UNIT
								,CLS1.LIMIT_PRODUCT_PREVIOUS_CA_NO
								,CLS1.MAPPING_STATUS
								,CLS1.ACCOUNT_NO
								,CLS1.ID_KEY
						FROM #TEMP_CLS AS CLS1
						WHERE CLS1.LIMIT_TYPE = 'R'
						
						UNION ALL

						SELECT CLS2.LIMIT_NO
								,CLS2.LIMIT_TYPE
								,CLS2.LIMIT_STATUS
								,CLS2.PRODUCT_NAME
								,CLS2.CIF_LIST
								,CLS2.LIMIT_AMOUNT
								,CLS2.LIMIT_CHANGE
								,CLS2.LIMIT_CHANGE_DATE
								,CLS2.LIMIT_NO_ROOT
								,CLS2.LIMIT_PRODUCT_EFFECT_DATE
								,CLS2.LIMIT_PRODUCT_EXPIRE_DATE
								,CTE_CLS2.PRIORITY +','+ CONVERT(NVARCHAR(18),CLS2.LIMIT_NO)
								,CLS2.LIMIT_PRODUCT_CA_NO
								,CLS2.LIMIT_PRODUCT_CA_DATE
								,CLS2.LIMIT_PRODUCT_APPV_DATE
								,CLS2.LIMIT_PRODUCT_APPV_AUTH_UNIT
								,CLS2.LIMIT_PRODUCT_PREVIOUS_CA_NO
								,CLS2.MAPPING_STATUS
								,CLS2.ACCOUNT_NO
								,CLS2.ID_KEY
						FROM #TEMP_CLS AS CLS2 INNER JOIN 
							CTE_CLS AS CTE_CLS2
							ON CLS2.LIMIT_NO_ROOT = CTE_CLS2.LIMIT_NO 
						WHERE CLS2.LIMIT_TYPE <> 'R'
					)

	SELECT DISTINCT CTE_CLS.LIMIT_NO
		,CTE_CLS.LIMIT_TYPE
		,CTE_CLS.LIMIT_STATUS
		,CTE_CLS.PRODUCT_NAME
		,CTE_CLS.CIF_LIST
		,CTE_CLS.LIMIT_AMOUNT
		,CTE_CLS.LIMIT_CHANGE
		,CTE_CLS.LIMIT_CHANGE_DATE
		,CTE_CLS.LIMIT_NO_ROOT
		,CTE_CLS.LIMIT_PRODUCT_EFFECT_DATE
		,CTE_CLS.LIMIT_PRODUCT_EXPIRE_DATE
		,CTE_CLS.PRIORITY
		,CTE_CLS.LIMIT_PRODUCT_CA_NO
		,CTE_CLS.LIMIT_PRODUCT_CA_DATE
		,CTE_CLS.LIMIT_PRODUCT_APPV_DATE
		,CTE_CLS.LIMIT_PRODUCT_APPV_AUTH_UNIT
		,CTE_CLS.LIMIT_PRODUCT_PREVIOUS_CA_NO
		,CTE_CLS.MAPPING_STATUS
		,CTE_CLS.ACCOUNT_NO
		,CTE_CLS.ID_KEY
	FROM CTE_CLS
	ORDER BY PRIORITY

	DROP TABLE #TEMP_CLS

END
