
CREATE  PROCEDURE [dbo].[ANNALS_CREDIT_FLOOD_TABLE_SELECT]
		@RECORD_TYPE nvarchar(20)
 AS 
 BEGIN 
	SELECT  * FROM [dbo].[ANNALS_CREDIT_FLOOD_TABLE]
   	WHERE RECORD_TYPE=@RECORD_TYPE
  END 




