
CREATE PROCEDURE [dbo].[ANNALS_NCB_CUSTYPE_SELECT]

AS 
BEGIN 
	
	SELECT     CATEGORY_KEY as CUS_TYPE_ID, CATEGORY_DESC_TH as CUS_TYPE
	FROM         CLASSIFY.CATEGORY
	WHERE     (CATEGORY_TYPE_KEY = 11) AND (DEL_FLAG = 0)
	ORDER BY PRIORITY

END

