-- =============================================
-- Author:		Prakit
-- Create date: 20 Jun 2008
-- Update date: 20 Feb 2009
-- Description:	CUSTOMER_SME_SELECT_BY_CIF
-- =============================================
CREATE PROCEDURE [dbo].[SP_CUSTOMER_SME_SELECT_BY_CIF] 
	-- Add the parameters for the stored procedure here
	@CIF int

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
--	SELECT     dbo.CUSTOMER_SME.CIF, ISNULL(dbo.CUSTOMER.CUS_TITLE, N'') + ISNULL(dbo.CUSTOMER.CUS_FIRST, N'') 
--                      + N'  ' + ISNULL(dbo.CUSTOMER.CUS_LAST, N'') AS CUSTOMER_NAME, dbo.CUSTOMER_SME.GROUP_ID, dbo.CUSTOMER_SME.CM_CODE, 
--                      ISNULL(CM_TITLE.TITLE_NAME, N'') + ISNULL(CM.EMPNAME, N'') + N' ' + ISNULL(CM.EMPSURNAME, N'') AS CM_NAME, 
--                      dbo.CUSTOMER_SME.OLD_CM_CODE, ISNULL(OLD_CM_TITLE.TITLE_NAME, N'') + ISNULL(OLD_CM.EMPNAME, N'') 
--                      + N' ' + ISNULL(OLD_CM.EMPSURNAME, N'') AS OLD_CM_NAME, dbo.CUSTOMER_SME.BRANCH_ID, dbo.Id_Branch.Branch_T AS BRANCH_NAME, 
--                      ISNULL(dbo.CUSTOMER_SME_GROUP.GROUP_SIZE_ID, 1) AS GROUP_SIZE_ID, ISNULL(dbo.CUSTOMER_SME.JUDGEMENT_ID, N'000') 
--                      AS JUDGEMENT_ID, dbo.CUSTOMER_SME.BUSI_RISK1_ID, BUSI_RISK1.TYPE3_DETAIL AS BUSI_RISK1_DETAIL, 
--                      dbo.CUSTOMER_SME.BUSI_RISK2_ID, BUSI_RISK2.TYPE3_DETAIL AS BUSI_RISK2_DETAIL, dbo.CUSTOMER_SME.BUSI_RISK3_ID, 
--                      BUSI_RISK3.TYPE3_DETAIL AS BUSI_RISK3_DETAIL, dbo.CUSTOMER_SME.UPDATE_BY, ISNULL(UPDATE_BY_TITLE.TITLE_NAME, N'') 
--                      + ISNULL(UPDATE_BY.EMPNAME, N'') + N' ' + ISNULL(UPDATE_BY.EMPSURNAME, N'') AS UPDATE_BY_NAME, 
--                      dbo.CUSTOMER_SME.UPDATE_DATE
--	FROM         dbo.CUSTOMER RIGHT OUTER JOIN
--                      dbo.TB_EMPLOYEE AS UPDATE_BY INNER JOIN
--                      dbo.TB_TITLE AS UPDATE_BY_TITLE ON UPDATE_BY.TITLE_CODE = UPDATE_BY_TITLE.TITLE_CODE RIGHT OUTER JOIN
--                      dbo.CUSTOMER_SME ON UPDATE_BY.EMP_ID = dbo.CUSTOMER_SME.UPDATE_BY LEFT OUTER JOIN
--                      dbo.BUSI_TYPE3 AS BUSI_RISK3 ON dbo.CUSTOMER_SME.BUSI_RISK3_ID = BUSI_RISK3.TYPE3_ID LEFT OUTER JOIN
--                      dbo.BUSI_TYPE3 AS BUSI_RISK2 ON dbo.CUSTOMER_SME.BUSI_RISK2_ID = BUSI_RISK2.TYPE3_ID LEFT OUTER JOIN
--                      dbo.BUSI_TYPE3 AS BUSI_RISK1 ON dbo.CUSTOMER_SME.BUSI_RISK1_ID = BUSI_RISK1.TYPE3_ID LEFT OUTER JOIN
--                      dbo.ANNALS_JUDGEMENT ON CONVERT(int, ISNULL(dbo.CUSTOMER_SME.JUDGEMENT_ID, N'000')) = CONVERT(int, dbo.ANNALS_JUDGEMENT.ID) 
--                      LEFT OUTER JOIN
--                      dbo.Id_Branch ON dbo.CUSTOMER_SME.BRANCH_ID = dbo.Id_Branch.Id_Branch LEFT OUTER JOIN
--                      dbo.TB_EMPLOYEE AS OLD_CM INNER JOIN
--                      dbo.TB_TITLE AS OLD_CM_TITLE ON OLD_CM.TITLE_CODE = OLD_CM_TITLE.TITLE_CODE ON 
--                      dbo.CUSTOMER_SME.OLD_CM_CODE = OLD_CM.EMP_ID ON dbo.CUSTOMER.CIF = dbo.CUSTOMER_SME.CIF LEFT OUTER JOIN
--                      dbo.TB_TITLE AS CM_TITLE INNER JOIN
--                      dbo.TB_EMPLOYEE AS CM ON CM_TITLE.TITLE_CODE = CM.TITLE_CODE ON dbo.CUSTOMER_SME.CM_CODE = CM.EMP_ID LEFT OUTER JOIN
--                      dbo.GROUP_SIZE INNER JOIN
--                      dbo.CUSTOMER_SME_GROUP ON dbo.GROUP_SIZE.GROUP_SIZE_ID = ISNULL(dbo.CUSTOMER_SME_GROUP.GROUP_SIZE_ID, 1) ON 
--                      dbo.CUSTOMER_SME.GROUP_ID = dbo.CUSTOMER_SME_GROUP.GROUP_ID
--	WHERE     (dbo.CUSTOMER_SME.CIF = @CIF)

	SELECT CIF, CUSTOMER_NAME, GROUP_ID, CM_CODE, CM_NAME, OLD_CM_CODE, OLD_CM_NAME, BRANCH_ID, BRANCH_NAME, GROUP_SIZE_ID, JUDGEMENT_ID
			, BUSI_RISK1_ID, BUSI_RISK1_DETAIL, BUSI_RISK2_ID, BUSI_RISK2_DETAIL, BUSI_RISK3_ID, BUSI_RISK3_DETAIL
			,BUSINESS_DESTINATION_ID
			,BUSINESS_DESTINATION_DESC
			,EXPORT_WEIGHT
			,LOCAL_WEIGHT
			,STATUS_ID
			,SIZE_ID
			,UPDATE_BY, UPDATE_BY_NAME, UPDATE_DATE
			,RATING_TYPE_KEY, RATING_KEY, RATING_UPDATE_DATE
			,NEXT_REVIEW_DATE
	FROM CUSTOMER_SME00_ALL_STATUS
	WHERE CIF=@CIF
END










