-- =============================================
-- AUTHOR:		<AUTHOR,,NAME>
-- CREATE DATE: <CREATE DATE,,>
-- DESCRIPTION:	<DESCRIPTION,,>
-- =============================================
CREATE PROCEDURE [dbo].[CA_PIVOT_FOR_PRODUCT] 
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@VALUE_FIELD_NAME VARCHAR(30)
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	SET NOCOUNT ON;

    -- INSERT STATEMENTS FOR PROCEDURE HERE
	DECLARE @PRODUCTLIST VARCHAR(MAX)


	SELECT @PRODUCTLIST = COALESCE_GL_TYPE
	FROM BAY01.DBO.COALESCE_GL_TYPE()


--	SELECT @PRODUCTLIST


	EXEC ('SELECT [CA_NO_ID]
			,[CA_CREATE_DATE]
			,[REFERENCE]
			,[REFERENCE_DATE]
			,[APPROVE_DATE]
			,[REJECT_DATE]
			,[REJECT_REASON]
			,[LAST_PROCESS]
			,[LAST_PROCESS_ID]
			,[LAST_PROCESS_GROUP]
			,[LAST_PROCESS_DATE]
			,[EMP_ID]
			,[LEVEL_ID]
			,[LEVEL_NAME]
			,'+ @PRODUCTLIST + '
		FROM (SELECT [CA_NO_ID]
				,[CA_CREATE_DATE]
				,[REFERENCE]
				,[REFERENCE_DATE]
				,[APPROVE_DATE]
				,[REJECT_DATE]
				,[REJECT_REASON]
				,[LAST_PROCESS]
				,[LAST_PROCESS_ID]
				,[LAST_PROCESS_GROUP]
				,[LAST_PROCESS_DATE]
				,[EMP_ID]
				,[LEVEL_ID]
				,[LEVEL_NAME]
				,[DECB_RD]
				,' + @VALUE_FIELD_NAME + ' FROM BAY01.DBO.REPORT07_SUMMARY) AS T        
		PIVOT
		(
			SUM(' + @VALUE_FIELD_NAME + ')
			FOR DECB_RD IN (' + @PRODUCTLIST + ')
		)AS PVT
		ORDER BY CA_NO_ID'
	)


--	EXEC ('SELECT CA_NO_ID,'+ @PRODUCTLIST + '
--		FROM (SELECT CA_NO_ID,DECB_RD,' + @VALUE_FIELD_NAME + ' FROM BAY01.DBO.REPORT07_SUMMARY) AS T
--		PIVOT
--		(
--			COUNT(' + @VALUE_FIELD_NAME + ')
--			FOR DECB_RD IN (' + @PRODUCTLIST + ')
--		)AS PVT
--		ORDER BY CA_NO_ID'
--	)

END
