
	CREATE PROCEDURE [dbo].[ANNALS_COVENANT_UPDATE]
		@IDEN int, 
		@CIF int, 
		@COVENANT_TYPE_ID nvarchar(1), 
		@DETAIL nvarchar(500), 
		@CREATE_DATE datetime, 
		@DEADLINE_DATE datetime, 
		@COVENANT_ACTION_ID nvarchar(2), 
		@REMARK nvarchar(500), 
		@ACTION_DATE datetime, 
	   	@USER_ID nchar(10), 
		@USER_UPDATE_DATE datetime, 
		@ID nvarchar(10),
		@COVENANT_DETAIL_ID nvarchar(3),
	    @NEXT_COVENANT_ACTION_ID nvarchar(2), 
		@NEXT_ACTION_DATE datetime 
	
AS 
BEGIN 
	UPDATE ANNALS_COVENANT
	SET
		CIF=@CIF,
		COVENANT_TYPE_ID=@COVENANT_TYPE_ID,
		DETAIL=@DETAIL,
		DEADLINE_DATE=@DEADLINE_DATE,
		COVENANT_ACTION_ID=@COVENANT_ACTION_ID,
		REMARK=@REMARK,
		ACTION_DATE=@ACTION_DATE,
		NEXT_COVENANT_ACTION_ID=@NEXT_COVENANT_ACTION_ID,
		NEXT_ACTION_DATE=@NEXT_ACTION_DATE,
		USER_ID=@USER_ID,
		USER_UPDATE_DATE=getdate(),
		ID=@ID,
		COVENANT_DETAIL_ID=@COVENANT_DETAIL_ID
	where IDEN=@IDEN
END 
BEGIN
	IF @COVENANT_ACTION_ID <> '4'
	BEGIN
		UPDATE ANNALS_CREDIT SET COVENANT_FLAG = 1 WHERE ID=@ID
	END
END
SET ANSI_NULLS ON




