-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_CA_IN_PROCESS_LEVEL_DROPDOWN]
	-- Add the parameters for the stored procedure here
	@EMP_ID nvarchar(10),
	@SINGLE varchar(3)

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    -- Insert statements for procedure here
	IF @SINGLE = 'yes'
		BEGIN
			SELECT LEVEL_ID, LEVEL_NAME + ' [' + CONVERT(VARCHAR,COUNT(OLD_ID)) +']' AS LEVEL_NAME
			FROM	REPORT67_07_IN_PROCESS AS R67
			WHERE	SEQ = 1 AND EMP_ID = @EMP_ID
			GROUP BY LEVEL_ID, LEVEL_NAME
			ORDER BY LEVEL_ID
		END
	ELSE
		BEGIN
			SELECT LEVEL_ID,LEVEL_NAME
			FROM (
					SELECT LEVEL_ID, LEVEL_NAME + ' [' + CONVERT(VARCHAR,COUNT(OLD_ID)) +']' AS LEVEL_NAME
					FROM	REPORT67_07_IN_PROCESS AS R67
					WHERE	SEQ = 1
					GROUP BY LEVEL_ID, LEVEL_NAME
			) AS CA INNER JOIN (
					SELECT CLASSIFY.V_002_CATEGORY_MAP_TYPE.CATEGORY_KEY 
					FROM  CLASSIFY.V_001_EXPANDED_CATEGORY_TYPE_1 INNER JOIN
								   CLASSIFY.CATE_AND_EMP ON 
								   CLASSIFY.V_001_EXPANDED_CATEGORY_TYPE_1.SEARCH_CATEGORY_KEY = CLASSIFY.CATE_AND_EMP.CATEGORY_KEY INNER JOIN
								   CLASSIFY.V_002_CATEGORY_MAP_TYPE ON 
								   CLASSIFY.V_001_EXPANDED_CATEGORY_TYPE_1.EXPANDED_CATEGORY_KEY = CLASSIFY.V_002_CATEGORY_MAP_TYPE.CATEGORY_KEY
					WHERE (CLASSIFY.CATE_AND_EMP.DEL_FLAG <> 1) 
						AND (CLASSIFY.V_002_CATEGORY_MAP_TYPE.CATEGORY_DEL_FLAG <> 1) 
						AND (CLASSIFY.V_002_CATEGORY_MAP_TYPE.CATEGORY_TYPE_DEL_FLAG <> 1) 
						AND (CLASSIFY.CATE_AND_EMP.EMP_ID = @EMP_ID)
			) AS ALL_CATE_OF_EMP ON CA.LEVEL_ID = ALL_CATE_OF_EMP.CATEGORY_KEY
			ORDER BY LEVEL_ID
		END

END
