

CREATE PROCEDURE [dbo].[UspACC_Sel]
(
    @CIF                int
)
AS
BEGIN
/*    SELECT ACCT,
          BRANCH,
          ID_BRANCH.BRANCH_T,
          GL_CODE,
          CIMFMS.DECB_RD,
          MIN(CLASS) AS MINCLASS,
          SUM(LIMIT_VALUE) AS SUMLIMIT,
          SUM(OUT_PRIN) AS SUMPRIN,
          SUM(OUT_ACCRU) AS SUMACCRU,
          SUM(OUT_SUSP) AS SUMSUSP,
          MAX(AGING) AS MAXAGING,
          (SELECT "วันเดือนปี " + CONVERT(VARCHAR(2),UPD_DAY) +  "/" + CONVERT(VARCHAR(2),UPD_MONTH) + "/" + CONVERT(VARCHAR(4),UPD_YEAR) FROM DEBTDATE WHERE UPD_TABLE = 'LCI_DAILY') As UPD

      FROM LCI_DAILY INNER JOIN ID_BRANCH ON LCI_DAILY.BRANCH = ID_BRANCH.ID_BRANCH INNER JOIN CIMFMS ON
	 LCI_DAILY.GL_CODE = CIMFMS.ACCGL
     WHERE CIF_NO        = @CIF
     GROUP BY ACCT, BRANCH, ID_BRANCH.BRANCH_T, GL_CODE,CIMFMS.DECB_RD*/

    SELECT BYACCOUNT.ACCNO,
          BRANCH,
          ID_BRANCH.BRANCH_T,
          BYACCOUNT.ACCGL,
          CIMFMS.DECB_RD,
          MIN(CLASS) AS MINCLASS,
		  MIN(CLADJ) AS MINCLADJ,
          SUM(DISTINCT BYACCOUNT.LIMIT) AS SUMLIMIT,
          SUM(BYACCOUNT.Principal) AS SUMPRIN,
          SUM(BYACCOUNT.Accru) AS SUMACCRU,
          SUM(BYACCOUNT.Susp) AS SUMSUSP,
          SUM(BYACCOUNT.PrincipalFull) AS SUMPRINFull,
          SUM(BYACCOUNT.AccruFull) AS SUMACCRUFull,
          SUM(BYACCOUNT.SuspOri) AS SUMSUSPOri,
          MAX(BYACCOUNT.AGING) AS MAXAGING,
          (SELECT 'เดือนปี ' +  CONVERT(VARCHAR(2),UPD_MONTH) + '/' + CONVERT(VARCHAR(4),UPD_YEAR) FROM DEBTDATE WHERE UPD_TABLE = 'BYACCOUNT') As UPD

      FROM BYACCOUNT INNER JOIN ID_BRANCH ON BYACCOUNT.BRANCH = ID_BRANCH.ID_BRANCH INNER JOIN CIMFMS ON
	 BYACCOUNT.ACCGL = CIMFMS.ACCGL
     WHERE BYACCOUNT.CIF        = @CIF
     GROUP BY BYACCOUNT.ACCNO, BRANCH, ID_BRANCH.BRANCH_T, BYACCOUNT.ACCGL,CIMFMS.DECB_RD
    RETURN(0)
END

