-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[INPUT_CLS]
	-- Add the parameters for the stored procedure here
	@approveDate datetime
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	--DELETE FROM CLS_WHEN_APPROVE
	--DBCC CHECKIDENT ('CLS_WHEN_APPROVE', reseed, 0)
	--TRUNCATE TABLE CLS_WHEN_APPROVE
	BEGIN TRY
		BEGIN TRANSACTION

	--		DECLARE @approveDate datetime;
			DECLARE @startDate datetime;
			DECLARE @endDate datetime;
			DECLARE @monthKey int;
			DECLARE @subjectGroup nvarchar(10);

	--		SET @approveDate = GETDATE();--convert(datetime,'2010-02-01 23:00:00',120);
			SET @startDate = dateadd(day,-1,@approveDate);
			SET @endDate = @approveDate;
			SET @monthKey = DAY(@startDate);--0;
			SET @subjectGroup = N'1_CREDIT';

			-- Check Older CLS Before Import

			IF EXISTS (SELECT * FROM CLS_WHEN_APPROVE WHERE MAPPING_STATUS IS NULL)
			BEGIN
				-- Clear TABLE [CLS_WHEN_APPROVE_LAST_UPDATE]
				DELETE FROM [CLS_WHEN_APPROVE_LAST_UPDATE]
				TRUNCATE TABLE [CLS_WHEN_APPROVE_LAST_UPDATE]
				-- เอาข้อมูลจาก Warehouse โดยเอาเฉพาะข้อมูลที่มีใน CLS_WHEN_APPROVE และ MAPPING_STATUS เป็น NULL
				-- เก็บข้อมูลไว้ใน CLS_WHEN_APPROVE_LAST_UPDATE
				INSERT INTO [CLS_WHEN_APPROVE_LAST_UPDATE]
				   ([CIF]
				   ,[LEADER1_CA_OLD_ID]
				   ,[CLS_LIMIT_ROOT_ID_KEY]
				   ,[CLS_LIMIT_L1_ID_KEY]
				   ,[CLS_LIMIT_L2_ID_KEY]
				   ,[CLS_LIMIT_L3_ID_KEY]
				   ,[CLS_LIMIT_L4_ID_KEY]
				   ,[CLS_LIMIT_L5_ID_KEY]
				   ,[CLS_LIMIT_L6_ID_KEY]
				   ,[CLS_LIMIT_L7_ID_KEY]
				   ,[CLS_LIMIT_L8_ID_KEY]
				   ,[CLS_LIMIT_PRODUCT_ID_KEY]
				   ,[PRODUCT_KEY]
				   ,[CLS_PRODUCT_ID_KEY]
				   ,[LIMIT_STATUS_ID_KEY]
				   ,[CLS_CURRENCY_ID_KEY]
				   ,[LIMIT_PURPOSE_ID_KEY]
				   ,[BUSINESS_RISK_ID_KEY]
				   ,[CA_KEY]
				   ,[CREATED_BY_USER_CODE]
				   ,[CREATED_BY_USER_NAME]
				   ,[UPDATED_BY_USER_CODE]
				   ,[UPDATED_BY_USER_NAME]
				   ,[UPDATED_STATUS_BY_USER_CODE]
				   ,[UPDATED_STATUS_BY_USER_NAME]
				   ,[LIMIT_NO_ROOT]
				   ,[LIMIT_NO_L1]
				   ,[LIMIT_NO_L2]
				   ,[LIMIT_NO_L3]
				   ,[LIMIT_NO_L4]
				   ,[LIMIT_NO_L5]
				   ,[LIMIT_NO_L6]
				   ,[LIMIT_NO_L7]
				   ,[LIMIT_NO_L8]
				   ,[LIMIT_NO_PRODUCT]
				   ,[LIMIT_ROOT_STATUS]
				   ,[LIMIT_L1_STATUS]
				   ,[LIMIT_L2_STATUS]
				   ,[LIMIT_L3_STATUS]
				   ,[LIMIT_L4_STATUS]
				   ,[LIMIT_L5_STATUS]
				   ,[LIMIT_L6_STATUS]
				   ,[LIMIT_L7_STATUS]
				   ,[LIMIT_L8_STATUS]
				   ,[LIMIT_PRODUCT_STATUS]
				   ,[LIMIT_REVOLVING_TYPE]
				   ,[APPL_KEY]
				   ,[APPL_ID]
				   ,[PRODUCT_CODE]
				   ,[PRODUCT_NAME]
				   ,[ACCOUNT_NO]
				   ,[CIF_LIST_CA_NO]
				   ,[CIF_LIST_ROOT]
				   ,[CIF_LIST_PRODUCT]
				   ,[NO_OF_CIF_CANO]
				   ,[LIMIT_AMOUNT_ROOT_THB]
				   ,[LIMIT_AMOUNT_ROOT_CCY]
				   ,[LIMIT_AMOUNT_L1_THB]
				   ,[LIMIT_AMOUNT_L1_CCY]
				   ,[LIMIT_AMOUNT_L2_THB]
				   ,[LIMIT_AMOUNT_L2_CCY]
				   ,[LIMIT_AMOUNT_L3_THB]
				   ,[LIMIT_AMOUNT_L3_CCY]
				   ,[LIMIT_AMOUNT_L4_THB]
				   ,[LIMIT_AMOUNT_L4_CCY]
				   ,[LIMIT_AMOUNT_L5_THB]
				   ,[LIMIT_AMOUNT_L5_CCY]
				   ,[LIMIT_AMOUNT_L6_THB]
				   ,[LIMIT_AMOUNT_L6_CCY]
				   ,[LIMIT_AMOUNT_L7_THB]
				   ,[LIMIT_AMOUNT_L7_CCY]
				   ,[LIMIT_AMOUNT_L8_THB]
				   ,[LIMIT_AMOUNT_L8_CCY]
				   ,[LIMIT_AMOUNT_PRODUCT_THB]
				   ,[LIMIT_AMOUNT_PRODUCT_CCY]
				   ,[LIMIT_USED_ROOT_THB]
				   ,[LIMIT_USED_ROOT_CCY]
				   ,[LIMIT_USED_L1_THB]
				   ,[LIMIT_USED_L1_CCY]
				   ,[LIMIT_USED_L2_THB]
				   ,[LIMIT_USED_L2_CCY]
				   ,[LIMIT_USED_L3_THB]
				   ,[LIMIT_USED_L3_CCY]
				   ,[LIMIT_USED_L4_THB]
				   ,[LIMIT_USED_L4_CCY]
				   ,[LIMIT_USED_L5_THB]
				   ,[LIMIT_USED_L5_CCY]
				   ,[LIMIT_USED_L6_THB]
				   ,[LIMIT_USED_L6_CCY]
				   ,[LIMIT_USED_L7_THB]
				   ,[LIMIT_USED_L7_CCY]
				   ,[LIMIT_USED_L8_THB]
				   ,[LIMIT_USED_L8_CCY]
				   ,[LIMIT_USED_PRODUCT_THB]
				   ,[LIMIT_USED_PRODUCT_CCY]
				   ,[LIMIT_AVAILABLE_ROOT_THB]
				   ,[LIMIT_AVAILABLE_L1_THB]
				   ,[LIMIT_AVAILABLE_L2_THB]
				   ,[LIMIT_AVAILABLE_L3_THB]
				   ,[LIMIT_AVAILABLE_L4_THB]
				   ,[LIMIT_AVAILABLE_L5_THB]
				   ,[LIMIT_AVAILABLE_L6_THB]
				   ,[LIMIT_AVAILABLE_L7_THB]
				   ,[LIMIT_AVAILABLE_L8_THB]
				   ,[LIMIT_AVAILABLE_PRODUCT_THB]
				   ,[LIMIT_AVAI_RATIO_L1_THB]
				   ,[LIMIT_AVAI_RATIO_L2_THB]
				   ,[LIMIT_AVAI_RATIO_L3_THB]
				   ,[LIMIT_AVAI_RATIO_L4_THB]
				   ,[LIMIT_AVAI_RATIO_L5_THB]
				   ,[LIMIT_AVAI_RATIO_L6_THB]
				   ,[LIMIT_AVAI_RATIO_L7_THB]
				   ,[LIMIT_AVAI_RATIO_L8_THB]
				   ,[LIMIT_AVAI_RATIO_PRODUCT_THB]
				   ,[HOLD_AMOUNT_THB]
				   ,[HOLD_AMOUNT_CCY]
				   ,[LIMIT_AMOUNT_CA_THB]
				   ,[LIMIT_USED_CA_THB]
				   ,[LIMIT_AVAILABLE_CA_THB]
				   ,[GECID]
				   ,[CREATED_DATE]
				   ,[UPDATE_DATE]
				   ,[UPDATE_STATUS_DATE]
				   ,[ASOFDATE]
				   ,[ETL_DT]
				   ,[LIMIT_PRODUCT_CA_NO]
				   ,[LIMIT_PRODUCT_CA_DATE]
				   ,[LIMIT_PRODUCT_APPV_DATE]
				   ,[LIMIT_PRODUCT_APPV_AUTH_UNIT]
				   ,[LIMIT_PRODUCT_PREVIOUS_CA_NO]
				   ,[LIMIT_PRODUCT_EFFECT_DATE]
				   ,[LIMIT_PRODUCT_EXPIRE_DATE]
				   ,[LIMIT_PRODUCT_SIGN_DATE]
				   ,[LIMIT_CHANGE_DATE])
			 
				SELECT C.CIF
					,R.LEADER1_CA_OLD_ID
					,L.[CLS_LIMIT_ROOT_ID_KEY]
					,L.[CLS_LIMIT_L1_ID_KEY]
					,L.[CLS_LIMIT_L2_ID_KEY]
					,L.[CLS_LIMIT_L3_ID_KEY]
					,L.[CLS_LIMIT_L4_ID_KEY]
					,L.[CLS_LIMIT_L5_ID_KEY]
					,L.[CLS_LIMIT_L6_ID_KEY]
					,L.[CLS_LIMIT_L7_ID_KEY]
					,L.[CLS_LIMIT_L8_ID_KEY]
					,L.[CLS_LIMIT_PRODUCT_ID_KEY]
					,L.[PRODUCT_KEY]
					,L.[CLS_PRODUCT_ID_KEY]
					,L.[LIMIT_STATUS_ID_KEY]
					,L.[CLS_CURRENCY_ID_KEY]
					,L.[LIMIT_PURPOSE_ID_KEY]
					,L.[BUSINESS_RISK_ID_KEY]
					,L.[CA_KEY]
					,L.[CREATED_BY_USER_CODE]
					,L.[CREATED_BY_USER_NAME]
					,L.[UPDATED_BY_USER_CODE]
					,L.[UPDATED_BY_USER_NAME]
					,L.[UPDATED_STATUS_BY_USER_CODE]
					,L.[UPDATED_STATUS_BY_USER_NAME]
					,L.[LIMIT_NO_ROOT]
					,L.[LIMIT_NO_L1]
					,L.[LIMIT_NO_L2]
					,L.[LIMIT_NO_L3]
					,L.[LIMIT_NO_L4]
					,L.[LIMIT_NO_L5]
					,L.[LIMIT_NO_L6]
					,L.[LIMIT_NO_L7]
					,L.[LIMIT_NO_L8]
					,L.[LIMIT_NO_PRODUCT]
					,L.[LIMIT_ROOT_STATUS]
					,L.[LIMIT_L1_STATUS]
					,L.[LIMIT_L2_STATUS]
					,L.[LIMIT_L3_STATUS]
					,L.[LIMIT_L4_STATUS]
					,L.[LIMIT_L5_STATUS]
					,L.[LIMIT_L6_STATUS]
					,L.[LIMIT_L7_STATUS]
					,L.[LIMIT_L8_STATUS]
					,L.[LIMIT_PRODUCT_STATUS]
					,L.[LIMIT_REVOLVING_TYPE]
					,L.[APPL_KEY]
					,L.[APPL_ID]
					,L.[PRODUCT_CODE]
					,L.[PRODUCT_NAME]
					,L.[ACCOUNT_NO]
					,L.[CIF_LIST_CA_NO]
					,L.[CIF_LIST_ROOT]
					,L.[CIF_LIST_PRODUCT]
					,L.[NO_OF_CIF_CANO]
					,L.[LIMIT_AMOUNT_ROOT_THB]
					,L.[LIMIT_AMOUNT_ROOT_CCY]
					,L.[LIMIT_AMOUNT_L1_THB]
					,L.[LIMIT_AMOUNT_L1_CCY]
					,L.[LIMIT_AMOUNT_L2_THB]
					,L.[LIMIT_AMOUNT_L2_CCY]
					,L.[LIMIT_AMOUNT_L3_THB]
					,L.[LIMIT_AMOUNT_L3_CCY]
					,L.[LIMIT_AMOUNT_L4_THB]
					,L.[LIMIT_AMOUNT_L4_CCY]
					,L.[LIMIT_AMOUNT_L5_THB]
					,L.[LIMIT_AMOUNT_L5_CCY]
					,L.[LIMIT_AMOUNT_L6_THB]
					,L.[LIMIT_AMOUNT_L6_CCY]
					,L.[LIMIT_AMOUNT_L7_THB]
					,L.[LIMIT_AMOUNT_L7_CCY]
					,L.[LIMIT_AMOUNT_L8_THB]
					,L.[LIMIT_AMOUNT_L8_CCY]
					,L.[LIMIT_AMOUNT_PRODUCT_THB]
					,L.[LIMIT_AMOUNT_PRODUCT_CCY]
					,L.[LIMIT_USED_ROOT_THB]
					,L.[LIMIT_USED_ROOT_CCY]
					,L.[LIMIT_USED_L1_THB]
					,L.[LIMIT_USED_L1_CCY]
					,L.[LIMIT_USED_L2_THB]
					,L.[LIMIT_USED_L2_CCY]
					,L.[LIMIT_USED_L3_THB]
					,L.[LIMIT_USED_L3_CCY]
					,L.[LIMIT_USED_L4_THB]
					,L.[LIMIT_USED_L4_CCY]
					,L.[LIMIT_USED_L5_THB]
					,L.[LIMIT_USED_L5_CCY]
					,L.[LIMIT_USED_L6_THB]
					,L.[LIMIT_USED_L6_CCY]
					,L.[LIMIT_USED_L7_THB]
					,L.[LIMIT_USED_L7_CCY]
					,L.[LIMIT_USED_L8_THB]
					,L.[LIMIT_USED_L8_CCY]
					,L.[LIMIT_USED_PRODUCT_THB]
					,L.[LIMIT_USED_PRODUCT_CCY]
					,L.[LIMIT_AVAILABLE_ROOT_THB]
					,L.[LIMIT_AVAILABLE_L1_THB]
					,L.[LIMIT_AVAILABLE_L2_THB]
					,L.[LIMIT_AVAILABLE_L3_THB]
					,L.[LIMIT_AVAILABLE_L4_THB]
					,L.[LIMIT_AVAILABLE_L5_THB]
					,L.[LIMIT_AVAILABLE_L6_THB]
					,L.[LIMIT_AVAILABLE_L7_THB]
					,L.[LIMIT_AVAILABLE_L8_THB]
					,L.[LIMIT_AVAILABLE_PRODUCT_THB]
					,L.[LIMIT_AVAI_RATIO_L1_THB]
					,L.[LIMIT_AVAI_RATIO_L2_THB]
					,L.[LIMIT_AVAI_RATIO_L3_THB]
					,L.[LIMIT_AVAI_RATIO_L4_THB]
					,L.[LIMIT_AVAI_RATIO_L5_THB]
					,L.[LIMIT_AVAI_RATIO_L6_THB]
					,L.[LIMIT_AVAI_RATIO_L7_THB]
					,L.[LIMIT_AVAI_RATIO_L8_THB]
					,L.[LIMIT_AVAI_RATIO_PRODUCT_THB]
					,L.[HOLD_AMOUNT_THB]
					,L.[HOLD_AMOUNT_CCY]
					,L.[LIMIT_AMOUNT_CA_THB]
					,L.[LIMIT_USED_CA_THB]
					,L.[LIMIT_AVAILABLE_CA_THB]
					,L.[GECID]
					,L.[CREATED_DATE]
					,L.[UPDATE_DATE]
					,L.[UPDATE_STATUS_DATE]
					,L.[ASOFDATE]
					,L.[ETL_DT]
					,CA.CA_NO AS LIMIT_PRODUCT_CA_NO
					,CA.CA_DATE AS LIMIT_PRODUCT_CA_DATE
					,CA.APPV_DATE AS LIMIT_PRODUCT_APPV_DATE
					,CA.APPV_AUTH_UNIT AS LIMIT_PRODUCT_APPV_AUTH_UNIT
					,CA.PREVIOUS_CA_NO AS LIMIT_PRODUCT_PREVIOUS_CA_NO
					,LIM.EFFECT_DATE AS LIMIT_PRODUCT_EFFECT_DATE
					,LIM.EXPIRE_DATE AS LIMIT_PRODUCT_EXPIRE_DATE
					,LIM.SIGN_DATE AS LIMIT_PRODUCT_SIGN_DATE
					,CASE WHEN @endDate < LIM.CHANGE_LIMIT_DATE
						THEN @endDate
						ELSE LIM.CHANGE_LIMIT_DATE
					 END AS LIMIT_CHANGE_DATE

				FROM	[EDW]..[DWHADMIN].[CLS_LIMIT_RELATION_FACT] L INNER JOIN
					[EDW]..[DWHADMIN].[CLS_CIF_PRODUCT_FACT] C 
					ON L.LIMIT_NO_PRODUCT = C.LIMIT_NO_PRODUCT INNER JOIN
					[EDW]..[DWHADMIN].[DIM_CLS_CA] CA
					ON L.CA_KEY = CA.CA_KEY INNER JOIN
					[EDW]..[DWHADMIN].[DIM_CLS_LIMIT] LIM
					ON L.CLS_LIMIT_PRODUCT_ID_KEY = LIM.CLS_LIMIT_ID_KEY INNER JOIN
					(SELECT DISTINCT [CIF],[LEADER1_CA_OLD_ID] AS LEADER1_CA_OLD_ID
						FROM CLS_WHEN_APPROVE
						WHERE MAPPING_STATUS IS NULL
							AND [LEADER1_CREATED_DATE] >= DATEADD(day,-150,@endDate)
					) R
					ON R.CIF = C.CIF
				WHERE L.MONTH_KEY = @monthKey
					AND C.MONTH_KEY = @monthKey

				-- UPDATE ข้อมูลที่มีอยู่แล้วใน [CLS_WHEN_APPROVE_LAST_UPDATE] (เฉพาะที่ [CLS_WHEN_APPROVE].MAPPING_STATUS IS NULL)
				-- และ LIMIT_CHANGE_DATE ของทั้งสอง Table ต้องไม่เท่ากัน
				UPDATE [CLS_WHEN_APPROVE_LAST_UPDATE]
					   SET [LIMIT_CHANGE_ROOT_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_ROOT_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_ROOT_THB]
						  ,[LIMIT_CHANGE_L1_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_L1_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_L1_THB]
						  ,[LIMIT_CHANGE_L2_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_L2_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_L2_THB]
						  ,[LIMIT_CHANGE_L3_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_L3_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_L3_THB]
						  ,[LIMIT_CHANGE_L4_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_L4_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_L4_THB]
						  ,[LIMIT_CHANGE_L5_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_L5_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_L5_THB]
						  ,[LIMIT_CHANGE_L6_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_L6_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_L6_THB]
						  ,[LIMIT_CHANGE_L7_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_L7_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_L7_THB]
						  ,[LIMIT_CHANGE_L8_THB] = [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_L8_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_L8_THB]
						  ,[LIMIT_CHANGE_PRODUCT_THB] = CASE 
														WHEN [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_PRODUCT_STATUS] = 'A' AND [CLS_WHEN_APPROVE].[LIMIT_PRODUCT_STATUS] <> 'A'
															THEN  [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_PRODUCT_THB] -- Last Status เป็น A และ Old Status ไม่ใช่ A แสดงว่าเป็นการ Active วงเงินใหม่
														WHEN [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_PRODUCT_STATUS] <> 'A' AND [CLS_WHEN_APPROVE].[LIMIT_PRODUCT_STATUS] = 'A'
															THEN (0 - [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_PRODUCT_THB]) --Last Status ไม่ใช่ A และ Old Status เป็น A แสดงว่าวงเงินถูกยกเลิก Limit Change ต้องติดลบ
														ELSE [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_PRODUCT_THB] - [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_PRODUCT_THB] END -- Status ไม่ได้เปลี่ยน
						  ,[LIMIT_CHANGE_DATE] = ISNULL([CLS_WHEN_APPROVE_LAST_UPDATE].LIMIT_CHANGE_DATE,@endDate)
						  ,MAPPING_STATUS = CASE 
											WHEN [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_PRODUCT_STATUS] <> [CLS_WHEN_APPROVE].[LIMIT_PRODUCT_STATUS] THEN 'S' --status change
											WHEN [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_PRODUCT_THB] <> [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_PRODUCT_THB] THEN 'L' --limit change
											ELSE 'U' END --unknown
					FROM [CLS_WHEN_APPROVE_LAST_UPDATE] INNER JOIN [CLS_WHEN_APPROVE]
						ON [CLS_WHEN_APPROVE_LAST_UPDATE].CIF = [CLS_WHEN_APPROVE].CIF
							AND [CLS_WHEN_APPROVE_LAST_UPDATE].LEADER1_CA_OLD_ID = [CLS_WHEN_APPROVE].LEADER1_CA_OLD_ID
							AND [CLS_WHEN_APPROVE_LAST_UPDATE].CLS_LIMIT_PRODUCT_ID_KEY = [CLS_WHEN_APPROVE].CLS_LIMIT_PRODUCT_ID_KEY
					WHERE [CLS_WHEN_APPROVE].MAPPING_STATUS IS NULL
						AND ([CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_AMOUNT_PRODUCT_THB] <> [CLS_WHEN_APPROVE].[LIMIT_AMOUNT_PRODUCT_THB]
							OR [CLS_WHEN_APPROVE_LAST_UPDATE].[LIMIT_PRODUCT_STATUS] <> [CLS_WHEN_APPROVE].[LIMIT_PRODUCT_STATUS]
						)

				-- UPDATE MAPPING_STATUS เป็น N(New Limit) เฉพาะ Record ที่มีใน [CLS_WHEN_APPROVE_LAST_UPDATE] แต่ไม่มีใน [CLS_WHEN_APPROVE]
				UPDATE [CLS_WHEN_APPROVE_LAST_UPDATE]
					SET [LIMIT_CHANGE_PRODUCT_THB] = [LIMIT_AMOUNT_PRODUCT_THB]
						,LIMIT_CHANGE_DATE = ISNULL(LIMIT_CHANGE_DATE,@endDate)
						,MAPPING_STATUS = 'N'
				WHERE NOT EXISTS (
								SELECT CIF
									,LEADER1_CA_OLD_ID
									,CLS_LIMIT_PRODUCT_ID_KEY
								FROM [CLS_WHEN_APPROVE]
								WHERE [CLS_WHEN_APPROVE].CIF = [CLS_WHEN_APPROVE_LAST_UPDATE].CIF
									AND [CLS_WHEN_APPROVE].LEADER1_CA_OLD_ID = [CLS_WHEN_APPROVE_LAST_UPDATE].LEADER1_CA_OLD_ID
									AND [CLS_WHEN_APPROVE].CLS_LIMIT_PRODUCT_ID_KEY = [CLS_WHEN_APPROVE_LAST_UPDATE].CLS_LIMIT_PRODUCT_ID_KEY
							)

				-- Compare วงเงินปัจจุบัน [CLS_WHEN_APPROVE_LAST_UPDATE] ที่อัพเดต Status แล้วกับสิ่งที่ขอใน CA ว่าตรงกันหรือไม่
				SELECT CLS.*
				INTO #CLS_MAP
				FROM [CLS_WHEN_APPROVE_LAST_UPDATE] CLS INNER JOIN [REPORT07_SUMMARY] R
					ON CLS.[LEADER1_CA_OLD_ID] = R.[OLD_ID]
						AND CLS.[CIF] = R.[CIF]
						AND CLS.[LIMIT_CHANGE_PRODUCT_THB] = R.APPROVE_VALUE
						AND CLS.[PRODUCT_NAME] = R.DECB_RD
				WHERE (R.SUBJECT_DETAIL_ID = 101 OR R.SUBJECT_DETAIL_ID = 102 OR R.SUBJECT_DETAIL_ID = 103
						OR R.SUBJECT_DETAIL_ID = 104 OR R.SUBJECT_DETAIL_ID = 105)
					AND CLS.MAPPING_STATUS IS NOT NULL
					AND R.APPROVE_VALUE <> 0
					
				-- Add on 21 Feb 2011	
				-- Change Process ไม่ว่าจะตรงกับใน CA หรือไม่ให้ stamp all data ไว้ก่อน
				-- แยกวงเงินที่ Compare แล้วไม่ตรงไว้อีก Table หนึ่ง แต่ต้องดูว่า MAPPING_STATUS ต้องไม่เป็น NULL
				SELECT CLS.*
				INTO #CLS_NOT_MAP
				FROM [CLS_WHEN_APPROVE_LAST_UPDATE] CLS
				WHERE NOT EXISTS (
									SELECT M.[LEADER1_CA_OLD_ID]
											,M.[CIF]
											,M.[CLS_LIMIT_PRODUCT_ID_KEY]
									FROM #CLS_MAP M
									WHERE M.[LEADER1_CA_OLD_ID] = CLS.[LEADER1_CA_OLD_ID]
										AND M.[CIF] = CLS.[CIF]
										AND M.[CLS_LIMIT_PRODUCT_ID_KEY] = CLS.[CLS_LIMIT_PRODUCT_ID_KEY]
				) AND CLS.MAPPING_STATUS IS NOT NULL
				
				-- Update ลง CLS_WHEN_APPROVE โดยทำการ Count จำนวนครั้งที่เปลี่ยนเพิ่มที่ละ 1 และ + total change เพิ่มด้วยทุกๆครั้ง
				UPDATE [CLS_WHEN_APPROVE]
				   SET [CIF] = #CLS_NOT_MAP.CIF
					  ,[LEADER1_CA_OLD_ID] = #CLS_NOT_MAP.[LEADER1_CA_OLD_ID]
					  ,[CLS_LIMIT_ROOT_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_ROOT_ID_KEY]
					  ,[CLS_LIMIT_L1_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_L1_ID_KEY]
					  ,[CLS_LIMIT_L2_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_L2_ID_KEY]
					  ,[CLS_LIMIT_L3_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_L3_ID_KEY]
					  ,[CLS_LIMIT_L4_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_L4_ID_KEY]
					  ,[CLS_LIMIT_L5_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_L5_ID_KEY]
					  ,[CLS_LIMIT_L6_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_L6_ID_KEY]
					  ,[CLS_LIMIT_L7_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_L7_ID_KEY]
					  ,[CLS_LIMIT_L8_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_L8_ID_KEY]
					  ,[CLS_LIMIT_PRODUCT_ID_KEY] = #CLS_NOT_MAP.[CLS_LIMIT_PRODUCT_ID_KEY]
					  ,[PRODUCT_KEY] = #CLS_NOT_MAP.[PRODUCT_KEY]
					  ,[CLS_PRODUCT_ID_KEY] = #CLS_NOT_MAP.[CLS_PRODUCT_ID_KEY]
					  ,[LIMIT_STATUS_ID_KEY] = #CLS_NOT_MAP.[LIMIT_STATUS_ID_KEY]
					  ,[CLS_CURRENCY_ID_KEY] = #CLS_NOT_MAP.[CLS_CURRENCY_ID_KEY]
					  ,[LIMIT_PURPOSE_ID_KEY] = #CLS_NOT_MAP.[LIMIT_PURPOSE_ID_KEY]
					  ,[BUSINESS_RISK_ID_KEY] = #CLS_NOT_MAP.[BUSINESS_RISK_ID_KEY]
					  ,[CA_KEY] = #CLS_NOT_MAP.[CA_KEY]
					  ,[CREATED_BY_USER_CODE] = #CLS_NOT_MAP.[CREATED_BY_USER_CODE]
					  ,[CREATED_BY_USER_NAME] = #CLS_NOT_MAP.[CREATED_BY_USER_NAME]
					  ,[UPDATED_BY_USER_CODE] = #CLS_NOT_MAP.[UPDATED_BY_USER_CODE]
					  ,[UPDATED_BY_USER_NAME] = #CLS_NOT_MAP.[UPDATED_BY_USER_NAME]
					  ,[UPDATED_STATUS_BY_USER_CODE] = #CLS_NOT_MAP.[UPDATED_STATUS_BY_USER_CODE]
					  ,[UPDATED_STATUS_BY_USER_NAME] = #CLS_NOT_MAP.[UPDATED_STATUS_BY_USER_NAME]
					  ,[LIMIT_NO_ROOT] = #CLS_NOT_MAP.[LIMIT_NO_ROOT]
					  ,[LIMIT_NO_L1] = #CLS_NOT_MAP.[LIMIT_NO_L1]
					  ,[LIMIT_NO_L2] = #CLS_NOT_MAP.[LIMIT_NO_L2]
					  ,[LIMIT_NO_L3] = #CLS_NOT_MAP.[LIMIT_NO_L3]
					  ,[LIMIT_NO_L4] = #CLS_NOT_MAP.[LIMIT_NO_L4]
					  ,[LIMIT_NO_L5] = #CLS_NOT_MAP.[LIMIT_NO_L5]
					  ,[LIMIT_NO_L6] = #CLS_NOT_MAP.[LIMIT_NO_L6]
					  ,[LIMIT_NO_L7] = #CLS_NOT_MAP.[LIMIT_NO_L7]
					  ,[LIMIT_NO_L8] = #CLS_NOT_MAP.[LIMIT_NO_L8]
					  ,[LIMIT_NO_PRODUCT] = #CLS_NOT_MAP.[LIMIT_NO_PRODUCT]
					  ,[LIMIT_ROOT_STATUS] = #CLS_NOT_MAP.[LIMIT_ROOT_STATUS]
					  ,[LIMIT_L1_STATUS] = #CLS_NOT_MAP.[LIMIT_L1_STATUS]
					  ,[LIMIT_L2_STATUS] = #CLS_NOT_MAP.[LIMIT_L2_STATUS]
					  ,[LIMIT_L3_STATUS] = #CLS_NOT_MAP.[LIMIT_L3_STATUS]
					  ,[LIMIT_L4_STATUS] = #CLS_NOT_MAP.[LIMIT_L4_STATUS]
					  ,[LIMIT_L5_STATUS] = #CLS_NOT_MAP.[LIMIT_L5_STATUS]
					  ,[LIMIT_L6_STATUS] = #CLS_NOT_MAP.[LIMIT_L6_STATUS]
					  ,[LIMIT_L7_STATUS] = #CLS_NOT_MAP.[LIMIT_L7_STATUS]
					  ,[LIMIT_L8_STATUS] = #CLS_NOT_MAP.[LIMIT_L8_STATUS]
					  ,[LIMIT_PRODUCT_STATUS] = #CLS_NOT_MAP.[LIMIT_PRODUCT_STATUS]
					  ,[LIMIT_REVOLVING_TYPE] = #CLS_NOT_MAP.[LIMIT_REVOLVING_TYPE]
					  ,[APPL_KEY] = #CLS_NOT_MAP.[APPL_KEY]
					  ,[APPL_ID] = #CLS_NOT_MAP.[APPL_ID]
					  ,[PRODUCT_CODE] = #CLS_NOT_MAP.[PRODUCT_CODE]
					  ,[PRODUCT_NAME] = #CLS_NOT_MAP.[PRODUCT_NAME]
					  ,[ACCOUNT_NO] = #CLS_NOT_MAP.[ACCOUNT_NO]
					  ,[CIF_LIST_CA_NO] = #CLS_NOT_MAP.[CIF_LIST_CA_NO]
					  ,[CIF_LIST_ROOT] = #CLS_NOT_MAP.[CIF_LIST_ROOT]
					  ,[CIF_LIST_PRODUCT] = #CLS_NOT_MAP.[CIF_LIST_PRODUCT]
					  ,[NO_OF_CIF_CANO] = #CLS_NOT_MAP.[NO_OF_CIF_CANO]
					  ,[LIMIT_AMOUNT_ROOT_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_ROOT_THB]
					  ,[LIMIT_AMOUNT_ROOT_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_ROOT_CCY]
					  ,[LIMIT_AMOUNT_L1_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L1_THB]
					  ,[LIMIT_AMOUNT_L1_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L1_CCY]
					  ,[LIMIT_AMOUNT_L2_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L2_THB]
					  ,[LIMIT_AMOUNT_L2_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L2_CCY]
					  ,[LIMIT_AMOUNT_L3_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L3_THB]
					  ,[LIMIT_AMOUNT_L3_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L3_CCY]
					  ,[LIMIT_AMOUNT_L4_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L4_THB]
					  ,[LIMIT_AMOUNT_L4_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L4_CCY]
					  ,[LIMIT_AMOUNT_L5_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L5_THB]
					  ,[LIMIT_AMOUNT_L5_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L5_CCY]
					  ,[LIMIT_AMOUNT_L6_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L6_THB]
					  ,[LIMIT_AMOUNT_L6_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L6_CCY]
					  ,[LIMIT_AMOUNT_L7_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L7_THB]
					  ,[LIMIT_AMOUNT_L7_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L7_CCY]
					  ,[LIMIT_AMOUNT_L8_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L8_THB]
					  ,[LIMIT_AMOUNT_L8_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_L8_CCY]
					  ,[LIMIT_AMOUNT_PRODUCT_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_PRODUCT_THB]
					  ,[LIMIT_AMOUNT_PRODUCT_CCY] = #CLS_NOT_MAP.[LIMIT_AMOUNT_PRODUCT_CCY]
					  ,[LIMIT_USED_ROOT_THB] = #CLS_NOT_MAP.[LIMIT_USED_ROOT_THB]
					  ,[LIMIT_USED_ROOT_CCY] = #CLS_NOT_MAP.[LIMIT_USED_ROOT_CCY]
					  ,[LIMIT_USED_L1_THB] = #CLS_NOT_MAP.[LIMIT_USED_L1_THB]
					  ,[LIMIT_USED_L1_CCY] = #CLS_NOT_MAP.[LIMIT_USED_L1_CCY]
					  ,[LIMIT_USED_L2_THB] = #CLS_NOT_MAP.[LIMIT_USED_L2_THB]
					  ,[LIMIT_USED_L2_CCY] = #CLS_NOT_MAP.[LIMIT_USED_L2_CCY]
					  ,[LIMIT_USED_L3_THB] = #CLS_NOT_MAP.[LIMIT_USED_L3_THB]
					  ,[LIMIT_USED_L3_CCY] = #CLS_NOT_MAP.[LIMIT_USED_L3_CCY]
					  ,[LIMIT_USED_L4_THB] = #CLS_NOT_MAP.[LIMIT_USED_L4_THB]
					  ,[LIMIT_USED_L4_CCY] = #CLS_NOT_MAP.[LIMIT_USED_L4_CCY]
					  ,[LIMIT_USED_L5_THB] = #CLS_NOT_MAP.[LIMIT_USED_L5_THB]
					  ,[LIMIT_USED_L5_CCY] = #CLS_NOT_MAP.[LIMIT_USED_L5_CCY]
					  ,[LIMIT_USED_L6_THB] = #CLS_NOT_MAP.[LIMIT_USED_L6_THB]
					  ,[LIMIT_USED_L6_CCY] = #CLS_NOT_MAP.[LIMIT_USED_L6_CCY]
					  ,[LIMIT_USED_L7_THB] = #CLS_NOT_MAP.[LIMIT_USED_L7_THB]
					  ,[LIMIT_USED_L7_CCY] = #CLS_NOT_MAP.[LIMIT_USED_L7_CCY]
					  ,[LIMIT_USED_L8_THB] = #CLS_NOT_MAP.[LIMIT_USED_L8_THB]
					  ,[LIMIT_USED_L8_CCY] = #CLS_NOT_MAP.[LIMIT_USED_L8_CCY]
					  ,[LIMIT_USED_PRODUCT_THB] = #CLS_NOT_MAP.[LIMIT_USED_PRODUCT_THB]
					  ,[LIMIT_USED_PRODUCT_CCY] = #CLS_NOT_MAP.[LIMIT_USED_PRODUCT_CCY]
					  ,[LIMIT_AVAILABLE_ROOT_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_ROOT_THB]
					  ,[LIMIT_AVAILABLE_L1_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_L1_THB]
					  ,[LIMIT_AVAILABLE_L2_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_L2_THB]
					  ,[LIMIT_AVAILABLE_L3_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_L3_THB]
					  ,[LIMIT_AVAILABLE_L4_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_L4_THB]
					  ,[LIMIT_AVAILABLE_L5_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_L5_THB]
					  ,[LIMIT_AVAILABLE_L6_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_L6_THB]
					  ,[LIMIT_AVAILABLE_L7_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_L7_THB]
					  ,[LIMIT_AVAILABLE_L8_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_L8_THB]
					  ,[LIMIT_AVAILABLE_PRODUCT_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_PRODUCT_THB]
					  ,[LIMIT_AVAI_RATIO_L1_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_L1_THB]
					  ,[LIMIT_AVAI_RATIO_L2_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_L2_THB]
					  ,[LIMIT_AVAI_RATIO_L3_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_L3_THB]
					  ,[LIMIT_AVAI_RATIO_L4_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_L4_THB]
					  ,[LIMIT_AVAI_RATIO_L5_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_L5_THB]
					  ,[LIMIT_AVAI_RATIO_L6_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_L6_THB]
					  ,[LIMIT_AVAI_RATIO_L7_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_L7_THB]
					  ,[LIMIT_AVAI_RATIO_L8_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_L8_THB]
					  ,[LIMIT_AVAI_RATIO_PRODUCT_THB] = #CLS_NOT_MAP.[LIMIT_AVAI_RATIO_PRODUCT_THB]
					  ,[HOLD_AMOUNT_THB] = #CLS_NOT_MAP.[HOLD_AMOUNT_THB]
					  ,[HOLD_AMOUNT_CCY] = #CLS_NOT_MAP.[HOLD_AMOUNT_CCY]
					  ,[LIMIT_AMOUNT_CA_THB] = #CLS_NOT_MAP.[LIMIT_AMOUNT_CA_THB]
					  ,[LIMIT_USED_CA_THB] = #CLS_NOT_MAP.[LIMIT_USED_CA_THB]
					  ,[LIMIT_AVAILABLE_CA_THB] = #CLS_NOT_MAP.[LIMIT_AVAILABLE_CA_THB]
					  ,[GECID] = #CLS_NOT_MAP.[GECID]
					  ,[CREATED_DATE] = #CLS_NOT_MAP.[CREATED_DATE]
					  ,[UPDATE_DATE] = #CLS_NOT_MAP.[UPDATE_DATE]
					  ,[UPDATE_STATUS_DATE] = #CLS_NOT_MAP.[UPDATE_STATUS_DATE]
					  ,[ASOFDATE] = #CLS_NOT_MAP.[ASOFDATE]
					  ,[ETL_DT] = #CLS_NOT_MAP.[ETL_DT]
					  ,[LIMIT_PRODUCT_CA_NO] = #CLS_NOT_MAP.[LIMIT_PRODUCT_CA_NO]
					  ,[LIMIT_PRODUCT_CA_DATE] = #CLS_NOT_MAP.[LIMIT_PRODUCT_CA_DATE]
					  ,[LIMIT_PRODUCT_APPV_DATE] = #CLS_NOT_MAP.[LIMIT_PRODUCT_APPV_DATE]
					  ,[LIMIT_PRODUCT_APPV_AUTH_UNIT] = #CLS_NOT_MAP.[LIMIT_PRODUCT_APPV_AUTH_UNIT]
					  ,[LIMIT_PRODUCT_PREVIOUS_CA_NO] = #CLS_NOT_MAP.[LIMIT_PRODUCT_PREVIOUS_CA_NO]
					  ,[LIMIT_PRODUCT_EFFECT_DATE] = #CLS_NOT_MAP.[LIMIT_PRODUCT_EFFECT_DATE]
					  ,[LIMIT_PRODUCT_EXPIRE_DATE] = #CLS_NOT_MAP.[LIMIT_PRODUCT_EXPIRE_DATE]
					  ,[LIMIT_PRODUCT_SIGN_DATE] = #CLS_NOT_MAP.[LIMIT_PRODUCT_SIGN_DATE]
					  ,[LIMIT_CHANGE_ROOT_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_ROOT_THB]
					  ,[LIMIT_CHANGE_L1_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_L1_THB]
					  ,[LIMIT_CHANGE_L2_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_L2_THB]
					  ,[LIMIT_CHANGE_L3_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_L3_THB]
					  ,[LIMIT_CHANGE_L4_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_L4_THB]
					  ,[LIMIT_CHANGE_L5_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_L5_THB]
					  ,[LIMIT_CHANGE_L6_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_L6_THB]
					  ,[LIMIT_CHANGE_L7_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_L7_THB]
					  ,[LIMIT_CHANGE_L8_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_L8_THB]
					  ,[LIMIT_CHANGE_PRODUCT_THB] = #CLS_NOT_MAP.[LIMIT_CHANGE_PRODUCT_THB]
					  ,[LIMIT_CHANGE_DATE] = #CLS_NOT_MAP.[LIMIT_CHANGE_DATE]
					  --,MAPPING_STATUS = NULL 
					  ,[LEADER1_UPDATE_DATE] = @endDate
					  ,LIMIT_CHANGE_COUNT = ISNULL(LIMIT_CHANGE_COUNT,0) + 1
					  ,LIMIT_CHANGE_PRODUCT_THB_TOTAL = ISNULL(LIMIT_CHANGE_PRODUCT_THB_TOTAL,0) + #CLS_NOT_MAP.[LIMIT_CHANGE_PRODUCT_THB]
					FROM [CLS_WHEN_APPROVE] INNER JOIN #CLS_NOT_MAP
						ON CLS_WHEN_APPROVE.CIF = #CLS_NOT_MAP.CIF
							AND CLS_WHEN_APPROVE.LEADER1_CA_OLD_ID = #CLS_NOT_MAP.LEADER1_CA_OLD_ID
							AND CLS_WHEN_APPROVE.CLS_LIMIT_PRODUCT_ID_KEY = #CLS_NOT_MAP.CLS_LIMIT_PRODUCT_ID_KEY
				 WHERE [CLS_WHEN_APPROVE].MAPPING_STATUS IS NULL
				 
				DROP TABLE #CLS_NOT_MAP
				-- End Change Process ไม่ว่าจะตรงกับใน CA หรือไม่ให้ stamp all data ไว้ก่อน

				-- ถ้าอันไหนที่ตรงกันก็ไป update หรือ insert ที่ [CLS_WHEN_APPROVE] ได้เลย
				UPDATE [CLS_WHEN_APPROVE]
				   SET [CIF] = #CLS_MAP.CIF
					  ,[LEADER1_CA_OLD_ID] = #CLS_MAP.[LEADER1_CA_OLD_ID]
					  ,[CLS_LIMIT_ROOT_ID_KEY] = #CLS_MAP.[CLS_LIMIT_ROOT_ID_KEY]
					  ,[CLS_LIMIT_L1_ID_KEY] = #CLS_MAP.[CLS_LIMIT_L1_ID_KEY]
					  ,[CLS_LIMIT_L2_ID_KEY] = #CLS_MAP.[CLS_LIMIT_L2_ID_KEY]
					  ,[CLS_LIMIT_L3_ID_KEY] = #CLS_MAP.[CLS_LIMIT_L3_ID_KEY]
					  ,[CLS_LIMIT_L4_ID_KEY] = #CLS_MAP.[CLS_LIMIT_L4_ID_KEY]
					  ,[CLS_LIMIT_L5_ID_KEY] = #CLS_MAP.[CLS_LIMIT_L5_ID_KEY]
					  ,[CLS_LIMIT_L6_ID_KEY] = #CLS_MAP.[CLS_LIMIT_L6_ID_KEY]
					  ,[CLS_LIMIT_L7_ID_KEY] = #CLS_MAP.[CLS_LIMIT_L7_ID_KEY]
					  ,[CLS_LIMIT_L8_ID_KEY] = #CLS_MAP.[CLS_LIMIT_L8_ID_KEY]
					  ,[CLS_LIMIT_PRODUCT_ID_KEY] = #CLS_MAP.[CLS_LIMIT_PRODUCT_ID_KEY]
					  ,[PRODUCT_KEY] = #CLS_MAP.[PRODUCT_KEY]
					  ,[CLS_PRODUCT_ID_KEY] = #CLS_MAP.[CLS_PRODUCT_ID_KEY]
					  ,[LIMIT_STATUS_ID_KEY] = #CLS_MAP.[LIMIT_STATUS_ID_KEY]
					  ,[CLS_CURRENCY_ID_KEY] = #CLS_MAP.[CLS_CURRENCY_ID_KEY]
					  ,[LIMIT_PURPOSE_ID_KEY] = #CLS_MAP.[LIMIT_PURPOSE_ID_KEY]
					  ,[BUSINESS_RISK_ID_KEY] = #CLS_MAP.[BUSINESS_RISK_ID_KEY]
					  ,[CA_KEY] = #CLS_MAP.[CA_KEY]
					  ,[CREATED_BY_USER_CODE] = #CLS_MAP.[CREATED_BY_USER_CODE]
					  ,[CREATED_BY_USER_NAME] = #CLS_MAP.[CREATED_BY_USER_NAME]
					  ,[UPDATED_BY_USER_CODE] = #CLS_MAP.[UPDATED_BY_USER_CODE]
					  ,[UPDATED_BY_USER_NAME] = #CLS_MAP.[UPDATED_BY_USER_NAME]
					  ,[UPDATED_STATUS_BY_USER_CODE] = #CLS_MAP.[UPDATED_STATUS_BY_USER_CODE]
					  ,[UPDATED_STATUS_BY_USER_NAME] = #CLS_MAP.[UPDATED_STATUS_BY_USER_NAME]
					  ,[LIMIT_NO_ROOT] = #CLS_MAP.[LIMIT_NO_ROOT]
					  ,[LIMIT_NO_L1] = #CLS_MAP.[LIMIT_NO_L1]
					  ,[LIMIT_NO_L2] = #CLS_MAP.[LIMIT_NO_L2]
					  ,[LIMIT_NO_L3] = #CLS_MAP.[LIMIT_NO_L3]
					  ,[LIMIT_NO_L4] = #CLS_MAP.[LIMIT_NO_L4]
					  ,[LIMIT_NO_L5] = #CLS_MAP.[LIMIT_NO_L5]
					  ,[LIMIT_NO_L6] = #CLS_MAP.[LIMIT_NO_L6]
					  ,[LIMIT_NO_L7] = #CLS_MAP.[LIMIT_NO_L7]
					  ,[LIMIT_NO_L8] = #CLS_MAP.[LIMIT_NO_L8]
					  ,[LIMIT_NO_PRODUCT] = #CLS_MAP.[LIMIT_NO_PRODUCT]
					  ,[LIMIT_ROOT_STATUS] = #CLS_MAP.[LIMIT_ROOT_STATUS]
					  ,[LIMIT_L1_STATUS] = #CLS_MAP.[LIMIT_L1_STATUS]
					  ,[LIMIT_L2_STATUS] = #CLS_MAP.[LIMIT_L2_STATUS]
					  ,[LIMIT_L3_STATUS] = #CLS_MAP.[LIMIT_L3_STATUS]
					  ,[LIMIT_L4_STATUS] = #CLS_MAP.[LIMIT_L4_STATUS]
					  ,[LIMIT_L5_STATUS] = #CLS_MAP.[LIMIT_L5_STATUS]
					  ,[LIMIT_L6_STATUS] = #CLS_MAP.[LIMIT_L6_STATUS]
					  ,[LIMIT_L7_STATUS] = #CLS_MAP.[LIMIT_L7_STATUS]
					  ,[LIMIT_L8_STATUS] = #CLS_MAP.[LIMIT_L8_STATUS]
					  ,[LIMIT_PRODUCT_STATUS] = #CLS_MAP.[LIMIT_PRODUCT_STATUS]
					  ,[LIMIT_REVOLVING_TYPE] = #CLS_MAP.[LIMIT_REVOLVING_TYPE]
					  ,[APPL_KEY] = #CLS_MAP.[APPL_KEY]
					  ,[APPL_ID] = #CLS_MAP.[APPL_ID]
					  ,[PRODUCT_CODE] = #CLS_MAP.[PRODUCT_CODE]
					  ,[PRODUCT_NAME] = #CLS_MAP.[PRODUCT_NAME]
					  ,[ACCOUNT_NO] = #CLS_MAP.[ACCOUNT_NO]
					  ,[CIF_LIST_CA_NO] = #CLS_MAP.[CIF_LIST_CA_NO]
					  ,[CIF_LIST_ROOT] = #CLS_MAP.[CIF_LIST_ROOT]
					  ,[CIF_LIST_PRODUCT] = #CLS_MAP.[CIF_LIST_PRODUCT]
					  ,[NO_OF_CIF_CANO] = #CLS_MAP.[NO_OF_CIF_CANO]
					  ,[LIMIT_AMOUNT_ROOT_THB] = #CLS_MAP.[LIMIT_AMOUNT_ROOT_THB]
					  ,[LIMIT_AMOUNT_ROOT_CCY] = #CLS_MAP.[LIMIT_AMOUNT_ROOT_CCY]
					  ,[LIMIT_AMOUNT_L1_THB] = #CLS_MAP.[LIMIT_AMOUNT_L1_THB]
					  ,[LIMIT_AMOUNT_L1_CCY] = #CLS_MAP.[LIMIT_AMOUNT_L1_CCY]
					  ,[LIMIT_AMOUNT_L2_THB] = #CLS_MAP.[LIMIT_AMOUNT_L2_THB]
					  ,[LIMIT_AMOUNT_L2_CCY] = #CLS_MAP.[LIMIT_AMOUNT_L2_CCY]
					  ,[LIMIT_AMOUNT_L3_THB] = #CLS_MAP.[LIMIT_AMOUNT_L3_THB]
					  ,[LIMIT_AMOUNT_L3_CCY] = #CLS_MAP.[LIMIT_AMOUNT_L3_CCY]
					  ,[LIMIT_AMOUNT_L4_THB] = #CLS_MAP.[LIMIT_AMOUNT_L4_THB]
					  ,[LIMIT_AMOUNT_L4_CCY] = #CLS_MAP.[LIMIT_AMOUNT_L4_CCY]
					  ,[LIMIT_AMOUNT_L5_THB] = #CLS_MAP.[LIMIT_AMOUNT_L5_THB]
					  ,[LIMIT_AMOUNT_L5_CCY] = #CLS_MAP.[LIMIT_AMOUNT_L5_CCY]
					  ,[LIMIT_AMOUNT_L6_THB] = #CLS_MAP.[LIMIT_AMOUNT_L6_THB]
					  ,[LIMIT_AMOUNT_L6_CCY] = #CLS_MAP.[LIMIT_AMOUNT_L6_CCY]
					  ,[LIMIT_AMOUNT_L7_THB] = #CLS_MAP.[LIMIT_AMOUNT_L7_THB]
					  ,[LIMIT_AMOUNT_L7_CCY] = #CLS_MAP.[LIMIT_AMOUNT_L7_CCY]
					  ,[LIMIT_AMOUNT_L8_THB] = #CLS_MAP.[LIMIT_AMOUNT_L8_THB]
					  ,[LIMIT_AMOUNT_L8_CCY] = #CLS_MAP.[LIMIT_AMOUNT_L8_CCY]
					  ,[LIMIT_AMOUNT_PRODUCT_THB] = #CLS_MAP.[LIMIT_AMOUNT_PRODUCT_THB]
					  ,[LIMIT_AMOUNT_PRODUCT_CCY] = #CLS_MAP.[LIMIT_AMOUNT_PRODUCT_CCY]
					  ,[LIMIT_USED_ROOT_THB] = #CLS_MAP.[LIMIT_USED_ROOT_THB]
					  ,[LIMIT_USED_ROOT_CCY] = #CLS_MAP.[LIMIT_USED_ROOT_CCY]
					  ,[LIMIT_USED_L1_THB] = #CLS_MAP.[LIMIT_USED_L1_THB]
					  ,[LIMIT_USED_L1_CCY] = #CLS_MAP.[LIMIT_USED_L1_CCY]
					  ,[LIMIT_USED_L2_THB] = #CLS_MAP.[LIMIT_USED_L2_THB]
					  ,[LIMIT_USED_L2_CCY] = #CLS_MAP.[LIMIT_USED_L2_CCY]
					  ,[LIMIT_USED_L3_THB] = #CLS_MAP.[LIMIT_USED_L3_THB]
					  ,[LIMIT_USED_L3_CCY] = #CLS_MAP.[LIMIT_USED_L3_CCY]
					  ,[LIMIT_USED_L4_THB] = #CLS_MAP.[LIMIT_USED_L4_THB]
					  ,[LIMIT_USED_L4_CCY] = #CLS_MAP.[LIMIT_USED_L4_CCY]
					  ,[LIMIT_USED_L5_THB] = #CLS_MAP.[LIMIT_USED_L5_THB]
					  ,[LIMIT_USED_L5_CCY] = #CLS_MAP.[LIMIT_USED_L5_CCY]
					  ,[LIMIT_USED_L6_THB] = #CLS_MAP.[LIMIT_USED_L6_THB]
					  ,[LIMIT_USED_L6_CCY] = #CLS_MAP.[LIMIT_USED_L6_CCY]
					  ,[LIMIT_USED_L7_THB] = #CLS_MAP.[LIMIT_USED_L7_THB]
					  ,[LIMIT_USED_L7_CCY] = #CLS_MAP.[LIMIT_USED_L7_CCY]
					  ,[LIMIT_USED_L8_THB] = #CLS_MAP.[LIMIT_USED_L8_THB]
					  ,[LIMIT_USED_L8_CCY] = #CLS_MAP.[LIMIT_USED_L8_CCY]
					  ,[LIMIT_USED_PRODUCT_THB] = #CLS_MAP.[LIMIT_USED_PRODUCT_THB]
					  ,[LIMIT_USED_PRODUCT_CCY] = #CLS_MAP.[LIMIT_USED_PRODUCT_CCY]
					  ,[LIMIT_AVAILABLE_ROOT_THB] = #CLS_MAP.[LIMIT_AVAILABLE_ROOT_THB]
					  ,[LIMIT_AVAILABLE_L1_THB] = #CLS_MAP.[LIMIT_AVAILABLE_L1_THB]
					  ,[LIMIT_AVAILABLE_L2_THB] = #CLS_MAP.[LIMIT_AVAILABLE_L2_THB]
					  ,[LIMIT_AVAILABLE_L3_THB] = #CLS_MAP.[LIMIT_AVAILABLE_L3_THB]
					  ,[LIMIT_AVAILABLE_L4_THB] = #CLS_MAP.[LIMIT_AVAILABLE_L4_THB]
					  ,[LIMIT_AVAILABLE_L5_THB] = #CLS_MAP.[LIMIT_AVAILABLE_L5_THB]
					  ,[LIMIT_AVAILABLE_L6_THB] = #CLS_MAP.[LIMIT_AVAILABLE_L6_THB]
					  ,[LIMIT_AVAILABLE_L7_THB] = #CLS_MAP.[LIMIT_AVAILABLE_L7_THB]
					  ,[LIMIT_AVAILABLE_L8_THB] = #CLS_MAP.[LIMIT_AVAILABLE_L8_THB]
					  ,[LIMIT_AVAILABLE_PRODUCT_THB] = #CLS_MAP.[LIMIT_AVAILABLE_PRODUCT_THB]
					  ,[LIMIT_AVAI_RATIO_L1_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_L1_THB]
					  ,[LIMIT_AVAI_RATIO_L2_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_L2_THB]
					  ,[LIMIT_AVAI_RATIO_L3_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_L3_THB]
					  ,[LIMIT_AVAI_RATIO_L4_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_L4_THB]
					  ,[LIMIT_AVAI_RATIO_L5_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_L5_THB]
					  ,[LIMIT_AVAI_RATIO_L6_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_L6_THB]
					  ,[LIMIT_AVAI_RATIO_L7_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_L7_THB]
					  ,[LIMIT_AVAI_RATIO_L8_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_L8_THB]
					  ,[LIMIT_AVAI_RATIO_PRODUCT_THB] = #CLS_MAP.[LIMIT_AVAI_RATIO_PRODUCT_THB]
					  ,[HOLD_AMOUNT_THB] = #CLS_MAP.[HOLD_AMOUNT_THB]
					  ,[HOLD_AMOUNT_CCY] = #CLS_MAP.[HOLD_AMOUNT_CCY]
					  ,[LIMIT_AMOUNT_CA_THB] = #CLS_MAP.[LIMIT_AMOUNT_CA_THB]
					  ,[LIMIT_USED_CA_THB] = #CLS_MAP.[LIMIT_USED_CA_THB]
					  ,[LIMIT_AVAILABLE_CA_THB] = #CLS_MAP.[LIMIT_AVAILABLE_CA_THB]
					  ,[GECID] = #CLS_MAP.[GECID]
					  ,[CREATED_DATE] = #CLS_MAP.[CREATED_DATE]
					  ,[UPDATE_DATE] = #CLS_MAP.[UPDATE_DATE]
					  ,[UPDATE_STATUS_DATE] = #CLS_MAP.[UPDATE_STATUS_DATE]
					  ,[ASOFDATE] = #CLS_MAP.[ASOFDATE]
					  ,[ETL_DT] = #CLS_MAP.[ETL_DT]
					  ,[LIMIT_PRODUCT_CA_NO] = #CLS_MAP.[LIMIT_PRODUCT_CA_NO]
					  ,[LIMIT_PRODUCT_CA_DATE] = #CLS_MAP.[LIMIT_PRODUCT_CA_DATE]
					  ,[LIMIT_PRODUCT_APPV_DATE] = #CLS_MAP.[LIMIT_PRODUCT_APPV_DATE]
					  ,[LIMIT_PRODUCT_APPV_AUTH_UNIT] = #CLS_MAP.[LIMIT_PRODUCT_APPV_AUTH_UNIT]
					  ,[LIMIT_PRODUCT_PREVIOUS_CA_NO] = #CLS_MAP.[LIMIT_PRODUCT_PREVIOUS_CA_NO]
					  ,[LIMIT_PRODUCT_EFFECT_DATE] = #CLS_MAP.[LIMIT_PRODUCT_EFFECT_DATE]
					  ,[LIMIT_PRODUCT_EXPIRE_DATE] = #CLS_MAP.[LIMIT_PRODUCT_EXPIRE_DATE]
					  ,[LIMIT_PRODUCT_SIGN_DATE] = #CLS_MAP.[LIMIT_PRODUCT_SIGN_DATE]
					  ,[LIMIT_CHANGE_ROOT_THB] = #CLS_MAP.[LIMIT_CHANGE_ROOT_THB]
					  ,[LIMIT_CHANGE_L1_THB] = #CLS_MAP.[LIMIT_CHANGE_L1_THB]
					  ,[LIMIT_CHANGE_L2_THB] = #CLS_MAP.[LIMIT_CHANGE_L2_THB]
					  ,[LIMIT_CHANGE_L3_THB] = #CLS_MAP.[LIMIT_CHANGE_L3_THB]
					  ,[LIMIT_CHANGE_L4_THB] = #CLS_MAP.[LIMIT_CHANGE_L4_THB]
					  ,[LIMIT_CHANGE_L5_THB] = #CLS_MAP.[LIMIT_CHANGE_L5_THB]
					  ,[LIMIT_CHANGE_L6_THB] = #CLS_MAP.[LIMIT_CHANGE_L6_THB]
					  ,[LIMIT_CHANGE_L7_THB] = #CLS_MAP.[LIMIT_CHANGE_L7_THB]
					  ,[LIMIT_CHANGE_L8_THB] = #CLS_MAP.[LIMIT_CHANGE_L8_THB]
					  ,[LIMIT_CHANGE_PRODUCT_THB] = #CLS_MAP.[LIMIT_CHANGE_PRODUCT_THB]
					  ,[LIMIT_CHANGE_DATE] = #CLS_MAP.[LIMIT_CHANGE_DATE]
					  ,MAPPING_STATUS = #CLS_MAP.MAPPING_STATUS 
					  ,[LEADER1_UPDATE_DATE] = @endDate
					FROM [CLS_WHEN_APPROVE] INNER JOIN #CLS_MAP
						ON CLS_WHEN_APPROVE.CIF = #CLS_MAP.CIF
							AND CLS_WHEN_APPROVE.LEADER1_CA_OLD_ID = #CLS_MAP.LEADER1_CA_OLD_ID
							AND CLS_WHEN_APPROVE.CLS_LIMIT_PRODUCT_ID_KEY = #CLS_MAP.CLS_LIMIT_PRODUCT_ID_KEY
				 WHERE [CLS_WHEN_APPROVE].MAPPING_STATUS IS NULL

				-- INSERT ข้อมูลที่มีใน TEMP TABLE แต่ยังไม่มีใน CLS_WHEN_APPROVE
				INSERT INTO [CLS_WHEN_APPROVE]
					   ([CIF]
					   ,[LEADER1_CA_OLD_ID]
					   ,[CLS_LIMIT_ROOT_ID_KEY]
					   ,[CLS_LIMIT_L1_ID_KEY]
					   ,[CLS_LIMIT_L2_ID_KEY]
					   ,[CLS_LIMIT_L3_ID_KEY]
					   ,[CLS_LIMIT_L4_ID_KEY]
					   ,[CLS_LIMIT_L5_ID_KEY]
					   ,[CLS_LIMIT_L6_ID_KEY]
					   ,[CLS_LIMIT_L7_ID_KEY]
					   ,[CLS_LIMIT_L8_ID_KEY]
					   ,[CLS_LIMIT_PRODUCT_ID_KEY]
					   ,[PRODUCT_KEY]
					   ,[CLS_PRODUCT_ID_KEY]
					   ,[LIMIT_STATUS_ID_KEY]
					   ,[CLS_CURRENCY_ID_KEY]
					   ,[LIMIT_PURPOSE_ID_KEY]
					   ,[BUSINESS_RISK_ID_KEY]
					   ,[CA_KEY]
					   ,[CREATED_BY_USER_CODE]
					   ,[CREATED_BY_USER_NAME]
					   ,[UPDATED_BY_USER_CODE]
					   ,[UPDATED_BY_USER_NAME]
					   ,[UPDATED_STATUS_BY_USER_CODE]
					   ,[UPDATED_STATUS_BY_USER_NAME]
					   ,[LIMIT_NO_ROOT]
					   ,[LIMIT_NO_L1]
					   ,[LIMIT_NO_L2]
					   ,[LIMIT_NO_L3]
					   ,[LIMIT_NO_L4]
					   ,[LIMIT_NO_L5]
					   ,[LIMIT_NO_L6]
					   ,[LIMIT_NO_L7]
					   ,[LIMIT_NO_L8]
					   ,[LIMIT_NO_PRODUCT]
					   ,[LIMIT_ROOT_STATUS]
					   ,[LIMIT_L1_STATUS]
					   ,[LIMIT_L2_STATUS]
					   ,[LIMIT_L3_STATUS]
					   ,[LIMIT_L4_STATUS]
					   ,[LIMIT_L5_STATUS]
					   ,[LIMIT_L6_STATUS]
					   ,[LIMIT_L7_STATUS]
					   ,[LIMIT_L8_STATUS]
					   ,[LIMIT_PRODUCT_STATUS]
					   ,[LIMIT_REVOLVING_TYPE]
					   ,[APPL_KEY]
					   ,[APPL_ID]
					   ,[PRODUCT_CODE]
					   ,[PRODUCT_NAME]
					   ,[ACCOUNT_NO]
					   ,[CIF_LIST_CA_NO]
					   ,[CIF_LIST_ROOT]
					   ,[CIF_LIST_PRODUCT]
					   ,[NO_OF_CIF_CANO]
					   ,[LIMIT_AMOUNT_ROOT_THB]
					   ,[LIMIT_AMOUNT_ROOT_CCY]
					   ,[LIMIT_AMOUNT_L1_THB]
					   ,[LIMIT_AMOUNT_L1_CCY]
					   ,[LIMIT_AMOUNT_L2_THB]
					   ,[LIMIT_AMOUNT_L2_CCY]
					   ,[LIMIT_AMOUNT_L3_THB]
					   ,[LIMIT_AMOUNT_L3_CCY]
					   ,[LIMIT_AMOUNT_L4_THB]
					   ,[LIMIT_AMOUNT_L4_CCY]
					   ,[LIMIT_AMOUNT_L5_THB]
					   ,[LIMIT_AMOUNT_L5_CCY]
					   ,[LIMIT_AMOUNT_L6_THB]
					   ,[LIMIT_AMOUNT_L6_CCY]
					   ,[LIMIT_AMOUNT_L7_THB]
					   ,[LIMIT_AMOUNT_L7_CCY]
					   ,[LIMIT_AMOUNT_L8_THB]
					   ,[LIMIT_AMOUNT_L8_CCY]
					   ,[LIMIT_AMOUNT_PRODUCT_THB]
					   ,[LIMIT_AMOUNT_PRODUCT_CCY]
					   ,[LIMIT_USED_ROOT_THB]
					   ,[LIMIT_USED_ROOT_CCY]
					   ,[LIMIT_USED_L1_THB]
					   ,[LIMIT_USED_L1_CCY]
					   ,[LIMIT_USED_L2_THB]
					   ,[LIMIT_USED_L2_CCY]
					   ,[LIMIT_USED_L3_THB]
					   ,[LIMIT_USED_L3_CCY]
					   ,[LIMIT_USED_L4_THB]
					   ,[LIMIT_USED_L4_CCY]
					   ,[LIMIT_USED_L5_THB]
					   ,[LIMIT_USED_L5_CCY]
					   ,[LIMIT_USED_L6_THB]
					   ,[LIMIT_USED_L6_CCY]
					   ,[LIMIT_USED_L7_THB]
					   ,[LIMIT_USED_L7_CCY]
					   ,[LIMIT_USED_L8_THB]
					   ,[LIMIT_USED_L8_CCY]
					   ,[LIMIT_USED_PRODUCT_THB]
					   ,[LIMIT_USED_PRODUCT_CCY]
					   ,[LIMIT_AVAILABLE_ROOT_THB]
					   ,[LIMIT_AVAILABLE_L1_THB]
					   ,[LIMIT_AVAILABLE_L2_THB]
					   ,[LIMIT_AVAILABLE_L3_THB]
					   ,[LIMIT_AVAILABLE_L4_THB]
					   ,[LIMIT_AVAILABLE_L5_THB]
					   ,[LIMIT_AVAILABLE_L6_THB]
					   ,[LIMIT_AVAILABLE_L7_THB]
					   ,[LIMIT_AVAILABLE_L8_THB]
					   ,[LIMIT_AVAILABLE_PRODUCT_THB]
					   ,[LIMIT_AVAI_RATIO_L1_THB]
					   ,[LIMIT_AVAI_RATIO_L2_THB]
					   ,[LIMIT_AVAI_RATIO_L3_THB]
					   ,[LIMIT_AVAI_RATIO_L4_THB]
					   ,[LIMIT_AVAI_RATIO_L5_THB]
					   ,[LIMIT_AVAI_RATIO_L6_THB]
					   ,[LIMIT_AVAI_RATIO_L7_THB]
					   ,[LIMIT_AVAI_RATIO_L8_THB]
					   ,[LIMIT_AVAI_RATIO_PRODUCT_THB]
					   ,[HOLD_AMOUNT_THB]
					   ,[HOLD_AMOUNT_CCY]
					   ,[LIMIT_AMOUNT_CA_THB]
					   ,[LIMIT_USED_CA_THB]
					   ,[LIMIT_AVAILABLE_CA_THB]
					   ,[GECID]
					   ,[CREATED_DATE]
					   ,[UPDATE_DATE]
					   ,[UPDATE_STATUS_DATE]
					   ,[ASOFDATE]
					   ,[ETL_DT]
					   ,[LIMIT_PRODUCT_CA_NO]
					   ,[LIMIT_PRODUCT_CA_DATE]
					   ,[LIMIT_PRODUCT_APPV_DATE]
					   ,[LIMIT_PRODUCT_APPV_AUTH_UNIT]
					   ,[LIMIT_PRODUCT_PREVIOUS_CA_NO]
					   ,[LIMIT_PRODUCT_EFFECT_DATE]
					   ,[LIMIT_PRODUCT_EXPIRE_DATE]
					   ,[LIMIT_PRODUCT_SIGN_DATE]
					   ,[LIMIT_CHANGE_ROOT_THB]
					   ,[LIMIT_CHANGE_L1_THB]
					   ,[LIMIT_CHANGE_L2_THB]
					   ,[LIMIT_CHANGE_L3_THB]
					   ,[LIMIT_CHANGE_L4_THB]
					   ,[LIMIT_CHANGE_L5_THB]
					   ,[LIMIT_CHANGE_L6_THB]
					   ,[LIMIT_CHANGE_L7_THB]
					   ,[LIMIT_CHANGE_L8_THB]
					   ,[LIMIT_CHANGE_PRODUCT_THB]
					   ,[LIMIT_CHANGE_DATE]
					   ,[MAPPING_STATUS]
					   ,[LEADER1_CREATED_DATE])
				 SELECT CIF
						,LEADER1_CA_OLD_ID
						,[CLS_LIMIT_ROOT_ID_KEY]
						,[CLS_LIMIT_L1_ID_KEY]
						,[CLS_LIMIT_L2_ID_KEY]
						,[CLS_LIMIT_L3_ID_KEY]
						,[CLS_LIMIT_L4_ID_KEY]
						,[CLS_LIMIT_L5_ID_KEY]
						,[CLS_LIMIT_L6_ID_KEY]
						,[CLS_LIMIT_L7_ID_KEY]
						,[CLS_LIMIT_L8_ID_KEY]
						,[CLS_LIMIT_PRODUCT_ID_KEY]
						,[PRODUCT_KEY]
						,[CLS_PRODUCT_ID_KEY]
						,[LIMIT_STATUS_ID_KEY]
						,[CLS_CURRENCY_ID_KEY]
						,[LIMIT_PURPOSE_ID_KEY]
						,[BUSINESS_RISK_ID_KEY]
						,[CA_KEY]
						,[CREATED_BY_USER_CODE]
						,[CREATED_BY_USER_NAME]
						,[UPDATED_BY_USER_CODE]
						,[UPDATED_BY_USER_NAME]
						,[UPDATED_STATUS_BY_USER_CODE]
						,[UPDATED_STATUS_BY_USER_NAME]
						,[LIMIT_NO_ROOT]
						,[LIMIT_NO_L1]
						,[LIMIT_NO_L2]
						,[LIMIT_NO_L3]
						,[LIMIT_NO_L4]
						,[LIMIT_NO_L5]
						,[LIMIT_NO_L6]
						,[LIMIT_NO_L7]
						,[LIMIT_NO_L8]
						,[LIMIT_NO_PRODUCT]
						,[LIMIT_ROOT_STATUS]
						,[LIMIT_L1_STATUS]
						,[LIMIT_L2_STATUS]
						,[LIMIT_L3_STATUS]
						,[LIMIT_L4_STATUS]
						,[LIMIT_L5_STATUS]
						,[LIMIT_L6_STATUS]
						,[LIMIT_L7_STATUS]
						,[LIMIT_L8_STATUS]
						,[LIMIT_PRODUCT_STATUS]
						,[LIMIT_REVOLVING_TYPE]
						,[APPL_KEY]
						,[APPL_ID]
						,[PRODUCT_CODE]
						,[PRODUCT_NAME]
						,[ACCOUNT_NO]
						,[CIF_LIST_CA_NO]
						,[CIF_LIST_ROOT]
						,[CIF_LIST_PRODUCT]
						,[NO_OF_CIF_CANO]
						,[LIMIT_AMOUNT_ROOT_THB]
						,[LIMIT_AMOUNT_ROOT_CCY]
						,[LIMIT_AMOUNT_L1_THB]
						,[LIMIT_AMOUNT_L1_CCY]
						,[LIMIT_AMOUNT_L2_THB]
						,[LIMIT_AMOUNT_L2_CCY]
						,[LIMIT_AMOUNT_L3_THB]
						,[LIMIT_AMOUNT_L3_CCY]
						,[LIMIT_AMOUNT_L4_THB]
						,[LIMIT_AMOUNT_L4_CCY]
						,[LIMIT_AMOUNT_L5_THB]
						,[LIMIT_AMOUNT_L5_CCY]
						,[LIMIT_AMOUNT_L6_THB]
						,[LIMIT_AMOUNT_L6_CCY]
						,[LIMIT_AMOUNT_L7_THB]
						,[LIMIT_AMOUNT_L7_CCY]
						,[LIMIT_AMOUNT_L8_THB]
						,[LIMIT_AMOUNT_L8_CCY]
						,[LIMIT_AMOUNT_PRODUCT_THB]
						,[LIMIT_AMOUNT_PRODUCT_CCY]
						,[LIMIT_USED_ROOT_THB]
						,[LIMIT_USED_ROOT_CCY]
						,[LIMIT_USED_L1_THB]
						,[LIMIT_USED_L1_CCY]
						,[LIMIT_USED_L2_THB]
						,[LIMIT_USED_L2_CCY]
						,[LIMIT_USED_L3_THB]
						,[LIMIT_USED_L3_CCY]
						,[LIMIT_USED_L4_THB]
						,[LIMIT_USED_L4_CCY]
						,[LIMIT_USED_L5_THB]
						,[LIMIT_USED_L5_CCY]
						,[LIMIT_USED_L6_THB]
						,[LIMIT_USED_L6_CCY]
						,[LIMIT_USED_L7_THB]
						,[LIMIT_USED_L7_CCY]
						,[LIMIT_USED_L8_THB]
						,[LIMIT_USED_L8_CCY]
						,[LIMIT_USED_PRODUCT_THB]
						,[LIMIT_USED_PRODUCT_CCY]
						,[LIMIT_AVAILABLE_ROOT_THB]
						,[LIMIT_AVAILABLE_L1_THB]
						,[LIMIT_AVAILABLE_L2_THB]
						,[LIMIT_AVAILABLE_L3_THB]
						,[LIMIT_AVAILABLE_L4_THB]
						,[LIMIT_AVAILABLE_L5_THB]
						,[LIMIT_AVAILABLE_L6_THB]
						,[LIMIT_AVAILABLE_L7_THB]
						,[LIMIT_AVAILABLE_L8_THB]
						,[LIMIT_AVAILABLE_PRODUCT_THB]
						,[LIMIT_AVAI_RATIO_L1_THB]
						,[LIMIT_AVAI_RATIO_L2_THB]
						,[LIMIT_AVAI_RATIO_L3_THB]
						,[LIMIT_AVAI_RATIO_L4_THB]
						,[LIMIT_AVAI_RATIO_L5_THB]
						,[LIMIT_AVAI_RATIO_L6_THB]
						,[LIMIT_AVAI_RATIO_L7_THB]
						,[LIMIT_AVAI_RATIO_L8_THB]
						,[LIMIT_AVAI_RATIO_PRODUCT_THB]
						,[HOLD_AMOUNT_THB]
						,[HOLD_AMOUNT_CCY]
						,[LIMIT_AMOUNT_CA_THB]
						,[LIMIT_USED_CA_THB]
						,[LIMIT_AVAILABLE_CA_THB]
						,[GECID]
						,[CREATED_DATE]
						,[UPDATE_DATE]
						,[UPDATE_STATUS_DATE]
						,[ASOFDATE]
						,[ETL_DT]
						,LIMIT_PRODUCT_CA_NO
						,LIMIT_PRODUCT_CA_DATE
						,LIMIT_PRODUCT_APPV_DATE
						,LIMIT_PRODUCT_APPV_AUTH_UNIT
						,LIMIT_PRODUCT_PREVIOUS_CA_NO
						,LIMIT_PRODUCT_EFFECT_DATE
						,LIMIT_PRODUCT_EXPIRE_DATE
						,LIMIT_PRODUCT_SIGN_DATE
						,[LIMIT_AMOUNT_ROOT_THB] AS LIMIT_CHANGE_ROOT_THB
						,[LIMIT_AMOUNT_L1_THB] AS LIMIT_CHANGE_L1_THB
						,[LIMIT_AMOUNT_L2_THB] AS LIMIT_CHANGE_L2_THB
						,[LIMIT_AMOUNT_L3_THB] AS LIMIT_CHANGE_L3_THB
						,[LIMIT_AMOUNT_L4_THB] AS LIMIT_CHANGE_L4_THB
						,[LIMIT_AMOUNT_L5_THB] AS LIMIT_CHANGE_L5_THB
						,[LIMIT_AMOUNT_L6_THB] AS LIMIT_CHANGE_L6_THB
						,[LIMIT_AMOUNT_L7_THB] AS LIMIT_CHANGE_L7_THB
						,[LIMIT_AMOUNT_L8_THB] AS LIMIT_CHANGE_L8_THB
						,[LIMIT_AMOUNT_PRODUCT_THB] AS LIMIT_CHANGE_PRODUCT_THB
						,LIMIT_CHANGE_DATE
						,MAPPING_STATUS
						,@endDate AS LEADER1_CREATED_DATE
					FROM #CLS_MAP
					WHERE NOT EXISTS (
							SELECT CIF,LEADER1_CA_OLD_ID,CLS_LIMIT_PRODUCT_ID_KEY
							FROM CLS_WHEN_APPROVE
							WHERE CLS_WHEN_APPROVE.CIF = #CLS_MAP.CIF
								AND CLS_WHEN_APPROVE.LEADER1_CA_OLD_ID = #CLS_MAP.LEADER1_CA_OLD_ID
								AND CLS_WHEN_APPROVE.CLS_LIMIT_PRODUCT_ID_KEY = #CLS_MAP.CLS_LIMIT_PRODUCT_ID_KEY
							)

				DROP TABLE #CLS_MAP

				-- ทำการ UPDATE MAPPING_STATUS ที่เป็นเลข CA เดียวกัน เพื่อให้รู้ว่า CA นั้น MAPPING เจอแล้ว
				-- โดยตัวที่ทำการ MAPPING นั้น COUNT PRODUCT ที่ Approve ต้องตรงกัน และ SUM วงเงินที่ Approve ต้องตรงกันด้วย
				UPDATE [CLS_WHEN_APPROVE]
				   SET MAPPING_STATUS = 'R'
				FROM CLS_WHEN_APPROVE INNER JOIN (
													SELECT [REPORT07_SUMMARY].[OLD_ID] AS LEADER1_CA_OLD_ID
															,COUNT(DISTINCT [REPORT07_SUMMARY].CIF) AS CIFs
															,SUM([REPORT07_SUMMARY].APPROVE_VALUE) APPROVE_VALUEs
															,COUNT(*) COUNT_RECORDs
															,LIMIT_CIFs
															,LIMIT_CHANGEs
															,COUNT_LIMIT_CHANGE_RECORDs
													FROM [REPORT07_SUMMARY] INNER JOIN (SELECT [LEADER1_CA_OLD_ID]
																								,COUNT(DISTINCT CIF) LIMIT_CIFs
																								,SUM(LIMIT_CHANGE_PRODUCT_THB) LIMIT_CHANGEs
																								, COUNT(*) COUNT_LIMIT_CHANGE_RECORDs
																						FROM CLS_WHEN_APPROVE
																						WHERE MAPPING_STATUS IS NOT NULL 
																							AND MAPPING_STATUS <> 'R'
																							AND LIMIT_CHANGE_PRODUCT_THB IS NOT NULL
																							AND LIMIT_CHANGE_DATE IS NOT NULL
																						GROUP BY [LEADER1_CA_OLD_ID]) AS CLS
															ON [REPORT07_SUMMARY].[OLD_ID] = CLS.LEADER1_CA_OLD_ID
													WHERE ([REPORT07_SUMMARY].SUBJECT_DETAIL_ID = 101 OR [REPORT07_SUMMARY].SUBJECT_DETAIL_ID = 102 OR [REPORT07_SUMMARY].SUBJECT_DETAIL_ID = 103
															OR [REPORT07_SUMMARY].SUBJECT_DETAIL_ID = 104 OR [REPORT07_SUMMARY].SUBJECT_DETAIL_ID = 105)
													GROUP BY [REPORT07_SUMMARY].[OLD_ID],LIMIT_CIFs,LIMIT_CHANGEs,COUNT_LIMIT_CHANGE_RECORDs
													HAVING COUNT(DISTINCT [REPORT07_SUMMARY].CIF) = LIMIT_CIFs
															AND SUM([REPORT07_SUMMARY].APPROVE_VALUE) = LIMIT_CHANGEs
															AND COUNT(*) = COUNT_LIMIT_CHANGE_RECORDs
													) AS C2
					ON CLS_WHEN_APPROVE.LEADER1_CA_OLD_ID = C2.LEADER1_CA_OLD_ID
				WHERE MAPPING_STATUS IS NULL
			END
			-- End Check Older CLS Before Import
			
			-- ทำการเปลี่ยน MAPPING_STATUS ของข้อมูลเก่าที่สร้างมาแล้วเกิน 150 วัน ให้เป็น expire
			UPDATE [CLS_WHEN_APPROVE]
				SET MAPPING_STATUS = 'E'
			WHERE MAPPING_STATUS IS NULL
				AND [LEADER1_CREATED_DATE] < DATEADD(day,-150,@endDate)
			-- End ทำการเปลี่ยน MAPPING_STATUS ของข้อมูลเก่าที่สร้างมาแล้วเกิน 150 วัน ให้เป็น expire

			-- Import Today Approve CLS
			INSERT INTO [CLS_WHEN_APPROVE]
					   ([CIF]
					   ,[LEADER1_CA_OLD_ID]
					   ,[CLS_LIMIT_ROOT_ID_KEY]
					   ,[CLS_LIMIT_L1_ID_KEY]
					   ,[CLS_LIMIT_L2_ID_KEY]
					   ,[CLS_LIMIT_L3_ID_KEY]
					   ,[CLS_LIMIT_L4_ID_KEY]
					   ,[CLS_LIMIT_L5_ID_KEY]
					   ,[CLS_LIMIT_L6_ID_KEY]
					   ,[CLS_LIMIT_L7_ID_KEY]
					   ,[CLS_LIMIT_L8_ID_KEY]
					   ,[CLS_LIMIT_PRODUCT_ID_KEY]
					   ,[PRODUCT_KEY]
					   ,[CLS_PRODUCT_ID_KEY]
					   ,[LIMIT_STATUS_ID_KEY]
					   ,[CLS_CURRENCY_ID_KEY]
					   ,[LIMIT_PURPOSE_ID_KEY]
					   ,[BUSINESS_RISK_ID_KEY]
					   ,[CA_KEY]
					   ,[CREATED_BY_USER_CODE]
					   ,[CREATED_BY_USER_NAME]
					   ,[UPDATED_BY_USER_CODE]
					   ,[UPDATED_BY_USER_NAME]
					   ,[UPDATED_STATUS_BY_USER_CODE]
					   ,[UPDATED_STATUS_BY_USER_NAME]
					   ,[LIMIT_NO_ROOT]
					   ,[LIMIT_NO_L1]
					   ,[LIMIT_NO_L2]
					   ,[LIMIT_NO_L3]
					   ,[LIMIT_NO_L4]
					   ,[LIMIT_NO_L5]
					   ,[LIMIT_NO_L6]
					   ,[LIMIT_NO_L7]
					   ,[LIMIT_NO_L8]
					   ,[LIMIT_NO_PRODUCT]
					   ,[LIMIT_ROOT_STATUS]
					   ,[LIMIT_L1_STATUS]
					   ,[LIMIT_L2_STATUS]
					   ,[LIMIT_L3_STATUS]
					   ,[LIMIT_L4_STATUS]
					   ,[LIMIT_L5_STATUS]
					   ,[LIMIT_L6_STATUS]
					   ,[LIMIT_L7_STATUS]
					   ,[LIMIT_L8_STATUS]
					   ,[LIMIT_PRODUCT_STATUS]
					   ,[LIMIT_REVOLVING_TYPE]
					   ,[APPL_KEY]
					   ,[APPL_ID]
					   ,[PRODUCT_CODE]
					   ,[PRODUCT_NAME]
					   ,[ACCOUNT_NO]
					   ,[CIF_LIST_CA_NO]
					   ,[CIF_LIST_ROOT]
					   ,[CIF_LIST_PRODUCT]
					   ,[NO_OF_CIF_CANO]
					   ,[LIMIT_AMOUNT_ROOT_THB]
					   ,[LIMIT_AMOUNT_ROOT_CCY]
					   ,[LIMIT_AMOUNT_L1_THB]
					   ,[LIMIT_AMOUNT_L1_CCY]
					   ,[LIMIT_AMOUNT_L2_THB]
					   ,[LIMIT_AMOUNT_L2_CCY]
					   ,[LIMIT_AMOUNT_L3_THB]
					   ,[LIMIT_AMOUNT_L3_CCY]
					   ,[LIMIT_AMOUNT_L4_THB]
					   ,[LIMIT_AMOUNT_L4_CCY]
					   ,[LIMIT_AMOUNT_L5_THB]
					   ,[LIMIT_AMOUNT_L5_CCY]
					   ,[LIMIT_AMOUNT_L6_THB]
					   ,[LIMIT_AMOUNT_L6_CCY]
					   ,[LIMIT_AMOUNT_L7_THB]
					   ,[LIMIT_AMOUNT_L7_CCY]
					   ,[LIMIT_AMOUNT_L8_THB]
					   ,[LIMIT_AMOUNT_L8_CCY]
					   ,[LIMIT_AMOUNT_PRODUCT_THB]
					   ,[LIMIT_AMOUNT_PRODUCT_CCY]
					   ,[LIMIT_USED_ROOT_THB]
					   ,[LIMIT_USED_ROOT_CCY]
					   ,[LIMIT_USED_L1_THB]
					   ,[LIMIT_USED_L1_CCY]
					   ,[LIMIT_USED_L2_THB]
					   ,[LIMIT_USED_L2_CCY]
					   ,[LIMIT_USED_L3_THB]
					   ,[LIMIT_USED_L3_CCY]
					   ,[LIMIT_USED_L4_THB]
					   ,[LIMIT_USED_L4_CCY]
					   ,[LIMIT_USED_L5_THB]
					   ,[LIMIT_USED_L5_CCY]
					   ,[LIMIT_USED_L6_THB]
					   ,[LIMIT_USED_L6_CCY]
					   ,[LIMIT_USED_L7_THB]
					   ,[LIMIT_USED_L7_CCY]
					   ,[LIMIT_USED_L8_THB]
					   ,[LIMIT_USED_L8_CCY]
					   ,[LIMIT_USED_PRODUCT_THB]
					   ,[LIMIT_USED_PRODUCT_CCY]
					   ,[LIMIT_AVAILABLE_ROOT_THB]
					   ,[LIMIT_AVAILABLE_L1_THB]
					   ,[LIMIT_AVAILABLE_L2_THB]
					   ,[LIMIT_AVAILABLE_L3_THB]
					   ,[LIMIT_AVAILABLE_L4_THB]
					   ,[LIMIT_AVAILABLE_L5_THB]
					   ,[LIMIT_AVAILABLE_L6_THB]
					   ,[LIMIT_AVAILABLE_L7_THB]
					   ,[LIMIT_AVAILABLE_L8_THB]
					   ,[LIMIT_AVAILABLE_PRODUCT_THB]
					   ,[LIMIT_AVAI_RATIO_L1_THB]
					   ,[LIMIT_AVAI_RATIO_L2_THB]
					   ,[LIMIT_AVAI_RATIO_L3_THB]
					   ,[LIMIT_AVAI_RATIO_L4_THB]
					   ,[LIMIT_AVAI_RATIO_L5_THB]
					   ,[LIMIT_AVAI_RATIO_L6_THB]
					   ,[LIMIT_AVAI_RATIO_L7_THB]
					   ,[LIMIT_AVAI_RATIO_L8_THB]
					   ,[LIMIT_AVAI_RATIO_PRODUCT_THB]
					   ,[HOLD_AMOUNT_THB]
					   ,[HOLD_AMOUNT_CCY]
					   ,[LIMIT_AMOUNT_CA_THB]
					   ,[LIMIT_USED_CA_THB]
					   ,[LIMIT_AVAILABLE_CA_THB]
					   ,[GECID]
					   ,[CREATED_DATE]
					   ,[UPDATE_DATE]
					   ,[UPDATE_STATUS_DATE]
					   ,[ASOFDATE]
					   ,[ETL_DT]
					   ,[LIMIT_PRODUCT_CA_NO]
					   ,[LIMIT_PRODUCT_CA_DATE]
					   ,[LIMIT_PRODUCT_APPV_DATE]
					   ,[LIMIT_PRODUCT_APPV_AUTH_UNIT]
					   ,[LIMIT_PRODUCT_PREVIOUS_CA_NO]
					   ,[LIMIT_PRODUCT_EFFECT_DATE]
					   ,[LIMIT_PRODUCT_EXPIRE_DATE]
					   ,[LIMIT_PRODUCT_SIGN_DATE]
						,LEADER1_CREATED_DATE)

				SELECT --L.[MONTH_KEY]
					C.CIF
				  ,R.LEADER1_CA_OLD_ID
				  ,L.[CLS_LIMIT_ROOT_ID_KEY]
				  ,L.[CLS_LIMIT_L1_ID_KEY]
				  ,L.[CLS_LIMIT_L2_ID_KEY]
				  ,L.[CLS_LIMIT_L3_ID_KEY]
				  ,L.[CLS_LIMIT_L4_ID_KEY]
				  ,L.[CLS_LIMIT_L5_ID_KEY]
				  ,L.[CLS_LIMIT_L6_ID_KEY]
				  ,L.[CLS_LIMIT_L7_ID_KEY]
				  ,L.[CLS_LIMIT_L8_ID_KEY]
				  ,L.[CLS_LIMIT_PRODUCT_ID_KEY]
				  ,L.[PRODUCT_KEY]
				  ,L.[CLS_PRODUCT_ID_KEY]
				  ,L.[LIMIT_STATUS_ID_KEY]
				  ,L.[CLS_CURRENCY_ID_KEY]
				  ,L.[LIMIT_PURPOSE_ID_KEY]
				  ,L.[BUSINESS_RISK_ID_KEY]
				  ,L.[CA_KEY]
				  ,L.[CREATED_BY_USER_CODE]
				  ,L.[CREATED_BY_USER_NAME]
				  ,L.[UPDATED_BY_USER_CODE]
				  ,L.[UPDATED_BY_USER_NAME]
				  ,L.[UPDATED_STATUS_BY_USER_CODE]
				  ,L.[UPDATED_STATUS_BY_USER_NAME]
				  ,L.[LIMIT_NO_ROOT]
				  ,L.[LIMIT_NO_L1]
				  ,L.[LIMIT_NO_L2]
				  ,L.[LIMIT_NO_L3]
				  ,L.[LIMIT_NO_L4]
				  ,L.[LIMIT_NO_L5]
				  ,L.[LIMIT_NO_L6]
				  ,L.[LIMIT_NO_L7]
				  ,L.[LIMIT_NO_L8]
				  ,L.[LIMIT_NO_PRODUCT]
				  ,L.[LIMIT_ROOT_STATUS]
				  ,L.[LIMIT_L1_STATUS]
				  ,L.[LIMIT_L2_STATUS]
				  ,L.[LIMIT_L3_STATUS]
				  ,L.[LIMIT_L4_STATUS]
				  ,L.[LIMIT_L5_STATUS]
				  ,L.[LIMIT_L6_STATUS]
				  ,L.[LIMIT_L7_STATUS]
				  ,L.[LIMIT_L8_STATUS]
				  ,L.[LIMIT_PRODUCT_STATUS]
				  ,L.[LIMIT_REVOLVING_TYPE]
				  ,L.[APPL_KEY]
				  ,L.[APPL_ID]
				  ,L.[PRODUCT_CODE]
				  ,L.[PRODUCT_NAME]
				  ,L.[ACCOUNT_NO]
				  ,L.[CIF_LIST_CA_NO]
				  ,L.[CIF_LIST_ROOT]
				  ,L.[CIF_LIST_PRODUCT]
				  ,L.[NO_OF_CIF_CANO]
				  ,L.[LIMIT_AMOUNT_ROOT_THB]
				  ,L.[LIMIT_AMOUNT_ROOT_CCY]
				  ,L.[LIMIT_AMOUNT_L1_THB]
				  ,L.[LIMIT_AMOUNT_L1_CCY]
				  ,L.[LIMIT_AMOUNT_L2_THB]
				  ,L.[LIMIT_AMOUNT_L2_CCY]
				  ,L.[LIMIT_AMOUNT_L3_THB]
				  ,L.[LIMIT_AMOUNT_L3_CCY]
				  ,L.[LIMIT_AMOUNT_L4_THB]
				  ,L.[LIMIT_AMOUNT_L4_CCY]
				  ,L.[LIMIT_AMOUNT_L5_THB]
				  ,L.[LIMIT_AMOUNT_L5_CCY]
				  ,L.[LIMIT_AMOUNT_L6_THB]
				  ,L.[LIMIT_AMOUNT_L6_CCY]
				  ,L.[LIMIT_AMOUNT_L7_THB]
				  ,L.[LIMIT_AMOUNT_L7_CCY]
				  ,L.[LIMIT_AMOUNT_L8_THB]
				  ,L.[LIMIT_AMOUNT_L8_CCY]
				  ,L.[LIMIT_AMOUNT_PRODUCT_THB]
				  ,L.[LIMIT_AMOUNT_PRODUCT_CCY]
				  ,L.[LIMIT_USED_ROOT_THB]
				  ,L.[LIMIT_USED_ROOT_CCY]
				  ,L.[LIMIT_USED_L1_THB]
				  ,L.[LIMIT_USED_L1_CCY]
				  ,L.[LIMIT_USED_L2_THB]
				  ,L.[LIMIT_USED_L2_CCY]
				  ,L.[LIMIT_USED_L3_THB]
				  ,L.[LIMIT_USED_L3_CCY]
				  ,L.[LIMIT_USED_L4_THB]
				  ,L.[LIMIT_USED_L4_CCY]
				  ,L.[LIMIT_USED_L5_THB]
				  ,L.[LIMIT_USED_L5_CCY]
				  ,L.[LIMIT_USED_L6_THB]
				  ,L.[LIMIT_USED_L6_CCY]
				  ,L.[LIMIT_USED_L7_THB]
				  ,L.[LIMIT_USED_L7_CCY]
				  ,L.[LIMIT_USED_L8_THB]
				  ,L.[LIMIT_USED_L8_CCY]
				  ,L.[LIMIT_USED_PRODUCT_THB]
				  ,L.[LIMIT_USED_PRODUCT_CCY]
				  ,L.[LIMIT_AVAILABLE_ROOT_THB]
				  ,L.[LIMIT_AVAILABLE_L1_THB]
				  ,L.[LIMIT_AVAILABLE_L2_THB]
				  ,L.[LIMIT_AVAILABLE_L3_THB]
				  ,L.[LIMIT_AVAILABLE_L4_THB]
				  ,L.[LIMIT_AVAILABLE_L5_THB]
				  ,L.[LIMIT_AVAILABLE_L6_THB]
				  ,L.[LIMIT_AVAILABLE_L7_THB]
				  ,L.[LIMIT_AVAILABLE_L8_THB]
				  ,L.[LIMIT_AVAILABLE_PRODUCT_THB]
				  ,L.[LIMIT_AVAI_RATIO_L1_THB]
				  ,L.[LIMIT_AVAI_RATIO_L2_THB]
				  ,L.[LIMIT_AVAI_RATIO_L3_THB]
				  ,L.[LIMIT_AVAI_RATIO_L4_THB]
				  ,L.[LIMIT_AVAI_RATIO_L5_THB]
				  ,L.[LIMIT_AVAI_RATIO_L6_THB]
				  ,L.[LIMIT_AVAI_RATIO_L7_THB]
				  ,L.[LIMIT_AVAI_RATIO_L8_THB]
				  ,L.[LIMIT_AVAI_RATIO_PRODUCT_THB]
				  ,L.[HOLD_AMOUNT_THB]
				  ,L.[HOLD_AMOUNT_CCY]
				  ,L.[LIMIT_AMOUNT_CA_THB]
				  ,L.[LIMIT_USED_CA_THB]
				  ,L.[LIMIT_AVAILABLE_CA_THB]
				  ,L.[GECID]
				  ,L.[CREATED_DATE]
				  ,L.[UPDATE_DATE]
				  ,L.[UPDATE_STATUS_DATE]
				  ,L.[ASOFDATE]
				  ,L.[ETL_DT]
				,CA.CA_NO AS LIMIT_PRODUCT_CA_NO
				,CA.CA_DATE AS LIMIT_PRODUCT_CA_DATE
				,CA.APPV_DATE AS LIMIT_PRODUCT_APPV_DATE
				,CA.APPV_AUTH_UNIT AS LIMIT_PRODUCT_APPV_AUTH_UNIT
				,CA.PREVIOUS_CA_NO AS LIMIT_PRODUCT_PREVIOUS_CA_NO
				,LIM.EFFECT_DATE AS LIMIT_PRODUCT_EFFECT_DATE
				,LIM.EXPIRE_DATE AS LIMIT_PRODUCT_EXPIRE_DATE
				,LIM.SIGN_DATE AS LIMIT_PRODUCT_SIGN_DATE
				,@endDate AS LEADER1_CREATED_DATE
			 
			  FROM	[EDW]..[DWHADMIN].[CLS_LIMIT_RELATION_FACT] L INNER JOIN
					[EDW]..[DWHADMIN].[CLS_CIF_PRODUCT_FACT] C 
					ON L.LIMIT_NO_PRODUCT = C.LIMIT_NO_PRODUCT INNER JOIN
					[EDW]..[DWHADMIN].[DIM_CLS_CA] CA
					ON L.CA_KEY = CA.CA_KEY INNER JOIN
					[EDW]..[DWHADMIN].[DIM_CLS_LIMIT] LIM
					ON L.CLS_LIMIT_PRODUCT_ID_KEY = LIM.CLS_LIMIT_ID_KEY INNER JOIN
					(SELECT DISTINCT [CIF],[OLD_ID] AS LEADER1_CA_OLD_ID
					  FROM [REPORT07_SUMMARY]
					WHERE [APPROVE_DATE] > @startDate
						AND [APPROVE_DATE] <= @endDate
						AND (SUBJECT_DETAIL_ID = 101 OR SUBJECT_DETAIL_ID = 102 OR SUBJECT_DETAIL_ID = 103
								OR SUBJECT_DETAIL_ID = 104 OR SUBJECT_DETAIL_ID = 105)
					) R
					ON R.CIF = C.CIF
			WHERE L.MONTH_KEY = @monthKey
				AND C.MONTH_KEY = @monthKey;
			-- End Import Today CLS

			-- Add dummy for cif that not have limit
			INSERT INTO [CLS_WHEN_APPROVE]
					   ([CIF]
					   ,[LEADER1_CA_OLD_ID]
						,[CIF_LIST_ROOT]
						,LEADER1_CREATED_DATE)
			SELECT DISTINCT [CIF],[OLD_ID] AS LEADER1_CA_OLD_ID,[CIF] AS [CIF_LIST],@endDate
			  FROM [REPORT07_SUMMARY] R
			WHERE [APPROVE_DATE] > @startDate
				AND [APPROVE_DATE] <= @endDate
				AND (R.SUBJECT_DETAIL_ID = 101 OR R.SUBJECT_DETAIL_ID = 102 OR R.SUBJECT_DETAIL_ID = 103
						OR R.SUBJECT_DETAIL_ID = 104 OR R.SUBJECT_DETAIL_ID = 105)
				AND NOT EXISTS (SELECT [CIF],[OLD_ID] AS [LEADER1_CA_OLD_ID]
								FROM [CLS_WHEN_APPROVE]
								WHERE [CLS_WHEN_APPROVE].CIF = R.CIF
									AND [CLS_WHEN_APPROVE].LEADER1_CA_OLD_ID = R.[OLD_ID]);

		COMMIT TRANSACTION
	END TRY

	BEGIN CATCH
		IF @@TRANCOUNT > 0

		ROLLBACK TRAN; --RollBack in case of Error

		-- you can Raise ERROR with RAISEERROR() Statement including the details of the exception

		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;

		SELECT @ErrorMessage = ERROR_MESSAGE(),
			   @ErrorSeverity = ERROR_SEVERITY(),
			   @ErrorState = ERROR_STATE();

		-- Use RAISERROR inside the CATCH block to return 
		-- error information about the original error that 
		-- caused execution to jump to the CATCH block.
		RAISERROR (@ErrorMessage, -- Message text.
				   @ErrorSeverity, -- Severity.
				   @ErrorState -- State.
				   );
		
	END CATCH
END
