CREATE PROCEDURE [dbo].[ANNALS_NCB_DEPT_SELECT]
AS 
BEGIN 

	--SELECT     CATEGORY_KEY as DEPT_ID, CATEGORY_DESC_TH as DEPT_NAME
 --   FROM       CLASSIFY.CATEGORY
 --   WHERE     (CATEGORY_TYPE_KEY = 8) AND (DEL_FLAG = 0)
 --   AND        CATEGORY_KEY <> 1156
 --   AND        CATEGORY_KEY <> 1157
 --   AND        CATEGORY_KEY <> 1158
 --   AND        CATEGORY_KEY <> 1164
 --   AND        CATEGORY_KEY <> 1165
    
 --   ORDER BY PRIORITY
    
    
    SELECT Q.* FROM (
		SELECT  C.CATEGORY_KEY  AS DEPT_ID,
				C.CATEGORY_DESC_TH + ' (' + E.EMPNAME + ')' as DEPT_NAME
		FROM	[BAY01].[CLASSIFY].[CATEGORY] C 
		LEFT OUTER JOIN  (
				SELECT E.CATEGORY_KEY,
					   EM.TITLE_NAME + EM.EMPNAME + ' ' + EM.EMPSURNAME as EMPNAME
				FROM [BAY01].[CLASSIFY].[CATE_AND_EMP] E
				LEFT OUTER JOIN 
				[BAY01].[DBO].[EMPLOYEE01] EM   ON E.EMP_ID=EM.EMP_ID
				WHERE E.DEL_FLAG=0 AND   E.HEAD_PRIORITY=1
			) AS E   ON	C.category_key=E.category_key
		WHERE   (C.category_type_key=8 AND C.DEL_FLAG=0)
		AND     (C.CATEGORY_KEY  NOT IN  (1156,1157,1158,1164,1165))
	) AS Q
    WHERE  DEPT_NAME IS NOT NULL

END