CREATE PROCEDURE [dbo].[UspDIC05SelProc2]
           							/*  %%%%%BY  DTOM%%%%%  */
(
		@APPS_ID     int  
)
AS
BEGIN
SELECT    	@APPS_ID		APPS_ID	, 
		Dic05.COLL_ID		COLL_ID	, 
		Id_TypeCid05.TypeCid05_Name AS TYPE, 
		Dic05.CHANODE	CHANODE	, 
		Dic05.LAND		LAND		, 
		Dic05.SURVEY		SURVEY	, 
		Dic05.PAGE		PAGE		, 
		Dic05.BOOK		BOOK		, 
                      	Dic05.BUILDNAME	BUILDNAME	, 
		Dic05.SOI		SOI		, 
		Dic05.ROAD		ROAD		, 
		Dic05.DISTRICT	DISTRICT	, 
		Dic05.AMPHUR		AMPHUR	, 
		REF_PROVINCE.PROVINCE_NAME AS PROV, 
		Dic05.AREA_RAI	AREA_RAI	, 
                      	Dic05.AREA_NGAN	AREA_NGAN	,	 
		Dic05.AREA_WAH	AREA_WAH	,
		COLLVAL.BUYCOLL	BUYCOLL	,
		COLLVAL.FORECASTVAL FORECASTVAL,
		COLLVAL.PRICE_DEPT	PRICE_DEPT	,
		COLLVAL.COLLVAL	CCOLLVAL	,
		COLLVAL.UNITVAL	UNITVAL	,
		COLLVAL.SELLER	SELLER	,
		COLLVAL.COMMENT	COMMENT	,
		COLLGROUP.COLL_ID as CollNotSel	,
		COLLVAL.COLL_ID 	AS COLLGROUP
/*FROM         	Dic05     INNER JOIN 	Id_TypeCid05 ON Dic05.Id_TypeCid05 = Id_TypeCid05.Id_TypeCid05 
		INNER JOIN   REF_PROVINCE ON Dic05.PROV_CODE = REF_PROVINCE.PROV_CODE
		LEFT OUTER JOIN COLLGROUP ON Dic05.COLL_ID = COLLGROUP.COLL_ID
		LEFT OUTER JOIN COLLVAL ON COLLGROUP.CIDGROUP = COLLVAL.COLL_ID*/

FROM         	COLLVAL INNER JOIN COLLGROUP ON (COLLGROUP.CIDGROUP = COLLVAL.COLL_ID And COLLVAL.DATEDELETE IS NULL)
		RIGHT OUTER JOIN Dic05 ON COLLGROUP.COLL_ID=Dic05.COLL_ID
		INNER JOIN Id_TypeCid05 ON Dic05.Id_TypeCid05 = Id_TypeCid05.Id_TypeCid05 
		LEFT OUTER JOIN REF_PROVINCE ON Dic05.PROV_CODE = REF_PROVINCE.PROV_CODE
WHERE    	Dic05.COLL_ID     IN	(SELECT     coll_id
			                            FROM          linkcoll
			                            WHERE      APPS_ID = @APPS_ID)
    
    RETURN(0)
END
